force-app/main/default/objects/Quality_Assurance__c/Quality_Assurance__c.object-meta.xml
<CustomObject>
    <description>Quality Assurance Records</description>
    <label>Quality Assurance</label>
    <nameField>
        <displayFormat>QA-{YYYY}-{MM}-{DD}-{0000}</displayFormat>
        <label>Quality Assurance</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quality Assurances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quality_Assurance__c/fields/Pass_All__c.field-meta.xml
<CustomField>
    <fullName>Pass_All__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Select to mass update all QA elements to pass.</inlineHelpText>
    <label>Pass All</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quality_Assurance__c/fields/Receiving_Line__c.field-meta.xml
<CustomField>
    <fullName>Receiving_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Receiving Line</label>
    <referenceTo>Receiving_Line__c</referenceTo>
    <relationshipLabel>Quality Assurances</relationshipLabel>
    <relationshipName>Quality_Assurances</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Receiving_Line__c/Receiving_Line__c.object-meta.xml
<CustomObject>
    <label>Receiving Line</label>
    <nameField>
        <displayFormat>RELI-{0000000000}</displayFormat>
        <label>Receiving Line</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Receiving Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Receiving_Line__c/fields/Receiving_ID__c.field-meta.xml
<CustomField>
    <fullName>Receiving_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Receiving ID</label>
    <referenceTo>Receiving__c</referenceTo>
    <relationshipLabel>Receiving Lines</relationshipLabel>
    <relationshipName>Receiving_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/MassQAController.cls
public class MassQAController {
	 private Static String Confirmation_for_QA_Record { 
        get{
            return  String.isNotBlank(Confirmation_for_QA_Record) ? Confirmation_for_QA_Record :  FiligreenConfigurationUtility.getConfigValueByObjectAndKey('Quality Assurance','Confirmation_for_QA_Record');
        }set;
    }
    
    @AuraEnabled
    public static AuraResponse createRecord(String recordId){
        AuraResponse r = new AuraResponse('MassQAController.createRecord()');
        Boolean showpopup = false;
        list<Receiving_Line__c> rlList = [SELECT Id, Name, Receiving_ID__c,(select Id From Quality_Assurances__r) FROM Receiving_Line__c where Receiving_ID__c =: recordId];
        String alreadyCreatedQAName = '';
        List<string> alreadyQAIds = new List<string>();
        List<Quality_Assurance__c> qaList = new List<Quality_Assurance__c>();
        String recordType = Schema.SObjectType.Quality_Assurance__c.getRecordTypeInfosByName().get('QA Receiving Line').getRecordTypeId();
        for(Receiving_Line__c rl : rlList){
                if(rl.Quality_Assurances__r.size() > 0){
                    showpopup = true;
                    alreadyCreatedQAName += alreadyCreatedQAName == '' ? rl.Name : ', '+rl.Name;
                    alreadyQAIds.add(rl.Id);
                }else{
                    Quality_Assurance__c QA = new Quality_Assurance__c();
                    QA.Receiving_Line__c = rl.Id;
                    QA.Pass_All__c = true;
                    QA.RecordTypeId = recordType;
                    qaList.add(QA);
                }
        }
        
        if(qaList.size() > 0 ){
            insert qaList;
        }
        
        r.data.put('showpopup',showpopup);
        r.data.put('Confirmation_for_QA_Record', Confirmation_for_QA_Record.replace('{0}', alreadyCreatedQAName));
        r.data.put('alreadyQAIds',alreadyQAIds);
       
        return r;
    }
    @AuraEnabled
    public static AuraResponse createNewRecord(List<String> recordIds){
        AuraResponse r = new AuraResponse('MassQAController.createNewRecord()');
        String recordType = Schema.SObjectType.Quality_Assurance__c.getRecordTypeInfosByName().get('QA Receiving Line').getRecordTypeId();
        list<Receiving_Line__c> rlList = [SELECT Id, Name, Receiving_ID__c FROM Receiving_Line__c where Id IN : recordIds];
        List<Quality_Assurance__c> qaList = new List<Quality_Assurance__c>();
        for(Receiving_Line__c rl : rlList){
            Quality_Assurance__c QA = new Quality_Assurance__c();
            QA.Receiving_Line__c = rl.Id;
            QA.Pass_All__c = true;
            QA.RecordTypeId = recordType;
            qaList.add(QA);
        }
        if(qaList.size() > 0 ){
            insert qaList;
        }
        return r;
        
    }
    
}