force-app/main/default/objects/Compliance_Images__c/Compliance_Images__c.object-meta.xml
<CustomObject>
    <description>Used for COA, Primary and Information Panel Upload for Downloading or auto attachment to Buy Sell objects.</description>
    <label>Compliance Image</label>
    <nameField>
        <displayFormat>CI-{YYYY}-{MM}-{00000}</displayFormat>
        <label>Compliance Images</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Compliance Images</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Compliance_Images__c/fields/COA_Issued_Date__c.field-meta.xml
<CustomField>
    <fullName>COA_Issued_Date__c</fullName>
    <inlineHelpText>Date in which COA was issued, COA expires 12 month from date of issue.</inlineHelpText>
    <label>COA Issued Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Compliance_Images__c/fields/Harvest_Batch_Code__c.field-meta.xml
<CustomField>
    <fullName>Harvest_Batch_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Batch ID</label>
    <referenceTo>Harvest_Batch_Code__c</referenceTo>
    <relationshipLabel>Compliance Images</relationshipLabel>
    <relationshipName>Compliance_Images</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Compliance_Images__c/fields/Producer_Name__c.field-meta.xml
<CustomField>
    <fullName>Producer_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Producer Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Compliance Images</relationshipLabel>
    <relationshipName>Compliance_Images</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Compliance_Images__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Name</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Compliance Images</relationshipLabel>
    <relationshipName>Compliance_Images</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Compliance_Images__c/fields/Terpene__c.field-meta.xml
<CustomField>
    <fullName>Terpene__c</fullName>
    <label>Terpene (%)</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Compliance_Images__c/fields/THC__c.field-meta.xml
<CustomField>
    <fullName>THC__c</fullName>
    <label>THC (%)</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Harvest_Batch_Code__c/Harvest_Batch_Code__c.object-meta.xml
<CustomObject>
    <description>Unique Harvest Batch ID, Lot Code, Production Batch</description>
    <label>Batch ID</label>
    <nameField>
        <label>Batch ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Batch IDs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Harvest_Batch_Code__c/fields/Batch_ID_Hold__c.field-meta.xml
<CustomField>
    <fullName>Batch_ID_Hold__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Global Hold for Batch ID and pushes to all related Inventory Positions</inlineHelpText>
    <label>Batch ID Hold</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Harvest_Batch_Code__c/fields/COA_Issued_Date__c.field-meta.xml
<CustomField>
    <fullName>COA_Issued_Date__c</fullName>
    <label>COA Issued Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Harvest_Batch_Code__c/fields/Producer_Name__c.field-meta.xml
<CustomField>
    <fullName>Producer_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Producer Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Batch IDs</relationshipLabel>
    <relationshipName>Batch_IDs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Harvest_Batch_Code__c/fields/Terpene__c.field-meta.xml
<CustomField>
    <fullName>Terpene__c</fullName>
    <label>Terpene (%)</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Harvest_Batch_Code__c/fields/THC__c.field-meta.xml
<CustomField>
    <fullName>THC__c</fullName>
    <label>THC (%)</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Inventory_Position__c/Inventory_Position__c.object-meta.xml
<CustomObject>
    <label>Inventory Position</label>
    <nameField>
        <displayFormat>IP-{YYYY}-{MM}-{0000000000}</displayFormat>
        <label>Inventory Position</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventory Positions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Inventory_Position__c/fields/COA_Issued_Date__c.field-meta.xml
<CustomField>
    <fullName>COA_Issued_Date__c</fullName>
    <inlineHelpText>Date in which COA was issued, COA expires 12 month from date of issue.</inlineHelpText>
    <label>Del_COA Issued Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Inventory_Position__c/fields/Harvest_Batch_Code__c.field-meta.xml
<CustomField>
    <fullName>Harvest_Batch_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Batch ID</label>
    <referenceTo>Harvest_Batch_Code__c</referenceTo>
    <relationshipLabel>Inventory Positions</relationshipLabel>
    <relationshipName>Inventory_Positions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Inventory_Position__c/fields/Hold__c.field-meta.xml
<CustomField>
    <fullName>Hold__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Inventory OnHOld for Order Allocation</inlineHelpText>
    <label>Hold</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Inventory_Position__c/fields/MOQ__c.field-meta.xml
<CustomField>
    <fullName>MOQ__c</fullName>
    <description>Used in Community -Marketplace reports.</description>
    <formula>Product_Name__r.MOQ__c</formula>
    <inlineHelpText>Used in Community -Marketplace reports.</inlineHelpText>
    <label>MOQ</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Inventory_Position__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Name</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Inventory Positions</relationshipLabel>
    <relationshipName>Inventory_Positions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Inventory_Position__c/fields/Qty_On_Hand__c.field-meta.xml
<CustomField>
    <fullName>Qty_On_Hand__c</fullName>
    <label>Qty On Hand</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Inventory_Position__c/fields/Quantity_Type__c.field-meta.xml
<CustomField>
    <fullName>Quantity_Type__c</fullName>
    <description>Used in Community -Marketplace reports.</description>
    <formula>text(Product_Name__r.Quantity_Type__c )</formula>
    <inlineHelpText>Used in Community -Marketplace reports.</inlineHelpText>
    <label>Quantity Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Inventory_Position__c/fields/Terpene__c.field-meta.xml
<CustomField>
    <fullName>Terpene__c</fullName>
    <description>Used in Community -Marketplace reports.</description>
    <formula>Product_Name__r.Terpene_percent__c</formula>
    <inlineHelpText>Used in Community -Marketplace reports.</inlineHelpText>
    <label>Terpene (%)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Inventory_Position__c/fields/THC__c.field-meta.xml
<CustomField>
    <fullName>THC__c</fullName>
    <description>Used in Community -Marketplace reports.</description>
    <formula>Product_Name__r.THC_Amount__c</formula>
    <inlineHelpText>Used in Community -Marketplace reports.</inlineHelpText>
    <label>THC (%)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/classes/BatchIDTriggerTest.cls
@isTest
public class BatchIDTriggerTest {
	private static testmethod void runTest(){
        Test.startTest();
        
        Account objAccount = new Account();
        objAccount.Name = 'Test Account1';
        objAccount.Payment_Terms__c = 'COD';
        insert objAccount;
        
        Id productRecordTypeId = Schema.SObjectType.Product2.getRecordTypeInfosByDeveloperName()
                          .get('Product').getRecordTypeId();
        
        //Create Product1
        Product2  objProduct1 = new Product2 ();
        objProduct1.Name = 'product 1';
        objProduct1.Quantity_Type__c = 'Quantity';
        objProduct1.Family = 'Accessories';
        objProduct1.Description = 'test product 1';
        objProduct1.Producer_Name__c = objAccount.id;
        objProduct1.Apply_Cultivation_Tax__c='Yes';
        objProduct1.Apply_Excise_Tax__c='Yes';
        objProduct1.IsActive = true;
        objProduct1.Unit_Height__c  = 10.0;
        objProduct1.Unit_Length__c = 10.0;
        objProduct1.Unit_Width__c = 5.0;
        objProduct1.Apply_Excise_Tax__c = 'Yes';
        objProduct1.RecordTypeId = productRecordTypeId;
        objProduct1.Track_Trace_Category__c='Capsule';
        objProduct1.Net_Weight_UOM__c='EA';
        objProduct1.Unit_Of_Measure__c='Grams';
        objProduct1.MOQ__c = 1;
        insert objProduct1;
        
        Compliance_Images__c com=new Compliance_Images__c();
        com.COA_Issued_Date__c=System.today().addDays(10);
        com.Product__c=objProduct1.id;
        insert com;
        
        Harvest_Batch_Code__c hbc = new Harvest_Batch_Code__c(Name='Test122',Active__c = true);
        insert hbc;
        
        Inventory_Position__c inv = new Inventory_Position__c();
        inv.Harvest_Batch_Code__c = hbc.Id;
        inv.Product_Name__c = objProduct1.Id;
        inv.Qty_On_Hand__c=10;
        inv.Hold__c = false;
        insert inv;
        
        com.Harvest_Batch_Code__c = hbc.Id;
        update com;
        
        hbc.THC__c = 10;
        hbc.Batch_ID_Hold__c = true;
        update hbc;
        
        hbc.Terpene__c = 12;
        hbc.Batch_ID_Hold__c = false;
        update hbc;
        
        try{
            Harvest_Batch_Code__c hbc2 = hbc.clone();
            insert hbc2;
        } catch(Exception ex){}
        
        System.assertEquals(com.Harvest_Batch_Code__c, hbc.Id);
        Test.stopTest();
    }
}