force-app/main/default/objects/Compliance_Images__c/Compliance_Images__c.object-meta.xml
<CustomObject>
    <description>Used for COA, Primary and Information Panel Upload for Downloading or auto attachment to Buy Sell objects.</description>
    <label>Compliance Image</label>
    <nameField>
        <displayFormat>CI-{YYYY}-{MM}-{00000}</displayFormat>
        <label>Compliance Images</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Compliance Images</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Compliance_Images__c/fields/COA_Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>COA_Expiration_Date__c</fullName>
    <formula>COA_Issued_Date__c + 365</formula>
    <label>COA Expiration Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Compliance_Images__c/fields/COA_Issued_Date__c.field-meta.xml
<CustomField>
    <fullName>COA_Issued_Date__c</fullName>
    <inlineHelpText>Date in which COA was issued, COA expires 12 month from date of issue.</inlineHelpText>
    <label>COA Issued Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Compliance_Images__c/fields/Harvest_Batch_Code__c.field-meta.xml
<CustomField>
    <fullName>Harvest_Batch_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Batch ID</label>
    <referenceTo>Harvest_Batch_Code__c</referenceTo>
    <relationshipLabel>Compliance Images</relationshipLabel>
    <relationshipName>Compliance_Images</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Compliance_Images__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Name</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Compliance Images</relationshipLabel>
    <relationshipName>Compliance_Images</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Harvest_Batch_Code__c/Harvest_Batch_Code__c.object-meta.xml
<CustomObject>
    <description>Unique Harvest Batch ID, Lot Code, Production Batch</description>
    <label>Batch ID</label>
    <nameField>
        <label>Batch ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Batch IDs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Harvest_Batch_Code__c/fields/Batch_ID_Hold__c.field-meta.xml
<CustomField>
    <fullName>Batch_ID_Hold__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Global Hold for Batch ID and pushes to all related Inventory Positions</inlineHelpText>
    <label>Batch ID Hold</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Harvest_Batch_Code__c/fields/COA_Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>COA_Expiration_Date__c</fullName>
    <formula>COA_Issued_Date__c + 365</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>COA Expiration Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Harvest_Batch_Code__c/fields/COA_Issued_Date__c.field-meta.xml
<CustomField>
    <fullName>COA_Issued_Date__c</fullName>
    <label>COA Issued Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Inventory_Location__c/Inventory_Location__c.object-meta.xml
<CustomObject>
    <label>Inventory Location</label>
    <nameField>
        <label>Inventory Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inventory Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Inventory_Position__c/Inventory_Position__c.object-meta.xml
<CustomObject>
    <label>Inventory Position</label>
    <nameField>
        <displayFormat>IP-{YYYY}-{MM}-{0000000000}</displayFormat>
        <label>Inventory Position</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventory Positions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Inventory_Position__c/fields/COA_Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>COA_Expiration_Date__c</fullName>
    <formula>Harvest_Batch_Code__r.COA_Expiration_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>COA Expiration Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Inventory_Position__c/fields/COA_Issued_Date__c.field-meta.xml
<CustomField>
    <fullName>COA_Issued_Date__c</fullName>
    <inlineHelpText>Date in which COA was issued, COA expires 12 month from date of issue.</inlineHelpText>
    <label>Del_COA Issued Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Inventory_Position__c/fields/Harvest_Batch_Code__c.field-meta.xml
<CustomField>
    <fullName>Harvest_Batch_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Batch ID</label>
    <referenceTo>Harvest_Batch_Code__c</referenceTo>
    <relationshipLabel>Inventory Positions</relationshipLabel>
    <relationshipName>Inventory_Positions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Inventory_Position__c/fields/Hold__c.field-meta.xml
<CustomField>
    <fullName>Hold__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Inventory OnHOld for Order Allocation</inlineHelpText>
    <label>Hold</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Inventory_Position__c/fields/Inventory_Location__c.field-meta.xml
<CustomField>
    <fullName>Inventory_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Inventory Location</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Inventory_Location__c.Site_Name__c</field>
            <operation>equals</operation>
            <valueField>$Source.Site__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Inventory_Location__c</referenceTo>
    <relationshipLabel>Inventory Positions</relationshipLabel>
    <relationshipName>Inventory_Positions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Inventory_Position__c/fields/Lab_Test_Status__c.field-meta.xml
<CustomField>
    <fullName>Lab_Test_Status__c</fullName>
    <label>Lab Test Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lab_Test_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Inventory_Position__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Name</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Inventory Positions</relationshipLabel>
    <relationshipName>Inventory_Positions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/BatchToUpdateBatchIdAndCI.cls
global class BatchToUpdateBatchIdAndCI implements Database.Batchable<sObject>, Schedulable{
    
    private static String LAB_TEST_STATUS_EXPIRED_COA{
        get{
            return String.isNotBlank(LAB_TEST_STATUS_EXPIRED_COA) ? LAB_TEST_STATUS_EXPIRED_COA : FiligreenConfigurationUtility.getConfigValueByObjectAndKey('Compliance Images','Lab_Test_Status_Expired_COA');
        }set;
    }
    /*private static String NAME_CANNAWASTE{
        get{
            return String.isNotBlank(NAME_CANNAWASTE) ? NAME_CANNAWASTE : FiligreenConfigurationUtility.getConfigValueByObjectAndKey('Inventory Location','Name_CannaWaste');
        }set;
    }
    private static String NAME_DELIVERED{
        get{
            return String.isNotBlank(NAME_DELIVERED) ? NAME_DELIVERED : FiligreenConfigurationUtility.getConfigValueByObjectAndKey('Inventory Location','Name_Delivered');
        }set;
    }
    private static String NAME_PACKAGED{
        get{
            return String.isNotBlank(NAME_PACKAGED) ? NAME_PACKAGED : FiligreenConfigurationUtility.getConfigValueByObjectAndKey('Inventory Location','Name_Packaged');
        }set;
    }
    private static String NAME_QUARANTINE{
        get{
            return String.isNotBlank(NAME_QUARANTINE) ? NAME_QUARANTINE : FiligreenConfigurationUtility.getConfigValueByObjectAndKey('Inventory Location','Name_Quarantine');
        }set;
    }
    private static String NAME_TEST_SAMPLED{
        get{
            return String.isNotBlank(NAME_TEST_SAMPLED) ? NAME_TEST_SAMPLED : FiligreenConfigurationUtility.getConfigValueByObjectAndKey('Inventory Location','Name_Test_Sampled');
        }set;
    }
    private static String NAME_TRANSFERRED{
        get{
            return String.isNotBlank(NAME_TRANSFERRED) ? NAME_TRANSFERRED : FiligreenConfigurationUtility.getConfigValueByObjectAndKey('Inventory Location','Name_Transferred');
        }set;
    }*/
    private static String EXCLUDE_INVENTORY_LOCATIONS{
        get{
            return String.isNotBlank(EXCLUDE_INVENTORY_LOCATIONS) ? EXCLUDE_INVENTORY_LOCATIONS : FiligreenConfigurationUtility.getConfigValueByObjectAndKey('Inventory Location','Exclude_Inventory_Locations');
        }set;
    }
    
    
    
    global Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator([SELECT Id,COA_Issued_Date__c,Product__c,Harvest_Batch_Code__c,Harvest_Batch_Code__r.Batch_ID_Hold__c,
                                         Harvest_Batch_Code__r.Lab_Test_Status__c,COA_Expiration_Date__c,Lab_Test_Status__c 
                                         FROM Compliance_Images__c WHERE Lab_Test_Status__c <> :LAB_TEST_STATUS_EXPIRED_COA AND COA_Expiration_Date__c =: Date.today()]);
    }
    global void execute(Database.BatchableContext bc, List<Compliance_Images__c> records){
        
        Set<Id> batchIds = new Set<Id>();
        Set<Id> productIds = new Set<Id>();
        
        for(Compliance_Images__c comp : records){
            comp.Lab_Test_Status__c = LAB_TEST_STATUS_EXPIRED_COA;
            if(comp.Harvest_Batch_Code__c != null){
                batchIds.add(comp.Harvest_Batch_Code__c);
            }
            if(comp.Product__c != null){
                productIds.add(comp.Product__c);
            }
        }
		update records;
        
        List<Harvest_Batch_Code__c> lstBatch = new List<Harvest_Batch_Code__c>();
        if(batchIds.size() > 0){
            List<Harvest_Batch_Code__c> batchList = [SELECT ID,Batch_ID_Hold__c,Lab_Test_Status__c,
                                                     (SELECT Id,Lab_Test_Status__c,COA_Expiration_Date__c FROM Compliance_Images__r)
                                                     FROM Harvest_Batch_Code__c WHERE Id IN : batchIds];
            for(Harvest_Batch_Code__c batch : batchList){
                Boolean isExist = false;
                for(Compliance_Images__c comp : batch.Compliance_Images__r){
                    if(comp.COA_Expiration_Date__c > Date.today()){
                        isExist = true;
                        break;
                    }
                }
                if(!isExist){
                    batch.Batch_ID_Hold__c = true;
                    batch.Lab_Test_Status__c = LAB_TEST_STATUS_EXPIRED_COA;
                    lstBatch.add(batch);
                }
            }
        }
        
        if(lstBatch.size() > 0){
            update lstBatch;
        }
        List<String> lstInvLocNames = EXCLUDE_INVENTORY_LOCATIONS.split(',');
        List<Inventory_Position__c> lstInvPos = new List<Inventory_Position__c>([SELECT Id,Harvest_Batch_Code__c,Inventory_Location__c,Product_Name__c,
                                                                                 Inventory_Location__r.Name,Lab_Test_Status__c,Hold__c
                                                                                 FROM Inventory_Position__c 
                                                                                 WHERE Harvest_Batch_Code__c IN : batchIds AND Product_Name__c IN : productIds
                                                                                 AND Hold__c =: false AND Inventory_Location__r.Name NOT IN :lstInvLocNames]);
        System.debug('lstInvPos.size() = '+lstInvPos.size());
        if(lstInvPos.size() > 0){
            List<Inventory_Position__c> updateList = new List<Inventory_Position__c>();
            for(Inventory_Position__c inv : lstInvPos){
                inv.Hold__c = true;
                inv.Lab_Test_Status__c = LAB_TEST_STATUS_EXPIRED_COA;  
                updateList.add(inv);
                /*if(inv.Inventory_Location__r.Name != NAME_CANNAWASTE && inv.Inventory_Location__r.Name != NAME_DELIVERED &&
                   inv.Inventory_Location__r.Name != NAME_PACKAGED && inv.Inventory_Location__r.Name != NAME_QUARANTINE &&
                   inv.Inventory_Location__r.Name != NAME_TEST_SAMPLED && inv.Inventory_Location__r.Name != NAME_TRANSFERRED){
                       inv.Hold__c = true;
                       inv.Lab_Test_Status__c = LAB_TEST_STATUS_EXPIRED_COA;  
                       updateList.add(inv);
            	}*/    
            }
            if(updateList.size() > 0) {
                update updateList;    
            }
        }
    }    
    
    global void execute(SchedulableContext sc){
        Database.executeBatch(new BatchToUpdateBatchIdAndCI());
    } 
    global void finish(Database.BatchableContext bc){}    
}