force-app/main/default/objects/Picklist__c/Picklist__c.object-meta.xml
<CustomObject>
    <description>Picklist is used for Warehouse Picking from inventory Positions</description>
    <label>Picklist</label>
    <nameField>
        <displayFormat>PL-{0000000000}</displayFormat>
        <label>Picklist</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Picklists</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Picklist__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <label>Sales Order</label>
    <referenceTo>Sales_Order__c</referenceTo>
    <relationshipLabel>Picklists</relationshipLabel>
    <relationshipName>Picklists</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Picklist__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site</label>
    <referenceTo>Site__c</referenceTo>
    <relationshipLabel>Picklists</relationshipLabel>
    <relationshipName>Picklists</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/Purchase_Order__c.object-meta.xml
<CustomObject>
    <label>Purchase Order</label>
    <nameField>
        <displayFormat>PO-{0000000000}</displayFormat>
        <label>Purchase Order</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Purchase_Order__c/fields/Receiver_Address__c.field-meta.xml
<CustomField>
    <fullName>Receiver_Address__c</fullName>
    <formula>Receiver_License__r.License_Address__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Receiver Address</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site</label>
    <referenceTo>Site__c</referenceTo>
    <relationshipLabel>Purchase Orders</relationshipLabel>
    <relationshipName>Purchase_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/fields/Supplier_City_State_Zip__c.field-meta.xml
<CustomField>
    <fullName>Supplier_City_State_Zip__c</fullName>
    <formula>Text(Supplier_License__r.License_City__c)  + &quot;, &quot; +
Text(Supplier_License__r.License_State__c) + &quot;, &quot; +
Supplier_License__r.License_Zip__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Supplier City, State, Zip</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/fields/Window_End__c.field-meta.xml
<CustomField>
    <fullName>Window_End__c</fullName>
    <inlineHelpText>Latest time supplier for pick-up</inlineHelpText>
    <label>Window End</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/fields/Window_Start__c.field-meta.xml
<CustomField>
    <fullName>Window_Start__c</fullName>
    <inlineHelpText>Earliest time supplier for pick-up</inlineHelpText>
    <label>Window Start</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Route_Schedule__c/Route_Schedule__c.object-meta.xml
<CustomObject>
    <label>Route Schedule</label>
    <nameField>
        <displayFormat>RS-{00000000}</displayFormat>
        <label>Route Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Route_Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Route_Schedule__c/fields/drivers__c.field-meta.xml
<CustomField>
    <fullName>drivers__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>driver</label>
    <referenceTo>Driver__c</referenceTo>
    <relationshipLabel>Route_Schedules</relationshipLabel>
    <relationshipName>Route_Schedules</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Route_Schedule__c/fields/Route_End_Time__c.field-meta.xml
<CustomField>
    <fullName>Route_End_Time__c</fullName>
    <label>Route End Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Route_Schedule__c/fields/Route_Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Route_Start_Time__c</fullName>
    <label>Route Start Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Route_Schedule__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site</label>
    <referenceTo>Site__c</referenceTo>
    <relationshipLabel>Route_Schedules</relationshipLabel>
    <relationshipName>Route_Schedules</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Route_Schedule_Line__c/Route_Schedule_Line__c.object-meta.xml
<CustomObject>
    <label>Route Schedule Line</label>
    <nameField>
        <displayFormat>RSL-{00000000}</displayFormat>
        <label>Route Schedule Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Route_Schedule_Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Route_Schedule_Line__c/fields/Purchase_Order__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Purchase Order</label>
    <referenceTo>Purchase_Order__c</referenceTo>
    <relationshipLabel>Route_Schedule_Lines</relationshipLabel>
    <relationshipName>Route_Schedule_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Route_Schedule_Line__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Order</label>
    <referenceTo>Sales_Order__c</referenceTo>
    <relationshipLabel>Route_Schedule_Lines</relationshipLabel>
    <relationshipName>Route_Schedule_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Route_Schedule_Line__c/fields/Shipping_Manifest__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Manifest__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Shipping Manifest</label>
    <referenceTo>Shipping_Manifest__c</referenceTo>
    <relationshipLabel>Route_Schedule_Lines</relationshipLabel>
    <relationshipName>Route_Schedule_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Route_Schedule_Line__c/fields/Window_Start__c.field-meta.xml
<CustomField>
    <fullName>Window_Start__c</fullName>
    <label>Window Start</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Sales_Order__c/Sales_Order__c.object-meta.xml
<CustomObject>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>SO-{0000000000}</displayFormat>
        <label>Sales Order</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Order__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site</label>
    <referenceTo>Site__c</referenceTo>
    <relationshipLabel>Sales Orders</relationshipLabel>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipping_Manifest__c/Shipping_Manifest__c.object-meta.xml
<CustomObject>
    <description>Used in the generation of compliance document to enable retail delivery.</description>
    <label>Shipping Manifest</label>
    <nameField>
        <displayFormat>SM-{YYYY}-{MM}-{0000000000}</displayFormat>
        <label>Shipping Manifest</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipping Manifests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Shipping_Manifest__c/fields/drivers__c.field-meta.xml
<CustomField>
    <fullName>drivers__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>driver</label>
    <referenceTo>Driver__c</referenceTo>
    <relationshipLabel>Shipping Manifests</relationshipLabel>
    <relationshipName>Shipping_Manifests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipping_Manifest__c/fields/Picklist__c.field-meta.xml
<CustomField>
    <fullName>Picklist__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Picklist</label>
    <referenceTo>Picklist__c</referenceTo>
    <relationshipLabel>Shipping Manifests</relationshipLabel>
    <relationshipName>Shipping_Manifests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipping_Manifest__c/fields/Purchase_Order__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Related to Purchase Order</description>
    <label>Purchase Order</label>
    <referenceTo>Purchase_Order__c</referenceTo>
    <relationshipLabel>Shipping Manifests</relationshipLabel>
    <relationshipName>Shipping_Manifests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipping_Manifest__c/fields/Route_End_Time__c.field-meta.xml
<CustomField>
    <fullName>Route_End_Time__c</fullName>
    <label>Route End Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Shipping_Manifest__c/fields/Route_Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Route_Start_Time__c</fullName>
    <label>Route Start Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Shipping_Manifest__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Order</label>
    <referenceTo>Sales_Order__c</referenceTo>
    <relationshipLabel>Shipping Manifests</relationshipLabel>
    <relationshipName>Shipping_Manifests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipping_Manifest__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site</label>
    <referenceTo>Site__c</referenceTo>
    <relationshipLabel>Shipping Manifests</relationshipLabel>
    <relationshipName>Shipping_Manifests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipping_Manifest__c/fields/Supplier_Address__c.field-meta.xml
<CustomField>
    <fullName>Supplier_Address__c</fullName>
    <formula>Supplier_License__r.License_Address__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Supplier Address</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Shipping_Manifest__c/fields/Window_End__c.field-meta.xml
<CustomField>
    <fullName>Window_End__c</fullName>
    <inlineHelpText>Latest time receiver can accept shipment</inlineHelpText>
    <label>Window End</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Shipping_Manifest__c/fields/Window_Start__c.field-meta.xml
<CustomField>
    <fullName>Window_Start__c</fullName>
    <inlineHelpText>Earliest time receiver can accept shipment</inlineHelpText>
    <label>Window Start</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Site__c/Site__c.object-meta.xml
<CustomObject>
    <description>All objects must have a Site Name and License Class or A or M. For separate sales and inventory record.</description>
    <label>Site</label>
    <nameField>
        <label>Site</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Site__c/fields/License_ID__c.field-meta.xml
<CustomField>
    <fullName>License_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>License ID</label>
    <referenceTo>State_Licenses__c</referenceTo>
    <relationshipLabel>Sites</relationshipLabel>
    <relationshipName>Sites</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/State_Licenses__c/State_Licenses__c.object-meta.xml
<CustomObject>
    <description>Object within the Account to track number of license and address as part of ship to.</description>
    <label>State License</label>
    <nameField>
        <displayFormat>SLID-{YYYY}-{MM}-{0000000000}</displayFormat>
        <label>License</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>State Licenses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/State_Licenses__c/fields/License_Address__c.field-meta.xml
<CustomField>
    <fullName>License_Address__c</fullName>
    <label>License Address</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/State_Licenses__c/fields/License_Country__c.field-meta.xml
<CustomField>
    <fullName>License_Country__c</fullName>
    <label>License Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>US</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/State_Licenses__c/fields/License_Zip__c.field-meta.xml
<CustomField>
    <fullName>License_Zip__c</fullName>
    <label>License Zip</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/routeScheduleRestWebServiceTest.cls
@isTest(OnInstall=false SeeAllData=false)
public class routeScheduleRestWebServiceTest {
    
    static Drivers__c driverObj;
    static Vehicles__c vehicleObj;
    static Sales_Order__c salesOrderObj;
    static Purchase_Order__c purchaseOrderObj;
    static Shipping_Manifest__c smObj;
    static PickList__c pickListObj;
    
    static testMethod void routeScheduleRestWebServiceTest(){
        Test.setMock(HttpCalloutMock.class, new StateLicense_MockResponseTest());     
          TestUtilData.skipTrigger = true;
        Google_Distance_Matrix_API__c[] GDMIs = new Google_Distance_Matrix_API__c[]{new Google_Distance_Matrix_API__c(Name='GMaps_Endpoint',Value__c = 'https://maps.googleapis.com/maps/api/distancematrix/json?'),new Google_Distance_Matrix_API__c(Name='Gmaps_APIKey',Value__c = 'gjhghj3232342jkhj'),new Google_Distance_Matrix_API__c(Name='Geocode_Endpoint',Value__c = 'https://maps.googleapis.com/maps/api/geocode/json?')};
            insert GDMIs; 
        Test.startTest();
         
          
    //Test.setMock(HttpCalloutMock.class, new StateLicense_MockResponseTest());
        routeScheduleRestWebService.doPostRouteInfo(system.today());
        routeScheduleRestWebService.getRouteSchedule(system.today());
        routeScheduleRestWebService.getMonthNumber('December');
        Test.setMock(HttpCalloutMock.class, new routeScheduleRestWebService_MockTest());
        
     /*List<Site__c>  sites=[SELECT Id,Name , License_ID__r.License_Address__c , License_ID__r.License_Zip__c ,
 License_ID__r.License_Country__c ,(SELECT Id, Name ,  Sales_Order__c, Purchase_Order__c,Purchase_Order__r.Receiver_Address__c,Purchase_Order__r.Receiver_City_State_Zip__c , 
 Purchase_Order__r.Name ,Sales_Order__r.Name, Purchase_Order__r.Supplier_Address__c , Purchase_Order__r.Supplier_City_State_Zip__c , 
 Sales_Order__r.Receiver_Address__c , Sales_Order__r.Receiver_City_State_Zip__c , Route_Start_Time__c , Route_End_Time__c , Window_Start__c , Window_End__c , Status__c , 
Planned_Ship_Transfer_Date__c FROM Shipping_Manifests__r WHERE Planned_Ship_Transfer_Date__c =:routeDate AND Id NOt IN:smIds ) FROM Site__c]; */
        
        
        
        
        
        
        
        
        
        List<Route_Schedule__c> updateRoute = [SELECT Id,Status__c  FROM Route_Schedule__c  where Route_Date__c=: system.today() limit 1];
        Route_Schedule__c rs = new Route_Schedule__c();
        rs.Route_Name__c ='test';
        rs.Route_Date__c=system.today();
        //Route_Schedule__c.Route_Date__c =system.today();
         rs.Status__c='Open';
        
        
      //  rs.Route_End_Time__c=now() ;
        insert rs;
        Route_Schedule_Line__c rsl = new Route_Schedule_Line__c();
        rsl.Schedule_sequence__c=1;
        rsl.Route_Schedule__c=rs.id;
        
        insert rsl;
        system.debug('rsl>>'+rsl);
         DateTime todaysDate = System.today();
        Date routeDate = Date.valueOf(todaysDate);
   List<Route_Schedule__c> getRoute = new  List<Route_Schedule__c>();
        Set<ID> routeIds = new Set<ID>();
           Set<ID> smIds = new Set<ID>();
        getRoute = [select Id, name,Status__c,(Select id, Name,Shipping_Manifest__c from Route_Schedule_Lines__r)  from Route_Schedule__c where Route_Date__c=:routeDate];
system.debug('getRoute>>'+getRoute.size());
                routeScheduleRestWebService.getDataLight(rs.id);
          Drivers__c driverO = new Drivers__c();
        driverO.Name = 'Test Driver1';
        driverO.Driver_License_Number__c = '12311';
        driverO.Expiration_Date__c = System.Today() + 100;
        driverO.State_Issued__c = 'NY';
        insert driverO;
        
        Vehicles__c vehicle1 = new Vehicles__c();
        vehicle1.Name = 'Test Vehicle'; // Same as Inventory Location of Picklist Line
        insert vehicle1;
        
routeScheduleRestWebService.assignDriverVehicle(rs.id,driverO.Id,vehicle1.Id,system.today(),'Save & Publish');
       routeScheduleRestWebService.publishRoute(rs.id);
        string month;
            month = routeScheduleRestWebService.HOLIDAY_RECURRENCE_LAST;
        month = routeScheduleRestWebService.AUGUST_MONTH;
        month = routeScheduleRestWebService.HOLIDAY_RECURRENCE_FIRST;
        month = routeScheduleRestWebService.DECEMBER_MONTH;
        month = routeScheduleRestWebService.NOVEMBER_MONTH;
        month = routeScheduleRestWebService.OCTOBER_MONTH;
        month = routeScheduleRestWebService.SEPTEMBER_MONTH;
         month = routeScheduleRestWebService.JULY_MONTH;
         month = routeScheduleRestWebService.JUNE_MONTH;
         month = routeScheduleRestWebService.SHIPPING_MANIFEST_STATUS_PENDING;
         month = routeScheduleRestWebService.HOLIDAY_RECURSMONTHLY;
         month = routeScheduleRestWebService.HOLIDAY_RECURSMONTHLYNTH;
         month = routeScheduleRestWebService.HOLIDAY_RECURSDAILY;
         month = routeScheduleRestWebService.HOLIDAY_RECURSEVERYWEEKDAY;
         month = routeScheduleRestWebService.MAY_MONTH;
         month = routeScheduleRestWebService.HOLIDAY_RECURSWEEKLY;
        routeSchduleBatch x = new routeSchduleBatch();
    database.executeBatch(x);
//QuickBookConncetion.SyncProductsWithQuickBooksdoint(objAccount.Id);
    Test.stopTest();
     
      
   

    }

}