force-app/main/default/objects/Picklist__c/Picklist__c.object-meta.xml
<CustomObject>
    <description>Picklist is used for Warehouse Picking from inventory Positions</description>
    <label>Picklist</label>
    <nameField>
        <displayFormat>PL-{0000000000}</displayFormat>
        <label>Picklist</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Picklists</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Picklist__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>QA Review</fullName>
            </value>
            <value>
                <fullName>QA Confirm</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Picklist__c/fields/Track_Trace_Sync__c.field-meta.xml
<CustomField>
    <fullName>Track_Trace_Sync__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Track &amp; Trace Sync</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Picklist_Line__c/Picklist_Line__c.object-meta.xml
<CustomObject>
    <description>Picklist Lines are Line Items within a Picklist and inherites Sales Order Line Items</description>
    <label>Picklist Line</label>
    <nameField>
        <displayFormat>PKLI-{0000000000}</displayFormat>
        <label>Picklist Line</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Picklist Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Picklist_Line__c/fields/Pack_out_UID__c.field-meta.xml
<CustomField>
    <fullName>Pack_out_UID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pack-out UID</label>
    <referenceTo>UID__c</referenceTo>
    <relationshipLabel>Picklist Lines</relationshipLabel>
    <relationshipName>Picklist_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Picklist_Line__c/fields/Picklist__c.field-meta.xml
<CustomField>
    <fullName>Picklist__c</fullName>
    <label>Picklist</label>
    <referenceTo>Picklist__c</referenceTo>
    <relationshipLabel>Picklist Lines</relationshipLabel>
    <relationshipName>Picklist_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Picklist_Line__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>QA Hold</fullName>
            </value>
            <value>
                <fullName>Shipment Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Picklist_Line__c/fields/UID__c.field-meta.xml
<CustomField>
    <fullName>UID__c</fullName>
    <formula>Inventory_Position__r.UID_New__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Source UID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UID__c/UID__c.object-meta.xml
<CustomObject>
    <description>Unique Identifiers, RFID Tags from Track &amp; Trace</description>
    <label>UID</label>
    <nameField>
        <label>UID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>UIDs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UID__c/fields/In_Use__c.field-meta.xml
<CustomField>
    <fullName>In_Use__c</fullName>
    <defaultValue>false</defaultValue>
    <label>In Use</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/Metrc_PicklistTriggerHandler.cls
/**************************************************************************************
Apex Class Name    : Metrc_PicklistTriggerHandler 
Test Class Name    : 
Version            : 1.0
Created Date       : 01/Sep/2019
Function           : used for Metrc_PicklistTriggerHandler businesslogic execute 
Modification Log   :
------------------------------------------------------------------------------
* Developer                   Date                   Description
* ----------------------------------------------------------------------------
* Suresha Shettigar                             01/Sep/2019              Original Version
*******************************************************************************/
public with sharing class Metrc_PicklistTriggerHandler {
    
    public static void afterUpdate(List<Picklist__c> picklist_List,Map<ID,Picklist__c> oldMap){
        for(Picklist__c picklistObj : picklist_List){
            if(picklistObj.Track_Trace_Sync__c && oldMap.get(picklistObj.ID).Track_Trace_Sync__c != picklistObj.Track_Trace_Sync__c){
               //if the flag is true ,update the picklist line package id
               updatepackageIDtoLineItem(picklistObj.ID);  //uncomment after checking with Vijay
            }
            if(picklistObj.Status__c == 'Cancelled'){
                //if any changes in these fields then only sync it to Metrc
                updatePicklistline_packoutUID(picklistObj.ID);
            }
        }
    }
        

    public static void syncDataToMetrc(ID picklistID,String eventType){
        system.debug('syncDataToMetrchandler');
        List<Picklist_Line__c> picklist_List = Metrc_SOQLDML_Handler.getPicklistLine(picklistID);
        
        Metrc_HttpCalloutHelper.createPicklist(picklistID,picklist_List,eventType);
    }
    

    public static void updatePicklistline_packoutUID(ID picklistID){
        List<String> UidList = new List<String>();
        List<Picklist_Line__c> picklist_List = Metrc_SOQLDML_Handler.getCancelledPicklistLine(picklistID);
        for(Picklist_Line__c obj:picklist_List ){
           UidList.add(obj.Pack_out_UID__c);
           //obj.Pack_out_UID__c=null;
        }
         system.debug('------------picklist_List ----------1--'+picklist_List );
        
        system.debug('------------UidList------------'+UidList);
        List<UID__c> objList = Metrc_SOQLDML_Handler.getUIDTagList(UidList);
        system.debug('------------objList ------------'+objList );
        for(Picklist_Line__c obj2:picklist_List ){
           //UidList.add(obj.Pack_out_UID__c);
           obj2.Pack_out_UID__c=null;
        }
        system.debug('------------picklist_List ------------'+picklist_List );
        
        for(UID__c var: objList ){
            var.In_Use__c = false;
        }
        
        update picklist_List;
        update objList;
    system.debug('objList>>'+objList);    
    }
    
    @future(callout=true)
    public static void updatepackageIDtoLineItem(ID picklistID){
    boolean isMetrcIDUpdated =false;  
       List<Picklist_Line__c> PicklistLine_List = Metrc_SOQLDML_Handler.getPicklistLine(picklistID);
       List<String> packoutUIDList= new List<String>();
       for(Picklist_Line__c var: PicklistLine_List){
           packoutUIDList.add(var.Pack_out_UID__c);
       }
        //create a map of <UID,Tag>
       Map<ID,String> packoutUIDMap = Metrc_SOQLDML_Handler.getUIDTagMap(packoutUIDList);
        
       isMetrcIDUpdated = Metrc_HttpCalloutHelper.updateMetrcPackageID(PicklistLine_List,packoutUIDMap,picklistID); 
       system.debug('------updatepackageIDtoLineItem------retry call-1-----------'+isMetrcIDUpdated );
       if(!isMetrcIDUpdated) {
           system.debug('------updatepackageIDtoLineItem------retry call---2---------' );
           Metrc_HttpCalloutHelper.updateMetrcPackageID(PicklistLine_List,packoutUIDMap,picklistID); //retry the API call for updating the Metrc packageid.
       }     
    }
}