force-app/main/default/objects/Picklist__c/Picklist__c.object-meta.xml
<CustomObject>
    <description>Picklist is used for Warehouse Picking from inventory Positions</description>
    <label>Picklist</label>
    <nameField>
        <displayFormat>PL-{0000000000}</displayFormat>
        <label>Picklist</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Picklists</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Picklist__c/fields/Pick_Start__c.field-meta.xml
<CustomField>
    <fullName>Pick_Start__c</fullName>
    <label>Pick Start</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Picklist__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>QA Review</fullName>
            </value>
            <value>
                <fullName>QA Confirm</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PLStartPickingController.cls
/*
TestClass : PickConfirmControllerTest
*/
public class PLStartPickingController {
    private static String PL_STATUS_IN_PROGRESS{
        get{
            return String.isNotBlank(PL_STATUS_IN_PROGRESS) ? PL_STATUS_IN_PROGRESS : FiligreenConfigurationUtility.getConfigValueByObjectAndKey('Picklist','PL_Status_In_Progress');
        }set;
    }
	 @AuraEnabled
    public static Void updatePLPickStart(String recordId){
        Picklist__c PL = new Picklist__c();
        PL.Id =recordId;
        PL.Pick_Start__c = System.now();
        PL.Status__c=PL_STATUS_IN_PROGRESS;
        update PL;
    }
}