force-app/main/default/objects/Metrc_IntegrationSettings__c/Metrc_IntegrationSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This is used to store the integration endpoints</description>
    <label>Metrc_IntegrationSettings</label>
</CustomObject>

force-app/main/default/objects/Site__c/Site__c.object-meta.xml
<CustomObject>
    <description>All objects must have a Site Name and License Class or A or M. For separate sales and inventory record.</description>
    <label>Site</label>
    <nameField>
        <label>Site</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Site__c/fields/Warehouse_Name__c.field-meta.xml
<CustomField>
    <fullName>Warehouse_Name__c</fullName>
    <description>Name of the warehouse to display in UI. Example : Communities.</description>
    <label>Warehouse Name</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Strain__c/Strain__c.object-meta.xml
<CustomObject>
    <label>Strain</label>
    <nameField>
        <label>Strain</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Strains</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Strain__c/fields/Track_Trace_Sync__c.field-meta.xml
<CustomField>
    <fullName>Track_Trace_Sync__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If True checkbox, Product is created in External Track and Trace System (i.e. Metrc)</inlineHelpText>
    <label>Track &amp; Trace Sync</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TTGS_Item__c/TTGS_Item__c.object-meta.xml
<CustomObject>
    <label>TTGS Item</label>
    <nameField>
        <displayFormat>TTGSI-{MMYY}-{000000}</displayFormat>
        <label>TTGS Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TTGS Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TTGS_Item__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Name</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>TTGS Items</relationshipLabel>
    <relationshipName>TTGS_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TTGS_Item__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site</label>
    <referenceTo>Site__c</referenceTo>
    <relationshipLabel>TTGS Items</relationshipLabel>
    <relationshipName>TTGS_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TTGS_Item__c/fields/Strain__c.field-meta.xml
<CustomField>
    <fullName>Strain__c</fullName>
    <formula>Product_Name__r.Strain__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Strain</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TTGS_Item__c/fields/Unit_Weight__c.field-meta.xml
<CustomField>
    <fullName>Unit_Weight__c</fullName>
    <formula>Product_Name__r.Unit_Net_Weight__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Unit Weight</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/Metrc_HttpCalloutProduct_Test.cls
@isTest(SeeAllData=false)
/**********************************************************************************************************
Apex TestClass Name    : Metrc_HttpCalloutProduct_Test 
Apex Class Name    : Metrc_HttpCalloutHelper 
Version            : 1.0
Created Date       : 01/Sep/2019
Function           : Used for HTTPcallout
------------------------------------------------------------------------------------------------------------
* Developer                                      Date                   Description
* ----------------------------------------------------------------------------------------------------------
* Suresha Shettigar                             01/Sep/2019              Original Version
************************************************************************************************************/

private class Metrc_HttpCalloutProduct_Test 
{
    /**************************************************************************************
    Method Name        : testsetupMethod  
    Version            : 1.0
    Function           : testdata setup Method
    *******************************************************************************/
    //@testSetup static void testsetupMethod() {
        static final String testEmail = 'tuser3@testMetrc.com';
        //Static final String emailId='%'+testEmail+'%';
    
    @testSetup static void setTestData(){
        
        Id profId= [select id from Profile where name='System Administrator' limit 1].Id; 
        User testUser=Metrc_TestdataFactory.createUser(testEmail+System.currentTimeMillis(),profId,testEmail);
        Database.insert(testUser);
                            
       //PermissionSet perms = [SELECT ID From PermissionSet WHERE Name = 'ABI_POCU_GCC_CMD' limit 1];
       //database.insert (new PermissionSetAssignment(AssigneeId = tuser.id, PermissionSetId = perms.Id ));
        List<Metrc_IntegrationSettings__C> customsettingList =Metrc_TestdataFactory.createIntegrationSettingData();
        Insert customsettingList;
        
        Strain__c strainObj1 = Metrc_TestdataFactory.createStrain();
        Metrc_Utility.IS_STRAIN_TRIGGER_ENABLED =FALSE;
        insert strainObj1 ;
        
        Strain__c  strainObj =[select id from Strain__c  limit 1];
        Product2 prod =Metrc_TestdataFactory.createProduct(strainObj.ID);
        prod.Track_Trace_Sync__c=true;
        prod.isActive=true;
        
        //Metrc_Utility.IS_PROD_TRIGGER_ENABLED  =false;
        insert prod;
    }
    
    /**************************************************************************************
    Method Name        : productCreate_httpCalloutTest1  
    Version            : 1.0
    Function           :purpose of this method to give coverage to Item HttpCallout method
    *******************************************************************************/
     static testMethod void productCreate_httpCalloutTest1()
    {
        User user1=[select Id,Name from User where Username like'%tuser3@testMetrc.com%' limit 1];
        system.runAs(user1){
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new Metrc_MockProductHttpResponseTest());        
        
        Product2  prod = [select id from Product2  limit 1];
        Metrc_ProductTriggerHandler.syncDataToMetrc(prod.ID,'INSERT');
        Test.stopTest();
        
         system.assertNotEquals(prod, NULL);
        }
    }
    
     /**************************************************************************************
    Method Name        : productCreate_httpCalloutTest1  
    Version            : 1.0
    Function           :purpose of this method to give coverage to Item HttpCallout method
    *******************************************************************************/
     static testMethod void productUpdate_httpCalloutTest1()
    {
        User user1=[select Id,Name from User where Username like'%tuser3@testMetrc.com%' limit 1];
       system.runAs(user1){
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new Metrc_MockHttpResponseTest());
        
        Product2  prod = [select id,Track_Trace_Sync__c,isActive,Name ,Metrc_ItemID__c  from Product2 limit 1];
        prod.Track_Trace_Sync__c=true;
        prod.isActive=true;
        prod.Name =prod.Name+'updatedtest4'+System.currentTimeMillis();
        prod.Metrc_ItemID__c  ='12312312';
        Metrc_Utility.IS_PROD_TRIGGER_ENABLED  =false;
        update prod;
       Metrc_ProductTriggerHandler.syncDataToMetrc(prod.ID,'UPDATE');
        Test.stopTest();
        
         system.assertNotEquals(prod, NULL);
        }
    }
    
    /**************************************************************************************
    Method Name        : productCreate_httpCalloutTest1  
    Version            : 1.0
    Function           :purpose of this method to give coverage to Item HttpCallout method
    *******************************************************************************/
     static testMethod void productDelete_httpCalloutTest1()
    {
        User user1=[select Id,Name from User where Username like'%tuser3@testMetrc.com%' limit 1];
        system.runAs(user1){
        Test.setMock(HttpCalloutMock.class, new Metrc_MockHttpResponseTest());
        Test.startTest();
        Product2  prod = [select id ,Net_Weight_UOM__c,Unit_Of_Measure__c,name from Product2  limit 1];
             Site__c objSite = new Site__c();
            objSite.Name = 'Test Site';
            objSite.Warehouse_Name__c='TestWarehouse1';
            insert objSite;
              List<string> LstTTgsname = new List<string>();

            List<TTGS_Item__c> LstTTgs = new List<TTGS_Item__c>();
            TTGS_Item__c TTGS = new TTGS_Item__c();
          TTGS.Site__c =objSite.Id;
            TTGS.Product_Name__c=prod.Id;
            	
          // TTGS.Unit_Weight__c = prod.Net_Weight_UOM__c;
            insert TTGS; 
            
            LstTTgs.add(TTGS);
            LstTTgsname.add(TTGS.Name);
            Metrc_ProductTriggerHandler.syncDataToMetrc_Delete(prod.ID); 
            Metrc_HttpCalloutHelper.getSingleProducts('1234');
            Metrc_HttpCalloutHelper.getAllProductsUpdate(prod.ID);
            Metrc_HttpCalloutHelper.createProduct(prod.ID,prod,'INSERT');
         //  Metrc_HttpCalloutHelper.createTTGSItem(LstTTgs,'INSERT','test','1234');
            Metrc_HttpCalloutHelper.getAllProducts();
            Test.stopTest();
        
         system.assertNotEquals(prod, NULL);
        }
    }

    

}