force-app/main/default/objects/Error_Log__c/Error_Log__c.object-meta.xml
<CustomObject>
    <label>Error Log</label>
    <nameField>
        <displayFormat>Err-{00000000}</displayFormat>
        <label>Error Logs Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Error_Log__c/fields/Additional_Information__c.field-meta.xml
<CustomField>
    <fullName>Additional_Information__c</fullName>
    <label>Additional Information</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/File_Name__c.field-meta.xml
<CustomField>
    <fullName>File_Name__c</fullName>
    <inlineHelpText>Class or trigger file Name</inlineHelpText>
    <label>File Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ErrorLogs.cls
/*
GLobal exception class to capture application error into error log object.
*/
/*
    Copyright (c) 2018 Filigreen Distro
    All rights reserved.

•  Test class  Name:  ErrorLog_Test
*/

global class ErrorLogs  {

global static void log(String fileName, String errorMessage)

{
	Error_Log__c eLog = new Error_Log__c();
	eLog.File_Name__c = fileName;
	if(errorMessage.length() >255)
		eLog.Error_Message__c = errorMessage.substring(0,254);
	else
		eLog.Error_Message__c = errorMessage;
	insert eLog;
}

global static void log(String fileName, String errorMessage, Exception e)
{
	Error_Log__c eLog = new Error_Log__c();
	eLog.File_Name__c = fileName;
	if(errorMessage.length() >255)
		eLog.Error_Message__c = errorMessage.substring(0,254);
	else
		eLog.Error_Message__c = errorMessage;
	eLog.Additional_Information__c = String.valueOf(e);
	insert eLog;
}
global static void log(String fileName, String errorMessage, String additionalInfo)
{
	Error_Log__c eLog = new Error_Log__c();
	eLog.File_Name__c = fileName;
	if(errorMessage.length() >255)
		eLog.Error_Message__c = errorMessage.substring(0,254);
	else
		eLog.Error_Message__c = errorMessage;
	eLog.Additional_Information__c = additionalInfo;
	insert eLog;
}
global static Error_Log__c AutomationFailedLog(String fileName, String errorMessage, String additionalInfo)
{
	Error_Log__c eLog = new Error_Log__c();
	eLog.File_Name__c = fileName;
	if(errorMessage.length() >255)
		eLog.Error_Message__c = errorMessage.substring(0,254);
	else
		eLog.Error_Message__c = errorMessage;
	eLog.Additional_Information__c = additionalInfo;
	insert eLog;
    return eLog;
}

}