force-app/main/default/objects/Service_Ticket__c/Service_Ticket__c.object-meta.xml
<CustomObject>
    <description>Service ticket object in Community</description>
    <label>Service Ticket</label>
    <nameField>
        <displayFormat>ST-{YYYY}-{MM}-{00000}</displayFormat>
        <label>Service Ticket #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Tickets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Ticket__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>New</fullName>
                <isActive>false</isActive>
                <label>New</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service_Ticket__c/fields/Transfer_Method__c.field-meta.xml
<CustomField>
    <fullName>Transfer_Method__c</fullName>
    <label>Transfer Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Drop-off</fullName>
            </value>
            <value>
                <fullName>Pick-up</fullName>
            </value>
            <value>
                <fullName>Product Conversions</fullName>
            </value>
            <value>
                <fullName>D2D Transfer</fullName>
                <isActive>false</isActive>
                <label>D2D Transfer</label>
            </value>
            <value>
                <fullName>None (In stock)</fullName>
                <isActive>false</isActive>
                <label>None (In stock)</label>
            </value>
            <value>
                <fullName>Sample Pick-Up</fullName>
                <isActive>false</isActive>
                <label>Sample Pick-Up</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service_Ticket_Line__c/Service_Ticket_Line__c.object-meta.xml
<CustomObject>
    <description>Service ticket object in Community</description>
    <label>Service Ticket Line</label>
    <nameField>
        <displayFormat>STL-{0000000}</displayFormat>
        <label>Service Ticket Line #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Ticket Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Ticket_Line__c/fields/New_Packaged_Product__c.field-meta.xml
<CustomField>
    <fullName>New_Packaged_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Select the new product name, which product will become.</inlineHelpText>
    <label>New Packaged Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Service Ticket Lines (New Packaged Product)</relationshipLabel>
    <relationshipName>Service_Ticket_Lines1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_Ticket_Line__c/fields/Service_Ticket__c.field-meta.xml
<CustomField>
    <fullName>Service_Ticket__c</fullName>
    <label>Service Ticket</label>
    <referenceTo>Service_Ticket__c</referenceTo>
    <relationshipLabel>Service Ticket Lines</relationshipLabel>
    <relationshipName>Service_Ticket_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Service_Ticket_Line__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service_Ticket_Line__c/fields/Total_Units__c.field-meta.xml
<CustomField>
    <fullName>Total_Units__c</fullName>
    <inlineHelpText>Please enter the total qty of units to transfer</inlineHelpText>
    <label>Total Units</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ServiceTicketLineTriggerTest.cls
@isTest
public class ServiceTicketLineTriggerTest {
	  @isTest
    public static void Test(){
        
        Test.setMock(HttpCalloutMock.class, new StateLicense_MockResponseTest());  
        TestUtilData.skipTrigger = true;
        TestUtilData.createTestData();
        
        Service_Ticket__c st =new Service_Ticket__c();
        st.Status__c ='Draft';
        st.Transfer_Method__c='Pick-up';
        insert st;
        
        List<Product2> products = [SELECT Id,Most_Popular__c FROM Product2];
        
        Service_Ticket_Line__c stl =new Service_Ticket_Line__c();
        stl.Status__c ='New';
        stl.Total_Units__c = 10;
        stl.Service_Ticket__c =st.id;
        stl.New_Packaged_Product__c = products[0].id;
        insert stl;
        stl.Status__c ='Completed';
        update stl;
        System.assertEquals(stl.Status__c, 'Completed');
    }
}