force-app/main/default/objects/Bill_of_Materials__c/Bill_of_Materials__c.object-meta.xml
<CustomObject>
    <label>Bill of Material</label>
    <nameField>
        <label>Bill of Materials</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bill of Materials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Bill_of_Materials__c/fields/BOM_Levels__c.field-meta.xml
<CustomField>
    <fullName>BOM_Levels__c</fullName>
    <label>BOM Levels</label>
    <precision>12</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Bill_of_Materials__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Bill of Materials</relationshipLabel>
    <relationshipName>Bill_of_Materials</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Bill_of_Materials__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BOM_Lines__c/BOM_Lines__c.object-meta.xml
<CustomObject>
    <label>BOM Line</label>
    <nameField>
        <displayFormat>BOML-{0000000}</displayFormat>
        <label>BOM Line</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BOM Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BOM_Lines__c/fields/Bill_of_Material__c.field-meta.xml
<CustomField>
    <fullName>Bill_of_Material__c</fullName>
    <label>Bill of Material</label>
    <referenceTo>Bill_of_Materials__c</referenceTo>
    <relationshipLabel>BOM Lines</relationshipLabel>
    <relationshipName>BOM_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/BOM_Lines__c/fields/Producer_Name__c.field-meta.xml
<CustomField>
    <fullName>Producer_Name__c</fullName>
    <formula>Product__r.Producer_Name__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Producer Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BOM_Lines__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>BOM Lines</relationshipLabel>
    <relationshipName>BOM_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BOM_Lines__c/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <formula>TEXT(Product__r.Product_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BOM_Lines__c/fields/Qty_Per__c.field-meta.xml
<CustomField>
    <fullName>Qty_Per__c</fullName>
    <label>Qty Per</label>
    <precision>16</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BOM_Lines__c/fields/Sequence__c.field-meta.xml
<CustomField>
    <fullName>Sequence__c</fullName>
    <label>Sequence</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BOM_Lines__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Redline</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BOMWithLinesForTreeGridControllerTest.cls
@isTest
public class BOMWithLinesForTreeGridControllerTest {
    static testmethod void runTest() {
        
        Account objAccount = new Account();
        objAccount.Name = 'Test Account1';
        objAccount.Payment_Terms__c = 'COD';
        insert objAccount;

        Product2  objProduct1 = new Product2 ();
        objProduct1.Name = 'product KD 1';
        objProduct1.Quantity_Type__c = 'Quantity';
        objProduct1.Family = 'Accessories';
        objProduct1.Description = 'test product 1';
        objProduct1.Producer_Name__c = objAccount.id;
        objProduct1.Apply_Cultivation_Tax__c='Yes';
        objProduct1.Apply_Excise_Tax__c='Yes';
        objProduct1.IsActive = true;
        objProduct1.Unit_Height__c  = 10.0;
        objProduct1.Unit_Length__c = 10.0;
        objProduct1.Unit_Width__c = 5.0;
        objProduct1.Apply_Excise_Tax__c = 'Yes';
        objProduct1.Track_Trace_Category__c='Capsule';
        objProduct1.Net_Weight_UOM__c='EA';
        objProduct1.Unit_Of_Measure__c='Grams';
        objProduct1.Product_Type__c = 'Make';
        insert objProduct1;
        
        Bill_of_Materials__c objBillofMat = new Bill_of_Materials__c();
        objBillofMat.Name = 'test BOM';
        objBillofMat.BOM_Levels__c = 1;
        objBillofMat.Product__c = objProduct1.Id;
        objBillofMat.Status__c = 'Draft';
        insert objBillofMat;
        
        BOM_Lines__c objbomline1 = new BOM_Lines__c();
        objbomline1.Bill_of_Material__c = objBillofMat.id;
        objbomline1.Product__c = objProduct1.id;
        objbomline1.Sequence__c = 10;
        objbomline1.Qty_Per__c = 20;
        insert objbomline1;
        
        BOMWithLinesForTreeGridController.bomLinesForMakeProductType(objBillofMat.Id);
    }
}