force-app/main/default/objects/Bill_of_Materials__c/Bill_of_Materials__c.object-meta.xml
<CustomObject>
    <label>Bill of Material</label>
    <nameField>
        <label>Bill of Materials</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bill of Materials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Bill_of_Materials__c/fields/BOM_Levels__c.field-meta.xml
<CustomField>
    <fullName>BOM_Levels__c</fullName>
    <label>BOM Levels</label>
    <precision>12</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Bill_of_Materials__c/fields/BOM_Routing__c.field-meta.xml
<CustomField>
    <fullName>BOM_Routing__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>BOM Routing</label>
    <referenceTo>BOM_Routing__c</referenceTo>
    <relationshipLabel>Bill of Materials</relationshipLabel>
    <relationshipName>Bill_of_Materials</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Bill_of_Materials__c/fields/BOM_Type__c.field-meta.xml
<CustomField>
    <fullName>BOM_Type__c</fullName>
    <label>BOM Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Make</fullName>
            </value>
            <value>
                <fullName>Buy</fullName>
            </value>
            <value>
                <fullName>Virtual</fullName>
            </value>
            <value>
                <fullName>Bundle</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Bill_of_Materials__c/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <label>Phase</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Design</fullName>
            </value>
            <value>
                <fullName>Prototype</fullName>
            </value>
            <value>
                <fullName>EVT</fullName>
            </value>
            <value>
                <fullName>DVT</fullName>
            </value>
            <value>
                <fullName>PVT</fullName>
            </value>
            <value>
                <fullName>Production</fullName>
            </value>
            <value>
                <fullName>Discontinued</fullName>
            </value>
            <value>
                <fullName>End-of-Life</fullName>
            </value>
            <value>
                <fullName>Obsolete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Bill_of_Materials__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Bill of Materials</relationshipLabel>
    <relationshipName>Bill_of_Materials</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Bill_of_Materials__c/fields/Revision__c.field-meta.xml
<CustomField>
    <fullName>Revision__c</fullName>
    <label>Revision</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Bill_of_Materials__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Bill_of_Materials__c/fields/Total_BOM_Cost__c.field-meta.xml
<CustomField>
    <fullName>Total_BOM_Cost__c</fullName>
    <label>Total BOM Cost</label>
    <summarizedField>BOM_Lines__c.Ext_Cost__c</summarizedField>
    <summaryForeignKey>BOM_Lines__c.Bill_of_Material__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/BOM_Lines__c/BOM_Lines__c.object-meta.xml
<CustomObject>
    <label>BOM Line</label>
    <nameField>
        <displayFormat>BOML-{0000000}</displayFormat>
        <label>BOM Line</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BOM Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BOM_Lines__c/fields/Bill_of_Material__c.field-meta.xml
<CustomField>
    <fullName>Bill_of_Material__c</fullName>
    <label>Bill of Material</label>
    <referenceTo>Bill_of_Materials__c</referenceTo>
    <relationshipLabel>BOM Lines</relationshipLabel>
    <relationshipName>BOM_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/BOM_Lines__c/fields/Effective_From__c.field-meta.xml
<CustomField>
    <fullName>Effective_From__c</fullName>
    <label>Effective From</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/BOM_Lines__c/fields/Effective_To__c.field-meta.xml
<CustomField>
    <fullName>Effective_To__c</fullName>
    <label>Effective To</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/BOM_Lines__c/fields/Ext_Cost__c.field-meta.xml
<CustomField>
    <fullName>Ext_Cost__c</fullName>
    <formula>Qty_Per__c *  Unit_Cost__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Ext Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/BOM_Lines__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <label>Level</label>
    <precision>12</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BOM_Lines__c/fields/Producer_Name__c.field-meta.xml
<CustomField>
    <fullName>Producer_Name__c</fullName>
    <formula>Product__r.Producer_Name__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Producer Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BOM_Lines__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>BOM Lines</relationshipLabel>
    <relationshipName>BOM_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BOM_Lines__c/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <formula>TEXT(Product__r.Product_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BOM_Lines__c/fields/Qty_Per__c.field-meta.xml
<CustomField>
    <fullName>Qty_Per__c</fullName>
    <label>Qty Per</label>
    <precision>16</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BOM_Lines__c/fields/Required_Qty__c.field-meta.xml
<CustomField>
    <fullName>Required_Qty__c</fullName>
    <formula>Qty_Per__c +  Yield_Lost_Qty__c +  Scrap_Lost_Qty__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Required Qty</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BOM_Lines__c/fields/Sequence__c.field-meta.xml
<CustomField>
    <fullName>Sequence__c</fullName>
    <label>Sequence</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BOM_Lines__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Redline</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BOM_Lines__c/fields/Unit_Cost__c.field-meta.xml
<CustomField>
    <fullName>Unit_Cost__c</fullName>
    <label>Unit Cost</label>
    <precision>16</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/BOM_Routing__c/BOM_Routing__c.object-meta.xml
<CustomObject>
    <label>BOM Routing</label>
    <nameField>
        <label>BOM Routings</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BOM Routings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BOM_Routing__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Prototype - Only</fullName>
            </value>
            <value>
                <fullName>Costing - Only</fullName>
            </value>
            <value>
                <fullName>Production</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/cloneBOMController.cls
public class cloneBOMController {
    
    private Static String BOM_STATUS_DRAFT{
        get{
            return String.isNotBlank(BOM_STATUS_DRAFT) ? BOM_STATUS_DRAFT: FiligreenConfigurationUtility.getConfigValueByObjectAndKey('Bill of Materials','BOM_Status_Draft');
        }set;
    }
    
    public Bill_of_Materials__c bom{set;get;}
    public List<BOMLineWrapper> setBOMLines {get; set;}
    public Boolean hasBOMLines {get; set;}
    public String redirectId;
    
    public cloneBOMController(){}
    
    @AuraEnabled
    public static AuraResponse cloneBOM(String recordId){
    AuraResponse r = new AuraResponse('cloneBOMController.cloneBOM()');
        
        cloneBOMController assign = new cloneBOMController();
        
        assign.bom = getBOM(recordId);
        assign.setBOMLines = getBOMLines(recordId);
        
        if(assign.setBOMLines != null && assign.setBOMLines.size() > 0) 
            {
              assign.hasBOMLines = true;
            }

    r.data.put('setBom', assign.bom);
    r.data.put('setBOMLines', assign.setBOMLines);
    r.data.put('hasBOMLines', assign.hasBOMLines);

    return r;
    }
    
    public static Bill_of_Materials__c getBOM(String bomId){
        Bill_of_Materials__c bom;
        if(bomId != null){
            bom = [select Id, Name, BOM_Levels__c, BOM_Routing__r.Name, BOM_Routing__c , BOM_Type__c, Product__c, Product__r.Name, Status__c, Total_BOM_Cost__c, 
                   Revision__c, Phase__c from Bill_of_Materials__c where Id =: bomId];
        }
        return bom;
    }
    
    public static List<BOMLineWrapper> getBOMLines(String bomId){
          List<BOMLineWrapper> bomWrapper = new List<BOMLineWrapper>();
        
          List <BOM_Lines__c> bomLines = [SELECT Id, Name, Effective_From__c , Effective_To__c, Level__c, Ext_Cost__c, Producer_Name__c, Status__c,
                                        Product__c,  Sequence__c, Product__r.Name, Product_Description__c ,Product_Type__c, Qty_Per__c, 
                                        Required_Qty__c, UOM__c, Unit_Cost__c
               							FROM BOM_Lines__c WHERE Bill_of_Material__c =: bomId ORDER BY Name];
        
        for(BOM_Lines__c billofMaterialsLineBOM : bomLines){
            BOMLineWrapper bomLineWrapper = new BOMLineWrapper(billofMaterialsLineBOM);
            bomWrapper.add(bomLineWrapper);
        } 
        return bomWrapper;
    } 
    
    
        @AuraEnabled
    public static AuraResponse cloneBOMLight(Bill_of_Materials__c bom, List<BOMLineWrapper> setBOMLines){
        AuraResponse r = new AuraResponse('cloneBOMController.cloneBOMLight()');
        
        cloneBOMController assign = new cloneBOMController();
        
        List<BOM_Lines__c> bomls = new List<BOM_Lines__c>();
        
        for(BOMLineWrapper bomLineWrapper : setBOMLines){ 
            if(bomLineWrapper.isSelected){ 
               bomls.add(bomLineWrapper.billofMaterialsLineBOM);
            }
        }
    
   
        		Bill_of_Materials__c cloneBOM = bom.clone();
                cloneBOM.Status__c = BOM_STATUS_DRAFT;
                insert cloneBOM;
        
        		List<BOM_Lines__c> BOMLIs = new List<BOM_Lines__c>();
        		for(BOM_Lines__c boml:bomls){
                    BOM_Lines__c bomli = boml.clone();
                    bomli.Bill_of_Material__c = cloneBOM.Id;
                    BOMLIs.add(bomli);
                }
        		insert BOMLIs;

     assign.redirectId  = cloneBOM.Id;	
     r.data.put('redirectId', assign.redirectId); 
     return r;
    }
    
        public class BOMLineWrapper{
        @AuraEnabled
        public Boolean isSelected {get; set;}
        @AuraEnabled
        public BOM_Lines__c billofMaterialsLineBOM {get; set;}
        
        public BOMLineWrapper(BOM_Lines__c billofMaterialsLineBOM){
            this.isSelected = false;
            this.billofMaterialsLineBOM = billofMaterialsLineBOM;
        }
        public BOMLineWrapper(){
            this.isSelected = false;
            this.billofMaterialsLineBOM = billofMaterialsLineBOM;
        }
    }

}