force-app/main/default/objects/Expense_Line__c/Expense_Line__c.object-meta.xml
<CustomObject>
    <label>Expense Line</label>
    <nameField>
        <displayFormat>EXLI-{YYYY}-{MM}-{0000000000}</displayFormat>
        <label>Expense Line</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expense Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Expense_Line__c/fields/ExpenseAmount__c.field-meta.xml
<CustomField>
    <fullName>ExpenseAmount__c</fullName>
    <inlineHelpText>Expense Amount on Receipt, if mileage use 0.58 as IRS mandate.</inlineHelpText>
    <label>Expense Amount</label>
    <precision>14</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Expense_Line__c/fields/ExpenseDate__c.field-meta.xml
<CustomField>
    <fullName>ExpenseDate__c</fullName>
    <inlineHelpText>Date Expense Incurred</inlineHelpText>
    <label>Expense Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Expense_Line__c/fields/ExpenseDescription__c.field-meta.xml
<CustomField>
    <fullName>ExpenseDescription__c</fullName>
    <inlineHelpText>Name of Receipt</inlineHelpText>
    <label>Expense Description</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Expense_Line__c/fields/ExpenseNumber__c.field-meta.xml
<CustomField>
    <fullName>ExpenseNumber__c</fullName>
    <label>Expense Number</label>
    <referenceTo>Expense_Number__c</referenceTo>
    <relationshipName>Expense_Line_IDs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Expense_Line__c/fields/ExpenseType__c.field-meta.xml
<CustomField>
    <fullName>ExpenseType__c</fullName>
    <label>Expense Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Airfare</fullName>
            </value>
            <value>
                <fullName>Breakfast</fullName>
            </value>
            <value>
                <fullName>Conference</fullName>
            </value>
            <value>
                <fullName>Dinner</fullName>
            </value>
            <value>
                <fullName>Entertainment</fullName>
            </value>
            <value>
                <fullName>Event</fullName>
            </value>
            <value>
                <fullName>Exam</fullName>
            </value>
            <value>
                <fullName>Gas</fullName>
            </value>
            <value>
                <fullName>General Supplies</fullName>
            </value>
            <value>
                <fullName>Hotel</fullName>
            </value>
            <value>
                <fullName>Internet</fullName>
            </value>
            <value>
                <fullName>Lunch</fullName>
            </value>
            <value>
                <fullName>Mileage</fullName>
            </value>
            <value>
                <fullName>Parking</fullName>
            </value>
            <value>
                <fullName>Phone</fullName>
            </value>
            <value>
                <fullName>Snacks</fullName>
            </value>
            <value>
                <fullName>Taxi</fullName>
            </value>
            <value>
                <fullName>Tech Services</fullName>
            </value>
            <value>
                <fullName>Tolls</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Expense_Line__c/fields/Qty__c.field-meta.xml
<CustomField>
    <fullName>Qty__c</fullName>
    <inlineHelpText>Enter 1 for each expense item, for mileage enter miles driven</inlineHelpText>
    <label>Qty</label>
    <precision>12</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Expense_Line__c/fields/Related_Account__c.field-meta.xml
<CustomField>
    <fullName>Related_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Enter the account name in which this expense is associated to. If none default to the business unit the expense is attributed to.</inlineHelpText>
    <label>Related Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Expense Lines</relationshipLabel>
    <relationshipName>Expense_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Expense_Number__c/Expense_Number__c.object-meta.xml
<CustomObject>
    <label>Expense</label>
    <nameField>
        <displayFormat>EXP-{YYYY}-{MM}-{0000000000}</displayFormat>
        <label>Expense Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Expense_Number__c/fields/Expense_Approver__c.field-meta.xml
<CustomField>
    <fullName>Expense_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Expense report approver</description>
    <label>Expense Approver</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Expenses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Expense_Number__c/fields/ExpenseStatus__c.field-meta.xml
<CustomField>
    <fullName>ExpenseStatus__c</fullName>
    <label>Expense Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
            <value>
                <fullName>Recalled</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Expense_Number__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Expenses</relationshipLabel>
    <relationshipName>Expenses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Expense_Number__c/fields/Reimbursed__c.field-meta.xml
<CustomField>
    <fullName>Reimbursed__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>True if Approved and Reimbured</inlineHelpText>
    <label>Reimbursed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Expense_Number__c/fields/Reimbursed_Date__c.field-meta.xml
<CustomField>
    <fullName>Reimbursed_Date__c</fullName>
    <inlineHelpText>Reimbursed Pay Period</inlineHelpText>
    <label>Reimbursed Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/UpdateExpenseControllerTest.cls
@isTest
public class UpdateExpenseControllerTest {
    private static testmethod void runTest(){
        Account objAccount = new Account();
        objAccount.Name = 'Test Account1';
        objAccount.Payment_Terms__c = 'COD';
        objAccount.Hide_from_Marketplace__c = false;
        insert objAccount;
        Expense_Number__c  en = new Expense_Number__c (Expense_Approver__c = UserInfo.getUserId(), Project__c = objAccount.Id,ExpenseStatus__c = 'Approved', Reimbursed__c =true,Reimbursed_Date__c = System.today());
        insert en;
        
        Expense_Line__c el = new Expense_Line__c (ExpenseNumber__c = en.Id, ExpenseDate__c = System.today().addDays(2),Related_Account__c = objAccount.Id, Qty__c =1, ExpenseAmount__c =100, ExpenseType__c = 'Event', ExpenseDescription__c = 'Test');
        insert el;
        Test.startTest();
        Approval.lock(en);
        Expense_Number__c  en1 = UpdateExpenseController.getExpenseRecord(en.Id);
        Map<String,Object> detaisl = UpdateExpenseController.updateExpenseRecord(JSON.serialize(en1));
    }
}