force-app/main/default/objects/Bin_Location__c/Bin_Location__c.object-meta.xml
<CustomObject>
    <label>Bin Location</label>
    <nameField>
        <label>Bin Location</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bin Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Bin_Location__c/fields/Inventory_Location__c.field-meta.xml
<CustomField>
    <fullName>Inventory_Location__c</fullName>
    <formula>Rack_Level__r.Rack__r.Inventory_Location__r.Name</formula>
    <label>Inventory Location</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bin_Location__c/fields/Rack__c.field-meta.xml
<CustomField>
    <fullName>Rack__c</fullName>
    <formula>Rack_Level__r.Rack__r.Name</formula>
    <label>Rack</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bin_Location__c/fields/Rack_Level__c.field-meta.xml
<CustomField>
    <fullName>Rack_Level__c</fullName>
    <label>Rack Level</label>
    <referenceTo>Rack_Level__c</referenceTo>
    <relationshipLabel>Bin Locations</relationshipLabel>
    <relationshipName>Bin_Locations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Picklist__c/Picklist__c.object-meta.xml
<CustomObject>
    <description>Picklist is used for Warehouse Picking from inventory Positions</description>
    <label>Picklist</label>
    <nameField>
        <displayFormat>PL-{0000000000}</displayFormat>
        <label>Picklist</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Picklists</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Picklist__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <label>Sales Order</label>
    <referenceTo>Sales_Order__c</referenceTo>
    <relationshipLabel>Picklists</relationshipLabel>
    <relationshipName>Picklists</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Picklist__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>QA Review</fullName>
            </value>
            <value>
                <fullName>QA Confirm</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Picklist_Line__c/Picklist_Line__c.object-meta.xml
<CustomObject>
    <description>Picklist Lines are Line Items within a Picklist and inherites Sales Order Line Items</description>
    <label>Picklist Line</label>
    <nameField>
        <displayFormat>PKLI-{0000000000}</displayFormat>
        <label>Picklist Line</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Picklist Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Picklist_Line__c/fields/Bin_Location__c.field-meta.xml
<CustomField>
    <fullName>Bin_Location__c</fullName>
    <formula>Inventory_Position__r.Bin_Location__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Bin Location</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Picklist_Line__c/fields/Harvest_Batch_or_Lot_Code__c.field-meta.xml
<CustomField>
    <fullName>Harvest_Batch_or_Lot_Code__c</fullName>
    <formula>Inventory_Position__r.Harvest_Batch_Code__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Batch ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Picklist_Line__c/fields/Inventory_Location__c.field-meta.xml
<CustomField>
    <fullName>Inventory_Location__c</fullName>
    <formula>Inventory_Position__r.Inventory_Location__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Inventory Location</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Picklist_Line__c/fields/Is_Sample__c.field-meta.xml
<CustomField>
    <fullName>Is_Sample__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Sample</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Picklist_Line__c/fields/Picklist__c.field-meta.xml
<CustomField>
    <fullName>Picklist__c</fullName>
    <label>Picklist</label>
    <referenceTo>Picklist__c</referenceTo>
    <relationshipLabel>Picklist Lines</relationshipLabel>
    <relationshipName>Picklist_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Picklist_Line__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Name</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Picklist Lines</relationshipLabel>
    <relationshipName>Picklist_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Picklist_Line__c/fields/Purchase_Order__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Order__c</fullName>
    <formula>Inventory_Position__r.Receiving_Line__r.Purchase_Order_Line__r.Purchase_Order__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Purchase Order</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Picklist_Line__c/fields/Qty_to_Pick__c.field-meta.xml
<CustomField>
    <fullName>Qty_to_Pick__c</fullName>
    <description>Sales_Order_Line__r.Qty_Ordered__c</description>
    <formula>Inventory_Position__r.Qty_Allocated__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Qty to Pick</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Picklist_Line__c/fields/Rack__c.field-meta.xml
<CustomField>
    <fullName>Rack__c</fullName>
    <formula>Inventory_Position__r.Rack__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Rack</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Picklist_Line__c/fields/Rack_Level__c.field-meta.xml
<CustomField>
    <fullName>Rack_Level__c</fullName>
    <formula>Inventory_Position__r.Rack_Level__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Rack Level</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Picklist_Line__c/fields/Sales_Order_Line__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Order Line</label>
    <referenceTo>Sales_Order_Line__c</referenceTo>
    <relationshipLabel>Picklist Lines</relationshipLabel>
    <relationshipName>Picklist_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Picklist_Line__c/fields/sorting__c.field-meta.xml
<CustomField>
    <fullName>sorting__c</fullName>
    <label>sorting</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Picklist_Line__c/fields/UID__c.field-meta.xml
<CustomField>
    <fullName>UID__c</fullName>
    <formula>Inventory_Position__r.UID_New__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Source UID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Rack__c/Rack__c.object-meta.xml
<CustomObject>
    <label>Rack</label>
    <nameField>
        <label>Rack</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Racks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Rack__c/fields/Bin_Location__c.field-meta.xml
<CustomField>
    <fullName>Bin_Location__c</fullName>
    <label>del_Bin Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Rack__c/fields/Inventory_Location__c.field-meta.xml
<CustomField>
    <fullName>Inventory_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Inventory Location</label>
    <referenceTo>Inventory_Location__c</referenceTo>
    <relationshipLabel>Racks</relationshipLabel>
    <relationshipName>Racks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Rack__c/fields/Rack_Level__c.field-meta.xml
<CustomField>
    <fullName>Rack_Level__c</fullName>
    <label>del Rack Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Rack_Level__c/Rack_Level__c.object-meta.xml
<CustomObject>
    <label>Rack Level</label>
    <nameField>
        <label>Rack Level</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rack Levels</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Rack_Level__c/fields/Inventory_Location__c.field-meta.xml
<CustomField>
    <fullName>Inventory_Location__c</fullName>
    <formula>Rack__r.Inventory_Location__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Inventory Location</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Rack_Level__c/fields/Rack__c.field-meta.xml
<CustomField>
    <fullName>Rack__c</fullName>
    <label>Rack</label>
    <referenceTo>Rack__c</referenceTo>
    <relationshipLabel>Rack Levels</relationshipLabel>
    <relationshipName>Rack_Levels</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Sales_Order_Line__c/Sales_Order_Line__c.object-meta.xml
<CustomObject>
    <label>Sales Order Line</label>
    <nameField>
        <displayFormat>SOLI-{0000000000}</displayFormat>
        <label>SO Line</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Order_Line__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Name</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Sales Order Lines</relationshipLabel>
    <relationshipName>Sales_Order_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Order_Line__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <label>Sales Order</label>
    <referenceTo>Sales_Order__c</referenceTo>
    <relationshipLabel>Sales Order Lines</relationshipLabel>
    <relationshipName>Sales_Order_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Sales_Order_Line__c/fields/UID__c.field-meta.xml
<CustomField>
    <fullName>UID__c</fullName>
    <label>UID</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PicklistController.cls
/**************************************************************************************
Apex Class Name    : PicklistController 
Test Class Name    :PicklistControllerTest
Version            : 1.0
Created Date       : Aug 28 2018
Function           : Used for PicklistPdf VF page
Modification Log   :
------------------------------------------------------------------------------
 * Developer                   Date                   Description
 * ----------------------------------------------------------------------------
 * Suresh                  08/28/2018              Original Version
*******************************************************************************/
/**************************************************************************************
Apex Class Name    : PicklistController 
Test Class Name    :PicklistControllerTest
Version            : 1.0
Created Date       : Aug 28 2018
Function           : Used for PicklistPdf VF page
Modification Log   :
------------------------------------------------------------------------------
 * Developer                   Date                   Description
 * ----------------------------------------------------------------------------
 * Suresh                  08/28/2018              Original Version
*******************************************************************************/

public class PicklistController {


Public Picklist__c picklist {get; set;}
Public List<PicklistLineWrapper> picklistLineList {get; set;}
Public String recordID {get; set;}

    
    @AuraEnabled
    public static AuraResponse updateSorting(String recordId){ 
        AuraResponse r = new AuraResponse('PicklistController.updateSorting()'); 
        
        List<Picklist_Line__c> picklistLines = new List<Picklist_Line__c>();  List<Picklist_Line__c> printPickListLine = new List<Picklist_Line__c>();
        printPickListLine =[SELECT id,Name,Product_Name__c,Product_Name__r.name,Harvest_Batch_or_Lot_Code__c, Product_Description__c,Producer_Name__c,Inventory_Location__c,Rack__c,Rack_Level__c,  Bin_Location__c,Purchase_Order__c,UID__c,Qty_to_Pick__c,Sales_Order_Line__r.Is_Sample__c,Is_Sample__c,IsPromo__c,Sorting__c FROM Picklist_Line__c WHERE Picklist__c = :recordID  ORDER BY Sorting__c ASC];
        
        for(Picklist_Line__c var:printPickListLine){  Picklist_Line__c pkSorting = new Picklist_Line__c();
                                                    String str = var.Inventory_Location__c+''+var.Rack__c+''+var.Rack_Level__c+''+var.Bin_Location__c;
                                                    str = str.replaceAll('\\D', '');
                                                    if(str!='')   {
                                                        pkSorting.sorting__c =   Decimal.valueOf(str); 
                                                    }  else{
                                                        pkSorting.sorting__c =1;
                                                    }                                  
                                                    
                                                    pkSorting.id= var.id; picklistLines.add(pkSorting);
                                                   }
        
        if(picklistLines.size() > 0){ UPDATE picklistLines;
                                    }
        
        return r;
        
    }
   
    
public PicklistController() {
    Map<ID,String> PicklistLineKeyMap = new Map<ID,String>();
    Map<String,Decimal> PicklistLineQtyMap = new Map<String,Decimal>();
    picklist =new Picklist__c();
    picklistLineList = new List<PicklistLineWrapper>();
    List<Picklist_Line__c> picklistLines = new List<Picklist_Line__c>();
    List<Picklist_Line__c> subPicklistLine = new List<Picklist_Line__c>();
    string status;
    recordID =ApexPages.currentPage().getParameters().get('Id');
    if(recordID!=null){
        picklist =[select id,Sales_Order__c,Sales_Order__r.Name,Status__c,Name,Assigned_To_Name__c,Scheduled_Pick_Date__c,
        Picklist_Lines__c,Receiver_DBA__c,Delivery_City__c,Planned_Ship_Date__c from Picklist__c where id = :recordID];
        
        picklistLines =[SELECT id,Name,Product_Name__c,Product_Name__r.name,Harvest_Batch_or_Lot_Code__c,
                        Product_Description__c,Producer_Name__c,Inventory_Location__c,Rack__c,Rack_Level__c,
                        Bin_Location__c,Purchase_Order__c,UID__c,Qty_to_Pick__c,Sales_Order_Line__r.Is_Sample__c,Is_Sample__c,IsPromo__c,sorting__c
                          FROM Picklist_Line__c WHERE Picklist__c = :recordID  ORDER BY Inventory_Location__c,sorting__c ASC];
        
      
        

        for(Picklist_Line__c var:picklistLines){

            String mapKey = var.Product_Name__c+'-'+var.Producer_Name__c+'-'+var.Inventory_Location__c+'-'+var.Rack__c+'-'+var.Rack_Level__c+'-'+var.Bin_Location__c+'-'+var.UID__c+'-'+var.Harvest_Batch_or_Lot_Code__c+'-'+var.sorting__c;
            mapKey += var.Is_Sample__c;

            if(PicklistLineQtyMap.containskey(mapKey)){ Decimal qty=PicklistLineQtyMap.get(mapKey);
                PicklistLineQtyMap.put(mapKey,qty+var.Qty_to_Pick__c);
            }else {
                PicklistLineKeyMap.put(var.ID,mapKey);
                PicklistLineQtyMap.put(mapKey,var.Qty_to_Pick__c);
            }
            
        }


        for(Picklist_Line__c var:picklistLines){

            String mapKey = var.Product_Name__c+'-'+var.Producer_Name__c+'-'+var.Inventory_Location__c+'-'+var.Rack__c+'-'+var.Rack_Level__c+'-'+var.Bin_Location__c+'-'+var.UID__c+'-'+var.Harvest_Batch_or_Lot_Code__c+'-'+var.sorting__c;
            mapKey += var.Is_Sample__c;
            if(PicklistLineKeyMap.containskey(var.ID) && PicklistLineQtyMap.containskey(mapKey)){
                PicklistLineWrapper wrap= new PicklistLineWrapper(var,PicklistLineQtyMap.get(mapKey));
                picklistLineList.add(wrap);
            }
        }
    }
    }
    
    
    
}