force-app/main/default/objects/Bin_Location__c/Bin_Location__c.object-meta.xml
<CustomObject>
    <label>Bin Location</label>
    <nameField>
        <label>Bin Location</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bin Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Bin_Location__c/fields/Inventory_Location__c.field-meta.xml
<CustomField>
    <fullName>Inventory_Location__c</fullName>
    <formula>Rack_Level__r.Rack__r.Inventory_Location__r.Name</formula>
    <label>Inventory Location</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bin_Location__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <formula>Rack_Level__r.Rack__r.Inventory_Location__r.Site_Name__r.Name</formula>
    <label>Site</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Inventory_Position__c/Inventory_Position__c.object-meta.xml
<CustomObject>
    <label>Inventory Position</label>
    <nameField>
        <displayFormat>IP-{YYYY}-{MM}-{0000000000}</displayFormat>
        <label>Inventory Position</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventory Positions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Inventory_Position__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <formula>HYPERLINK( Sales_Order_Line__r.Sales_Order__c  , Sales_Order_Line__r.Sales_Order__r.Name)</formula>
    <label>Sales Order</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Inventory_Position__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site</label>
    <referenceTo>Site__c</referenceTo>
    <relationshipLabel>Inventory Positions</relationshipLabel>
    <relationshipName>Inventory_Positions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Picklist__c/Picklist__c.object-meta.xml
<CustomObject>
    <description>Picklist is used for Warehouse Picking from inventory Positions</description>
    <label>Picklist</label>
    <nameField>
        <displayFormat>PL-{0000000000}</displayFormat>
        <label>Picklist</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Picklists</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Picklist__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <label>Sales Order</label>
    <referenceTo>Sales_Order__c</referenceTo>
    <relationshipLabel>Picklists</relationshipLabel>
    <relationshipName>Picklists</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Picklist__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site</label>
    <referenceTo>Site__c</referenceTo>
    <relationshipLabel>Picklists</relationshipLabel>
    <relationshipName>Picklists</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Picklist__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>QA Review</fullName>
            </value>
            <value>
                <fullName>QA Confirm</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Picklist_Line__c/Picklist_Line__c.object-meta.xml
<CustomObject>
    <description>Picklist Lines are Line Items within a Picklist and inherites Sales Order Line Items</description>
    <label>Picklist Line</label>
    <nameField>
        <displayFormat>PKLI-{0000000000}</displayFormat>
        <label>Picklist Line</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Picklist Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Picklist_Line__c/fields/Inventory_Position__c.field-meta.xml
<CustomField>
    <fullName>Inventory_Position__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Inventory Position</label>
    <referenceTo>Inventory_Position__c</referenceTo>
    <relationshipLabel>Picklist Lines</relationshipLabel>
    <relationshipName>Picklist_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Picklist_Line__c/fields/Picklist__c.field-meta.xml
<CustomField>
    <fullName>Picklist__c</fullName>
    <label>Picklist</label>
    <referenceTo>Picklist__c</referenceTo>
    <relationshipLabel>Picklist Lines</relationshipLabel>
    <relationshipName>Picklist_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Picklist_Line__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>QA Hold</fullName>
            </value>
            <value>
                <fullName>Shipment Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Order__c/Sales_Order__c.object-meta.xml
<CustomObject>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>SO-{0000000000}</displayFormat>
        <label>Sales Order</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Order__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site</label>
    <referenceTo>Site__c</referenceTo>
    <relationshipLabel>Sales Orders</relationshipLabel>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Order_Line__c/Sales_Order_Line__c.object-meta.xml
<CustomObject>
    <label>Sales Order Line</label>
    <nameField>
        <displayFormat>SOLI-{0000000000}</displayFormat>
        <label>SO Line</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Order_Line__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <label>Sales Order</label>
    <referenceTo>Sales_Order__c</referenceTo>
    <relationshipLabel>Sales Order Lines</relationshipLabel>
    <relationshipName>Sales_Order_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Sales_Order_Line__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <formula>Sales_Order__r.Site__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Site</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Order_Line__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Allocated</fullName>
            </value>
            <value>
                <fullName>Partially Allocated</fullName>
            </value>
            <value>
                <fullName>Back Ordered</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Shipment Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Shipping_Manifest__c/Shipping_Manifest__c.object-meta.xml
<CustomObject>
    <description>Used in the generation of compliance document to enable retail delivery.</description>
    <label>Shipping Manifest</label>
    <nameField>
        <displayFormat>SM-{YYYY}-{MM}-{0000000000}</displayFormat>
        <label>Shipping Manifest</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipping Manifests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Shipping_Manifest__c/fields/Picklist__c.field-meta.xml
<CustomField>
    <fullName>Picklist__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Picklist</label>
    <referenceTo>Picklist__c</referenceTo>
    <relationshipLabel>Shipping Manifests</relationshipLabel>
    <relationshipName>Shipping_Manifests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipping_Manifest__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Order</label>
    <referenceTo>Sales_Order__c</referenceTo>
    <relationshipLabel>Shipping Manifests</relationshipLabel>
    <relationshipName>Shipping_Manifests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipping_Manifest__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site</label>
    <referenceTo>Site__c</referenceTo>
    <relationshipLabel>Shipping Manifests</relationshipLabel>
    <relationshipName>Shipping_Manifests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipping_Manifest__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
            <value>
                <fullName>Shipment Pending</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Pending Delivery</fullName>
            </value>
            <value>
                <fullName>Shipment Complete</fullName>
            </value>
            <value>
                <fullName>In-Transit</fullName>
            </value>
            <value>
                <fullName>Received</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
                <isActive>false</isActive>
                <label>Submitted</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Shipping_Manifest__c/recordTypes/RSM.recordType-meta.xml
<RecordType>
    <fullName>RSM</fullName>
    <active>true</active>
    <description>Used for Retail Shipments - Ship Confirm to &quot;Delivered&quot; Inventory Location, Rename to &quot;Retail&quot;</description>
    <label>RSM</label>
</RecordType>

force-app/main/default/objects/Shipping_Manifest_Line__c/Shipping_Manifest_Line__c.object-meta.xml
<CustomObject>
    <label>Shipping Manifest Line</label>
    <nameField>
        <displayFormat>SML-{0000000000}</displayFormat>
        <label>SM Line</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipping Manifest Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Shipping_Manifest_Line__c/fields/Picklist_Line__c.field-meta.xml
<CustomField>
    <fullName>Picklist_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Picklist Line</label>
    <referenceTo>Picklist_Line__c</referenceTo>
    <relationshipLabel>Shipping Manifest Lines</relationshipLabel>
    <relationshipName>Shipping_Manifest_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipping_Manifest_Line__c/fields/Shipping_Manifest__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Manifest__c</fullName>
    <label>Shipping Manifest</label>
    <referenceTo>Shipping_Manifest__c</referenceTo>
    <relationshipLabel>Shipping Manifest Lines</relationshipLabel>
    <relationshipName>Shipping_Manifest_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Shipping_Manifest_Line__c/recordTypes/RSM_Line.recordType-meta.xml
<RecordType>
    <fullName>RSM_Line</fullName>
    <active>true</active>
    <description>Used for Retail Shipments - Ship Confirm to &quot;Delivered&quot; Inventory Location, Rename to &quot;Retail&quot;</description>
    <label>RSM Line</label>
</RecordType>

force-app/main/default/classes/PickConfirmControllerTest.cls
/**
 * Copyright (c) 2018 Filigreen Distro
 * All rights reserved.
 * PickConfirmControllerTest
 */
@isTest(OnInstall=false SeeAllData=false)
public class PickConfirmControllerTest{

    static PickList__c pickListObj;
    static List<PickList_Line__c> pickListLines;
    static Sales_Order__c salesOrderObj;
    static List<Inventory_Position__c> invPositions;
    static List<Shipping_Manifest__c> rsm;
    static List<Shipping_Manifest_Line__c> rsmLines;
      
    // Test Updating picklist status to confirmed and create RSM and lines
    static testMethod void testUpdatePicklistConfirmedAndCreateRSMAndLines(){
        TestUtilData.skipTrigger = true;
        // Get data created from setup
        retrieveData();
        
        // Create picklist and lines
        pickListObj = TestUtilData.createPicklist(salesOrderObj, 'Open', true);
        Shipping_Manifest__c rsmObj = PicklistSupport.createRSM(pickListObj);
        pickListLines = TestUtilData.createPicklistLines(invPositions, pickListObj.Id, true);
        Id rtId = Schema.SObjectType.Shipping_Manifest_Line__c.getRecordTypeInfosByDeveloperName().get('RSM_Line').getRecordTypeId();
        PicklistSupport.createRSMLine(pickListLines[0],rsmObj.Id,rtId);
        
        PageReference pageRef = Page.PickConfirm;
        pageRef.getParameters().put('id', pickListObj.Id);
        Test.setCurrentPage(pageRef);
        
        ApexPages.StandardController stdController = new ApexPages.StandardController(pickListObj);
        PickConfirmController controllerObj = new PickConfirmController(stdController);
        
        pageRef = controllerObj.pickConfirm();
        
        PickConfirmController.pickConfirm(pickListObj.Id);
     	PLStartPickingController.updatePLPickStart(pickListObj.Id);
        // Verify picklist status
        //System.assertEquals(PicklistSupport.STATUS_QA_REVIEW,[Select Status__c From PickList__c Where Id =:pickListObj.Id].Status__c,'Picklist status mis-match');
        
        // Validate Inventory Location as QA Review
        invPositions = invPositions = [Select Site__c, 
                                       Inventory_Location__r.Name,
                                       Rack__r.Name, 
                                       Rack_Level__r.Name, 
                                       Bin_Location__r.Name
                                       From Inventory_Position__c];
        for(Inventory_Position__c invPosition : invPositions){
            System.assertEquals(PicklistSupport.STATUS_QA_REVIEW, invPosition.Inventory_Location__r.Name,
                                'Inventory Location mis-match');
            System.assertEquals(PicklistSupport.STATUS_QA_REVIEW, invPosition.Rack__r.Name,
                                'Rack mis-match');
            System.assertEquals(PicklistSupport.STATUS_QA_REVIEW, invPosition.Rack_Level__r.Name,
                                'Rack Level mis-match');
            System.assertEquals(PicklistSupport.STATUS_QA_REVIEW, invPosition.Bin_Location__r.Name,
                                'Bin Location mis-match');
        }
                        
        System.assertEquals('/'+String.valueOf(pickListObj.Id), pageRef.getURL(), 'Page reference mis-match');
                PickConfirmController.pickConfirm(pickListObj.Id);

    }
    
    // Test validating already QA Confirmed picklist to confirm
    static testMethod void testValidateQAConfirmedPicklistToConfirm(){
        TestUtilData.skipTrigger = true;
        // Get data created from setup
        retrieveData();
        
        // Create picklist with QA Confirmed status and lines
        pickListObj = TestUtilData.createPicklist(salesOrderObj, PicklistSupport.STATUS_QA_CONFIRM, true);
        pickListLines = TestUtilData.createPicklistLines(invPositions, pickListObj.Id, true);
        
        PageReference pageRef = Page.PickConfirm;
        pageRef.getParameters().put('id', pickListObj.Id);
        Test.setCurrentPage(pageRef);
        
        ApexPages.StandardController stdController = new ApexPages.StandardController(pickListObj);
        PickConfirmController controllerObj = new PickConfirmController(stdController);

        pageRef = controllerObj.pickConfirm();
        
        PickConfirmController.pickConfirm(pickListObj.Id);
        
        List<Account> lstAcc = [SELECT Id,Hold__c from Account LIMIT 10];
        for(Account acc : lstAcc){
        	acc.Hold__c = true;    
        }
        update lstAcc;
        
        List<Sales_Order__c> sOrder = [SELECT Id,Account_Hold_Exception__c from Sales_Order__c LIMIT 10];
        for(Sales_Order__c acc : sOrder){
        	acc.Account_Hold_Exception__c = false;    
        }
        update sOrder;
        
        
        PickConfirmController.pickConfirm(pickListObj.Id);
        
        System.assertEquals(null, pageRef, 'Page reference mis-match');

        // Verify validation messages
        List<ApexPages.Message> msgList = ApexPages.getMessages();
        System.assertEquals(1, msgList.size(), 'Number of Validation messages mis-match');
        System.assert(msgList[0].getDetail().contains(Label.Already_QA_Confirm_Picklist), 'Validation message mis-match');
    }
    
    // Test validating already QA Review picklist to confirm
    static testMethod void testValidateQAReviewPicklistToConfirm(){
        TestUtilData.skipTrigger = true;
        // Get data created from setup
        retrieveData();
        
        // Create picklist with QA Review status and lines
        pickListObj = TestUtilData.createPicklist(salesOrderObj, PicklistSupport.STATUS_QA_REVIEW, true);
        pickListLines = TestUtilData.createPicklistLines(invPositions, pickListObj.Id, true);
         pickListObj = TestUtilData.createPicklist(salesOrderObj, PicklistSupport.STATUS_QA_REVIEW, false);
        pickListLines = TestUtilData.createPicklistLines(invPositions, pickListObj.Id, false);
        PageReference pageRef = Page.PickConfirm;
        pageRef.getParameters().put('id', pickListObj.Id);
        Test.setCurrentPage(pageRef);
        
        ApexPages.StandardController stdController = new ApexPages.StandardController(pickListObj);
        PickConfirmController controllerObj = new PickConfirmController(stdController);

        pageRef = controllerObj.pickConfirm();
          PickConfirmController.pickConfirm(pickListObj.Id);

        System.assertEquals(null, pageRef, 'Page reference mis-match');
                System.assertEquals(null, pageRef, 'Validation message mis-match');

          PickConfirmController.pickConfirm(pickListObj.Id);

        // Verify validation messages
        List<ApexPages.Message> msgList = ApexPages.getMessages();
        System.assertEquals(1, msgList.size(), 'Number of Validation messages mis-match');
        //System.assert(msgList[0].getDetail().contains(Label.Already_QA_Review_Picklist), 'Validation message mis-match');

    }
    
    @TestSetUp
    static void testDataSetUp(){
        Test.setMock(HttpCalloutMock.class, new StateLicense_MockResponseTest()); 
        TestUtilData.skipTrigger = true;
        TestUtilData.createTestData();
    }
    
    // Retrieve data created from data setup
    public static void retrieveData(){
        
        TestUtilData.skipTrigger = true;
        invPositions = [Select Sales_Order_Line__c,
                               Sales_Order_Line__r.Product_Name__c
                               From Inventory_Position__c];
                               
        salesOrderObj = new Sales_Order__c();
        salesOrderObj = [Select Site__c from Sales_Order__c];
                //  PickConfirmController.pickConfirm(pickListObj.Id);

        // Create inventory location with name as "QA Review"
        Inventory_Location__c newInventoryLocation = new Inventory_Location__c();
        newInventoryLocation.Name = 'Test Location';
        newInventoryLocation.Site_Name__c = [Select Id From Site__c LIMIT 1].Id;
        newInventoryLocation.Name = PicklistSupport.STATUS_QA_REVIEW;
        insert newInventoryLocation;
        
        
        // Create Rack with name as "QA Review"
        Rack__c rackSO = new Rack__c();
        rackSO.Inventory_Location__c = newInventoryLocation.Id;
        rackSO.Name = PicklistSupport.STATUS_QA_REVIEW;
        insert rackSO;
        
        // Create Rack Level with name as "QA Review"
        Rack_Level__c rackLevelSO = new Rack_Level__c();
        rackLevelSO.Rack__c = rackSO.Id;
        rackLevelSO.Name = PicklistSupport.STATUS_QA_REVIEW;
        insert rackLevelSO;
        
        // Create Bin location with name as "QA Review"
        Bin_Location__c binLocationSO = new Bin_Location__c();
        binLocationSO.Rack_Level__c = rackLevelSO.Id;
        binLocationSO.Bin_Height__c = 10.0;
        binLocationSO.Bin_Length__c = 10.0;
        binLocationSO.Bin_Width__c = 20.0;
        binLocationSO.Name = PicklistSupport.STATUS_QA_REVIEW;
        insert binLocationSO;
    }
}