force-app/main/default/objects/Bin_Location__c/Bin_Location__c.object-meta.xml
<CustomObject>
    <label>Bin Location</label>
    <nameField>
        <label>Bin Location</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bin Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Bin_Location__c/fields/Cubic_Volume_Utilization__c.field-meta.xml
<CustomField>
    <fullName>Cubic_Volume_Utilization__c</fullName>
    <label>Cubic Volume Utilization</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Inventory_Position__c/Inventory_Position__c.object-meta.xml
<CustomObject>
    <label>Inventory Position</label>
    <nameField>
        <displayFormat>IP-{YYYY}-{MM}-{0000000000}</displayFormat>
        <label>Inventory Position</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventory Positions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Inventory_Position__c/fields/Bin_Location__c.field-meta.xml
<CustomField>
    <fullName>Bin_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Bin in the Rack Level</inlineHelpText>
    <label>Bin Location</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Bin_Location__c.Rack_Level__c</field>
            <operation>equals</operation>
            <valueField>$Source.Rack_Level__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Bin_Location__c</referenceTo>
    <relationshipLabel>Inventory Positions</relationshipLabel>
    <relationshipName>Inventory_Positions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/BatchToUpdateCVUinBin.cls
global class BatchToUpdateCVUinBin implements Database.Batchable<sObject>, Schedulable {
    
    global Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator([SELECT Id, Name, Cubic_Volume_Utilization__c, (SELECT id, name FROM Inventory_Positions__r LIMIT 1) FROM Bin_Location__c]);
    }
    
    global void execute(Database.BatchableContext bc, List<Bin_Location__c> records){
        List<Bin_Location__c> binToUpdate = new List<Bin_Location__c>();
         for(Bin_Location__c bin : records){
             if(bin.Inventory_Positions__r.size() == 0){
                 bin.Cubic_Volume_Utilization__c = 0;
                 binToUpdate.add(bin);
             } 
         }
        if(binToUpdate.size() > 0){
            update binToUpdate;
        }
         
    }
    
    global void execute(SchedulableContext sc){
        Database.executeBatch(new BatchToUpdateCVUinBin());
    } 
    global void finish(Database.BatchableContext bc){}

}