force-app/main/default/objects/Bin_Location__c/Bin_Location__c.object-meta.xml
<CustomObject>
    <label>Bin Location</label>
    <nameField>
        <label>Bin Location</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bin Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Bin_Location__c/fields/Inventory_Location__c.field-meta.xml
<CustomField>
    <fullName>Inventory_Location__c</fullName>
    <formula>Rack_Level__r.Rack__r.Inventory_Location__r.Name</formula>
    <label>Inventory Location</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bin_Location__c/fields/Rack__c.field-meta.xml
<CustomField>
    <fullName>Rack__c</fullName>
    <formula>Rack_Level__r.Rack__r.Name</formula>
    <label>Rack</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bin_Location__c/fields/Rack_Level__c.field-meta.xml
<CustomField>
    <fullName>Rack_Level__c</fullName>
    <label>Rack Level</label>
    <referenceTo>Rack_Level__c</referenceTo>
    <relationshipLabel>Bin Locations</relationshipLabel>
    <relationshipName>Bin_Locations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Bin_Location__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <formula>Rack_Level__r.Rack__r.Inventory_Location__r.Site_Name__r.Name</formula>
    <label>Site</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Inventory_Location__c/Inventory_Location__c.object-meta.xml
<CustomObject>
    <label>Inventory Location</label>
    <nameField>
        <label>Inventory Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inventory Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Inventory_Location__c/fields/Include_in_Heat_Map__c.field-meta.xml
<CustomField>
    <fullName>Include_in_Heat_Map__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Include in Heat Map?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Inventory_Location__c/fields/Site_Name__c.field-meta.xml
<CustomField>
    <fullName>Site_Name__c</fullName>
    <label>Site Name</label>
    <referenceTo>Site__c</referenceTo>
    <relationshipLabel>Inventory Locations</relationshipLabel>
    <relationshipName>Inventory_Locations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Inventory_Position__c/Inventory_Position__c.object-meta.xml
<CustomObject>
    <label>Inventory Position</label>
    <nameField>
        <displayFormat>IP-{YYYY}-{MM}-{0000000000}</displayFormat>
        <label>Inventory Position</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventory Positions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Inventory_Position__c/fields/Bin_Location__c.field-meta.xml
<CustomField>
    <fullName>Bin_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Bin in the Rack Level</inlineHelpText>
    <label>Bin Location</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Bin_Location__c.Rack_Level__c</field>
            <operation>equals</operation>
            <valueField>$Source.Rack_Level__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Bin_Location__c</referenceTo>
    <relationshipLabel>Inventory Positions</relationshipLabel>
    <relationshipName>Inventory_Positions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Inventory_Position__c/fields/Inventory_Location__c.field-meta.xml
<CustomField>
    <fullName>Inventory_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Inventory Location</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Inventory_Location__c.Site_Name__c</field>
            <operation>equals</operation>
            <valueField>$Source.Site__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Inventory_Location__c</referenceTo>
    <relationshipLabel>Inventory Positions</relationshipLabel>
    <relationshipName>Inventory_Positions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Inventory_Position__c/fields/Rack__c.field-meta.xml
<CustomField>
    <fullName>Rack__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Rack in the Inventory location</inlineHelpText>
    <label>Rack</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Rack__c.Inventory_Location__c</field>
            <operation>equals</operation>
            <valueField>$Source.Inventory_Location__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Rack__c</referenceTo>
    <relationshipLabel>Inventory Positions</relationshipLabel>
    <relationshipName>Inventory_Positions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Inventory_Position__c/fields/Rack_Level__c.field-meta.xml
<CustomField>
    <fullName>Rack_Level__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Rack Level in the Rack</inlineHelpText>
    <label>Rack Level</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Rack_Level__c.Rack__c</field>
            <operation>equals</operation>
            <valueField>$Source.Rack__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Rack_Level__c</referenceTo>
    <relationshipLabel>Inventory Positions</relationshipLabel>
    <relationshipName>Inventory_Positions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Inventory_Position__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site</label>
    <referenceTo>Site__c</referenceTo>
    <relationshipLabel>Inventory Positions</relationshipLabel>
    <relationshipName>Inventory_Positions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Rack__c/Rack__c.object-meta.xml
<CustomObject>
    <label>Rack</label>
    <nameField>
        <label>Rack</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Racks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Rack__c/fields/Bin_Location__c.field-meta.xml
<CustomField>
    <fullName>Bin_Location__c</fullName>
    <label>del_Bin Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Rack__c/fields/Inventory_Location__c.field-meta.xml
<CustomField>
    <fullName>Inventory_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Inventory Location</label>
    <referenceTo>Inventory_Location__c</referenceTo>
    <relationshipLabel>Racks</relationshipLabel>
    <relationshipName>Racks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Rack__c/fields/Rack_Level__c.field-meta.xml
<CustomField>
    <fullName>Rack_Level__c</fullName>
    <label>del Rack Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Rack_Level__c/Rack_Level__c.object-meta.xml
<CustomObject>
    <label>Rack Level</label>
    <nameField>
        <label>Rack Level</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rack Levels</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Rack_Level__c/fields/Inventory_Location__c.field-meta.xml
<CustomField>
    <fullName>Inventory_Location__c</fullName>
    <formula>Rack__r.Inventory_Location__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Inventory Location</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Rack_Level__c/fields/Rack__c.field-meta.xml
<CustomField>
    <fullName>Rack__c</fullName>
    <label>Rack</label>
    <referenceTo>Rack__c</referenceTo>
    <relationshipLabel>Rack Levels</relationshipLabel>
    <relationshipName>Rack_Levels</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Site__c/Site__c.object-meta.xml
<CustomObject>
    <description>All objects must have a Site Name and License Class or A or M. For separate sales and inventory record.</description>
    <label>Site</label>
    <nameField>
        <label>Site</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/HeatMapGeneratorTest.cls
@IsTest 
public class HeatMapGeneratorTest {
    @testSetup static void setup() {
        Site__c site = new Site__c(Name='Test Site');
        insert site;
		Inventory_Location__c iLocation = new Inventory_Location__c(Name = 'Test Location',Site_Name__c = site.Id,Include_in_Heat_Map__c = TRUE);
        insert iLocation;
        
        Rack__c rack = new Rack__c(Name = 'Test Rack',Inventory_Location__c = iLocation.Id);
        insert rack;
        Rack_Level__c rackLevel = new Rack_Level__c(Name = 'Test Rack Level',Rack__c = rack.Id);
        insert rackLevel;
        Bin_Location__c binLocation = new Bin_Location__c(Name = 'Test Rack Level',Rack_Level__c = rackLevel.Id);
        insert binLocation;
        
        Rack__c rack1 = new Rack__c(Name = 'Test Rack',Inventory_Location__c = iLocation.Id);
        insert rack1;
        Rack_Level__c rackLevel1 = new Rack_Level__c(Name = 'Test Rack Level',Rack__c = rack.Id);
        insert rackLevel1;
        Bin_Location__c binLocation1 = new Bin_Location__c(Name = 'Test Rack Level',Rack_Level__c = rackLevel.Id);
        insert binLocation1;
        
        Inventory_Position__c iPosition = new Inventory_Position__c(
            Bin_Location__c = binLocation.Id,
            Rack__c  = rack.id,
            Rack_Level__c = rackLevel.Id,
         Inventory_Location__c  = iLocation.Id,
         Site__c  = site.Id);
        insert iPosition;
    }
    @isTest
    public static void testHeatMap(){
        HeatMapGeneratorCtlr heatMap = new HeatMapGeneratorCtlr();
        HeatMapGeneratorCtlr.heatMapGenerator();
        HeatMapGeneratorCtlr.getAllLocations(heatMap.siteId);
        HeatMapGeneratorCtlr.getProcessRackData(heatMap.iLocation);
        System.assertNotEquals(null, heatMap.jsonData);
    }
}