force-app/main/default/objects/Bin_Location__c/Bin_Location__c.object-meta.xml
<CustomObject>
    <label>Bin Location</label>
    <nameField>
        <label>Bin Location</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bin Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Bin_Location__c/fields/Inventory_Location__c.field-meta.xml
<CustomField>
    <fullName>Inventory_Location__c</fullName>
    <formula>Rack_Level__r.Rack__r.Inventory_Location__r.Name</formula>
    <label>Inventory Location</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bin_Location__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <formula>Rack_Level__r.Rack__r.Inventory_Location__r.Site_Name__r.Name</formula>
    <label>Site</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Inventory_Position__c/Inventory_Position__c.object-meta.xml
<CustomObject>
    <label>Inventory Position</label>
    <nameField>
        <displayFormat>IP-{YYYY}-{MM}-{0000000000}</displayFormat>
        <label>Inventory Position</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventory Positions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Inventory_Position__c/fields/Hold__c.field-meta.xml
<CustomField>
    <fullName>Hold__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Inventory OnHOld for Order Allocation</inlineHelpText>
    <label>Hold</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Inventory_Position__c/fields/Inventory_Location__c.field-meta.xml
<CustomField>
    <fullName>Inventory_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Inventory Location</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Inventory_Location__c.Site_Name__c</field>
            <operation>equals</operation>
            <valueField>$Source.Site__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Inventory_Location__c</referenceTo>
    <relationshipLabel>Inventory Positions</relationshipLabel>
    <relationshipName>Inventory_Positions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Inventory_Position__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <formula>HYPERLINK( Sales_Order_Line__r.Sales_Order__c  , Sales_Order_Line__r.Sales_Order__r.Name)</formula>
    <label>Sales Order</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Inventory_Position__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site</label>
    <referenceTo>Site__c</referenceTo>
    <relationshipLabel>Inventory Positions</relationshipLabel>
    <relationshipName>Inventory_Positions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Inventory_Position__c/fields/Supplier_Name__c.field-meta.xml
<CustomField>
    <fullName>Supplier_Name__c</fullName>
    <formula>Receiving_Line__r.Purchase_Order_Line__r.Purchase_Order__r.Supplier_Name__r.Name</formula>
    <label>Supplier Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Picklist__c/Picklist__c.object-meta.xml
<CustomObject>
    <description>Picklist is used for Warehouse Picking from inventory Positions</description>
    <label>Picklist</label>
    <nameField>
        <displayFormat>PL-{0000000000}</displayFormat>
        <label>Picklist</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Picklists</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Picklist__c/fields/Pick_Confirm_Date__c.field-meta.xml
<CustomField>
    <fullName>Pick_Confirm_Date__c</fullName>
    <label>Pick Confirm Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Picklist__c/fields/Pick_End__c.field-meta.xml
<CustomField>
    <fullName>Pick_End__c</fullName>
    <label>Pick End</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Picklist__c/fields/Picklist_Lines__c.field-meta.xml
<CustomField>
    <fullName>Picklist_Lines__c</fullName>
    <label>Picklist Lines</label>
    <summaryForeignKey>Picklist_Line__c.Picklist__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Picklist__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <label>Sales Order</label>
    <referenceTo>Sales_Order__c</referenceTo>
    <relationshipLabel>Picklists</relationshipLabel>
    <relationshipName>Picklists</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Picklist__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site</label>
    <referenceTo>Site__c</referenceTo>
    <relationshipLabel>Picklists</relationshipLabel>
    <relationshipName>Picklists</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Picklist__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>QA Review</fullName>
            </value>
            <value>
                <fullName>QA Confirm</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Picklist_Line__c/Picklist_Line__c.object-meta.xml
<CustomObject>
    <description>Picklist Lines are Line Items within a Picklist and inherites Sales Order Line Items</description>
    <label>Picklist Line</label>
    <nameField>
        <displayFormat>PKLI-{0000000000}</displayFormat>
        <label>Picklist Line</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Picklist Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Picklist_Line__c/fields/Inventory_Location__c.field-meta.xml
<CustomField>
    <fullName>Inventory_Location__c</fullName>
    <formula>Inventory_Position__r.Inventory_Location__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Inventory Location</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Picklist_Line__c/fields/Inventory_Position__c.field-meta.xml
<CustomField>
    <fullName>Inventory_Position__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Inventory Position</label>
    <referenceTo>Inventory_Position__c</referenceTo>
    <relationshipLabel>Picklist Lines</relationshipLabel>
    <relationshipName>Picklist_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Picklist_Line__c/fields/Picklist__c.field-meta.xml
<CustomField>
    <fullName>Picklist__c</fullName>
    <label>Picklist</label>
    <referenceTo>Picklist__c</referenceTo>
    <relationshipLabel>Picklist Lines</relationshipLabel>
    <relationshipName>Picklist_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Picklist_Line__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>QA Hold</fullName>
            </value>
            <value>
                <fullName>Shipment Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Rack__c/Rack__c.object-meta.xml
<CustomObject>
    <label>Rack</label>
    <nameField>
        <label>Rack</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Racks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Rack__c/fields/Inventory_Location__c.field-meta.xml
<CustomField>
    <fullName>Inventory_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Inventory Location</label>
    <referenceTo>Inventory_Location__c</referenceTo>
    <relationshipLabel>Racks</relationshipLabel>
    <relationshipName>Racks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Rack_Level__c/Rack_Level__c.object-meta.xml
<CustomObject>
    <label>Rack Level</label>
    <nameField>
        <label>Rack Level</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rack Levels</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Rack_Level__c/fields/Inventory_Location__c.field-meta.xml
<CustomField>
    <fullName>Inventory_Location__c</fullName>
    <formula>Rack__r.Inventory_Location__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Inventory Location</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Order__c/Sales_Order__c.object-meta.xml
<CustomObject>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>SO-{0000000000}</displayFormat>
        <label>Sales Order</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Order__c/fields/Account_Hold_Exception__c.field-meta.xml
<CustomField>
    <fullName>Account_Hold_Exception__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Override Account Hold to allocate and process the order.</inlineHelpText>
    <label>Account Hold Exception</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Sales_Order__c/fields/Distributor_Name__c.field-meta.xml
<CustomField>
    <fullName>Distributor_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Distributor Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sales Orders as Distributor</relationshipLabel>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Order__c/fields/Receiver_Name__c.field-meta.xml
<CustomField>
    <fullName>Receiver_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Receiver Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sales Orders as Receiver</relationshipLabel>
    <relationshipName>Sales_Orders1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Order__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site</label>
    <referenceTo>Site__c</referenceTo>
    <relationshipLabel>Sales Orders</relationshipLabel>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Order__c/fields/Supplier_Name__c.field-meta.xml
<CustomField>
    <fullName>Supplier_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Supplier Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sales Orders as Supplier</relationshipLabel>
    <relationshipName>Sales_Orders2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Site__c/Site__c.object-meta.xml
<CustomObject>
    <description>All objects must have a Site Name and License Class or A or M. For separate sales and inventory record.</description>
    <label>Site</label>
    <nameField>
        <label>Site</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Site__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active ?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Site_User__c/Site_User__c.object-meta.xml
<CustomObject>
    <description>Users assigned to one or more warehouses. Visibility in putaway and Available inventory is managed using user record mapping.</description>
    <label>Site User</label>
    <nameField>
        <displayFormat>SU-{00000}</displayFormat>
        <label>Site User #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site Users</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Site_User__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <label>Site</label>
    <referenceTo>Site__c</referenceTo>
    <relationshipLabel>Site Users</relationshipLabel>
    <relationshipName>Site_Users</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Site_User__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Select user to view warehouse inventory details.</inlineHelpText>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Site_Users</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Site_User__c/fields/User_Active__c.field-meta.xml
<CustomField>
    <fullName>User_Active__c</fullName>
    <formula>User__r.IsActive</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>User Active?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/PickConfirmController.cls
/**
 * Copyright (c) 2018 Filigreen Distro
 * All rights reserved.
 * PickConfirmController
 */
public class PickConfirmController{  
 private static String ERR_MSG_LA_SITE{
        get{
            return String.isNotBlank(ERR_MSG_LA_SITE) ? ERR_MSG_LA_SITE : FiligreenConfigurationUtility.getConfigValueByObjectAndKey('Picklist','Err_Msg_Pickconfirm_LASite');
        }set;
    }
    private ApexPages.StandardController stdController;
    private Picklist__c picklistObj = null;
    private Id rsmId;

public  PickConfirmController()
        { 
           
        }

    // Constructor
    public PickConfirmController(ApexPages.StandardController controller) {
        this.stdController = controller;
        picklistObj = (Picklist__c)stdController.getRecord();
    }
    
    
    
    
    public class UserException extends Exception{ }
    
    @AuraEnabled
    public static AuraResponse pickConfirm(String recordId){
        AuraResponse r = new AuraResponse('PickConfirmController.pickConfirm()');    
        PickConfirmController assign = new PickConfirmController();
        Picklist__c  picklistObj = new Picklist__c();
        assign.picklistObj = new Picklist__c();
        Savepoint savePoint;
        
        try {
            // Define save point for rollback
            savePoint = Database.setSavepoint();
                   
                    picklist__c pick = [select id ,Sales_Order__c,Site__c,Site__r.Name from  picklist__c where id  =: recordId];

          

            Sales_Order__c SOHold = [select id,Supplier_Name__c ,Receiver_Name__c,Distributor_Name__c,Account_Hold_Exception__c, (select id, Sales_Order__c from picklists__r)  from Sales_Order__c where id =: pick.Sales_Order__c];  
            system.debug('so>>>>'+SOHold);
            Account  supAcc = [SELECT  id , Hold__c, DBA__c  from Account  where id =:SOHold.Supplier_Name__c];
            Account  recAcc = [SELECT  id , Hold__c, DBA__c  from Account  where id =:SOHold.Receiver_Name__c];
            Account  disAcc = [SELECT  id , Hold__c, DBA__c  from Account  where id =:SOHold.Distributor_Name__c];
            String accountName = '';
            Set<String> my_list = new Set<String>();
            if((supAcc.Hold__c == true || recAcc.Hold__c == true || disAcc.Hold__c == true) && SOHold.Account_Hold_Exception__c == false)
            {
                if(supAcc.Hold__c == true){
                    my_list.add(supAcc.DBA__c);
                }
                if(disAcc.Hold__c == true){
                    my_list.add(disAcc.DBA__c);
                }
                if(recAcc.Hold__c == true){
                    my_list.add(recAcc.DBA__c);
                }
                accountName = String.join(new List<String>(my_list), ', ');  
                String ErrorMessage = 'Account: '+ accountName + ' is on HOLD. Please check with Finance team.';
                r.data.put('errorMsg',ErrorMessage);
            }
             String loggedUserUserName = UserInfo.getName();
            List<Site_User__c> lstusersitedata =[select id ,name,User__c,User__r.Name ,User_Active__c,Site__c,Site__r.Active__c,Active__c from Site_User__c where User__r.Name =:loggedUserUserName and Site__c=:pick.Site__c and Site__r.Active__c=True and User_Active__c=True and Active__c=True];
            system.debug('usersite>>>>'+lstusersitedata); 
            system.debug('usersite>>>>'+lstusersitedata.size());
            
            if(lstusersitedata.size()==0){
                r.data.put('errormsgSite',ERR_MSG_LA_SITE);
                return r;  
            }
            else{
                assign.picklistObj = PicklistSupport.retrievePicklistAndLines(recordId);
                
                // Change picklist status to QA Review
                if(assign.picklistObj.Status__c != PicklistSupport.STATUS_QA_CONFIRM &&
                   assign.picklistObj.Status__c != PicklistSupport.STATUS_QA_REVIEW){  assign.picklistObj.Status__c = PicklistSupport.STATUS_QA_REVIEW;
                       //update assign.picklistObj;
                       system.debug('statuspick >>>>>>>'+assign.picklistObj.Status__c);
                       assign.picklistObj.Pick_End__c =system.now();assign.picklistObj.Pick_Confirm_Date__c = system.today();
                       string statuspick = assign.picklistObj.Status__c;  r.data.put('statuspick',statuspick);
                       system.debug('statuspick >>>>'+statuspick);
                       // Update Inventory Positions by moving Inventory Location, Rack, Rack Level and Bin Location to
                       // "QA Review"
                       Set<Id> invPositionIds = new Set<Id>(); List<Inventory_Position__c> invPositions = new List<Inventory_Position__c>();
                       Set<Id> siteIds = new Set<Id>();
                       for(Picklist_Line__c picklistLineObj : assign.picklistObj.Picklist_Lines__r){
                           if(picklistLineObj.Status__c != 'Cancelled' && picklistLineObj.Status__c != 'Rejected'){invPositionIds.add(picklistLineObj.Inventory_Position__c);
                               siteIds.add(picklistLineObj.Inventory_Position__r.Site__c);    
                           }
                       }
                       System.debug('Size = '+invPositionIds.size());
                       if(invPositionIds.size() > 0){ update assign.picklistObj;
                           invPositions = [Select Site__c, Inventory_Location__c,Rack__c,Rack_Level__c,  Bin_Location__c From Inventory_Position__c Where Id IN: invPositionIds];
                           InventoryPositionSupport.updateInvPositions(invPositions, siteIds, PicklistSupport.STATUS_QA_REVIEW);
                           system.debug('i am inside update');    
                       }
                       
                   }else{
                       if(assign.picklistObj.Status__c == PicklistSupport.STATUS_QA_CONFIRM){   string statusBQ = assign.picklistObj.Status__c;
                           r.data.put('statusBQ',statusBQ); return r;
                       }else if(assign.picklistObj.Status__c == PicklistSupport.STATUS_QA_REVIEW){}
                       
                       system.debug('i am inside 2nd if');
                       string statusBQ = assign.picklistObj.Status__c;r.data.put('statusBQ',statusBQ);
                       system.debug('statusBQ >>>>'+statusBQ);
                       
                       // r.data.put('picklistObj', assign.picklistObj.Status__c);
                       system.debug('assign.picklistObj.Status__c>>>>'+assign.picklistObj.Status__c);
                       return r; 
                   }
            }
            
            
        }catch (Exception ex){
            Database.rollback(savePoint);	
            ErrorLogs.log('PickConfirmController:pickConfirm()', 
                          ex.getStackTraceString(), ex.getMessage());
            ApexPages.Message msg = new ApexPages.Message(ApexPages.Severity.ERROR,ex.getMessage());
            ApexPages.addMessage(msg);
            return null;
        }
        return r;
    }
    /**
     * Change picklist status to QA Review
     *
     * @return PageReference of picklist detail page
     */
    public PageReference pickConfirm() {
        PageReference pageRef = null;
        
        Savepoint savePoint;
        
        try {
            
            // Define save point for rollback
            savePoint = Database.setSavepoint();
    

            picklistObj = PicklistSupport.retrievePicklistAndLines(picklistObj.Id);
            
            // Change picklist status to QA Review
            if(picklistObj.Status__c != PicklistSupport.STATUS_QA_CONFIRM &&
               picklistObj.Status__c != PicklistSupport.STATUS_QA_REVIEW){
                picklistObj.Status__c = PicklistSupport.STATUS_QA_REVIEW;
                update picklistObj;
                
                // Update Inventory Positions by moving Inventory Location, Rack, Rack Level and Bin Location to
                // "QA Review"
                Set<Id> invPositionIds = new Set<Id>();
                List<Inventory_Position__c> invPositions = new List<Inventory_Position__c>();
                Set<Id> siteIds = new Set<Id>();
                for(Picklist_Line__c picklistLineObj : picklistObj.Picklist_Lines__r){
                    invPositionIds.add(picklistLineObj.Inventory_Position__c);
                    siteIds.add(picklistLineObj.Inventory_Position__r.Site__c);
                }
                
                invPositions = [Select Site__c, 
                                       Inventory_Location__c,
                                       Rack__c, 
                                       Rack_Level__c, 
                                       Bin_Location__c
                                       From Inventory_Position__c 
                                       Where Id IN: invPositionIds];
                InventoryPositionSupport.updateInvPositions(invPositions, siteIds, PicklistSupport.STATUS_QA_REVIEW);
                   system.debug('i am in update');
            }else{
                ApexPages.Message msg;
                String errMessage;
                if(picklistObj.Status__c == PicklistSupport.STATUS_QA_CONFIRM){
                    errMessage = Label.Already_QA_Confirm_Picklist;
                }else if(picklistObj.Status__c == PicklistSupport.STATUS_QA_REVIEW){
                    errMessage = Label.Already_QA_Review_Picklist;
                }
                msg = new ApexPages.Message(ApexPages.Severity.WARNING, errMessage);
                ApexPages.addMessage(msg);
                return null;
            }
        }catch (Exception ex){
            Database.rollback(savePoint);
            ErrorLogs.log('PickConfirmController:pickConfirm()', 
                          ex.getStackTraceString(), ex.getMessage());
            ApexPages.Message msg = new ApexPages.Message(ApexPages.Severity.ERROR,ex.getMessage());
            ApexPages.addMessage(msg);
            return null;
        }
        system.debug('i am chnaging open to qa');
        return redirectToPickList();
    }

    /**
     * Redirect to Picklist detail page
     *
     * @return PageReference
     */         
    public PageReference redirectToPickList() {
        PageReference pageRef;
        if(picklistObj != null){
            pageRef = new PageReference('/'+picklistObj.Id);
        }else{
            pageRef = stdController.view();
        }
        pageRef.setRedirect(true);
        return pageRef;
    }
}