force-app/main/default/objects/Bin_Location__c/Bin_Location__c.object-meta.xml
<CustomObject>
    <label>Bin Location</label>
    <nameField>
        <label>Bin Location</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bin Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Bin_Location__c/fields/Inventory_Location__c.field-meta.xml
<CustomField>
    <fullName>Inventory_Location__c</fullName>
    <formula>Rack_Level__r.Rack__r.Inventory_Location__r.Name</formula>
    <label>Inventory Location</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bin_Location__c/fields/Rack__c.field-meta.xml
<CustomField>
    <fullName>Rack__c</fullName>
    <formula>Rack_Level__r.Rack__r.Name</formula>
    <label>Rack</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bin_Location__c/fields/Rack_Level__c.field-meta.xml
<CustomField>
    <fullName>Rack_Level__c</fullName>
    <label>Rack Level</label>
    <referenceTo>Rack_Level__c</referenceTo>
    <relationshipLabel>Bin Locations</relationshipLabel>
    <relationshipName>Bin_Locations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Bin_Location__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <formula>Rack_Level__r.Rack__r.Inventory_Location__r.Site_Name__r.Name</formula>
    <label>Site</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Inventory_Location__c/Inventory_Location__c.object-meta.xml
<CustomObject>
    <label>Inventory Location</label>
    <nameField>
        <label>Inventory Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inventory Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Inventory_Location__c/fields/Include_Auto_Merge_IP__c.field-meta.xml
<CustomField>
    <fullName>Include_Auto_Merge_IP__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Include Auto Merge IP</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Inventory_Position__c/Inventory_Position__c.object-meta.xml
<CustomObject>
    <label>Inventory Position</label>
    <nameField>
        <displayFormat>IP-{YYYY}-{MM}-{0000000000}</displayFormat>
        <label>Inventory Position</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventory Positions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Inventory_Position__c/fields/Bin_Location__c.field-meta.xml
<CustomField>
    <fullName>Bin_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Bin in the Rack Level</inlineHelpText>
    <label>Bin Location</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Bin_Location__c.Rack_Level__c</field>
            <operation>equals</operation>
            <valueField>$Source.Rack_Level__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Bin_Location__c</referenceTo>
    <relationshipLabel>Inventory Positions</relationshipLabel>
    <relationshipName>Inventory_Positions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Inventory_Position__c/fields/Inventory_Location__c.field-meta.xml
<CustomField>
    <fullName>Inventory_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Inventory Location</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Inventory_Location__c.Site_Name__c</field>
            <operation>equals</operation>
            <valueField>$Source.Site__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Inventory_Location__c</referenceTo>
    <relationshipLabel>Inventory Positions</relationshipLabel>
    <relationshipName>Inventory_Positions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Inventory_Position__c/fields/Qty_Allocated__c.field-meta.xml
<CustomField>
    <fullName>Qty_Allocated__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Qty Allocated</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Inventory_Position__c/fields/Qty_On_Hand__c.field-meta.xml
<CustomField>
    <fullName>Qty_On_Hand__c</fullName>
    <label>Qty On Hand</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Inventory_Position__c/fields/Rack__c.field-meta.xml
<CustomField>
    <fullName>Rack__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Rack in the Inventory location</inlineHelpText>
    <label>Rack</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Rack__c.Inventory_Location__c</field>
            <operation>equals</operation>
            <valueField>$Source.Inventory_Location__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Rack__c</referenceTo>
    <relationshipLabel>Inventory Positions</relationshipLabel>
    <relationshipName>Inventory_Positions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Inventory_Position__c/fields/Rack_Level__c.field-meta.xml
<CustomField>
    <fullName>Rack_Level__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Rack Level in the Rack</inlineHelpText>
    <label>Rack Level</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Rack_Level__c.Rack__c</field>
            <operation>equals</operation>
            <valueField>$Source.Rack__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Rack_Level__c</referenceTo>
    <relationshipLabel>Inventory Positions</relationshipLabel>
    <relationshipName>Inventory_Positions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Inventory_Position__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site</label>
    <referenceTo>Site__c</referenceTo>
    <relationshipLabel>Inventory Positions</relationshipLabel>
    <relationshipName>Inventory_Positions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/Purchase_Order__c.object-meta.xml
<CustomObject>
    <label>Purchase Order</label>
    <nameField>
        <displayFormat>PO-{0000000000}</displayFormat>
        <label>Purchase Order</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Purchase_Order__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site</label>
    <referenceTo>Site__c</referenceTo>
    <relationshipLabel>Purchase Orders</relationshipLabel>
    <relationshipName>Purchase_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase_Order_Line__c/Purchase_Order_Line__c.object-meta.xml
<CustomObject>
    <label>Purchase Order Line</label>
    <nameField>
        <displayFormat>POLI-{0000000000}</displayFormat>
        <label>PO Line</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Purchase_Order_Line__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <formula>Purchase_Order__r.Site__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Site</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Rack__c/Rack__c.object-meta.xml
<CustomObject>
    <label>Rack</label>
    <nameField>
        <label>Rack</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Racks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Rack__c/fields/Inventory_Location__c.field-meta.xml
<CustomField>
    <fullName>Inventory_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Inventory Location</label>
    <referenceTo>Inventory_Location__c</referenceTo>
    <relationshipLabel>Racks</relationshipLabel>
    <relationshipName>Racks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Rack__c/fields/Rack_Level__c.field-meta.xml
<CustomField>
    <fullName>Rack_Level__c</fullName>
    <label>del Rack Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Rack_Level__c/Rack_Level__c.object-meta.xml
<CustomObject>
    <label>Rack Level</label>
    <nameField>
        <label>Rack Level</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rack Levels</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Rack_Level__c/fields/Inventory_Location__c.field-meta.xml
<CustomField>
    <fullName>Inventory_Location__c</fullName>
    <formula>Rack__r.Inventory_Location__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Inventory Location</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Rack_Level__c/fields/Rack__c.field-meta.xml
<CustomField>
    <fullName>Rack__c</fullName>
    <label>Rack</label>
    <referenceTo>Rack__c</referenceTo>
    <relationshipLabel>Rack Levels</relationshipLabel>
    <relationshipName>Rack_Levels</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Receiving_Line__c/Receiving_Line__c.object-meta.xml
<CustomObject>
    <label>Receiving Line</label>
    <nameField>
        <displayFormat>RELI-{0000000000}</displayFormat>
        <label>Receiving Line</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Receiving Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Receiving_Line__c/fields/Inventory_Location__c.field-meta.xml
<CustomField>
    <fullName>Inventory_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Inventory Location</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Inventory_Location__c.Site_Name__c</field>
            <operation>equals</operation>
            <valueField>$Source.Site__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Inventory_Location__c</referenceTo>
    <relationshipLabel>Receiving Lines</relationshipLabel>
    <relationshipName>Receiving_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Receiving_Line__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site</label>
    <referenceTo>Site__c</referenceTo>
    <relationshipLabel>Receiving Lines</relationshipLabel>
    <relationshipName>Receiving_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Order_Line__c/Sales_Order_Line__c.object-meta.xml
<CustomObject>
    <label>Sales Order Line</label>
    <nameField>
        <displayFormat>SOLI-{0000000000}</displayFormat>
        <label>SO Line</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Order_Line__c/fields/Qty_Allocated__c.field-meta.xml
<CustomField>
    <fullName>Qty_Allocated__c</fullName>
    <label>Qty Allocated</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sales_Order_Line__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <formula>Sales_Order__r.Site__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Site</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UID__c/UID__c.object-meta.xml
<CustomObject>
    <description>Unique Identifiers, RFID Tags from Track &amp; Trace</description>
    <label>UID</label>
    <nameField>
        <label>UID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>UIDs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UID__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site</label>
    <referenceTo>Site__c</referenceTo>
    <relationshipLabel>UIDs</relationshipLabel>
    <relationshipName>UIDs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/MergeIPsBatch.cls
global class MergeIPsBatch implements Database.Batchable<Inventory_Location__c>,Schedulable {
     
    global Iterable<Inventory_Location__c> start(Database.BatchableContext bc) {
        // collect the batches of Inventory Locations to be passed to execute where Include_Auto_Merge_IP__c is checked.
        return [Select Id from Inventory_Location__c Where Include_Auto_Merge_IP__c = true];
    }
    
    global void execute(Database.BatchableContext bc, List<Inventory_Location__c> records){
        String inventoryLocationId = records[0].Id;
        Boolean isMerge = true;
        String mergeTo = '';
        Decimal totalQty = 0;
        Map<String,String> valueChecker = new Map<String,String>();
        List<Inventory_Position__c> ls = [SELECT Id,Qty_On_Hand__c,Qty_Allocated__c, Site__c ,Inventory_Location__c ,Rack__c, Rack_Level__c, Bin_Location__c,
                                          Ownership__c, Sales_Order_Line__c,Harvest_Batch_Code__c, UID__c,Receiving_Line__c,Hold__c,Product_Name__c,Product_Name__r.IsActive, 
                                          Lab_Test_Status__c,Receiving_Line__r.Purchase_Order_Line__r.Purchase_Order__c,Date_Received__c
                                          FROM Inventory_Position__c WHERE Inventory_Location__c = :inventoryLocationId AND Product_Name__r.IsActive =: true AND (Qty_Allocated__c =: 0 OR Qty_Allocated__c =: null OR Qty_Allocated__c =: 0.00) AND Sales_Order_Line__c =: null Order By CreatedDate Asc];
        Map<String,List<Inventory_Position__c>> data = new Map<String,List<Inventory_Position__c>>();
        System.debug('Hello = '+ls.size());
        for(Inventory_Position__c obj : ls){
            String combination = obj.Site__c+'_' + obj.Hold__c+'_';
            combination += obj.Rack__c+'_'+obj.Rack_Level__c+'_';
            combination += obj.Bin_Location__c+'_'+obj.Ownership__c+'_'+obj.Date_Received__c+'_';
            combination += obj.Harvest_Batch_Code__c+'_';
            combination += obj.UID__c+'_'+obj.Lab_Test_Status__c+'_'+obj.Receiving_Line__c;
            List<Inventory_Position__c> ips = new List<Inventory_Position__c>();
            
            if(data.containsKey(combination)) ips = data.get(combination);

            ips.add(obj);
            data.put(combination,ips);
        }  //end for
        Set<Id> toDelete = new Set<Id>();
        List<Inventory_Position__c> toUpdate = new List<Inventory_Position__c>();
        Set<String> nonDuplicate = new Set<String>();
        for(String cmb : data.keySet()){
            totalQty = 0;
            String mergeId = '';
            if(data.get(cmb).size() > 1){
                for(Inventory_Position__c ip : data.get(cmb)){
                    if(nonDuplicate.contains(cmb)){
                        toDelete.add(ip.Id);
                    }else{
                        nonDuplicate.add(cmb);
                        mergeId = ip.Id;
                    }
                    totalQty += ip.Qty_On_Hand__c != null ? ip.Qty_On_Hand__c : 0;
                    //totalQtyAllocated += ip.Qty_Allocated__c != null ? ip.Qty_Allocated__c : 0;
                }
                toUpdate.add(new Inventory_Position__c(Id = mergeId,Qty_On_Hand__c = totalQty));
            }
        }
        try{
            update toUpdate;
            DELETE [SELECT Id FROM Inventory_Position__c WHERE Id = :toDelete];
        }catch(Exception ex){
            return;
        }
    }
    global void execute(SchedulableContext sc){
        Database.executeBatch(new MergeIPsBatch(), 1);
    }    
    global void finish(Database.BatchableContext bc){
        // execute any post-processing operations
    }
}