force-app/main/default/objects/Inventory_Position__c/Inventory_Position__c.object-meta.xml
<CustomObject>
    <label>Inventory Position</label>
    <nameField>
        <displayFormat>IP-{YYYY}-{MM}-{0000000000}</displayFormat>
        <label>Inventory Position</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventory Positions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Inventory_Position__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <formula>HYPERLINK( Sales_Order_Line__r.Sales_Order__c  , Sales_Order_Line__r.Sales_Order__r.Name)</formula>
    <label>Sales Order</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Inventory_Position__c/fields/Sales_Order_Line__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Order Line</label>
    <referenceTo>Sales_Order_Line__c</referenceTo>
    <relationshipLabel>Inventory Positions</relationshipLabel>
    <relationshipName>Inventory_Positions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Picklist__c/Picklist__c.object-meta.xml
<CustomObject>
    <description>Picklist is used for Warehouse Picking from inventory Positions</description>
    <label>Picklist</label>
    <nameField>
        <displayFormat>PL-{0000000000}</displayFormat>
        <label>Picklist</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Picklists</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Picklist__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <label>Sales Order</label>
    <referenceTo>Sales_Order__c</referenceTo>
    <relationshipLabel>Picklists</relationshipLabel>
    <relationshipName>Picklists</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Picklist__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>QA Review</fullName>
            </value>
            <value>
                <fullName>QA Confirm</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Picklist_Line__c/Picklist_Line__c.object-meta.xml
<CustomObject>
    <description>Picklist Lines are Line Items within a Picklist and inherites Sales Order Line Items</description>
    <label>Picklist Line</label>
    <nameField>
        <displayFormat>PKLI-{0000000000}</displayFormat>
        <label>Picklist Line</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Picklist Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Picklist_Line__c/fields/Inventory_Position__c.field-meta.xml
<CustomField>
    <fullName>Inventory_Position__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Inventory Position</label>
    <referenceTo>Inventory_Position__c</referenceTo>
    <relationshipLabel>Picklist Lines</relationshipLabel>
    <relationshipName>Picklist_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Picklist_Line__c/fields/Picklist__c.field-meta.xml
<CustomField>
    <fullName>Picklist__c</fullName>
    <label>Picklist</label>
    <referenceTo>Picklist__c</referenceTo>
    <relationshipLabel>Picklist Lines</relationshipLabel>
    <relationshipName>Picklist_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Picklist_Line__c/fields/Sales_Order_Line__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Order Line</label>
    <referenceTo>Sales_Order_Line__c</referenceTo>
    <relationshipLabel>Picklist Lines</relationshipLabel>
    <relationshipName>Picklist_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Picklist_Line__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>QA Hold</fullName>
            </value>
            <value>
                <fullName>Shipment Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Order__c/Sales_Order__c.object-meta.xml
<CustomObject>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>SO-{0000000000}</displayFormat>
        <label>Sales Order</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Order__c/fields/Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Vehicle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vehicle</label>
    <referenceTo>Vehicles__c</referenceTo>
    <relationshipLabel>Sales Orders</relationshipLabel>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Order_Line__c/Sales_Order_Line__c.object-meta.xml
<CustomObject>
    <label>Sales Order Line</label>
    <nameField>
        <displayFormat>SOLI-{0000000000}</displayFormat>
        <label>SO Line</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Order_Line__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <label>Sales Order</label>
    <referenceTo>Sales_Order__c</referenceTo>
    <relationshipLabel>Sales Order Lines</relationshipLabel>
    <relationshipName>Sales_Order_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Sales_Order_Line__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Allocated</fullName>
            </value>
            <value>
                <fullName>Partially Allocated</fullName>
            </value>
            <value>
                <fullName>Back Ordered</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Shipment Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Shipping_Manifest__c/Shipping_Manifest__c.object-meta.xml
<CustomObject>
    <description>Used in the generation of compliance document to enable retail delivery.</description>
    <label>Shipping Manifest</label>
    <nameField>
        <displayFormat>SM-{YYYY}-{MM}-{0000000000}</displayFormat>
        <label>Shipping Manifest</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipping Manifests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Shipping_Manifest__c/fields/Picklist__c.field-meta.xml
<CustomField>
    <fullName>Picklist__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Picklist</label>
    <referenceTo>Picklist__c</referenceTo>
    <relationshipLabel>Shipping Manifests</relationshipLabel>
    <relationshipName>Shipping_Manifests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipping_Manifest__c/fields/Planned_Ship_Transfer_Date__c.field-meta.xml
<CustomField>
    <fullName>Planned_Ship_Transfer_Date__c</fullName>
    <inlineHelpText>Date in which the products are to be delivered</inlineHelpText>
    <label>Planned Ship/Transfer Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Shipping_Manifest__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Order</label>
    <referenceTo>Sales_Order__c</referenceTo>
    <relationshipLabel>Shipping Manifests</relationshipLabel>
    <relationshipName>Shipping_Manifests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipping_Manifest__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
            <value>
                <fullName>Shipment Pending</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Pending Delivery</fullName>
            </value>
            <value>
                <fullName>Shipment Complete</fullName>
            </value>
            <value>
                <fullName>In-Transit</fullName>
            </value>
            <value>
                <fullName>Received</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
                <isActive>false</isActive>
                <label>Submitted</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Shipping_Manifest__c/fields/Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Vehicle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vehicle</label>
    <referenceTo>Vehicles__c</referenceTo>
    <relationshipLabel>Shipping Manifests</relationshipLabel>
    <relationshipName>Shipping_Manifests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipping_Manifest__c/recordTypes/RSM.recordType-meta.xml
<RecordType>
    <fullName>RSM</fullName>
    <active>true</active>
    <description>Used for Retail Shipments - Ship Confirm to &quot;Delivered&quot; Inventory Location, Rename to &quot;Retail&quot;</description>
    <label>RSM</label>
</RecordType>

force-app/main/default/objects/Shipping_Manifest_Line__c/Shipping_Manifest_Line__c.object-meta.xml
<CustomObject>
    <label>Shipping Manifest Line</label>
    <nameField>
        <displayFormat>SML-{0000000000}</displayFormat>
        <label>SM Line</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipping Manifest Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Shipping_Manifest_Line__c/fields/Picklist_Line__c.field-meta.xml
<CustomField>
    <fullName>Picklist_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Picklist Line</label>
    <referenceTo>Picklist_Line__c</referenceTo>
    <relationshipLabel>Shipping Manifest Lines</relationshipLabel>
    <relationshipName>Shipping_Manifest_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipping_Manifest_Line__c/fields/Sales_Order_Line__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Order Line</label>
    <referenceTo>Sales_Order_Line__c</referenceTo>
    <relationshipLabel>Shipping Manifest Lines</relationshipLabel>
    <relationshipName>Shipping_Manifest_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipping_Manifest_Line__c/fields/Shipping_Manifest__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Manifest__c</fullName>
    <label>Shipping Manifest</label>
    <referenceTo>Shipping_Manifest__c</referenceTo>
    <relationshipLabel>Shipping Manifest Lines</relationshipLabel>
    <relationshipName>Shipping_Manifest_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/AssignVehicleControllerTest.cls
/**
 * Copyright (c) 2018 Filigreen Distro
 * All rights reserved.
 * AssignVehicleControllerTest
 */
@isTest(OnInstall=false SeeAllData=false)
public class AssignVehicleControllerTest{
    
    static PickList__c pickListObj;
    static Vehicles__c vehicleObj;
    static List<PickList_Line__c> pickListLines;
    static Sales_Order__c salesOrderObj;
    static List<Sales_Order_Line__c> soLines;
    static List<Inventory_Position__c> invPositions;
    static Shipping_Manifest__c rsmObj;
    static List<Shipping_Manifest_Line__c> rsmLines;
    
    // Test loading of Assign Vehicle page from RSM detail page
    static testMethod void testLoadVehicleAndRSMDetails_FromRSMPage(){
        
        // Get data created from setup
        retrieveData();
        
        // Update and create necessary data
        updateAndCreateData();
        
        PageReference pageRef = Page.AssignVehicle;
        pageRef.getParameters().put('id', rsmObj.Id);
        Test.setCurrentPage(pageRef);
        
        ApexPages.StandardController stdController = new ApexPages.StandardController(rsmObj);
        AssignVehicleController controllerObj = new AssignVehicleController(stdController);
        
        pageRef = controllerObj.doPrepare();
        System.assertEquals(null, pageRef, 'Page reference mis-match');
        System.assertEquals(rsmObj.Id, controllerObj.rsmObj.Id, 'RSM mis-match');
        System.assertEquals(1, controllerObj.totalProduct, 'RSM Line mis-match');
        System.assertEquals(vehicleObj.Id, controllerObj.vehicleObj.Id, 'Vehicle mis-match');
        System.assertEquals(1, controllerObj.rsmList.size(), 'RSM List mis-match');
        
        pageRef = controllerObj.cancelAction();
        System.assertEquals('/'+String.valueOf(rsmObj.Id).subString(0, 15), pageRef.getURL(), 'Page reference mis-match');
    }
    
    // Test loading of Assign Vehicle page as VF tab
    static testMethod void testLoadVehicleAndRSMDetails_FromTab(){
        
        // Get data created from setup
        retrieveData();
        
        // Update and create necessary data
        updateAndCreateData();
        
        AssignVehicleController controllerObj = new AssignVehicleController();
        
        PageReference pageRef = controllerObj.doPrepare();
        System.assertEquals(null, pageRef, 'Page reference mis-match');
        System.assertEquals(null, controllerObj.rsmObj.Id, 'RSM mis-match');
        System.assertEquals(null, controllerObj.totalProduct, 'RSM Line mis-match');
        System.assertEquals(null, controllerObj.vehicleObj.Id, 'Vehicle mis-match');
        System.assertEquals(0, controllerObj.rsmList.size(), 'RSM List mis-match');
    }
    
    // Test update Vehicle of RSM
    static testMethod void testAssignVehicleToRSM(){
        
        // Get data created from setup
        retrieveData();
        
        // Update and create necessary data
        updateAndCreateData();
        
        PageReference pageRef = Page.AssignVehicle;
        pageRef.getParameters().put('id', rsmObj.Id);
        Test.setCurrentPage(pageRef);
        
        ApexPages.StandardController stdController = new ApexPages.StandardController(rsmObj);
        AssignVehicleController controllerObj = new AssignVehicleController(stdController);
        
        pageRef = controllerObj.doPrepare();
        System.assertEquals(null, pageRef, 'Page reference mis-match');
        System.assertEquals(rsmObj.Id, controllerObj.rsmObj.Id, 'RSM mis-match');
        System.assertEquals(1, controllerObj.totalProduct, 'RSM Line mis-match');
        System.assertEquals(vehicleObj.Id, controllerObj.vehicleObj.Id, 'Vehicle mis-match');
        System.assertEquals(1, controllerObj.rsmList.size(), 'RSM List mis-match');
        
        Test.startTest();
        
        // Set RSM vehicle to null to throw validation
        controllerObj.rsmObj.Vehicle__c = null;
        pageRef = controllerObj.assignVehicle();
        System.assertEquals(null, pageRef, 'Page reference mis-match');
        
        // Verify validation messages
        List<ApexPages.Message> msgList = ApexPages.getMessages();
        System.assertEquals(1, msgList.size(), 'Number of Validation messages mis-match');
        System.assert(msgList[0].getDetail().contains(Label.Select_Vehicle), 'Validation message mis-match');
        
        // Assign new vehicle and planned ship date to RSM
        Vehicles__c newVehicleObj = TestUtilData.createVehicle(false);
        insert newVehicleObj;
        
        controllerObj.rsmObj.Vehicle__c = newVehicleObj.Id;
        controllerObj.rsmObj.Planned_Ship_Transfer_Date__c = System.Today() + 13;
        pageRef = controllerObj.assignVehicle();
        System.assertEquals('/'+String.valueOf(rsmObj.Id).subString(0, 15), pageRef.getURL(), 'Page reference mis-match');
        
        // verify RSM vehicle and planned ship date
        rsmObj = [Select Status__c, Planned_Ship_Transfer_Date__c, Vehicle__c From Shipping_Manifest__c Where Id =: rsmObj.Id AND RecordTypeId =: ShippinManifestSupport.getRSMRecordTypeId()];
        System.assertEquals(newVehicleObj.Id, rsmObj.Vehicle__c, 'Vehicle mis-match');
        System.assertEquals(System.Today() + 13, rsmObj.Planned_Ship_Transfer_Date__c, 'Planned ship date mis-match');
        System.assertEquals(RSMSupport.STATUS_DRAFT, rsmObj.Status__c, 'RSM Status mis-match');
        
        Test.stopTest();
    }
    
    // Test update Vehicle of RSM
    static testMethod void testUpdateRSMStatusToShipmentPending_DriverAndVehicleAssignedToRSM(){
        
        // Get data created from setup
        retrieveData();
        
        // Update and create necessary data
        updateAndCreateData();
        
        // Create Driver record
        Drivers__c driverObj = TestUtilData.createDriver(true);
        rsmObj.Driver__c = driverObj.Id;
        update rsmObj;
        
        PageReference pageRef = Page.AssignVehicle;
        pageRef.getParameters().put('id', rsmObj.Id);
        Test.setCurrentPage(pageRef);
        
        ApexPages.StandardController stdController = new ApexPages.StandardController(rsmObj);
        AssignVehicleController controllerObj = new AssignVehicleController(stdController);
        
        pageRef = controllerObj.doPrepare();
        System.assertEquals(null, pageRef, 'Page reference mis-match');
        System.assertEquals(rsmObj.Id, controllerObj.rsmObj.Id, 'RSM mis-match');
        System.assertEquals(1, controllerObj.totalProduct, 'RSM Line mis-match');
        System.assertEquals(vehicleObj.Id, controllerObj.vehicleObj.Id, 'Vehicle mis-match');
        System.assertEquals(1, controllerObj.rsmList.size(), 'RSM List mis-match');
        
        Test.startTest();
        
        // Set RSM vehicle to null to throw validation
        controllerObj.rsmObj.Vehicle__c = null;
        pageRef = controllerObj.assignVehicle();
        System.assertEquals(null, pageRef, 'Page reference mis-match');
        
        // Verify validation messages
        List<ApexPages.Message> msgList = ApexPages.getMessages();
        System.assertEquals(1, msgList.size(), 'Number of Validation messages mis-match');
        System.assert(msgList[0].getDetail().contains(Label.Select_Vehicle), 'Validation message mis-match');
        
        // Assign new vehicle and planned ship date to RSM
        Vehicles__c newVehicleObj = TestUtilData.createVehicle(false);
        insert newVehicleObj;
        
        controllerObj.rsmObj.Vehicle__c = newVehicleObj.Id;
        controllerObj.rsmObj.Planned_Ship_Transfer_Date__c = System.Today() + 13;
        pageRef = controllerObj.assignVehicle();
        System.assertEquals('/'+String.valueOf(rsmObj.Id).subString(0, 15), pageRef.getURL(), 'Page reference mis-match');
        
        // verify RSM vehicle and planned ship date
        rsmObj = [Select Status__c, Planned_Ship_Transfer_Date__c, Vehicle__c From Shipping_Manifest__c Where Id =: rsmObj.Id AND RecordTypeId =: ShippinManifestSupport.getRSMRecordTypeId()];
        System.assertEquals(newVehicleObj.Id, rsmObj.Vehicle__c, 'Vehicle mis-match');
        System.assertEquals(System.Today() + 13, rsmObj.Planned_Ship_Transfer_Date__c, 'Planned ship date mis-match');
        System.assertEquals(RSMSupport.STATUS_SHIPMENT_PENDING, rsmObj.Status__c, 'RSM Status mis-match');
        
        Test.stopTest();
    }
    
    // Test update Driver of RSM - Status should not be changed if it is already In-Transit
    static testMethod void testDoNotUpdateRSMStatusToShipmentPending_ExistingStatusInTransit_DriverAndVehicleAssignedToRSM(){
        
        // Get data created from setup
        retrieveData();
        
        // Update and create necessary data
        updateAndCreateData();
        
        // Create Driver record
        Drivers__c driverObj = TestUtilData.createDriver(true);
        rsmObj.Driver__c = driverObj.Id;
        rsmObj.Status__c = RSMSupport.STATUS_IN_TRANSIT;
        update rsmObj;
        
        PageReference pageRef = Page.AssignVehicle;
        pageRef.getParameters().put('id', rsmObj.Id);
        Test.setCurrentPage(pageRef);
        
        ApexPages.StandardController stdController = new ApexPages.StandardController(rsmObj);
        AssignVehicleController controllerObj = new AssignVehicleController(stdController);
        
        pageRef = controllerObj.doPrepare();
        System.assertEquals(null, pageRef, 'Page reference mis-match');
        System.assertEquals(rsmObj.Id, controllerObj.rsmObj.Id, 'RSM mis-match');
        System.assertEquals(1, controllerObj.totalProduct, 'RSM Line mis-match');
        System.assertEquals(vehicleObj.Id, controllerObj.vehicleObj.Id, 'Vehicle mis-match');
        System.assertEquals(1, controllerObj.rsmList.size(), 'RSM List mis-match');
        
        Test.startTest();
        
        // Set RSM vehicle to null to throw validation
        controllerObj.rsmObj.Vehicle__c = null;
        pageRef = controllerObj.assignVehicle();
        System.assertEquals(null, pageRef, 'Page reference mis-match');
        
        // Verify validation messages
        List<ApexPages.Message> msgList = ApexPages.getMessages();
        System.assertEquals(1, msgList.size(), 'Number of Validation messages mis-match');
        System.assert(msgList[0].getDetail().contains(Label.Select_Vehicle), 'Validation message mis-match');
        
        // Assign new vehicle and planned ship date to RSM
        Vehicles__c newVehicleObj = TestUtilData.createVehicle(false);
        insert newVehicleObj;
        
        controllerObj.rsmObj.Vehicle__c = newVehicleObj.Id;
        controllerObj.rsmObj.Planned_Ship_Transfer_Date__c = System.Today() + 13;
        pageRef = controllerObj.assignVehicle();
        System.assertEquals('/'+String.valueOf(rsmObj.Id).subString(0, 15), pageRef.getURL(), 'Page reference mis-match');
        
        // verify RSM vehicle and planned ship date
        rsmObj = [Select Status__c, Planned_Ship_Transfer_Date__c, Vehicle__c From Shipping_Manifest__c Where Id =: rsmObj.Id AND RecordTypeId =: ShippinManifestSupport.getRSMRecordTypeId()];
        System.assertEquals(newVehicleObj.Id, rsmObj.Vehicle__c, 'Vehicle mis-match');
        System.assertEquals(System.Today() + 13, rsmObj.Planned_Ship_Transfer_Date__c, 'Planned ship date mis-match');
        System.assertEquals(RSMSupport.STATUS_IN_TRANSIT, rsmObj.Status__c, 'RSM Status mis-match');
        
        Test.stopTest();
    }
    
    // Test update Vehicle of RSM - Status should not be changed if it is already shipment complete
    static testMethod void testVehicleAssignedToRSM_AfterStatusChangedToShipmentComplete(){
        
        // Get data created from setup
        retrieveData();
        
        // Update and create necessary data
        updateAndCreateData();
        
        rsmObj.Status__c = RSMSupport.STATUS_SHIPMENT_COMPLETE;
        update rsmObj;
        
        PageReference pageRef = Page.AssignVehicle;
        pageRef.getParameters().put('id', rsmObj.Id);
        Test.setCurrentPage(pageRef);
        
        ApexPages.StandardController stdController = new ApexPages.StandardController(rsmObj);
        AssignVehicleController controllerObj = new AssignVehicleController(stdController);
        
        pageRef = controllerObj.doPrepare();
        System.assertEquals(null, pageRef, 'Page reference mis-match');
        System.assertEquals(rsmObj.Id, controllerObj.rsmObj.Id, 'RSM mis-match');
        System.assertEquals(1, controllerObj.totalProduct, 'RSM Line mis-match');
        System.assertEquals(vehicleObj.Id, controllerObj.vehicleObj.Id, 'Vehicle mis-match');
        System.assertEquals(1, controllerObj.rsmList.size(), 'RSM List mis-match');
        
        Test.startTest();
        
        // Set RSM vehicle to null to throw validation
        controllerObj.rsmObj.Vehicle__c = null;
        pageRef = controllerObj.assignVehicle();
        System.assertEquals(null, pageRef, 'Page reference mis-match');
        
        // Verify validation messages
        List<ApexPages.Message> msgList = ApexPages.getMessages();
        System.assertEquals(1, msgList.size(), 'Number of Validation messages mis-match');
        System.assert(msgList[0].getDetail().contains(Label.Select_Vehicle), 'Validation message mis-match');
        
        // Assign new vehicle and planned ship date to RSM
        Vehicles__c newVehicleObj = TestUtilData.createVehicle(false);
        insert newVehicleObj;
        
        controllerObj.rsmObj.Vehicle__c = newVehicleObj.Id;
        controllerObj.rsmObj.Planned_Ship_Transfer_Date__c = System.Today() + 13;
        pageRef = controllerObj.assignVehicle();
        System.assertEquals('/'+String.valueOf(rsmObj.Id).subString(0, 15), pageRef.getURL(), 'Page reference mis-match');
        
        // verify RSM vehicle and planned ship date
        rsmObj = [Select Status__c, Planned_Ship_Transfer_Date__c, Vehicle__c From Shipping_Manifest__c Where Id =: rsmObj.Id AND RecordTypeId =: ShippinManifestSupport.getRSMRecordTypeId()];
        System.assertEquals(newVehicleObj.Id, rsmObj.Vehicle__c, 'Vehicle mis-match');
        System.assertEquals(System.Today() + 13, rsmObj.Planned_Ship_Transfer_Date__c, 'Planned ship date mis-match');
        System.assertEquals(RSMSupport.STATUS_SHIPMENT_COMPLETE, rsmObj.Status__c, 'RSM Status mis-match');
        
        Test.stopTest();
    }
    
    @TestSetUp
    static void testDataSetUp(){
        TestUtilData.createTestData();
    }
    
    // Retrieve data created from data setup
    public static void retrieveData(){
        invPositions = [Select Sales_Order_Line__c,
                               Sales_Order_Line__r.Product_Name__c,
                               Inventory_Location__r.Name
                               From Inventory_Position__c];
                               
        salesOrderObj = new Sales_Order__c();
        salesOrderObj = [Select Site__c from Sales_Order__c];
        
        soLines = new List<Sales_Order_Line__c>();
        soLines = [Select Id from Sales_Order_Line__c];
    }
    
    // Update necessary data for Assign Vehicle logic
    public static void updateAndCreateData(){
        // Update SO lines in Inventory positions
        for(Integer i=0; i<invPositions.size(); i++){
            invPositions[i].Sales_Order_Line__c = soLines[i].Id;
        }
        update invPositions;
        
        // Create picklist and lines
        pickListObj = TestUtilData.createPicklist(salesOrderObj, 'Open', true);
        pickListLines = TestUtilData.createPicklistLines(invPositions, pickListObj.Id, true);
        
        // Create Vehicle
        vehicleObj = TestUtilData.createVehicle(true);
        
        // Create RSM with planned ship date greater than license expiration date
        rsmObj = TestUtilData.createRSM(pickListObj, false);
        rsmObj.Vehicle__c = vehicleObj.Id;
        insert rsmObj;
        
        Shipping_Manifest_Line__c rsmLineObj = TestUtilData.createRSMLine(pickListLines[0], rsmObj.Id, true);
    }
}