force-app/main/default/objects/Inventory_Position__c/Inventory_Position__c.object-meta.xml
<CustomObject>
    <label>Inventory Position</label>
    <nameField>
        <displayFormat>IP-{YYYY}-{MM}-{0000000000}</displayFormat>
        <label>Inventory Position</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventory Positions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Inventory_Position__c/fields/Qty_Allocated__c.field-meta.xml
<CustomField>
    <fullName>Qty_Allocated__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Qty Allocated</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Inventory_Position__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <formula>HYPERLINK( Sales_Order_Line__r.Sales_Order__c  , Sales_Order_Line__r.Sales_Order__r.Name)</formula>
    <label>Sales Order</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Inventory_Position__c/fields/Sales_Order_Line__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Order Line</label>
    <referenceTo>Sales_Order_Line__c</referenceTo>
    <relationshipLabel>Inventory Positions</relationshipLabel>
    <relationshipName>Inventory_Positions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Inventory_Position__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site</label>
    <referenceTo>Site__c</referenceTo>
    <relationshipLabel>Inventory Positions</relationshipLabel>
    <relationshipName>Inventory_Positions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Inventory_Position__c/fields/SO_Status__c.field-meta.xml
<CustomField>
    <fullName>SO_Status__c</fullName>
    <formula>TEXT(Sales_Order_Line__r.Sales_Order__r.SO_Status__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SO Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Picklist__c/Picklist__c.object-meta.xml
<CustomObject>
    <description>Picklist is used for Warehouse Picking from inventory Positions</description>
    <label>Picklist</label>
    <nameField>
        <displayFormat>PL-{0000000000}</displayFormat>
        <label>Picklist</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Picklists</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Picklist__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <label>Sales Order</label>
    <referenceTo>Sales_Order__c</referenceTo>
    <relationshipLabel>Picklists</relationshipLabel>
    <relationshipName>Picklists</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Picklist__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site</label>
    <referenceTo>Site__c</referenceTo>
    <relationshipLabel>Picklists</relationshipLabel>
    <relationshipName>Picklists</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Picklist__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>QA Review</fullName>
            </value>
            <value>
                <fullName>QA Confirm</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Order__c/Sales_Order__c.object-meta.xml
<CustomObject>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>SO-{0000000000}</displayFormat>
        <label>Sales Order</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Order__c/fields/Allocated__c.field-meta.xml
<CustomField>
    <fullName>Allocated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Allocated?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Sales_Order__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site</label>
    <referenceTo>Site__c</referenceTo>
    <relationshipLabel>Sales Orders</relationshipLabel>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Order__c/fields/SO_Status__c.field-meta.xml
<CustomField>
    <fullName>SO_Status__c</fullName>
    <label>SO Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Order_Line__c/Sales_Order_Line__c.object-meta.xml
<CustomObject>
    <label>Sales Order Line</label>
    <nameField>
        <displayFormat>SOLI-{0000000000}</displayFormat>
        <label>SO Line</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Order_Line__c/fields/Qty_Allocated__c.field-meta.xml
<CustomField>
    <fullName>Qty_Allocated__c</fullName>
    <label>Qty Allocated</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sales_Order_Line__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <label>Sales Order</label>
    <referenceTo>Sales_Order__c</referenceTo>
    <relationshipLabel>Sales Order Lines</relationshipLabel>
    <relationshipName>Sales_Order_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Sales_Order_Line__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <formula>Sales_Order__r.Site__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Site</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Order_Line__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Allocated</fullName>
            </value>
            <value>
                <fullName>Partially Allocated</fullName>
            </value>
            <value>
                <fullName>Back Ordered</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Shipment Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Shipping_Manifest__c/Shipping_Manifest__c.object-meta.xml
<CustomObject>
    <description>Used in the generation of compliance document to enable retail delivery.</description>
    <label>Shipping Manifest</label>
    <nameField>
        <displayFormat>SM-{YYYY}-{MM}-{0000000000}</displayFormat>
        <label>Shipping Manifest</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipping Manifests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Shipping_Manifest__c/fields/Picklist__c.field-meta.xml
<CustomField>
    <fullName>Picklist__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Picklist</label>
    <referenceTo>Picklist__c</referenceTo>
    <relationshipLabel>Shipping Manifests</relationshipLabel>
    <relationshipName>Shipping_Manifests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipping_Manifest__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Order</label>
    <referenceTo>Sales_Order__c</referenceTo>
    <relationshipLabel>Shipping Manifests</relationshipLabel>
    <relationshipName>Shipping_Manifests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipping_Manifest__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site</label>
    <referenceTo>Site__c</referenceTo>
    <relationshipLabel>Shipping Manifests</relationshipLabel>
    <relationshipName>Shipping_Manifests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipping_Manifest__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
            <value>
                <fullName>Shipment Pending</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Pending Delivery</fullName>
            </value>
            <value>
                <fullName>Shipment Complete</fullName>
            </value>
            <value>
                <fullName>In-Transit</fullName>
            </value>
            <value>
                <fullName>Received</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
                <isActive>false</isActive>
                <label>Submitted</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Shipping_Manifest__c/recordTypes/RSM.recordType-meta.xml
<RecordType>
    <fullName>RSM</fullName>
    <active>true</active>
    <description>Used for Retail Shipments - Ship Confirm to &quot;Delivered&quot; Inventory Location, Rename to &quot;Retail&quot;</description>
    <label>RSM</label>
</RecordType>

force-app/main/default/objects/Site__c/Site__c.object-meta.xml
<CustomObject>
    <description>All objects must have a Site Name and License Class or A or M. For separate sales and inventory record.</description>
    <label>Site</label>
    <nameField>
        <label>Site</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/CancelSOTEST.cls
/**************************************************************************************

*******************************************************************************/
@isTest
public class CancelSOTEST {
   static Sales_Order__c objSO;
   static Picklist__c picklistObj;

    @TestSetUp
    static void testDataSetUp(){
        Test.setMock(HttpCalloutMock.class, new StateLicense_MockResponseTest());
        TestUtilData.skipTrigger = true;
        TestUtilData.createTestData();
    }
  
    static testMethod void inventoryDetailsTest(){
        retrieveData();
        Test.startTest();
        ApexPages.StandardController stdController = new ApexPages.StandardController(objSO);
        CancelSO controllerObj = new CancelSO(stdController);
        
        controllerObj.CancelProcess();
        CancelSO.CancelSorder(objSO.Id, true);
        controllerObj.goBack();

        
    }
    
     static testMethod void inventoryDetailsCancelTest(){
        retrieveData();
         Test.startTest();
        objSO.SO_Status__c = 'Cancelled';
        update objSO;    
        ApexPages.StandardController stdController = new ApexPages.StandardController(objSO);
        CancelSO controllerObj = new CancelSO(stdController);
        
        controllerObj.CancelProcess();
         CancelSO.CancelSorder(objSO.Id, true);
    
     }
    
     static testMethod void inventoryDetailsApprovedTest(){
        retrieveData();
         Test.startTest();
        objSO.SO_Status__c = 'Approved';
        update objSO;    
        objSO.Allocated__c = true;
        ApexPages.StandardController stdController = new ApexPages.StandardController(objSO);
        CancelSO controllerObj = new CancelSO(stdController);
        
        controllerObj.CancelProcess();
         CancelSO.CancelSorder(objSO.Id, true);
    
     }
    
    static testMethod void picklistDetailsOpenTest(){ 
        retrieveData();
        Test.startTest();
        objSO.SO_Status__c = 'Approved';
        objSO.Allocated__c = true;
        update objSO;    

        
        Picklist__c objPicklist = [select id,Sales_Order__c, Status__c from Picklist__c limit 1];
        objPicklist.Status__c = 'Confirmed';
        update objPicklist;
        
         system.debug('objPicklist----'+objPicklist);
        
        
        
        ApexPages.StandardController stdController = new ApexPages.StandardController(objSO);CancelSO controllerObj = new CancelSO(stdController);   

        controllerObj.CancelProcess();
        CancelSO.CancelSorder(objSO.Id, true);
    }


    static testMethod void picklistDetailsTest(){ 
        retrieveData();
        Test.startTest();
        objSO.SO_Status__c = 'Approved';
        objSO.Allocated__c = true;
        update objSO;    
        
            
            
       Picklist__c objPicklist = [select id,Sales_Order__c, Status__c from Picklist__c limit 1];
        objPicklist.Status__c = 'Confirmed';
        update objPicklist;
        
        system.debug('objPicklist1----'+objPicklist);

   

        ApexPages.StandardController stdController = new ApexPages.StandardController(objSO);
        CancelSO controllerObj = new CancelSO(stdController);   
         CancelSO.isConfirmed = true;
        controllerObj.CancelProcess();
        CancelSO.CancelSorder(objSO.Id, true);
        
                
    }


    
    static testMethod void picklistDetailsConfirmedTest(){ 
        retrieveData();
        Test.startTest();
        objSO.SO_Status__c = 'Approved';
        update objSO;    
        ApexPages.StandardController stdController = new ApexPages.StandardController(objSO);
        CancelSO controllerObj = new CancelSO(stdController);
        
        controllerObj.CancelProcess();
        CancelSO.CancelSorder(objSO.Id, true);
    }
    
    static testMethod void SOdetailsDraftTest(){ 
        retrieveData();
        Test.startTest();
        objSO.SO_Status__c = 'Draft';
        update objSO;    
        ApexPages.StandardController stdController = new ApexPages.StandardController(objSO);
        CancelSO controllerObj = new CancelSO(stdController);
        
        controllerObj.CancelProcess();
        CancelSO.CancelSorder(objSO.Id, true);
    }
    
    static testMethod void SOdetailsHoldTest(){ 
        retrieveData();
        Test.startTest();
        objSO.SO_Status__c = 'Hold';
        update objSO;    
        ApexPages.StandardController stdController = new ApexPages.StandardController(objSO);
        CancelSO controllerObj = new CancelSO(stdController);
        
        controllerObj.CancelProcess();
        String Status;
        Status = CancelSO.SHIPPING_MANIFEST_STATUS_CANCELLED;
        Status = CancelSO.SHIPPING_MANIFEST_STATUS_DRAFT;
        Status = CancelSO.PICKLIST_STATUS_QACONFIRM;
        Status = CancelSO.PICKLIST_STATUS_CONFIRMED;
        Status = CancelSO.ERR_MSG_CANT_CANCEL_SO_CANCEL_PICKLIST;
        Status = CancelSO.ORDERCANCELLED_CUSTOMER;
        
        //AuraResponse r = new AuraResponse('CancelSO.CancelSorder()');
        CancelSO.CancelSorder(objSO.Id, true);
        CancelSO.getRecordName(objSO.Id);
    }
    
    
    public static void retrieveData(){
        objSO = new Sales_Order__c();
        objSO = [Select Id, SO_Status__c, Site__c, Allocated__c from Sales_Order__c];
        system.debug('objSO'+objSO);
       
        
        picklistObj = new Picklist__c();
        picklistObj.Sales_Order__c = objSO.Id;
        picklistObj.Site__c = objSO.Site__c;
        picklistObj.Status__c = 'Open';
       
        insert picklistObj;
        
        
        list<Sales_Order_Line__c> lstSO = [select id, Status__c from Sales_Order_Line__c]; 
        
        lstSO[0].Status__c = 'Back Ordered';
        
        lstSO[0].Qty_Allocated__c = 20;     
        
        lstSO[1].Status__c = 'Allocated';
        
        lstSO[1].Qty_Allocated__c = 10;
        
        lstSO[2].Status__c = 'Partially Allocated';
        
        lstSO[0].Qty_Allocated__c = 5;
        update lstSO;
                
        List<Inventory_Position__c> invPositions =[select id, Sales_Order_Line__c from Inventory_Position__c];
 
        invPositions[0].Sales_Order_Line__c = lstSO[0].id;
        invPositions[1].Sales_Order_Line__c = lstSO[0].id;
        invPositions[2].Sales_Order_Line__c = lstSO[0].id;
        
        update invPositions;
    }
    
    static testMethod void cancelSOWithShipmentCompleteRSM(){
        retrieveData();
        Test.startTest();
        objSO.SO_Status__c = 'Draft';
        update objSO;   

        Shipping_Manifest__c rsmObj = TestUtilData.createRSM(pickListObj, false);
        rsmObj.Sales_Order__c = objSO.Id;
        rsmObj.Status__c = CancelSO.SHIPMENT_COMPLETE;
        insert rsmObj;
        
        ApexPages.StandardController stdController = new ApexPages.StandardController(objSO);
        CancelSO controllerObj = new CancelSO(stdController);
        
        PageReference pageRef = controllerObj.CancelProcess();
        System.assertEquals(null, pageRef, 'Page reference mis-match');
        
        // Verify validation messages
        List<ApexPages.Message> msgList = ApexPages.getMessages();
        System.assertEquals(1, msgList.size(), 'Number of Validation messages mis-match');
        System.assert(msgList[0].getDetail().contains('SO can be cancelled only for open RSM'), 'Validation message mis-match');
    
     }
     
    static testMethod void cancelSOWithShipmentDraftRSM(){
        
        retrieveData();
        Test.startTest();
        objSO.SO_Status__c = 'Draft';
        update objSO;   

        Shipping_Manifest__c rsmObj = TestUtilData.createRSM(pickListObj, false);
        rsmObj.Sales_Order__c = objSO.Id;
        insert rsmObj;
        
        List<Picklist__c> pickLists = [Select Id from Picklist__c Where Sales_Order__c =: objSO.Id];
        System.assertEquals(1, pickLists.size(), 'Picklist size mis-match');
        
        List<Shipping_Manifest__c> rsms = [Select Id from Shipping_Manifest__c Where Sales_Order__c =: objSO.Id];
        System.assertEquals(1, rsms.size(), 'RSM size mis-match');
        
        ApexPages.StandardController stdController = new ApexPages.StandardController(objSO);
        CancelSO controllerObj = new CancelSO(stdController);
        
        PageReference pageRef = controllerObj.CancelProcess();
       
        pickLists = [Select Id from Picklist__c Where Sales_Order__c =: objSO.Id]; rsms = [Select Id from Shipping_Manifest__c Where Sales_Order__c =: objSO.Id];
        Test.stopTest();
     }
}