force-app/main/default/objects/Inventory_Position__c/Inventory_Position__c.object-meta.xml
<CustomObject>
    <label>Inventory Position</label>
    <nameField>
        <displayFormat>IP-{YYYY}-{MM}-{0000000000}</displayFormat>
        <label>Inventory Position</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventory Positions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Inventory_Position__c/fields/Qty_Allocated__c.field-meta.xml
<CustomField>
    <fullName>Qty_Allocated__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Qty Allocated</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Inventory_Position__c/fields/Qty_On_Hand__c.field-meta.xml
<CustomField>
    <fullName>Qty_On_Hand__c</fullName>
    <label>Qty On Hand</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Inventory_Position__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <formula>HYPERLINK( Sales_Order_Line__r.Sales_Order__c  , Sales_Order_Line__r.Sales_Order__r.Name)</formula>
    <label>Sales Order</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Inventory_Position__c/fields/Sales_Order_Line__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Order Line</label>
    <referenceTo>Sales_Order_Line__c</referenceTo>
    <relationshipLabel>Inventory Positions</relationshipLabel>
    <relationshipName>Inventory_Positions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Inventory_Position__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site</label>
    <referenceTo>Site__c</referenceTo>
    <relationshipLabel>Inventory Positions</relationshipLabel>
    <relationshipName>Inventory_Positions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Inventory_Position__c/fields/SO_Status__c.field-meta.xml
<CustomField>
    <fullName>SO_Status__c</fullName>
    <formula>TEXT(Sales_Order_Line__r.Sales_Order__r.SO_Status__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SO Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Picklist__c/Picklist__c.object-meta.xml
<CustomObject>
    <description>Picklist is used for Warehouse Picking from inventory Positions</description>
    <label>Picklist</label>
    <nameField>
        <displayFormat>PL-{0000000000}</displayFormat>
        <label>Picklist</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Picklists</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Picklist__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <label>Sales Order</label>
    <referenceTo>Sales_Order__c</referenceTo>
    <relationshipLabel>Picklists</relationshipLabel>
    <relationshipName>Picklists</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Picklist__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site</label>
    <referenceTo>Site__c</referenceTo>
    <relationshipLabel>Picklists</relationshipLabel>
    <relationshipName>Picklists</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Picklist__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>QA Review</fullName>
            </value>
            <value>
                <fullName>QA Confirm</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Order__c/Sales_Order__c.object-meta.xml
<CustomObject>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>SO-{0000000000}</displayFormat>
        <label>Sales Order</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Order__c/fields/Allocated__c.field-meta.xml
<CustomField>
    <fullName>Allocated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Allocated?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Sales_Order__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site</label>
    <referenceTo>Site__c</referenceTo>
    <relationshipLabel>Sales Orders</relationshipLabel>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Order__c/fields/SO_Status__c.field-meta.xml
<CustomField>
    <fullName>SO_Status__c</fullName>
    <label>SO Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Order_Line__c/Sales_Order_Line__c.object-meta.xml
<CustomObject>
    <label>Sales Order Line</label>
    <nameField>
        <displayFormat>SOLI-{0000000000}</displayFormat>
        <label>SO Line</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Order_Line__c/fields/Qty_Allocated__c.field-meta.xml
<CustomField>
    <fullName>Qty_Allocated__c</fullName>
    <label>Qty Allocated</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sales_Order_Line__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <label>Sales Order</label>
    <referenceTo>Sales_Order__c</referenceTo>
    <relationshipLabel>Sales Order Lines</relationshipLabel>
    <relationshipName>Sales_Order_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Sales_Order_Line__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <formula>Sales_Order__r.Site__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Site</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Order_Line__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Allocated</fullName>
            </value>
            <value>
                <fullName>Partially Allocated</fullName>
            </value>
            <value>
                <fullName>Back Ordered</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Shipment Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Site__c/Site__c.object-meta.xml
<CustomObject>
    <description>All objects must have a Site Name and License Class or A or M. For separate sales and inventory record.</description>
    <label>Site</label>
    <nameField>
        <label>Site</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ReverseAllocationProcessForSOCtlrTest.cls
/**
 * Copyright (c) 2018 Filigreen Distro
 * All rights reserved.
 * ReverseAllocationProcessForSOCtlrTest
 */
@isTest(OnInstall=false SeeAllData=false)
public class ReverseAllocationProcessForSOCtlrTest{
    
    static Sales_Order__c salesOrderObj;
    static List<Sales_Order_Line__c> soLines;
    static List<Inventory_Position__c> invPositions;
    
    // Test Reverse allocation process - One SO line to one Inventory Position
    static testMethod void testReverseAllocationProcess_OneSOLineToOneInvPosition(){
        Test.startTest();
        // Get data created from setup
        retrieveData();
        
        // Update SO, SO lines and Inventory position to support allocation process
        salesOrderObj.Allocated__c = true;
        update salesOrderObj;
        
        System.assertEquals(3, invPositions.size(), 'Inventory positions size mis-match');
        Integer counter = 0;
        for(Inventory_Position__c invPositionObj : invPositions){
            invPositionObj.Qty_On_Hand__c = 0.0;
            invPositionObj.Qty_Allocated__c = 20.0;
            invPositionObj.Sales_Order_Line__c = soLines[counter].Id;
            counter++;
        }
        update invPositions;
        
        System.assertEquals(3, soLines.size());
        for(Sales_Order_Line__c soLineObj : soLines){
            soLineObj.Status__c = SalesOrderSupport.SO_LINE_STATUS_ALLOCATED;
            soLineObj.Qty_Allocated__c = 20.0;
        }
        update soLines;
        
        PageReference pageRef = Page.ReverseAllocationProcessForSO;
        pageRef.getParameters().put('id', salesOrderObj.Id);
        Test.setCurrentPage(pageRef);
        
        ApexPages.StandardController stdController = new ApexPages.StandardController(salesOrderObj);
        ReverseAllocationProcessForSOController controllerObj = new ReverseAllocationProcessForSOController(stdController);
        
        pageRef = controllerObj.reverseAllocationProcess();
        System.assertEquals('/'+String.valueOf(salesOrderObj.Id).subString(0, 15), pageRef.getURL(), 'Page reference mis-match');
        
        // Get updated data after reverse allocation process
        retrieveData();
        
        // Verify SO, SO lines and inventory positions data
        System.assertEquals(false, salesOrderObj.Allocated__c, 'SO Allocated flag mis-match');
        
        System.assertEquals(3, invPositions.size(), 'Inventory positions size mis-match');
        for(Inventory_Position__c invPositionObj : invPositions){
            System.assertEquals(20.0, invPositionObj.Qty_On_Hand__c, 'Qty on hand of Inventory position mis-match');
            System.assertEquals(0.0, invPositionObj.Qty_Allocated__c, 'Qty Allocated of Inventory position mis-match');
            System.assertEquals(null, invPositionObj.Sales_Order_Line__c, 'SO line of Inventory position mis-match');
        }
        
        System.assertEquals(3, soLines.size(), 'SO lines size mis-match');
        for(Sales_Order_Line__c soLineObj : soLines){
            System.assertEquals(0.0, soLineObj.Qty_Allocated__c, 'Qty Allocated of SO line mis-match');
            System.assertEquals(SalesOrderSupport.SO_LINE_STATUS_OPEN, 
                                soLineObj.Status__c, 
                                'Status of SO line mis-match');
        }
        Test.stopTest();
    }
    
    // Test Reverse allocation process - One SO line to many Inventory Positions
    static testMethod void testReverseAllocationProcess_OneSOLineToManyInvPositions(){
        
        // Get data created from setup
        retrieveData();
        
        // Update SO, SO lines and Inventory position to support allocation process
        salesOrderObj.Allocated__c = true;
        update salesOrderObj;
        
        System.assertEquals(3, invPositions.size(), 'Inventory positions size mis-match');
        
        // One SO line is related with two inventory position 
        // last SO line is not related with any inventory position
        for(Inventory_Position__c invPositionObj : invPositions){
            invPositionObj.Qty_On_Hand__c = 0.0;
            invPositionObj.Qty_Allocated__c = 20.0;
        }
        invPositions[0].Sales_Order_Line__c = soLines[0].Id;
        invPositions[1].Sales_Order_Line__c = soLines[0].Id;
        invPositions[2].Sales_Order_Line__c = soLines[1].Id;
        update invPositions;
        
        System.assertEquals(3, soLines.size());
        soLines[0].Status__c = SalesOrderSupport.SO_LINE_STATUS_ALLOCATED;
        soLines[0].Qty_Allocated__c = 40;
        soLines[1].Status__c = SalesOrderSupport.SO_LINE_STATUS_ALLOCATED;
        soLines[1].Qty_Allocated__c = 20;
        soLines[1].Status__c = SalesOrderSupport.SO_LINE_STATUS_BACK_ORDERED;
        soLines[2].Qty_Allocated__c = 0;
        update soLines;
        
        PageReference pageRef = Page.ReverseAllocationProcessForSO;
        pageRef.getParameters().put('id', salesOrderObj.Id);
        Test.setCurrentPage(pageRef);
        
        ApexPages.StandardController stdController = new ApexPages.StandardController(salesOrderObj);
        ReverseAllocationProcessForSOController controllerObj = new ReverseAllocationProcessForSOController(stdController);
        
        pageRef = controllerObj.reverseAllocationProcess();
        System.assertEquals('/'+String.valueOf(salesOrderObj.Id).subString(0, 15), pageRef.getURL(), 'Page reference mis-match');
        
        // Get updated data after reverse allocation process
        retrieveData();
        
        // Verify SO, SO lines and inventory positions data
        System.assertEquals(false, salesOrderObj.Allocated__c, 'SO Allocated flag mis-match');
        
        System.assertEquals(3, invPositions.size(), 'Inventory positions size mis-match');
        for(Inventory_Position__c invPositionObj : invPositions){
            System.assertEquals(20.0, invPositionObj.Qty_On_Hand__c, 'Qty on hand of Inventory position mis-match');
            System.assertEquals(0.0, invPositionObj.Qty_Allocated__c, 'Qty Allocated of Inventory position mis-match');
            System.assertEquals(null, invPositionObj.Sales_Order_Line__c, 'SO line of Inventory position mis-match');
        }
        
        System.assertEquals(3, soLines.size(), 'SO lines size mis-match');
        
        System.assertEquals(0.0, soLines[0].Qty_Allocated__c, 'Qty Allocated of SO line mis-match');
        System.assertEquals(SalesOrderSupport.SO_LINE_STATUS_OPEN, 
                            soLines[0].Status__c, 
                            'Status of SO line mis-match');
        
        System.assertEquals(0.0, soLines[1].Qty_Allocated__c, 'Qty Allocated of SO line mis-match');
        System.assertEquals(SalesOrderSupport.SO_LINE_STATUS_OPEN, 
                            soLines[1].Status__c, 
                            'Status of SO line mis-match');
        
        System.assertEquals(0.0, soLines[2].Qty_Allocated__c, 'Qty Allocated of SO line mis-match');
        System.assertEquals(SalesOrderSupport.SO_LINE_STATUS_OPEN, 
                            soLines[2].Status__c, 
                            'Status of SO line mis-match');
        
    }
    
    // Test Reverse allocation process 
    // Back ordered status of SO line to open 
    // Cancelled status of SO line should not be changed
    // One SO line to one Inventory Position
    static testMethod void testReverseAllocationProcess_BackOrderedAndCancelledSOLine(){
        Test.startTest();
        // Get data created from setup
        retrieveData();
        
        // Create open Picklist
        Picklist__c picklistObj = TestUtilData.createPicklist(salesOrderObj, 'Open', true);
        List<Picklist__c> picklists = [Select Id from Picklist__c];
        System.assertEquals(1, picklists.size(), 'Picklist size mis-match');
        
        // Update SO, SO lines and Inventory position to support allocation process
        salesOrderObj.Allocated__c = true;
        update salesOrderObj;
        
        System.assertEquals(3, invPositions.size(), 'Inventory positions size mis-match');
        Integer counter = 0;
        for(Inventory_Position__c invPositionObj : invPositions){
            invPositionObj.Qty_On_Hand__c = 0.0;
            invPositionObj.Qty_Allocated__c = 20.0;
            if(counter < 2){
                invPositionObj.Sales_Order_Line__c = soLines[counter].Id;
            }
            counter++;
        }
        update invPositions;
        
        System.assertEquals(3, soLines.size());
        soLines[0].Status__c = SalesOrderSupport.SO_LINE_STATUS_PARTIALLY_ALLOCATED;
        soLines[0].Qty_Allocated__c = 15.0;
        soLines[1].Status__c = SalesOrderSupport.SO_LINE_STATUS_BACK_ORDERED;
        soLines[1].Qty_Allocated__c = 0.0;
        soLines[2].Status__c = SalesOrderSupport.SO_LINE_STATUS_CANCELLED;
        soLines[2].Qty_Allocated__c = 20.0;
        update soLines;
        
        PageReference pageRef = Page.ReverseAllocationProcessForSO;
        pageRef.getParameters().put('id', salesOrderObj.Id);
        Test.setCurrentPage(pageRef);
        
        ApexPages.StandardController stdController = new ApexPages.StandardController(salesOrderObj);
        ReverseAllocationProcessForSOController controllerObj = new ReverseAllocationProcessForSOController(stdController);
        ReverseAllocationProcessForSOController.updateSOLinesAndInventoryPositionslight(salesOrderObj.Id);
        pageRef = controllerObj.reverseAllocationProcess();
        System.assertEquals('/'+String.valueOf(salesOrderObj.Id).subString(0, 15), pageRef.getURL(), 'Page reference mis-match');
        
        // Get updated data after reverse allocation process
        retrieveData();
        
        // Verify picklist record associated with sales order is deleted
        picklists = [Select Id from Picklist__c];
        System.assertEquals(0, picklists.size(), 'Picklist size mis-match');
        
        // Verify SO, SO lines and inventory positions data
        System.assertEquals(false, salesOrderObj.Allocated__c, 'SO Allocated flag mis-match');
        
        System.assertEquals(3, invPositions.size(), 'Inventory positions size mis-match');
        counter = 0;
        for(Inventory_Position__c invPositionObj : invPositions){
            if(counter < 2){
                System.assertEquals(20.0, invPositionObj.Qty_On_Hand__c, 'Qty on hand of Inventory position mis-match');
                System.assertEquals(0.0, invPositionObj.Qty_Allocated__c, 'Qty Allocated of Inventory position mis-match');
            }else{
                System.assertEquals(0.0, invPositionObj.Qty_On_Hand__c, 'Qty on hand of Inventory position mis-match');
                System.assertEquals(20.0, invPositionObj.Qty_Allocated__c, 'Qty Allocated of Inventory position mis-match');
            }
            System.assertEquals(null, invPositionObj.Sales_Order_Line__c, 'SO line of Inventory position mis-match');
            counter ++;
        }
        
        System.assertEquals(3, soLines.size(), 'SO lines size mis-match');
        
        counter = 0;
        for(Sales_Order_Line__c soLineObj : soLines){
            
            if(counter < 2){
                System.assertEquals(0.0, soLineObj.Qty_Allocated__c, 'Qty Allocated of SO line mis-match');
                System.assertEquals(SalesOrderSupport.SO_LINE_STATUS_OPEN, 
                                    soLineObj.Status__c, 
                                    'Status of SO line mis-match');
            }else{
                System.assertEquals(20.0, soLineObj.Qty_Allocated__c, 'Qty Allocated of SO line mis-match');
                System.assertEquals(SalesOrderSupport.SO_LINE_STATUS_CANCELLED, 
                                    soLineObj.Status__c, 
                                    'Status of SO line mis-match');
            }
            counter++;
        }
        Test.stopTest();
    }
    
    // Test Reverse allocation process for cancelled SO
    static testMethod void testReverseAllocationProcess_ForCancelledSO(){
        
        // Get data created from setup
        retrieveData();
        
        // Update SO, SO lines and Inventory position to support allocation process
        salesOrderObj.SO_Status__c = SalesOrderSupport.SO_STATUS_CANCELLED;
        update salesOrderObj;
        
        PageReference pageRef = Page.ReverseAllocationProcessForSO;
        pageRef.getParameters().put('id', salesOrderObj.Id);
        Test.setCurrentPage(pageRef);
        
        ApexPages.StandardController stdController = new ApexPages.StandardController(salesOrderObj);
        ReverseAllocationProcessForSOController controllerObj = new ReverseAllocationProcessForSOController(stdController);
        ReverseAllocationProcessForSOController.updateSOLinesAndInventoryPositionslight(salesOrderObj.Id);
        pageRef = controllerObj.reverseAllocationProcess();
        System.assertEquals(null, pageRef, 'Page reference mis-match');
        
        // Verify validation messages
        List<ApexPages.Message> msgList = ApexPages.getMessages();
        System.assertEquals(1, msgList.size(), 'Number of Validation messages mis-match');
        System.assert(msgList[0].getDetail().contains(Label.No_Reverse_Allocation_For_Cancelled_SO), 'Validation message mis-match');
    }
    
    // Test Reverse allocation process for confirmed picklist
    static testMethod void testReverseAllocationProcess_ForConfirmedPicklist(){
        
        // Get data created from setup
        retrieveData();
        
        // Create confirmed Picklist
        Picklist__c picklistObj = TestUtilData.createPicklist(salesOrderObj, 'Confirmed', true);
        
        PageReference pageRef = Page.ReverseAllocationProcessForSO;
        pageRef.getParameters().put('id', salesOrderObj.Id);
        Test.setCurrentPage(pageRef);
        
        ApexPages.StandardController stdController = new ApexPages.StandardController(salesOrderObj);
        ReverseAllocationProcessForSOController controllerObj = new ReverseAllocationProcessForSOController(stdController);
        ReverseAllocationProcessForSOController.updateSOLinesAndInventoryPositionslight(salesOrderObj.Id);
        
        pageRef = controllerObj.reverseAllocationProcess();
        System.assertEquals(null, pageRef, 'Page reference mis-match');
        
        // Verify validation messages
        List<ApexPages.Message> msgList = ApexPages.getMessages();
        System.assertEquals(1, msgList.size(), 'Number of Validation messages mis-match');
        System.assert(msgList[0].getDetail().contains(Label.No_Reverse_Allocation_For_Cancelled_SO), 'Validation message mis-match');
    }
    
    @TestSetUp
    static void testDataSetUp(){
        TestUtilData.skipTrigger = true;
        TestUtilData.createTestData();
        Test.setMock(HttpCalloutMock.class, new StateLicense_MockResponseTest());
    }
    
    // Retrieve data created from data setup
    public static void retrieveData(){
        invPositions = [Select Qty_On_Hand__c,
                               Qty_Allocated__c,
                               Sales_Order_Line__c
                               From Inventory_Position__c];
                               
        salesOrderObj = new Sales_Order__c();
        salesOrderObj = [Select Allocated__c, Site__c from Sales_Order__c];
        
        soLines = new List<Sales_Order_Line__c>();
        soLines = [Select Status__c, Qty_Allocated__c From Sales_Order_Line__c];
    }
}