force-app/main/default/objects/Picklist_Line__c/Picklist_Line__c.object-meta.xml
<CustomObject>
    <description>Picklist Lines are Line Items within a Picklist and inherites Sales Order Line Items</description>
    <label>Picklist Line</label>
    <nameField>
        <displayFormat>PKLI-{0000000000}</displayFormat>
        <label>Picklist Line</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Picklist Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Picklist_Line__c/fields/Harvest_Batch_or_Lot_Code__c.field-meta.xml
<CustomField>
    <fullName>Harvest_Batch_or_Lot_Code__c</fullName>
    <formula>Inventory_Position__r.Harvest_Batch_Code__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Batch ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Picklist_Line__c/fields/UID__c.field-meta.xml
<CustomField>
    <fullName>UID__c</fullName>
    <formula>Inventory_Position__r.UID_New__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Source UID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UID__c/UID__c.object-meta.xml
<CustomObject>
    <description>Unique Identifiers, RFID Tags from Track &amp; Trace</description>
    <label>UID</label>
    <nameField>
        <label>UID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>UIDs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/PicklistLineWrapper.cls
Public Class PicklistLineWrapper
{
    @AuraEnabled Public Picklist_Line__c picklistLineObj {get; set;}
    @AuraEnabled Public Decimal qtytoPick {get; set;}
    @AuraEnabled Public String uid {get; set;}
    @AuraEnabled Public String harvestBatchOrLotCode {get; set;}

   
    public PicklistLineWrapper(Picklist_Line__c picklistLineObj , Decimal qtytoPick)
    {
        this.picklistLineObj = picklistLineObj ;
        this.qtytoPick = qtytoPick;
        this.uid = splitLongWord(picklistLineObj.UID__c, 9);
        this.harvestBatchOrLotCode = splitLongWord(picklistLineObj.Harvest_Batch_or_Lot_Code__c, 9);

    }
    
    public String splitLongWord(String input, Integer lineLength){
        LineSplitter splitter = new LineSplitter();
        splitter.myInput = input;
        splitter.myLineLength = lineLength;
        return splitter.output;
    }
}