force-app/main/default/objects/Google_Distance_Matrix_API__c/Google_Distance_Matrix_API__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Google_Distance_Matrix_API</label>
</CustomObject>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>IN-{0000000000}</displayFormat>
        <label>Invoice</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Invoice_Date__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Date__c</fullName>
    <defaultValue>Today()</defaultValue>
    <label>Invoice Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/IsLocked__c.field-meta.xml
<CustomField>
    <fullName>IsLocked__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsLocked</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Revenue_Recognition_Date__c.field-meta.xml
<CustomField>
    <fullName>Revenue_Recognition_Date__c</fullName>
    <inlineHelpText>Date in which revenue was recognized</inlineHelpText>
    <label>Revenue Recognition Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Revenue_Recognition__c/Revenue_Recognition__c.object-meta.xml
<CustomObject>
    <label>Revenue Recognition</label>
    <nameField>
        <displayFormat>RR-{0000}</displayFormat>
        <label>Revenue Recognition Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Revenue Recognitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Revenue_Recognition__c/fields/Revenue_Recognition_Date__c.field-meta.xml
<CustomField>
    <fullName>Revenue_Recognition_Date__c</fullName>
    <label>Revenue Recognition Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/InvoiceLockingScreenControllerTest.cls
@isTest
public class InvoiceLockingScreenControllerTest {
    static testMethod void runtest(){
        Test.setMock(HttpCalloutMock.class, new Miles_Mock());  
        TestUtilData.skipTrigger = true;
        
        Google_Distance_Matrix_API__c[] GDMIs = new Google_Distance_Matrix_API__c[]{new Google_Distance_Matrix_API__c(Name='GMaps_Endpoint',Value__c = 'https://maps.googleapis.com/maps/api/distancematrix/json?'),new Google_Distance_Matrix_API__c(Name='Gmaps_APIKey',Value__c = 'gjhghj3232342jkhj'),new Google_Distance_Matrix_API__c(Name='Geocode_Endpoint',Value__c = 'https://maps.googleapis.com/maps/api/geocode/json?')};
        insert GDMIs;
        TestUtilData.createTestData();
        
        Invoice__c inv =[SELECT id,Invoice_Date__c,IsLocked__c,Revenue_Recognition_Date__c FROM Invoice__c LIMIT 1];
        inv.Invoice_Date__c  = system.today();
        inv.IsLocked__c = true;
        inv.Revenue_Recognition_Date__c = system.today();
        update inv;
        
        Revenue_Recognition__c rr =new  Revenue_Recognition__c();
        rr.Revenue_Recognition_Date__c = system.today();
        rr.IsLocked__c = true;
        insert rr;
        
        InvoiceLockingScreenController.init();
        InvoiceLockingScreenController.LockedInvoices(system.today().year(),system.today().month());
        InvoiceLockingScreenController.lockAndUnlockToInvoice(inv.Id,true);
        InvoiceLockingScreenController.lockAndUnlockToInvoice(inv.Id,false);
        InvoiceLockingScreenController.getInvoiceData(1,10,system.today().year(),system.today().month());
        InvoiceLockingScreenController.checkMonthInvoices(system.today().year(),system.today().month());
        
        
    }
}