force-app/main/default/objects/Google_Distance_Matrix_API__c/Google_Distance_Matrix_API__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Google_Distance_Matrix_API</label>
</CustomObject>

force-app/main/default/objects/Service_Ticket__c/Service_Ticket__c.object-meta.xml
<CustomObject>
    <description>Service ticket object in Community</description>
    <label>Service Ticket</label>
    <nameField>
        <displayFormat>ST-{YYYY}-{MM}-{00000}</displayFormat>
        <label>Service Ticket #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Tickets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Ticket__c/fields/Brand_Contact__c.field-meta.xml
<CustomField>
    <fullName>Brand_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Brand Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Service Tickets</relationshipLabel>
    <relationshipName>Service_Tickets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_Ticket__c/fields/Brand_Name__c.field-meta.xml
<CustomField>
    <fullName>Brand_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Brand Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Service Tickets</relationshipLabel>
    <relationshipName>Service_Tickets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_Ticket__c/fields/License_Number__c.field-meta.xml
<CustomField>
    <fullName>License_Number__c</fullName>
    <formula>Licensed_Premise__r.License_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>License Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service_Ticket__c/fields/License_Type__c.field-meta.xml
<CustomField>
    <fullName>License_Type__c</fullName>
    <formula>TEXT(Licensed_Premise__r.License_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>License Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service_Ticket__c/fields/Licensed_Premise__c.field-meta.xml
<CustomField>
    <fullName>Licensed_Premise__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Licensed Premise</label>
    <referenceTo>State_Licenses__c</referenceTo>
    <relationshipLabel>Service Tickets</relationshipLabel>
    <relationshipName>Service_Tickets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_Ticket__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>New</fullName>
                <isActive>false</isActive>
                <label>New</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service_Ticket__c/fields/Transfer_Method__c.field-meta.xml
<CustomField>
    <fullName>Transfer_Method__c</fullName>
    <label>Transfer Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Drop-off</fullName>
            </value>
            <value>
                <fullName>Pick-up</fullName>
            </value>
            <value>
                <fullName>Product Conversions</fullName>
            </value>
            <value>
                <fullName>D2D Transfer</fullName>
                <isActive>false</isActive>
                <label>D2D Transfer</label>
            </value>
            <value>
                <fullName>None (In stock)</fullName>
                <isActive>false</isActive>
                <label>None (In stock)</label>
            </value>
            <value>
                <fullName>Sample Pick-Up</fullName>
                <isActive>false</isActive>
                <label>Sample Pick-Up</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Site__c/Site__c.object-meta.xml
<CustomObject>
    <description>All objects must have a Site Name and License Class or A or M. For separate sales and inventory record.</description>
    <label>Site</label>
    <nameField>
        <label>Site</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Site__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active ?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Site__c/fields/License_Class__c.field-meta.xml
<CustomField>
    <fullName>License_Class__c</fullName>
    <formula>TEXT(License_ID__r.License_Class__c)</formula>
    <label>License Class</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site__c/fields/License_Name__c.field-meta.xml
<CustomField>
    <fullName>License_Name__c</fullName>
    <formula>License_ID__r.License_Name__r.Name</formula>
    <label>License Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site__c/fields/License_Number__c.field-meta.xml
<CustomField>
    <fullName>License_Number__c</fullName>
    <formula>License_ID__r.License_Number__c</formula>
    <label>License Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site__c/fields/Warehouse_Name__c.field-meta.xml
<CustomField>
    <fullName>Warehouse_Name__c</fullName>
    <description>Name of the warehouse to display in UI. Example : Communities.</description>
    <label>Warehouse Name</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/State_Licenses__c/State_Licenses__c.object-meta.xml
<CustomObject>
    <description>Object within the Account to track number of license and address as part of ship to.</description>
    <label>State License</label>
    <nameField>
        <displayFormat>SLID-{YYYY}-{MM}-{0000000000}</displayFormat>
        <label>License</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>State Licenses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/State_Licenses__c/fields/Default_Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Default_Warehouse__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Default Warehouse</label>
    <referenceTo>Site__c</referenceTo>
    <relationshipLabel>State Licenses</relationshipLabel>
    <relationshipName>State_Licenses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/State_Licenses__c/fields/License_City__c.field-meta.xml
<CustomField>
    <fullName>License_City__c</fullName>
    <label>License City</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Delivery_Cities</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/State_Licenses__c/fields/License_Class__c.field-meta.xml
<CustomField>
    <fullName>License_Class__c</fullName>
    <inlineHelpText>License Classification:
Adult Use = A-License
Medicinal Use = M-License</inlineHelpText>
    <label>License Class</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A-License</fullName>
            </value>
            <value>
                <fullName>M-License</fullName>
            </value>
            <value>
                <fullName>AM-License</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/State_Licenses__c/fields/License_Country__c.field-meta.xml
<CustomField>
    <fullName>License_Country__c</fullName>
    <label>License Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>US</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/State_Licenses__c/fields/License_Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>License_Expiration_Date__c</fullName>
    <inlineHelpText>License Expiration Date</inlineHelpText>
    <label>License Expiration Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/State_Licenses__c/fields/License_Name__c.field-meta.xml
<CustomField>
    <fullName>License_Name__c</fullName>
    <label>License Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>State Licenses</relationshipLabel>
    <relationshipName>State_Licenses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/State_Licenses__c/fields/License_Number__c.field-meta.xml
<CustomField>
    <fullName>License_Number__c</fullName>
    <inlineHelpText>State License Number</inlineHelpText>
    <label>License Number</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/State_Licenses__c/fields/License_State__c.field-meta.xml
<CustomField>
    <fullName>License_State__c</fullName>
    <label>License State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>States</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/State_Licenses__c/fields/License_Status__c.field-meta.xml
<CustomField>
    <fullName>License_Status__c</fullName>
    <inlineHelpText>License Status from State</inlineHelpText>
    <label>License Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
            <value>
                <fullName>Revoked</fullName>
            </value>
            <value>
                <fullName>Terminated</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/State_Licenses__c/fields/License_Type__c.field-meta.xml
<CustomField>
    <fullName>License_Type__c</fullName>
    <label>License Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>License_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/State_Licenses__c/fields/License_Zip__c.field-meta.xml
<CustomField>
    <fullName>License_Zip__c</fullName>
    <label>License Zip</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PublishServicesTicketToSlackTest.cls
@isTest
public class PublishServicesTicketToSlackTest {
	@isTest
    private static void runTest(){
        Google_Distance_Matrix_API__c g = new Google_Distance_Matrix_API__c();
        g.Value__c = 'https://maps.googleapis.com/maps/api/geocode/json?';
        g.Name = 'Geocode_Endpoint';
        insert g;
        Test.setMock(HttpCalloutMock.class, new StateLicense_MockResponseTest());  
        TestUtilData.skipTrigger = true;
        TestUtilData.createTestData();
        Site__c s = new Site__c(Name= '2089-3',Warehouse_Name__c='San Francisco',Sort_Order__c=1,Active__c=true);
        insert s;
        Account acc =new Account();
        acc.Name='acName';
        acc.Type = 'Distributor';
        insert acc;
        Contact con =new Contact();
        con.FirstName='con';
        con.LastName='test';
        con.AccountId=acc.Id;
        con.Email = 'Testcontactat1@filigreencustomer.com';
        con.Primary_Contact__c = true;
        insert con;
        integer j=10;
        State_Licenses__c objStateLicenses = new State_Licenses__c();
        objStateLicenses.License_Name__c = acc.id;
        objStateLicenses.License_Number__c = 'AbcTest'+(j*10)+10;
        objStateLicenses.License_Status__c ='Active';
        objStateLicenses.License_Type__c ='Type 1';
        objStateLicenses.License_Class__c='A-License';
        objStateLicenses.License_City__c = 'Banning';
        objStateLicenses.License_State__c = 'Florida';
        objStateLicenses.License_Country__c = 'US';
        objStateLicenses.License_Zip__c = '12333';
        objStateLicenses.Default_Warehouse__c =s.id;
        objStateLicenses.License_Expiration_Date__c = date.valueof(system.now()) + 10;
        insert objStateLicenses;
        
        Service_Ticket__c st =new Service_Ticket__c();
     //   st.Status__c ='New';
        st.Brand_Contact__c=con.Id;
        st.Brand_Name__c=acc.Id;
        st.Licensed_Premise__c =objStateLicenses.id;
        st.Transfer_Method__c='Product Conversions';
      //  st.Status__c='New';
        insert st;
        PublishServicesTicketToSlack.publishToSlack(new List<Id>{st.Id});
        st.Transfer_Method__c='Drop-off';
        update st;
        PublishServicesTicketToSlack.publishToSlack(new List<Id>{st.Id});
        
    }
}