force-app/main/default/objects/Google_Distance_Matrix_API__c/Google_Distance_Matrix_API__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Google_Distance_Matrix_API</label>
</CustomObject>

force-app/main/default/objects/Service_Ticket__c/Service_Ticket__c.object-meta.xml
<CustomObject>
    <description>Service ticket object in Community</description>
    <label>Service Ticket</label>
    <nameField>
        <displayFormat>ST-{YYYY}-{MM}-{00000}</displayFormat>
        <label>Service Ticket #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Tickets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Ticket__c/fields/Brand_Contact__c.field-meta.xml
<CustomField>
    <fullName>Brand_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Brand Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Service Tickets</relationshipLabel>
    <relationshipName>Service_Tickets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_Ticket__c/fields/Brand_Name__c.field-meta.xml
<CustomField>
    <fullName>Brand_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Brand Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Service Tickets</relationshipLabel>
    <relationshipName>Service_Tickets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_Ticket__c/fields/License_Number__c.field-meta.xml
<CustomField>
    <fullName>License_Number__c</fullName>
    <formula>Licensed_Premise__r.License_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>License Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service_Ticket__c/fields/License_Type__c.field-meta.xml
<CustomField>
    <fullName>License_Type__c</fullName>
    <formula>TEXT(Licensed_Premise__r.License_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>License Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service_Ticket__c/fields/Licensed_Premise__c.field-meta.xml
<CustomField>
    <fullName>Licensed_Premise__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Licensed Premise</label>
    <referenceTo>State_Licenses__c</referenceTo>
    <relationshipLabel>Service Tickets</relationshipLabel>
    <relationshipName>Service_Tickets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_Ticket__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>New</fullName>
                <isActive>false</isActive>
                <label>New</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service_Ticket__c/fields/Transfer_Method__c.field-meta.xml
<CustomField>
    <fullName>Transfer_Method__c</fullName>
    <label>Transfer Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Drop-off</fullName>
            </value>
            <value>
                <fullName>Pick-up</fullName>
            </value>
            <value>
                <fullName>Product Conversions</fullName>
            </value>
            <value>
                <fullName>D2D Transfer</fullName>
                <isActive>false</isActive>
                <label>D2D Transfer</label>
            </value>
            <value>
                <fullName>None (In stock)</fullName>
                <isActive>false</isActive>
                <label>None (In stock)</label>
            </value>
            <value>
                <fullName>Sample Pick-Up</fullName>
                <isActive>false</isActive>
                <label>Sample Pick-Up</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service_Ticket_Line__c/Service_Ticket_Line__c.object-meta.xml
<CustomObject>
    <description>Service ticket object in Community</description>
    <label>Service Ticket Line</label>
    <nameField>
        <displayFormat>STL-{0000000}</displayFormat>
        <label>Service Ticket Line #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Ticket Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Ticket_Line__c/fields/New_Packaged_Product__c.field-meta.xml
<CustomField>
    <fullName>New_Packaged_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Select the new product name, which product will become.</inlineHelpText>
    <label>New Packaged Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Service Ticket Lines (New Packaged Product)</relationshipLabel>
    <relationshipName>Service_Ticket_Lines1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_Ticket_Line__c/fields/Service_Ticket__c.field-meta.xml
<CustomField>
    <fullName>Service_Ticket__c</fullName>
    <label>Service Ticket</label>
    <referenceTo>Service_Ticket__c</referenceTo>
    <relationshipLabel>Service Ticket Lines</relationshipLabel>
    <relationshipName>Service_Ticket_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Service_Ticket_Line__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service_Ticket_Line__c/fields/Total_Units__c.field-meta.xml
<CustomField>
    <fullName>Total_Units__c</fullName>
    <inlineHelpText>Please enter the total qty of units to transfer</inlineHelpText>
    <label>Total Units</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Site__c/Site__c.object-meta.xml
<CustomObject>
    <description>All objects must have a Site Name and License Class or A or M. For separate sales and inventory record.</description>
    <label>Site</label>
    <nameField>
        <label>Site</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Site__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active ?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Site__c/fields/License_Class__c.field-meta.xml
<CustomField>
    <fullName>License_Class__c</fullName>
    <formula>TEXT(License_ID__r.License_Class__c)</formula>
    <label>License Class</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site__c/fields/License_Name__c.field-meta.xml
<CustomField>
    <fullName>License_Name__c</fullName>
    <formula>License_ID__r.License_Name__r.Name</formula>
    <label>License Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site__c/fields/License_Number__c.field-meta.xml
<CustomField>
    <fullName>License_Number__c</fullName>
    <formula>License_ID__r.License_Number__c</formula>
    <label>License Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site__c/fields/Warehouse_Name__c.field-meta.xml
<CustomField>
    <fullName>Warehouse_Name__c</fullName>
    <description>Name of the warehouse to display in UI. Example : Communities.</description>
    <label>Warehouse Name</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/State_Licenses__c/State_Licenses__c.object-meta.xml
<CustomObject>
    <description>Object within the Account to track number of license and address as part of ship to.</description>
    <label>State License</label>
    <nameField>
        <displayFormat>SLID-{YYYY}-{MM}-{0000000000}</displayFormat>
        <label>License</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>State Licenses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/State_Licenses__c/fields/Default_Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Default_Warehouse__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Default Warehouse</label>
    <referenceTo>Site__c</referenceTo>
    <relationshipLabel>State Licenses</relationshipLabel>
    <relationshipName>State_Licenses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/State_Licenses__c/fields/License_City__c.field-meta.xml
<CustomField>
    <fullName>License_City__c</fullName>
    <label>License City</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Delivery_Cities</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/State_Licenses__c/fields/License_Class__c.field-meta.xml
<CustomField>
    <fullName>License_Class__c</fullName>
    <inlineHelpText>License Classification:
Adult Use = A-License
Medicinal Use = M-License</inlineHelpText>
    <label>License Class</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A-License</fullName>
            </value>
            <value>
                <fullName>M-License</fullName>
            </value>
            <value>
                <fullName>AM-License</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/State_Licenses__c/fields/License_Country__c.field-meta.xml
<CustomField>
    <fullName>License_Country__c</fullName>
    <label>License Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>US</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/State_Licenses__c/fields/License_Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>License_Expiration_Date__c</fullName>
    <inlineHelpText>License Expiration Date</inlineHelpText>
    <label>License Expiration Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/State_Licenses__c/fields/License_Name__c.field-meta.xml
<CustomField>
    <fullName>License_Name__c</fullName>
    <label>License Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>State Licenses</relationshipLabel>
    <relationshipName>State_Licenses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/State_Licenses__c/fields/License_Number__c.field-meta.xml
<CustomField>
    <fullName>License_Number__c</fullName>
    <inlineHelpText>State License Number</inlineHelpText>
    <label>License Number</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/State_Licenses__c/fields/License_State__c.field-meta.xml
<CustomField>
    <fullName>License_State__c</fullName>
    <label>License State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>States</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/State_Licenses__c/fields/License_Status__c.field-meta.xml
<CustomField>
    <fullName>License_Status__c</fullName>
    <inlineHelpText>License Status from State</inlineHelpText>
    <label>License Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
            <value>
                <fullName>Revoked</fullName>
            </value>
            <value>
                <fullName>Terminated</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/State_Licenses__c/fields/License_Type__c.field-meta.xml
<CustomField>
    <fullName>License_Type__c</fullName>
    <label>License Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>License_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/State_Licenses__c/fields/License_Zip__c.field-meta.xml
<CustomField>
    <fullName>License_Zip__c</fullName>
    <label>License Zip</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ServiceTicketsCtlrTest.cls
@isTest
public class ServiceTicketsCtlrTest {
    private static testmethod void runTest(){
        Google_Distance_Matrix_API__c g = new Google_Distance_Matrix_API__c();
        g.Value__c = 'https://maps.googleapis.com/maps/api/geocode/json?';
        g.Name = 'Geocode_Endpoint';
        insert g;
        Test.setMock(HttpCalloutMock.class, new StateLicense_MockResponseTest());  
        TestUtilData.skipTrigger = true;
        TestUtilData.createTestData();
        Site__c s = new Site__c(Name= '2089-3',Warehouse_Name__c='San Francisco',Sort_Order__c=1,Active__c=true);
        insert s;
        Pricebook2 customPB = new Pricebook2(Name='Custom Pricebook', isActive=true);
        insert customPB;
        Account acc =new Account();
        acc.Name='acName';
        acc.Type = 'Distributor';
        insert acc;
        Contact con =new Contact();
        con.FirstName='con';
        con.LastName='test';
        con.AccountId=acc.Id;
        con.Email = 'Testcontactat1@filigreencustomer.com';
        con.Primary_Contact__c = true;
        insert con;
        integer j=10;
        State_Licenses__c objStateLicenses = new State_Licenses__c();
        objStateLicenses.License_Name__c = acc.id;
        objStateLicenses.License_Number__c = 'AbcTest'+(j*10)+10;
        objStateLicenses.License_Status__c ='Active';
        objStateLicenses.License_Type__c ='Type 1';
        objStateLicenses.License_Class__c='A-License';
        objStateLicenses.License_City__c = 'Banning';
        objStateLicenses.License_State__c = 'Florida';
        objStateLicenses.License_Country__c = 'US';
        objStateLicenses.License_Zip__c = '12333';
        objStateLicenses.Default_Warehouse__c =s.id;
        objStateLicenses.License_Expiration_Date__c = date.valueof(system.now()) + 10;
        insert objStateLicenses;
        
        List<Product2> products = [SELECT Id,Most_Popular__c FROM Product2];
        products[0].Most_Popular__c = true;
        products[0].Available_Inventory__c = 200;
        update products[0];
        
        Service_Ticket__c st =new Service_Ticket__c();
        st.Status__c ='Pending';
        st.Brand_Contact__c=con.Id;
        st.Brand_Name__c=acc.Id;
        st.Licensed_Premise__c =objStateLicenses.id;
        st.Transfer_Method__c='Product Conversions';
        st.Status__c='Pending';
        insert st;
        
        Service_Ticket_Line__c stl =new Service_Ticket_Line__c();
        stl.New_Packaged_Product__c=products[0].id;
        stl.Service_Ticket__c =st.Id;
        stl.Status__c='Completed';
        stl.Total_Units__c =10;
        stl.New_Packaged_Product__c =products[0].id;
        insert stl;
        
        List<Profile> profiles = [SELECT Id, Name FROM Profile WHERE Name = 'Customer Community Plus User Custom'];
        User u = new User();
        u.ProfileId = profiles[0].Id;
        u.firstName = 'testcontact1';
        u.lastName = 'customeruser';
        u.Username = 'Testcontactat1@filigreencustomer.com.testaccount1';
        u.Email = 'Testcontactat1@filigreencustomer.com';
        u.ContactId = con.Id;
        u.Title = 'Customer';
        u.CommunityNickname = 'ruser';
        u.Alias = 'testser';
        u.TimeZoneSidKey = 'America/Los_Angeles'; // Required
        u.LocaleSidKey = 'en_US'; // Required
        u.EmailEncodingKey = 'ISO-8859-1'; // Required
        u.LanguageLocaleKey = 'en_US'; // Required
        insert u;
        
        Id pricebookId = Test.getStandardPricebookId();
        
        // 1. Insert a price book entry for the standard price book.
        // Standard price book entries require the standard price book ID we got earlier.
        List<PricebookEntry> pbeList = new List<PricebookEntry>();
        Map<String,PriceBookEntry> pbeMap = new Map<String,PriceBookEntry>();
        for(PriceBookEntry pbe: [SELECT Id, PriceBook2Id, Product2Id FROM PriceBookEntry]){
            pbeMap.put(pbe.PriceBook2Id+'-'+pbe.Product2Id,pbe);
        }
        
         
        
        for(Product2 p: products){
            p.MOQ__c = 1;
            p.Available_Inventory__c = 100;
            p.Producer_Name__c = acc.Id;
            //p.Supplier_UOM__c='CT';
           // p.Case_Radius__c=122;
           // p.Case_Height__c=152;
            p.Product_Rating__c = 0;
            p.Unit_Gross_Weight__c =10;
            p.Retail_Unit_Form_Factor__c  ='Jar';
            p.Unit_Radius__c =3;
            p.Unit_Height__c =6;
            //p.Case_Dim_Weight__c=20;
            if(!pbeMap.containsKey(pricebookId+'-'+p.Id)){
                pbeList.add(new PricebookEntry(
                    Pricebook2Id = pricebookId, Product2Id = p.Id,
                    UnitPrice = 10000, IsActive = true));
            }
            if(!pbeMap.containsKey(customPB.Id+'-'+p.Id)){
                pbeList.add(new PricebookEntry(
                    Pricebook2Id = customPB.Id, Product2Id = p.Id,
                    UnitPrice = 12000, IsActive = true));
            }
        }
        insert pbeList;
        update products;
        
        Test.startTest();
        System.runAs(u){
            AuraResponse r = ServiceTicketsCtlr.init(st.id);
            ServiceTicketsCtlr.ServiceTicket ServiceTicket =  (ServiceTicketsCtlr.ServiceTicket) r.data.get('serviceTicket');
            List<ServiceTicketsCtlr.serviceTicketLine> serviceTicketLine = (list<ServiceTicketsCtlr.serviceTicketLine>) r.data.get('serviceTicketLines');
            //List<Map<String, String>> ServiceTicketList = (List<Map<String, String>>) r.data.get('ServiceTicket');
            List<ServiceTicketsCtlr.BrandProduct> bproducts = (List<ServiceTicketsCtlr.BrandProduct>) r.data.get('products');
            Datetime todayDateTime = Date.today();
            String reqDate = todayDateTime+'';
            System.debug('reqDate = '+serviceTicketLine);
            
            //serviceTicketLine[0].Product = bproducts[0].id; 
            //serviceTicketLine[0].
            //ServiceTicketsCtlr.saveSeriveTicket('',JSON.serialize(ServiceTicket),JSON.serialize(serviceTicketLine),dateStr,true);
            
            
            
            r=ServiceTicketsCtlr.getServiceTicket(st.id);
            ServiceTicketsCtlr.insertBatchId('01214',acc.Id);
            //ServiceTicketsCtlr.insertUId('01256');
            Map<String, Object> filters = new Map<String, Object>();
            filters.put('orderByField','Name');
            filters.put('isASC','false');
            filters.put('searchTerm','S');
            filters.put('family','false');
            r=ServiceTicketsCtlr.getIds(filters,'true');
            Set<Id> ids = (Set<Id>)r.data.get('ids');
            List<String> idsList = new List<String>();
            for(Id idStr : ids){
                idsList.add(idStr);
            }
            ServiceTicketsCtlr.getServiceTickets(idsList,filters);
            r=ServiceTicketsCtlr.getIdsForFile(filters,'true');
            ids = (Set<Id>)r.data.get('ids');
            idsList = new List<String>();
            for(Id idStr : ids){
                idsList.add(idStr);
            }
            ServiceTicketsCtlr.getServiceTicketsFile(idsList,filters);
            
            try{
                for(ServiceTicketsCtlr.serviceTicketLine ser: serviceTicketLine){
                    ser.Product = products[0].Id;
                }
                
                r = ServiceTicketsCtlr.saveSeriveTicket('',JSON.serialize(ServiceTicket),JSON.serialize(serviceTicketLine),'',true);
            } catch(Exception ex){}
            
        }
    }
    private static testmethod void runProductCtrl(){
        
        
        Account[] rAccounts = new Account[]{};
            Account objAccount = new Account();
        objAccount.Name = 'Test Microbusiness';
        objAccount.Payment_Terms__c = 'COD';
        objAccount.Hide_from_Marketplace__c = false;
        objAccount.Type = 'Microbusiness';
        objAccount.Licensed_Verticals__c = 'Cultivator';
        rAccounts.add(objAccount);
        objAccount = new Account();
        objAccount.Name = 'Test Retailer';
        objAccount.Payment_Terms__c = 'COD';
        objAccount.Hide_from_Marketplace__c = false;
        objAccount.Type = 'Retailer';
        rAccounts.add(objAccount);
        objAccount = new Account();
        objAccount.Name = 'Test NonStoreFront';
        objAccount.Payment_Terms__c = 'COD';
        objAccount.Hide_from_Marketplace__c = false;
        objAccount.Type = 'Retailer NonStoreFront';
        insert objAccount;
        
        Contact con = new Contact();
        con.lastname = 'test';
        con.firstname = 'con';
        con.AccountId = objAccount.id;
        insert con;
        
        List<Profile> profiles = [SELECT Id, Name FROM Profile WHERE Name = 'Customer Community Plus User Custom'];
        User u = new User();
        u.ProfileId = profiles[0].Id;
        u.firstName = 'testcontact1';
        u.lastName = 'customeruser';
        u.Username = 'Testcontactat1@filigreencustomer.com.testaccount1';
        u.Email = 'Testcontactat1@filigreencustomer.com';
        u.ContactId = con.Id;
        u.Title = 'Customer';
        u.CommunityNickname = 'ruser';
        u.Alias = 'testser';
        u.TimeZoneSidKey = 'America/Los_Angeles'; // Required
        u.LocaleSidKey = 'en_US'; // Required
        u.EmailEncodingKey = 'ISO-8859-1'; // Required
        u.LanguageLocaleKey = 'en_US'; // Required
        insert u;
        
        system.runAs(u){
            Test.startTest();
            list<Holiday>holidayList = new List<Holiday>();
            Holiday h1 = new Holiday();
            h1.ActivityDate = system.today().addMonths(2);
            h1.Name = 'test 1';
            h1.RecurrenceType = 'RecursYearly';
            h1.IsRecurrence = true;
            h1.RecurrenceStartDate = system.today().addMonths(2);
            h1.RecurrenceDayOfMonth = 5;
            h1.RecurrenceMonthOfYear = 'July';
            holidayList.add(h1);
            
            Holiday h2 = new Holiday();
            h2.ActivityDate = system.today().addMonths(2);
            h2.Name = 'test 2';
            h2.RecurrenceType = 'RecursMonthly';
            h2.IsRecurrence = true;
            h2.RecurrenceStartDate = system.today().addMonths(2);
            h2.RecurrenceInterval = 3;
            h2.RecurrenceDayOfMonth = 5;
            holidayList.add(h2);
            
            insert holidayList;
            Test.stopTest(); 
            ServiceTicketsCtlr.getMonthNumber('December');
            ServiceTicketsCtlr.getHolidayDate(system.today(),holidayList[0]);
            ServiceTicketsCtlr.calanderEvents('01-01-2021','10:25 a');
            //ServiceTicketsCtlr.downloadFile();
            //ServiceTicketsCtlr.downloadPDFFile();
            ServiceTicketsCtlr.insertUId('N/A');
            //ServiceTicketsCtlr.saveSeriveTicket();
        }
    }
}