force-app/main/default/objects/Google_Distance_Matrix_API__c/Google_Distance_Matrix_API__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Google_Distance_Matrix_API</label>
</CustomObject>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <displayFormat>O-{000000}</displayFormat>
        <label>Order #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Brand Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Default_Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Default_Warehouse__c</fullName>
    <formula>State_License__r.Default_Warehouse__r.Warehouse_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Default Warehouse</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Delivered_Date__c.field-meta.xml
<CustomField>
    <fullName>Delivered_Date__c</fullName>
    <label>Delivered Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Order_Date__c.field-meta.xml
<CustomField>
    <fullName>Order_Date__c</fullName>
    <label>Order Date</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Payment_Terms__c.field-meta.xml
<CustomField>
    <fullName>Payment_Terms__c</fullName>
    <label>Payment Terms</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Payment_Terms</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/Request_Ship_Date__c.field-meta.xml
<CustomField>
    <fullName>Request_Ship_Date__c</fullName>
    <label>Request Ship Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Requested_Delivery_Earliest_Time__c.field-meta.xml
<CustomField>
    <fullName>Requested_Delivery_Earliest_Time__c</fullName>
    <label>Requested Delivery Earliest Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Requested_Delivery_Latest_Time__c.field-meta.xml
<CustomField>
    <fullName>Requested_Delivery_Latest_Time__c</fullName>
    <label>Requested Delivery Latest Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Retailer__c.field-meta.xml
<CustomField>
    <fullName>Retailer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Retailer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Retailer_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Retailer_Contact__c.field-meta.xml
<CustomField>
    <fullName>Retailer_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Retailer Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site</label>
    <referenceTo>Site__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/State_License__c.field-meta.xml
<CustomField>
    <fullName>State_License__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>State License</label>
    <referenceTo>State_Licenses__c</referenceTo>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Cancelled by Customer</fullName>
            </value>
            <value>
                <fullName>Cancelled by WOVN</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Payment</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Returned</fullName>
            </value>
            <value>
                <fullName>Shipped</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/recordTypes/Transfer.recordType-meta.xml
<RecordType>
    <fullName>Transfer</fullName>
    <active>true</active>
    <label>Transfer</label>
</RecordType>

force-app/main/default/objects/Site__c/Site__c.object-meta.xml
<CustomObject>
    <description>All objects must have a Site Name and License Class or A or M. For separate sales and inventory record.</description>
    <label>Site</label>
    <nameField>
        <label>Site</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Site__c/fields/License_Class__c.field-meta.xml
<CustomField>
    <fullName>License_Class__c</fullName>
    <formula>TEXT(License_ID__r.License_Class__c)</formula>
    <label>License Class</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site__c/fields/License_Name__c.field-meta.xml
<CustomField>
    <fullName>License_Name__c</fullName>
    <formula>License_ID__r.License_Name__r.Name</formula>
    <label>License Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site__c/fields/License_Number__c.field-meta.xml
<CustomField>
    <fullName>License_Number__c</fullName>
    <formula>License_ID__r.License_Number__c</formula>
    <label>License Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site__c/fields/Warehouse_Name__c.field-meta.xml
<CustomField>
    <fullName>Warehouse_Name__c</fullName>
    <description>Name of the warehouse to display in UI. Example : Communities.</description>
    <label>Warehouse Name</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/State_Licenses__c/State_Licenses__c.object-meta.xml
<CustomObject>
    <description>Object within the Account to track number of license and address as part of ship to.</description>
    <label>State License</label>
    <nameField>
        <displayFormat>SLID-{YYYY}-{MM}-{0000000000}</displayFormat>
        <label>License</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>State Licenses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/State_Licenses__c/fields/Default_Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Default_Warehouse__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Default Warehouse</label>
    <referenceTo>Site__c</referenceTo>
    <relationshipLabel>State Licenses</relationshipLabel>
    <relationshipName>State_Licenses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/State_Licenses__c/fields/License_Address__c.field-meta.xml
<CustomField>
    <fullName>License_Address__c</fullName>
    <label>License Address</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/State_Licenses__c/fields/License_City__c.field-meta.xml
<CustomField>
    <fullName>License_City__c</fullName>
    <label>License City</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Delivery_Cities</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/State_Licenses__c/fields/License_Class__c.field-meta.xml
<CustomField>
    <fullName>License_Class__c</fullName>
    <inlineHelpText>License Classification:
Adult Use = A-License
Medicinal Use = M-License</inlineHelpText>
    <label>License Class</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A-License</fullName>
            </value>
            <value>
                <fullName>M-License</fullName>
            </value>
            <value>
                <fullName>AM-License</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/State_Licenses__c/fields/License_Country__c.field-meta.xml
<CustomField>
    <fullName>License_Country__c</fullName>
    <label>License Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>US</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/State_Licenses__c/fields/License_Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>License_Expiration_Date__c</fullName>
    <inlineHelpText>License Expiration Date</inlineHelpText>
    <label>License Expiration Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/State_Licenses__c/fields/License_Name__c.field-meta.xml
<CustomField>
    <fullName>License_Name__c</fullName>
    <label>License Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>State Licenses</relationshipLabel>
    <relationshipName>State_Licenses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/State_Licenses__c/fields/License_Number__c.field-meta.xml
<CustomField>
    <fullName>License_Number__c</fullName>
    <inlineHelpText>State License Number</inlineHelpText>
    <label>License Number</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/State_Licenses__c/fields/License_State__c.field-meta.xml
<CustomField>
    <fullName>License_State__c</fullName>
    <label>License State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>States</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/State_Licenses__c/fields/License_Status__c.field-meta.xml
<CustomField>
    <fullName>License_Status__c</fullName>
    <inlineHelpText>License Status from State</inlineHelpText>
    <label>License Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
            <value>
                <fullName>Revoked</fullName>
            </value>
            <value>
                <fullName>Terminated</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/State_Licenses__c/fields/License_Type__c.field-meta.xml
<CustomField>
    <fullName>License_Type__c</fullName>
    <label>License Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>License_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/State_Licenses__c/fields/License_Zip__c.field-meta.xml
<CustomField>
    <fullName>License_Zip__c</fullName>
    <label>License Zip</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/State_Licenses__c/fields/Total_Miles__c.field-meta.xml
<CustomField>
    <fullName>Total_Miles__c</fullName>
    <defaultValue>0.00</defaultValue>
    <description>Total driving distance between default warehouse and licensee address</description>
    <inlineHelpText>Total driving distance between default warehouse and licensee address</inlineHelpText>
    <label>Total Miles</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/BatchMonthlyOrderCountTest.cls
@isTest
public class BatchMonthlyOrderCountTest {
    static testMethod void runTest(){
        Google_Distance_Matrix_API__c g = new Google_Distance_Matrix_API__c();
        g.Value__c = 'https://maps.googleapis.com/maps/api/geocode/json?';
        g.Name = 'Geocode_Endpoint';
        insert g;
        
        Test.setMock(HttpCalloutMock.class, new StateLicense_MockResponseTest());  
        TestUtilData.skipTrigger = true;
        
        Site__c s = new Site__c();
        s.Name = 'Test Site';
        s.Warehouse_Name__c='TestWarehouse1';
        insert s;
        
        Account acc =new Account();
        acc.Name = 'Test Account2';
        acc.Payment_Terms__c = 'COD';
        acc.Hide_from_Marketplace__c = false;
        acc.Type = 'Distributor';
        acc.DBA__c = 'WOVN LA | Zasp';
        insert acc;
        
        Contact con =new Contact();
        con.FirstName='con';
        con.LastName='test';
        con.AccountId=acc.Id;
        con.Email = 'Testcontactat1@filigreencustomer.com';
        con.Primary_Contact__c = true;
        
        insert con;
        

        State_Licenses__c sl = new State_Licenses__c();
        sl.License_Name__c = acc.Id;
        sl.License_Class__c = 'A-License';
        sl.License_Type__c = 'Type 11';
        sl.License_Number__c = 'A11-18-0000054-TEMP';
        sl.License_Status__c = 'Active';
        sl.License_Expiration_Date__c = System.today().addDays(60);
        sl.License_Address__c = '44650 101 Hwy N, Suite F';
        sl.License_City__c = 'Lafayette';
        sl.License_State__c = 'California';
        sl.License_Zip__c = '95454';
        sl.License_Country__c = 'US';
        sl.Default_Warehouse__c = s.Id;
        sl.Total_Miles__c=1;
        
        insert sl;
        Order__c ord= new Order__c();
        ord.Status__c='Shipped';
        ord.Account__c = acc.Id;
        ord.Order_Date__c=Date.today();
        ord.RecordTypeId = Schema.SObjectType.Order__c.getRecordTypeInfosByName().get('Transfer').getRecordTypeId();
        ord.State_License__c = sl.id;
        ord.Retailer__c = acc.Id;
        ord.Retailer_Contact__c =con.Id;
        ord.Request_Ship_Date__c =Date.today();
        ord.Delivered_Date__c =Date.today();
        ord.Requested_Delivery_Earliest_Time__c = Time.newInstance(1, 12, 13, 12);
        ord.Requested_Delivery_Latest_Time__c = Time.newInstance(1, 12, 13, 12);
        insert ord;
        
         List<Order__c> o = new List<Order__c>();
        o.add(ord);
        
         //Database.executeBatch(new BatchMonthlyOrderCount());
        Test.startTest();
        BatchMonthlyOrderCount bmc = new BatchMonthlyOrderCount();
        Database.QueryLocator ql = bmc.Start(null);
        bmc.execute(null, o);
        bmc.finish(null);
        //Database.executeBatch(bmc);
        Test.stopTest();
    }
}