force-app/main/default/objects/Google_Distance_Matrix_API__c/Google_Distance_Matrix_API__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Google_Distance_Matrix_API</label>
</CustomObject>

force-app/main/default/objects/Site__c/Site__c.object-meta.xml
<CustomObject>
    <description>All objects must have a Site Name and License Class or A or M. For separate sales and inventory record.</description>
    <label>Site</label>
    <nameField>
        <label>Site</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Site__c/fields/License_ID__c.field-meta.xml
<CustomField>
    <fullName>License_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>License ID</label>
    <referenceTo>State_Licenses__c</referenceTo>
    <relationshipLabel>Sites</relationshipLabel>
    <relationshipName>Sites</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Site__c/fields/License_Name__c.field-meta.xml
<CustomField>
    <fullName>License_Name__c</fullName>
    <formula>License_ID__r.License_Name__r.Name</formula>
    <label>License Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/State_Licenses__c/State_Licenses__c.object-meta.xml
<CustomObject>
    <description>Object within the Account to track number of license and address as part of ship to.</description>
    <label>State License</label>
    <nameField>
        <displayFormat>SLID-{YYYY}-{MM}-{0000000000}</displayFormat>
        <label>License</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>State Licenses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/State_Licenses__c/fields/Default_Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Default_Warehouse__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Default Warehouse</label>
    <referenceTo>Site__c</referenceTo>
    <relationshipLabel>State Licenses</relationshipLabel>
    <relationshipName>State_Licenses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/State_Licenses__c/fields/License_Address__c.field-meta.xml
<CustomField>
    <fullName>License_Address__c</fullName>
    <label>License Address</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/State_Licenses__c/fields/License_City__c.field-meta.xml
<CustomField>
    <fullName>License_City__c</fullName>
    <label>License City</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Delivery_Cities</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/State_Licenses__c/fields/License_Country__c.field-meta.xml
<CustomField>
    <fullName>License_Country__c</fullName>
    <label>License Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>US</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/State_Licenses__c/fields/License_Name__c.field-meta.xml
<CustomField>
    <fullName>License_Name__c</fullName>
    <label>License Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>State Licenses</relationshipLabel>
    <relationshipName>State_Licenses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/State_Licenses__c/fields/License_State__c.field-meta.xml
<CustomField>
    <fullName>License_State__c</fullName>
    <label>License State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>States</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/State_Licenses__c/fields/License_Zip__c.field-meta.xml
<CustomField>
    <fullName>License_Zip__c</fullName>
    <label>License Zip</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/State_Licenses__c/fields/Total_Miles__c.field-meta.xml
<CustomField>
    <fullName>Total_Miles__c</fullName>
    <defaultValue>0.00</defaultValue>
    <description>Total driving distance between default warehouse and licensee address</description>
    <inlineHelpText>Total driving distance between default warehouse and licensee address</inlineHelpText>
    <label>Total Miles</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/BatchToUpdateLicenceRecords.cls
global class BatchToUpdateLicenceRecords implements Database.Batchable<sObject>, Database.Stateful, Database.AllowsCallouts{
    global Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator([select Default_Warehouse__r.License_ID__r.License_City__c,
                                              Default_Warehouse__r.License_ID__r.License_State__c, 
                                              Default_Warehouse__r.License_ID__r.License_Address__c,
                                              Default_Warehouse__r.License_ID__r.License_Country__c,
                                              Default_Warehouse__r.License_ID__r.License_Zip__c,License_Name__c, 
                                              License_City__c, License_Address__c, License_State__c, License_Country__c,Total_Miles__c, 
                                              License_Zip__c,License_Location__Latitude__s,License_Location__Longitude__s, Id FROM State_Licenses__c]);   
    }
    
    global void execute(Database.BatchableContext bc, List<State_Licenses__c> records){
        
        for(State_Licenses__c sl : records){
        	sl =  getMiles(sl); 
            sl =  getGeoCodes(sl); 
        }
		update records;       
    }
    
    private static State_Licenses__c getGeoCodes(State_Licenses__c sl){
        String url = Google_Distance_Matrix_API__c.getValues('Geocode_Endpoint').Value__c;
        String apiKey = Google_Distance_Matrix_API__c.getValues('Gmaps_APIKey').Value__c;
        String parameters = 'address=' +sl.License_Address__c +','+ sl.License_City__c +','+ sl.License_Country__c +','+ sl.License_State__c +','+ sl.License_Zip__c;
        String param2 =  '&language=en&key=';
        parameters = parameters.replace(' ','%20');
        url = url+parameters+param2+apiKey;
        url = url.replaceAll('#', '%20');
        url += '&sensor=false';
        System.debug('After... '+url);
        
        HTTP http = new HTTP();
        HTTPRequest request = new HTTPRequest();
        request.setEndpoint(url);
        request.setMethod('GET');
        HTTPResponse response = http.send(request);
        system.debug('response.getStatusCode()'+response.getStatusCode());
        System.debug('Respons..'+response.getBody());
        if(response.getStatusCode() == 200) {
            JSONParser parser = JSON.createParser(response.getBody());
            double lat = null;
            double lon = null;
            while (parser.nextToken() != null) {
                if ((parser.getCurrentToken() == JSONToken.FIELD_NAME) && (parser.getText() == 'location')){
                    parser.nextToken(); // object start
                    while (parser.nextToken() != JSONToken.END_OBJECT){    
                        String txt = parser.getText();
                        parser.nextToken();
                        if (txt == 'lat')
                            lat = parser.getDoubleValue();
                        else if (txt == 'lng')
                            lon = parser.getDoubleValue();
                    }
                }
            }
            sl.License_Location__Latitude__s = lat;
            sl.License_Location__Longitude__s = lon;
        }
        return sl;
    }
    
    private static State_Licenses__c getMiles(State_Licenses__c sl){
        String url = Google_Distance_Matrix_API__c.getValues('GMaps_Endpoint').Value__c;
        String apiKey = Google_Distance_Matrix_API__c.getValues('Gmaps_APIKey').Value__c;
        String parameters = 'origins=' + sl.Default_Warehouse__r.License_ID__r.License_Address__c +','+ sl.Default_Warehouse__r.License_ID__r.License_City__c +','+ sl.Default_Warehouse__r.License_ID__r.License_Country__c + ','+sl.Default_Warehouse__r.License_ID__r.License_State__c +','+ sl.Default_Warehouse__r.License_ID__r.License_Zip__c+ '&destinations=' + sl.License_Address__c +','+ sl.License_City__c +','+ sl.License_Country__c +','+ sl.License_State__c +','+ sl.License_Zip__c;
        String param2 =  '&language=en&key=';
        parameters = parameters.replace(' ','%20');
        url = url+parameters+param2+apiKey;
        url = url.replaceAll('#', '%20');
        System.debug('After... '+url);
        
        HTTP http = new HTTP();
        HTTPRequest request = new HTTPRequest();
        request.setEndpoint(url);
        request.setMethod('GET');
        HTTPResponse response = http.send(request);
        system.debug('response.getStatusCode()'+response.getStatusCode());
        System.debug('Respons..'+response.getBody());
        if(response.getStatusCode() == 200) {
            double distVal = 0;
            StateLicenseTotalMilesTriggerHelper.DistanceResponse reponse = (StateLicenseTotalMilesTriggerHelper.DistanceResponse) JSON.deserialize(response.getBody(), StateLicenseTotalMilesTriggerHelper.DistanceResponse.class); 
            if(reponse != null && reponse.rows != null){
                if(reponse.rows[0].elements != null){
                    if(reponse.rows[0].elements[0].distance != null && reponse.rows[0].elements[0].distance.value != null){
                        distVal = reponse.rows[0].elements[0].distance.value;
                        distVal = distVal * 0.00062137;
                    }
                }
            }
            sl.Total_Miles__c =  distVal;
        }
        return sl;
    }
    
    global void finish(Database.BatchableContext bc){} 
}