force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>IN-{0000000000}</displayFormat>
        <label>Invoice</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/AR_Status__c.field-meta.xml
<CustomField>
    <fullName>AR_Status__c</fullName>
    <label>AR Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Shipped</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Order_Line__c/Sales_Order_Line__c.object-meta.xml
<CustomObject>
    <label>Sales Order Line</label>
    <nameField>
        <displayFormat>SOLI-{0000000000}</displayFormat>
        <label>SO Line</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Order_Line__c/fields/Qty_Invoiced__c.field-meta.xml
<CustomField>
    <fullName>Qty_Invoiced__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Qty Invoiced</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CancelInvoiceControllerTest.cls
/**
 * Copyright (c) 2018 Filigreen Distro
 * All rights reserved.
 * CancelInvoiceControllerTest
 */
@isTest(OnInstall=false SeeAllData=false)
public class CancelInvoiceControllerTest{
    
    static Invoice__c invoiceSO;
    static List<Sales_Order_Line__c> soLines;
    
    // Test loading VF page
    static testMethod void testUpdateInvoiceAndSOLines(){
        retrieveData();
        
        // verify invoice status
        System.assertEquals('Draft', 
                            invoiceSO.AR_Status__c,
                            'Invoice status mis-match');
        
        // verify SO lines Qty invoiced
        System.assertEquals(3, soLines.size(), 'SO lines size mis-match');
        
        System.assertEquals(5.0,
                            soLines[0].Qty_Invoiced__c, 
                            'SO Line Qty Invoiced mis-match');
                            
        System.assertEquals(15.0,
                            soLines[1].Qty_Invoiced__c, 
                            'SO Line Qty Invoiced mis-match');
                            
        System.assertEquals(25.0,
                            soLines[2].Qty_Invoiced__c, 
                            'SO Line Qty Invoiced mis-match');
        
        PageReference pageRef = Page.CancelInvoice;
        pageRef.getParameters().put('id', invoiceSO.Id);
        Test.setCurrentPage(pageRef);
        
        ApexPages.StandardController stdController = new ApexPages.StandardController(invoiceSO);
        CancelInvoiceController controllerObj = new CancelInvoiceController(stdController);
        controllerObj.updateInevoiceAndLines();
        
        // verify invoice status
        invoiceSO = [Select Id, AR_Status__c from Invoice__c where Id =: invoiceSO.Id];
        System.assertEquals(InvoiceSupport.INVOICE_STATUS_CANCELLED,
                            invoiceSO.AR_Status__c, 
                            'Invoice status mis-match');
                            
        // verify SO lines Qty invoiced
        soLines = [Select Qty_Invoiced__c From Sales_Order_Line__c];
        System.assertEquals(3, soLines.size(), 'SO lines size mis-match');
        
        System.assertEquals(0.0,
                            soLines[0].Qty_Invoiced__c, 
                            'SO Line Qty Invoiced mis-match');
                            
        System.assertEquals(0.0,
                            soLines[1].Qty_Invoiced__c, 
                            'SO Line Qty Invoiced mis-match');
                            
        System.assertEquals(0.0,
                            soLines[2].Qty_Invoiced__c, 
                            'SO Line Qty Invoiced mis-match');
                    
    }
    
    @TestSetUp
    static void testDataSetUp(){
        TestUtilData.createTestData();
    }
    
    // Retrieve data created from data setup
    public static void retrieveData(){
        invoiceSO = new Invoice__c();
        invoiceSO = [Select Id, AR_Status__c from Invoice__c];
        
        soLines = new List<Sales_Order_Line__c>();
        soLines = [Select Qty_Invoiced__c From Sales_Order_Line__c];
    }
}