force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>IN-{0000000000}</displayFormat>
        <label>Invoice</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Invoice_Date__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Date__c</fullName>
    <defaultValue>Today()</defaultValue>
    <label>Invoice Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Receiver_License__c.field-meta.xml
<CustomField>
    <fullName>Receiver_License__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Receiver License</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>State_Licenses__c.License_Name__c</field>
            <operation>equals</operation>
            <valueField>$Source.Receiver_Name__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>State_Licenses__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Subtotal_Local_Cannabis_Tax__c.field-meta.xml
<CustomField>
    <fullName>Subtotal_Local_Cannabis_Tax__c</fullName>
    <label>Subtotal Local Cannabis Tax</label>
    <summarizedField>Invoice_Line__c.Subtotal_Local_Cannabis_Tax__c</summarizedField>
    <summaryFilterItems>
        <field>Invoice_Line__c.InvoiceLine_Status__c</field>
        <operation>notEqual</operation>
        <value>Cancelled, Rejected</value>
    </summaryFilterItems>
    <summaryForeignKey>Invoice_Line__c.Invoice__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Invoice_Line__c/Invoice_Line__c.object-meta.xml
<CustomObject>
    <label>Invoice Line</label>
    <nameField>
        <displayFormat>INLI-{0000000000}</displayFormat>
        <label>Invoice Line</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_Line__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Invoice Lines</relationshipLabel>
    <relationshipName>Invoice_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice_Line__c/fields/Line_Total_Product_Price__c.field-meta.xml
<CustomField>
    <fullName>Line_Total_Product_Price__c</fullName>
    <formula>if(TEXT( InvoiceLine_Status__c )  &lt;&gt; &apos;Rejected&apos;  &amp;&amp;  TEXT( InvoiceLine_Status__c )  &lt;&gt; &apos;Cancelled&apos;
, Retail_Wholesale_Price__c *  Invoice_Qty__c , 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Line Total Product Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice_Line__c/fields/Subtotal_Local_Cannabis_Tax__c.field-meta.xml
<CustomField>
    <fullName>Subtotal_Local_Cannabis_Tax__c</fullName>
    <label>Subtotal Local Cannabis Tax</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment_Terms_Settings__c/Payment_Terms_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Contains all values of Payment Terms picklist value set. 
Used to calculate invoice due date</description>
    <label>Payment Terms Settings</label>
</CustomObject>

force-app/main/default/objects/Payment_Terms_Settings__c/fields/Offset__c.field-meta.xml
<CustomField>
    <fullName>Offset__c</fullName>
    <label>Offset</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Tax_Table__c/Tax_Table__c.object-meta.xml
<CustomObject>
    <label>Tax Table</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>Tax Table Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tax Tables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tax_Table__c/fields/Actual_Tax_Rate_on_Product_Rev__c.field-meta.xml
<CustomField>
    <fullName>Actual_Tax_Rate_on_Product_Rev__c</fullName>
    <label>Actual Tax Rate on Product Rev</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Tax_Table__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Delivery_Cities</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Tax_Table__c/fields/Tax_Due_Rate__c.field-meta.xml
<CustomField>
    <fullName>Tax_Due_Rate__c</fullName>
    <label>Tax Due Rate</label>
    <precision>4</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Tax_Table__c/fields/Taxable_Gross_Receipts_Rate__c.field-meta.xml
<CustomField>
    <fullName>Taxable_Gross_Receipts_Rate__c</fullName>
    <label>Taxable Gross Receipts Rate</label>
    <precision>4</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/classes/InvoiceSupport.cls
/**
 * Copyright (c) 2018 Filigreen Distro
 * All rights reserved.
 * InvoiceSupport
 */
public with sharing class InvoiceSupport {
    public static Map<String, Tax_Table__c > cityTaxMap{
        get{
            if(cityTaxMap == null){
                cityTaxMap = new Map<String, Tax_Table__c >();
                for(Tax_Table__c tt: [SELECT Id,Active__c ,Actual_Tax_Rate_on_Product_Rev__c ,City__c, End_Date__c , Start_Date__c , Taxable_Gross_Receipts_Rate__c, Tax_Due_Rate__c  FROM Tax_Table__c WHERE Active__c = true]){
                    cityTaxMap.put(tt.City__c,tt);
                }
            }
            return cityTaxMap;
        }set;
    }
    public static final String INVOICE_STATUS_CANCELLED = 'Cancelled';
    public static final String INVOICE_COLLECTION_STATUS_PAID_IN_FULL = 'Paid in Full';
    public static final String INVOICE_COLLECTION_STATUS_PAST_DUE = 'Past Due';
    
    /**
     * Calculate Invoice Due date based on SO planned ship date and Payment terms
     * @param plannedShipDate The planned ship date of SO
     * @param paymentTerms The payment term value
     *
     * @return Calculated invoice due date
     */
    public static Date calculateInvoiceDueDate(Date plannedShipDate,
                                               String paymentTerms){
        
        if(plannedShipDate == null || String.isBlank(paymentTerms)){
            return plannedShipDate;
        }
        
        Date invoiceDueDate = plannedShipDate;
        
        // Get payment term custom settings and find the offset to add days
        Payment_Terms_Settings__c paymentTermSettings = Payment_Terms_Settings__c.getInstance(paymentTerms);
        
        if(paymentTermSettings != null && paymentTermSettings.Offset__c != null){
            invoiceDueDate = invoiceDueDate.addDays(Integer.valueOf(paymentTermSettings.Offset__c));
        }
        return invoiceDueDate;
    }
    public static Date calculateInvoiceDueDate(Date shipConfirmationDate,Date plannedShipDate, String paymentTerms){
        System.Debug('##shipConfirmationDate:'+shipConfirmationDate);
        Date invoiceDueDate = NULL;//System.today();
        if(shipConfirmationDate != null){
            invoiceDueDate = shipConfirmationDate;
            System.Debug('##invoiceDueDate updating from Ship Confirmation:'+invoiceDueDate);
        }/*else  if(plannedShipDate != null){
            invoiceDueDate = plannedShipDate;
            System.Debug('##invoiceDueDate updating from Plan Ship date:'+invoiceDueDate);
        }*/
        if(String.isNotBlank(paymentTerms) && invoiceDueDate != NULL){
            // Get payment term custom settings and find the offset to add days
            Payment_Terms_Settings__c paymentTermSettings = Payment_Terms_Settings__c.getInstance(paymentTerms);
            System.Debug('##invoiceDueDate before adding days:'+invoiceDueDate);
            if(paymentTermSettings != null && paymentTermSettings.Offset__c != null){
                System.debug('##Offset:'+Integer.valueOf(paymentTermSettings.Offset__c));
                invoiceDueDate = invoiceDueDate.addDays(Integer.valueOf(paymentTermSettings.Offset__c));
            }
        }
        System.Debug('##invoiceDueDate:'+invoiceDueDate);
        return invoiceDueDate;
    }
    public static void calculateTaxOnCity(Invoice__c[] newList, Map<Id,Invoice__c> oldInvoiceMap){
        Set<Id> invoiceNewRLIds = new Set<Id>();
        Set<Id> invoiceRemovedRLIds = new Set<Id>();
        for(Invoice__c inv: newList){
            if(Trigger.isInsert || inv.Receiver_License__c != oldInvoiceMap.get(inv.Id).Receiver_License__c){
                invoiceNewRLIds.add(inv.Id);
            }
        }
        if(!invoiceNewRLIds.isEmpty()){
            Invoice_Line__c[] invoiceLines = new Invoice_Line__c[]{};
            Invoice__c[] invoices = [SELECT Id, Invoice_Date__c ,Delivery_City__c,(SELECT Id,Line_Total_Product_Price__c ,Subtotal_Local_Cannabis_Tax__c FROM Invoice_Lines__r) FROM Invoice__c WHERE Id =:invoiceNewRLIds];
            for(Invoice__c inv: invoices){
                System.debug('#####Delivery_City:'+inv.Delivery_City__c);
                if(cityTaxMap.containsKey(inv.Delivery_City__c)){
                    Tax_Table__c tt = cityTaxMap.get(inv.Delivery_City__c);
                    System.debug('###Tax_Table__c:::'+tt);
                    Decimal subTotal = 0;
                    decimal taxRateOnProd = tt.Actual_Tax_Rate_on_Product_Rev__c != null?tt.Actual_Tax_Rate_on_Product_Rev__c/100:0;
                    decimal taxableGrossReceiptsRate = tt.Taxable_Gross_Receipts_Rate__c != null?tt.Taxable_Gross_Receipts_Rate__c/100:0; 
                    decimal taxDueRate = tt.Tax_Due_Rate__c != null?tt.Tax_Due_Rate__c/100:0;
                    if(tt != null && tt.End_Date__c >= inv.Invoice_Date__c){
                        for(Invoice_Line__c invLine: inv.Invoice_Lines__r){
                            subTotal = invLine.Line_Total_Product_Price__c * taxableGrossReceiptsRate * taxDueRate;
                            if(taxRateOnProd > 0){
                                subTotal = subTotal * taxRateOnProd;
                            }
                            invLine.Subtotal_Local_Cannabis_Tax__c = subTotal;
                            invoiceLines.add(invLine);
                        }
                        
                    }else{
                        for(Invoice_Line__c invLine: inv.Invoice_Lines__r){
                            invLine.Subtotal_Local_Cannabis_Tax__c = 0;
                            invoiceLines.add(invLine);
                        }
                    }
                    
                }else{
                    for(Invoice_Line__c invLine: inv.Invoice_Lines__r){
                        invLine.Subtotal_Local_Cannabis_Tax__c = 0;
                        invoiceLines.add(invLine);
                    }
                }
            }
            if(!invoiceLines.isEmpty()){
                update invoiceLines;
            }
        }
    }
}