force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>IN-{0000000000}</displayFormat>
        <label>Invoice</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Invoice_Date__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Date__c</fullName>
    <defaultValue>Today()</defaultValue>
    <label>Invoice Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/IsLocked__c.field-meta.xml
<CustomField>
    <fullName>IsLocked__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsLocked</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Revenue_Recognition_Date__c.field-meta.xml
<CustomField>
    <fullName>Revenue_Recognition_Date__c</fullName>
    <inlineHelpText>Date in which revenue was recognized</inlineHelpText>
    <label>Revenue Recognition Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/BatchToLockInvoice.cls
global class BatchToLockInvoice implements Database.Batchable<sObject>, Database.Stateful, Schedulable{
    global Database.QueryLocator start(Database.BatchableContext bc) {
        /*Date datobj = system.today();
        Integer year = datobj.year();
        Integer month = datobj.month();//CALENDAR_MONTH(Invoice_Date__c) =: month AND CALENDAR_YEAR(Invoice_Date__c) =: year*/
        return Database.getQueryLocator([SELECT id,IsLocked__c,Revenue_Recognition_Date__c FROM Invoice__c WHERE Invoice_Date__c <=: system.today() AND Revenue_Recognition_Date__c != null AND IsLocked__c = false]);
    }
    global void execute(Database.BatchableContext bc, List<Invoice__c> records){
        if(records.size() > 0){
            for(Invoice__c inv : records){
                inv.IsLocked__c = true;
            }
            update records;
        }
    }
    global void finish(Database.BatchableContext bc){
        
        /*for(CronTrigger c:[SELECT NextFireTime, CronJobDetail.Name, Id, State, StartTime, EndTime, CronExpression, TimesTriggered FROM CronTrigger WHERE TimesTriggered >= 1]){
            System.abortJob(c.Id);
        }*/
    } 
    global void execute(SchedulableContext sc){
        Database.executeBatch(new BatchToLockInvoice());
    }
}