force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>IN-{0000000000}</displayFormat>
        <label>Invoice</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Collections_Status__c.field-meta.xml
<CustomField>
    <fullName>Collections_Status__c</fullName>
    <inlineHelpText>Auto updated based on payment received and due dates.</inlineHelpText>
    <label>Collections Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Past Due</fullName>
            </value>
            <value>
                <fullName>Partial Payment</fullName>
            </value>
            <value>
                <fullName>Paid in Full</fullName>
            </value>
            <value>
                <fullName>Not Collectable</fullName>
            </value>
            <value>
                <fullName>Brand Collections</fullName>
            </value>
            <value>
                <fullName>Charge-off</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Invoice_Aged__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Aged__c</fullName>
    <formula>IF(ISPICKVAL(Collections_Status__c,&apos;Past Due&apos;), today() - Invoice_Due_Date__c ,
IF(ISPICKVAL(Collections_Status__c,&apos;Paid in Full&apos;), Last_Payment_Date__c - Invoice_Due_Date__c ,
IF(ISPICKVAL(Collections_Status__c,&apos;Pending&apos;), today() - Invoice_Due_Date__c , Null)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>This fields displays how many days retailer payment is past due.</inlineHelpText>
    <label>Invoice Aged</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/InvoiceCollectionStatusUpdateBatch.cls
/**
 * Copyright (c) 2018 Filigreen Distro
 * All rights reserved.
 * InvoiceCollectionStatusUpdateBatch
 */
public class InvoiceCollectionStatusUpdateBatch implements Database.Batchable<sObject>{

    private static final String statusPastDue = InvoiceSupport.INVOICE_COLLECTION_STATUS_PAST_DUE;
    
    // Start method having scope of invoice object
    public Database.QueryLocator start(Database.BatchableContext BC){
        String statusPaidInFull = InvoiceSupport.INVOICE_COLLECTION_STATUS_PAID_IN_FULL;
        String statusPastDue = InvoiceSupport.INVOICE_COLLECTION_STATUS_PAST_DUE;
        String query= 'Select Collections_Status__c From Invoice__c '+
                      'Where Invoice_Aged__c > 0 ' + 
                      'AND Collections_Status__c NOT IN (:statusPaidInFull, :statusPastDue)';
        return Database.getQueryLocator(Query);
    }

    // execute method to update invoice status
    public void execute(Database.BatchableContext BC, List<sObject> scope){
        List<Invoice__c> scopeList = (List<Invoice__c>)scope;
        for(Invoice__c invoiceSO : scopeList){
            invoiceSO.Collections_Status__c = statusPastDue;
        }
        update scopeList;
    }

    // finish method - nothing to do as of now
    public void finish(Database.BatchableContext BC){}
}