force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>IN-{0000000000}</displayFormat>
        <label>Invoice</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/AR_Status__c.field-meta.xml
<CustomField>
    <fullName>AR_Status__c</fullName>
    <label>AR Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Shipped</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Collections_Status__c.field-meta.xml
<CustomField>
    <fullName>Collections_Status__c</fullName>
    <inlineHelpText>Auto updated based on payment received and due dates.</inlineHelpText>
    <label>Collections Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Past Due</fullName>
            </value>
            <value>
                <fullName>Partial Payment</fullName>
            </value>
            <value>
                <fullName>Paid in Full</fullName>
            </value>
            <value>
                <fullName>Not Collectable</fullName>
            </value>
            <value>
                <fullName>Brand Collections</fullName>
            </value>
            <value>
                <fullName>Charge-off</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Posted_Date__c.field-meta.xml
<CustomField>
    <fullName>Posted_Date__c</fullName>
    <label>Posted Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Ship_Confirmation_Date__c.field-meta.xml
<CustomField>
    <fullName>Ship_Confirmation_Date__c</fullName>
    <inlineHelpText>Date shipment was delivered to Retail. This is an field is updated by process builder and used in the Purchase Order Invoice Only to determine Supplier Payable Date</inlineHelpText>
    <label>Ship Confirmation Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/BatchToMigrateAttachmentToFilesTest.cls
@isTest
public class BatchToMigrateAttachmentToFilesTest {
    private static testmethod void runTest(){
        Invoice__c lstInvoice = new Invoice__c();
        lstInvoice.Ship_Confirmation_Date__c = Date.today();
        lstInvoice.Posted_Date__c = null;
        lstInvoice.AR_Status__c = 'Shipped';
        lstInvoice.Collections_Status__c = 'Pending';
        insert lstInvoice;
        
        Attachment attach=new Attachment();   	
    	attach.Name='Unit Test Attachment';
    	Blob bodyBlob=Blob.valueOf('Unit Test Attachment Body');
    	attach.body=bodyBlob;
        attach.parentId=lstInvoice.id;
        insert attach;
        
        BatchToMigrateAttachmentToFiles batch= new BatchToMigrateAttachmentToFiles();
		ID rec = Database.executeBatch(batch);
    }
}