force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>IN-{0000000000}</displayFormat>
        <label>Invoice</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Collections_Status__c.field-meta.xml
<CustomField>
    <fullName>Collections_Status__c</fullName>
    <inlineHelpText>Auto updated based on payment received and due dates.</inlineHelpText>
    <label>Collections Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Past Due</fullName>
            </value>
            <value>
                <fullName>Partial Payment</fullName>
            </value>
            <value>
                <fullName>Paid in Full</fullName>
            </value>
            <value>
                <fullName>Not Collectable</fullName>
            </value>
            <value>
                <fullName>Brand Collections</fullName>
            </value>
            <value>
                <fullName>Charge-off</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Invoice_Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Due_Date__c</fullName>
    <label>Invoice Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/InvoiceCollectionStatusUpdateBatchTest.cls
/**
 * Copyright (c) 2018 Filigreen Distro
 * All rights reserved.
 * InvoiceCollectionStatusUpdateBatchTest
 */
@isTest(OnInstall=false SeeAllData=false)
public class InvoiceCollectionStatusUpdateBatchTest{
    
    // Test method to update invoice status 
    public static testmethod void testUpdateInvoiceCollectionStatus(){
        
        TestUtilData.createTestData();
        
        String statusPaidInFull = InvoiceSupport.INVOICE_COLLECTION_STATUS_PAID_IN_FULL;
        String statusPastDue = InvoiceSupport.INVOICE_COLLECTION_STATUS_PAST_DUE;
        
        Invoice__c invoiceSO = [Select Invoice_Due_Date__c, Collections_Status__c From Invoice__c];
        invoiceSO.Invoice_Due_Date__c = System.Today () - 5;
        invoiceSO.Collections_Status__c = 'Pending';
        update invoiceSO;
        
        Invoice__c anotherInvoice = invoiceSO.clone(false, true);
        insert anotherInvoice;
        
        Test.StartTest();
        InvoiceCollectionStatusUpdateBatch batchJob = new InvoiceCollectionStatusUpdateBatch(); 
        database.executebatch(batchJob);
        Test.StopTest();
        
        List<Invoice__c> invoices = [Select Collections_Status__c From Invoice__c];
        System.assertEquals(2, invoices.size(), 'Invoice size mis-match');
        System.assertEquals(statusPastDue, invoices[0].Collections_Status__c, 'Invoice collection status mis-match');
        System.assertEquals(statusPastDue, invoices[1].Collections_Status__c, 'Invoice collection status mis-match');
    }
}