force-app/main/default/objects/Brand_Quote_Line__c/Brand_Quote_Line__c.object-meta.xml
<CustomObject>
    <label>Brand Quote Line</label>
    <nameField>
        <displayFormat>BQLI-{0000000000}</displayFormat>
        <label>BQ Line</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Brand Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Brand_Quote_Line__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Name</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Product2.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Brand Quote Lines</relationshipLabel>
    <relationshipName>Brand_Quote_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Driver__c/Driver__c.object-meta.xml
<CustomObject>
    <label>driver</label>
    <nameField>
        <label>Driver Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>drivers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Drivers__c/Drivers__c.object-meta.xml
<CustomObject>
    <label>Driver</label>
    <nameField>
        <label>Driver Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Drivers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Purchase_Order__c/Purchase_Order__c.object-meta.xml
<CustomObject>
    <label>Purchase Order</label>
    <nameField>
        <displayFormat>PO-{0000000000}</displayFormat>
        <label>Purchase Order</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Purchase_Order__c/fields/Driver__c.field-meta.xml
<CustomField>
    <fullName>Driver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Driver</label>
    <referenceTo>Drivers__c</referenceTo>
    <relationshipLabel>Purchase Orders</relationshipLabel>
    <relationshipName>Purchase_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/fields/Planned_Ship_Transfer_Date__c.field-meta.xml
<CustomField>
    <fullName>Planned_Ship_Transfer_Date__c</fullName>
    <label>Planned Ship/Transfer Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/fields/Ship_Confirmation_Date__c.field-meta.xml
<CustomField>
    <fullName>Ship_Confirmation_Date__c</fullName>
    <formula>Brand_Quote__r.Ship_Confirmation_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Ship Confirmation Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/fields/Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Vehicle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vehicle</label>
    <referenceTo>Vehicles__c</referenceTo>
    <relationshipLabel>Purchase Orders</relationshipLabel>
    <relationshipName>Purchase_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase_Order_Line__c/Purchase_Order_Line__c.object-meta.xml
<CustomObject>
    <label>Purchase Order Line</label>
    <nameField>
        <displayFormat>POLI-{0000000000}</displayFormat>
        <label>PO Line</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Purchase_Order_Line__c/fields/Brand_Quote_Line__c.field-meta.xml
<CustomField>
    <fullName>Brand_Quote_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Brand Quote Line</label>
    <referenceTo>Brand_Quote_Line__c</referenceTo>
    <relationshipLabel>Purchase Order Lines</relationshipLabel>
    <relationshipName>Purchase_Order_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase_Order_Line__c/fields/POLI_Status__c.field-meta.xml
<CustomField>
    <fullName>POLI_Status__c</fullName>
    <label>POLI Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Partially Received</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Purchase_Order_Line__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Name</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Purchase Order Lines</relationshipLabel>
    <relationshipName>Purchase_Order_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase_Order_Line__c/fields/Purchase_Order__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Order__c</fullName>
    <label>Purchase Order</label>
    <referenceTo>Purchase_Order__c</referenceTo>
    <relationshipLabel>Purchase Order Lines</relationshipLabel>
    <relationshipName>Purchase_Order_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Purchase_Order_Line__c/fields/Qty_Ordered__c.field-meta.xml
<CustomField>
    <fullName>Qty_Ordered__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Qty Ordered</inlineHelpText>
    <label>Qty Ordered</label>
    <precision>16</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Purchase_Order_Line__c/fields/Unit_Cost__c.field-meta.xml
<CustomField>
    <fullName>Unit_Cost__c</fullName>
    <inlineHelpText>Unit Cost</inlineHelpText>
    <label>Unit Cost</label>
    <precision>16</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Vehicles__c/Vehicles__c.object-meta.xml
<CustomObject>
    <label>Vehicle</label>
    <nameField>
        <label>Vehicle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/AssignDriverVehicleToPOCtlrTest.cls
@isTest
public class AssignDriverVehicleToPOCtlrTest {
    static Drivers__c driverObj;
    static Vehicles__c vehicleObj;
    static Purchase_Order__c purchaseOrderObj;
    static List<Purchase_Order_Line__c> poLines;
	@TestSetUp
    static void testDataSetUp(){
        Test.setMock(HttpCalloutMock.class, new StateLicense_MockResponseTest());
        TestUtilData.skipTrigger = true;
        TestUtilData.createTestData();
    }
    @isTest
    static void testAssignDriverVehicleToPO(){
        retrieveData();
        updateAndCreateData();
        ApexPages.StandardController stdController = new ApexPages.StandardController(purchaseOrderObj);
        AssignDriverVehicleToPOCtlr controllerObj = new AssignDriverVehicleToPOCtlr(stdController);
        Test.startTest();
        AssignDriverVehicleToPOCtlr.init(purchaseOrderObj.id);
        AssignDriverVehicleToPOCtlr.assignDriverVehicle(purchaseOrderObj);
        AssignDriverVehicleToPOCtlr.retrieveDriverVehicleAndRelated(purchaseOrderObj,vehicleObj.id,driverObj.id,''+System.today());
        controllerObj.cancelAction();
        controllerObj.redirectToRSM();
        Test.stopTest();
    }
    // Retrieve data created from data setup
    public static void retrieveData(){
        
        purchaseOrderObj = new Purchase_Order__c();
        purchaseOrderObj = [Select Id,Planned_Ship_Transfer_Date__c,
                         		Driver__c,Ship_Confirmation_Date__c,
                         		Vehicle__c
                                from Purchase_Order__c];
        poLines = new List<Purchase_Order_Line__c>();
        poLines = [Select Id, Purchase_Order__c,Product_Name__c, Qty_Ordered__c,Unit_Cost__c,Brand_Quote_Line__c from Purchase_Order_Line__c];
        
    }
    public static void updateAndCreateData(){
        purchaseOrderObj.Planned_Ship_Transfer_Date__c =system.today();
        update purchaseOrderObj;
        // Create Vehicle
        vehicleObj = TestUtilData.createVehicle(true);
        
        // Create Driver
        driverObj = TestUtilData.createDriver(true);
        purchaseOrderObj.Vehicle__c=vehicleObj.id;
        purchaseOrderObj.Driver__c=driverObj.Id;
        update purchaseOrderObj;
        poLines[0].POLI_Status__c='New';
        poLines[1].POLI_Status__c='New';
        poLines[2].POLI_Status__c='New';
        update poLines;
    }
}