force-app/main/default/objects/Brand_Quote_Line__c/Brand_Quote_Line__c.object-meta.xml
<CustomObject>
    <label>Brand Quote Line</label>
    <nameField>
        <displayFormat>BQLI-{0000000000}</displayFormat>
        <label>BQ Line</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Brand Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Brand_Quote_Line__c/fields/Opportunity_Name__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Name__c</fullName>
    <formula>Brand_Quote_Number__r.Opportunity_Name__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Opportunity Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Brand_Quote_Line__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <formula>Brand_Quote_Number__r.Opportunity_Name__r.Order__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Order #</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Brand_Quote_Line__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Name</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Product2.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Brand Quote Lines</relationshipLabel>
    <relationshipName>Brand_Quote_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Brand_Quote_Line__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Brand Quote line status</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>IN-{0000000000}</displayFormat>
        <label>Invoice</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Opportunity_Name__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Name</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Purchase_Order__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Purchase Order</label>
    <referenceTo>Purchase_Order__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/recordTypes/Product.recordType-meta.xml
<RecordType>
    <fullName>Product</fullName>
    <active>true</active>
    <description>Use for all Product and Services</description>
    <label>Product</label>
</RecordType>

force-app/main/default/objects/Invoice__c/recordTypes/Service.recordType-meta.xml
<RecordType>
    <fullName>Service</fullName>
    <active>true</active>
    <description>Used for Packaging and or Services</description>
    <label>Service</label>
</RecordType>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <displayFormat>O-{000000}</displayFormat>
        <label>Order #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Cancelled by Customer</fullName>
            </value>
            <value>
                <fullName>Cancelled by WOVN</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Payment</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Returned</fullName>
            </value>
            <value>
                <fullName>Shipped</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/Purchase_Order__c.object-meta.xml
<CustomObject>
    <label>Purchase Order</label>
    <nameField>
        <displayFormat>PO-{0000000000}</displayFormat>
        <label>Purchase Order</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Purchase_Order__c/fields/Goods_Receipt_Date__c.field-meta.xml
<CustomField>
    <fullName>Goods_Receipt_Date__c</fullName>
    <label>Goods Receipt Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/fields/Opportunity_Name__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Name</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Purchase Orders</relationshipLabel>
    <relationshipName>Purchase_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/fields/PO_Status__c.field-meta.xml
<CustomField>
    <fullName>PO_Status__c</fullName>
    <label>PO Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Partially Received</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/recordTypes/Product.recordType-meta.xml
<RecordType>
    <fullName>Product</fullName>
    <active>true</active>
    <description>Products Are For Buy Sell</description>
    <label>Product</label>
</RecordType>

force-app/main/default/objects/Purchase_Order_Line__c/Purchase_Order_Line__c.object-meta.xml
<CustomObject>
    <label>Purchase Order Line</label>
    <nameField>
        <displayFormat>POLI-{0000000000}</displayFormat>
        <label>PO Line</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Purchase_Order_Line__c/fields/Balance_Qty__c.field-meta.xml
<CustomField>
    <fullName>Balance_Qty__c</fullName>
    <formula>IF((TEXT(POLI_Status__c) &lt;&gt; &apos;Rejected&apos; &amp;&amp; TEXT(POLI_Status__c) &lt;&gt; &apos;Cancelled&apos; ) &amp;&amp; NOT(Product_Name__r.Auto_Receive__c),
Qty_Ordered__c - Total_Received_Qty__c , 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Balance Qty</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Purchase_Order_Line__c/fields/Cannabis_Category_1__c.field-meta.xml
<CustomField>
    <fullName>Cannabis_Category_1__c</fullName>
    <label>Cannabis Category 1</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Cannabis_Category</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Purchase_Order_Line__c/fields/Cannabis_Category_2__c.field-meta.xml
<CustomField>
    <fullName>Cannabis_Category_2__c</fullName>
    <label>Cannabis Category 2</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Cannabis_Category</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Purchase_Order_Line__c/fields/Cannabis_Ratio_1__c.field-meta.xml
<CustomField>
    <fullName>Cannabis_Ratio_1__c</fullName>
    <label>Cannabis Ratio 1</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Purchase_Order_Line__c/fields/Cannabis_Ratio_2__c.field-meta.xml
<CustomField>
    <fullName>Cannabis_Ratio_2__c</fullName>
    <label>Cannabis Ratio 2</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Purchase_Order_Line__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <formula>Purchase_Order__r.Brand_Quote__r.Opportunity_Name__r.Order__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Order #</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Purchase_Order_Line__c/fields/POLI_Status__c.field-meta.xml
<CustomField>
    <fullName>POLI_Status__c</fullName>
    <label>POLI Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Partially Received</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Purchase_Order_Line__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Name</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Purchase Order Lines</relationshipLabel>
    <relationshipName>Purchase_Order_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase_Order_Line__c/fields/Purchase_Order__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Order__c</fullName>
    <label>Purchase Order</label>
    <referenceTo>Purchase_Order__c</referenceTo>
    <relationshipLabel>Purchase Order Lines</relationshipLabel>
    <relationshipName>Purchase_Order_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Purchase_Order_Line__c/fields/Qty_Ordered__c.field-meta.xml
<CustomField>
    <fullName>Qty_Ordered__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Qty Ordered</inlineHelpText>
    <label>Qty Ordered</label>
    <precision>16</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Purchase_Order_Line__c/fields/Total_Received_Qty__c.field-meta.xml
<CustomField>
    <fullName>Total_Received_Qty__c</fullName>
    <label>Total Received Qty</label>
    <summarizedField>Receiving_Line__c.Total_Received_Qty__c</summarizedField>
    <summaryForeignKey>Receiving_Line__c.Purchase_Order_Line__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Purchase_Order_Line__c/fields/Unit_Cannabis_Weight_1__c.field-meta.xml
<CustomField>
    <fullName>Unit_Cannabis_Weight_1__c</fullName>
    <label>Unit Cannabis Weight 1</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Purchase_Order_Line__c/fields/Unit_Cannabis_Weight_2__c.field-meta.xml
<CustomField>
    <fullName>Unit_Cannabis_Weight_2__c</fullName>
    <label>Unit Cannabis Weight 2</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Purchase_Order_Line__c/fields/Unit_Cultivation_Tax_1__c.field-meta.xml
<CustomField>
    <fullName>Unit_Cultivation_Tax_1__c</fullName>
    <label>Unit Cultivation Tax 1</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Purchase_Order_Line__c/fields/Unit_Cultivation_Tax_2__c.field-meta.xml
<CustomField>
    <fullName>Unit_Cultivation_Tax_2__c</fullName>
    <label>Unit Cultivation Tax 2</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Purchase_Order_Line__c/recordTypes/Product.recordType-meta.xml
<RecordType>
    <fullName>Product</fullName>
    <active>true</active>
    <description>Product Purchases</description>
    <label>Product</label>
</RecordType>

force-app/main/default/objects/Service_Ticket__c/Service_Ticket__c.object-meta.xml
<CustomObject>
    <description>Service ticket object in Community</description>
    <label>Service Ticket</label>
    <nameField>
        <displayFormat>ST-{YYYY}-{MM}-{00000}</displayFormat>
        <label>Service Ticket #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Tickets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Ticket__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>New</fullName>
                <isActive>false</isActive>
                <label>New</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PurchaseOrderLineHelper.cls
public class PurchaseOrderLineHelper {
    public Static String PURCHASE_ORDER_STATUS_CLOSED{
        get{
            return String.isNotBlank(PURCHASE_ORDER_STATUS_CLOSED) ? PURCHASE_ORDER_STATUS_CLOSED: FiligreenConfigurationUtility.getConfigValueByObjectAndKey('Purchase Order','Purchase_Order_Status_Closed');
        }set;
    }
    public Static String PURCHASE_ORDER_LINE_STATUS_CLOSED{
        get{
            return String.isNotBlank(PURCHASE_ORDER_LINE_STATUS_CLOSED) ? PURCHASE_ORDER_LINE_STATUS_CLOSED: FiligreenConfigurationUtility.getConfigValueByObjectAndKey('Purchase Order Line','POLI_Status_Closed');
        }set;
    }
    public Static String PURCHASE_ORDER_LINE_STATUS_CANCELLED{
        get{
            return String.isNotBlank(PURCHASE_ORDER_LINE_STATUS_CANCELLED) ? PURCHASE_ORDER_LINE_STATUS_CANCELLED: FiligreenConfigurationUtility.getConfigValueByObjectAndKey('Purchase Order Line','POLI_Status_Cancelled');
        }set;
    }
    public Static String POL_Record_Type_DevName_Product{
        get{
            return String.isNotBlank(POL_Record_Type_DevName_Product) ? POL_Record_Type_DevName_Product: FiligreenConfigurationUtility.getConfigValueByObjectAndKey('Purchase Order Line','POL_Record_Type_DevName_Product');
        }set;
    }
    public Static String POLI_Status_Partially_Received{
        get{
            return String.isNotBlank(POLI_Status_Partially_Received) ? POLI_Status_Partially_Received: FiligreenConfigurationUtility.getConfigValueByObjectAndKey('Purchase Order Line','POLI_Status_Partially_Received');
        }set;
    }
    public Static String ST_Transfer_Method_Product_Conversions{
        get{
            return String.isNotBlank(ST_Transfer_Method_Product_Conversions) ? ST_Transfer_Method_Product_Conversions: FiligreenConfigurationUtility.getConfigValueByObjectAndKey('Service_Ticket__c','ST_Transfer_Method_Product_Conversions');
        }set;
    }
    Public Static String INVOICE_AR_STATUS_CANCELLED{
        get{
            return String.isNotBlank(INVOICE_AR_STATUS_CANCELLED) ? INVOICE_AR_STATUS_CANCELLED: FiligreenConfigurationUtility.getConfigValueByObjectAndKey('Invoice','Invoice_Ar_Status_Cancelled');
        }set;
    }
    Public Static String INVOICE_AR_STATUS_REJECTED{
        get{
            return String.isNotBlank(INVOICE_AR_STATUS_REJECTED) ? INVOICE_AR_STATUS_REJECTED: FiligreenConfigurationUtility.getConfigValueByObjectAndKey('Invoice','Invoice_Ar_Status_Rejected');
        }set;
    }
    
    public static void onbeforeInsert(List<Purchase_Order_Line__c> newPOs){
        Set<Id> parentIds = new Set<Id>();
        for (Purchase_Order_Line__c newRecord : newPOs){
            if(newRecord.Product_Name__c != null) parentIds.add(newRecord.Product_Name__c);
        }
        if(parentIds.size() > 0){
            Map<Id, Product2> parents = new Map<Id, Product2>([ SELECT Id,Name,Cannabis_Category_1__c,Unit_Cannabis_Weight_1__c,Unit_Cultivation_Tax_1__c,
                                                           Cannabis_Ratio_1__c,Cannabis_Category_2__c,Unit_Cannabis_Weight_2__c,Unit_Cultivation_Tax_2__c,
                                                           Cannabis_Ratio_2__c FROM Product2 WHERE Id IN :parentIds]);
            for (Purchase_Order_Line__c newRecord : newPOs){
                if(parents.containskey(newRecord.Product_Name__c)){
                    Product2 product = parents.get(newRecord.Product_Name__c);
                    if(product.Unit_Cultivation_Tax_1__c != null && product.Cannabis_Category_1__c != null && product.Unit_Cannabis_Weight_1__c != null && product.Cannabis_Ratio_1__c != null){
                    	newRecord.Cannabis_Ratio_1__c = product.Cannabis_Ratio_1__c;
                        newRecord.Cannabis_Category_1__c = product.Cannabis_Category_1__c; 
                        newRecord.Unit_Cannabis_Weight_1__c = product.Unit_Cannabis_Weight_1__c;
                        newRecord.Unit_Cultivation_Tax_1__c = product.Unit_Cultivation_Tax_1__c;
                    }
                    if(product.Unit_Cultivation_Tax_2__c != null && product.Cannabis_Category_2__c != null && product.Unit_Cannabis_Weight_2__c != null && product.Cannabis_Ratio_2__c != null){
                    	newRecord.Cannabis_Ratio_2__c = product.Cannabis_Ratio_2__c;
                        newRecord.Cannabis_Category_2__c = product.Cannabis_Category_2__c; 
                        newRecord.Unit_Cannabis_Weight_2__c = product.Unit_Cannabis_Weight_2__c;
                        newRecord.Unit_Cultivation_Tax_2__c = product.Unit_Cultivation_Tax_2__c;
                    }
                }
            }
        }
    }
    
    public static void onBeforeUpdate(List<Purchase_Order_Line__c> newPOs, Map<Id,Purchase_Order_Line__c> oldMap){
        for(Purchase_Order_Line__c POLI: newPOs){
            System.debug('##Balance_Qty__c:'+POLI.Balance_Qty__c);
            String recDevloperName = Schema.getGlobalDescribe().get('Purchase_Order_Line__c').getDescribe().getRecordTypeInfosById().get(POLI.RecordTypeId).getDeveloperName();
            if(((POLI.POLI_Status__c  != PURCHASE_ORDER_LINE_STATUS_CLOSED && POLI.POLI_Status__c  != PURCHASE_ORDER_LINE_STATUS_CANCELLED) && recDevloperName == POL_Record_Type_DevName_Product) && (Trigger.isInsert || (Trigger.isUpdate && POLI.Balance_Qty__c  != oldMap.get(POLI.Id).Balance_Qty__c))){
                if(POLI.Balance_Qty__c != 0 && POLI.Total_Received_Qty__c > 0){
                    POLI.POLI_Status__c = POLI_Status_Partially_Received;
                }
                if(POLI.Balance_Qty__c == 0){
                    
                    POLI.POLI_Status__c = PURCHASE_ORDER_LINE_STATUS_CLOSED;
                    system.debug('###PURCHASE_ORDER_LINE_STATUS_CLOSED  :'+POLI.POLI_Status__c);
                }
            }
        }
    }
    public static void onAfterUpdate(List<Purchase_Order_Line__c> newPOs, Map<Id,Purchase_Order_Line__c> oldMap){
        System.debug('###onAfterUpdate...');
        Set<Id> POIds = new Set<Id>();
        Set<Id> closedPOIds = new Set<Id>();
        for(Purchase_Order_Line__c POLI: newPOs){
            if(Trigger.isInsert ||(Trigger.isUpdate && (POLI.POLI_Status__c  != oldMap.get(POLI.Id).POLI_Status__c  || 
                                                        POLI.Qty_Ordered__c != oldMap.get(POLI.Id).Qty_Ordered__c || 
                                                        POLI.Total_Received_Qty__c != oldMap.get(POLI.Id).Total_Received_Qty__c))){
                POIds.add(POLI.Purchase_Order__c);
            }
            if(Trigger.isUpdate && POLI.POLI_Status__c == PURCHASE_ORDER_STATUS_CLOSED && POLI.POLI_Status__c  != oldMap.get(POLI.Id).POLI_Status__c){
                closedPOIds.add(POLI.Purchase_Order__c);
            }
        }
        System.debug('##POIds:'+POIds);
        Map<Id,Service_Ticket__c> serviceTicketsMap = new Map<Id,Service_Ticket__c>();
        if(POIds.size() > 0){
            List<Purchase_Order__c> POList = [SELECT Id,Goods_Receipt_Date__c, Opportunity_Name__c ,PO_Status__c, (SELECT Id,Balance_Qty__c FROM Purchase_Order_Lines__r WHERE Balance_Qty__c > 0) FROM Purchase_Order__c WHERE Id IN :POIds];
            Set<Id> opportunityIds = new Set<Id>();
            if(POList.size() >0){
                for(Purchase_Order__c PO: POList){
                    if(PO.Purchase_Order_Lines__r.size() == 0){
                        if(PO.Goods_Receipt_Date__c == null){
                            PO.Goods_Receipt_Date__c = System.now();
                        }
                        opportunityIds.add(PO.Opportunity_Name__c);
                    }else{
                        PO.Goods_Receipt_Date__c = NULL;
                    }
                }
                update POList;
                if(opportunityIds.size() > 0){
                    List<Service_Ticket__c> serviceTickets = [SELECT Id,Opportunity__c,Status__c,Transfer_Method__c FROM Service_Ticket__c WHERE Opportunity__c IN :opportunityIds ];
                    for(Service_Ticket__c ST: serviceTickets){
                        serviceTicketsMap.put(ST.Opportunity__c,ST);
                        ST.Status__c = 'Completed';
                    }
                    update serviceTickets;
                }
            }
        }
        //Create Service Invoice Records
        if(closedPOIds.size() > 0){
            Set<String> POToCreateServiceInvoice = new Set<String>();
            List<Purchase_Order__c> POList = [SELECT Id,Goods_Receipt_Date__c,Opportunity_Name__c,Opportunity_Name__r.Order__c, Payment_Eligible__c ,PO_Status__c, (SELECT Id,Balance_Qty__c FROM Purchase_Order_Lines__r WHERE Balance_Qty__c > 0),(SELECT Id FROM Invoices__r WHERE AR_Status__c NOT IN (:INVOICE_AR_STATUS_CANCELLED,:INVOICE_AR_STATUS_REJECTED)) FROM Purchase_Order__c WHERE Id IN :closedPOIds];
            List<Purchase_Order__c> POListUpdate = new List<Purchase_Order__c>();
            if(POList.size() >0){
                for(Purchase_Order__c PO: POList){
                    if(PO.Purchase_Order_Lines__r.size() == 0){
                        if((serviceTicketsMap.containsKey(PO.Opportunity_Name__c) && serviceTicketsMap.get(PO.Opportunity_Name__c).Transfer_Method__c != ST_Transfer_Method_Product_Conversions) && PO.Payment_Eligible__c != true && PO.Invoices__r.Size() == 0){
                            POToCreateServiceInvoice.add(PO.Id);
                        }
                        if(PO.Opportunity_Name__r.Order__c != NULL && PO.Payment_Eligible__c != true && PO.Invoices__r.Size() == 0){
                            POToCreateServiceInvoice.add(PO.Id);
                        }
                        if(PO.Payment_Eligible__c != true){ 
                            POListUpdate.add(new Purchase_Order__c(Id = PO.Id, PO_Status__c = PURCHASE_ORDER_STATUS_CLOSED));
                        }
                    }
                }
                if(POListUpdate.size() > 0){
                    update POListUpdate;
                }
                if(POToCreateServiceInvoice.size() > 0){
                    Company_Custom_Settings__c Company_Settings= Company_Custom_Settings__c.getOrgDefaults();
                    if(Company_Settings.Auto_Create_Service_Invoice__c){
                    	PurchaseOrderHelper.createServiceInvoice(POToCreateServiceInvoice);    	
                    } 
                }
            }
        }
    }
    public static void onBeforeDelete(List<Purchase_Order_Line__c> oldPOs){
        List<Brand_Quote_Line__c> bqLines = new List<Brand_Quote_Line__c>();
        List<Purchase_Order_Line__c> polis = [SELECT 
                                              Brand_Quote_Line__c,Qty_Ordered__c,
                                              Brand_Quote_Line__r.Invoiced_Quantity__c
                                              FROM Purchase_Order_Line__c
                                              WHERE Id IN : oldPOs];
        
        for(Purchase_Order_Line__c poli : polis){
            if(poli.Brand_Quote_Line__c != null && poli.Brand_Quote_Line__r.Invoiced_Quantity__c != null && poli.Qty_Ordered__c != null){
                Decimal qty = poli.Brand_Quote_Line__r.Invoiced_Quantity__c - poli.Qty_Ordered__c;
                bqLines.add(new Brand_Quote_Line__c(Id=poli.Brand_Quote_Line__c,Invoiced_Quantity__c = qty));     
            }  
        }
        if(bqLines.size() > 0){
            update bqLines;
        }
    }
}