force-app/main/default/objects/Drivers__c/Drivers__c.object-meta.xml
<CustomObject>
    <label>Driver</label>
    <nameField>
        <label>Driver Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Drivers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <displayFormat>O-{000000}</displayFormat>
        <label>Order #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Account_DBA__c.field-meta.xml
<CustomField>
    <fullName>Account_DBA__c</fullName>
    <formula>Account__r.DBA__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account DBA</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Payment_Terms__c.field-meta.xml
<CustomField>
    <fullName>Payment_Terms__c</fullName>
    <label>Payment Terms</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Payment_Terms</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Cancelled by Customer</fullName>
            </value>
            <value>
                <fullName>Cancelled by WOVN</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Payment</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Returned</fullName>
            </value>
            <value>
                <fullName>Shipped</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/Total__c.field-meta.xml
<CustomField>
    <fullName>Total__c</fullName>
    <label>Total Price</label>
    <summarizedField>Order_Line_Item__c.Total__c</summarizedField>
    <summaryForeignKey>Order_Line_Item__c.Order__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Total_Line_Items__c.field-meta.xml
<CustomField>
    <fullName>Total_Line_Items__c</fullName>
    <label>Total Line Items</label>
    <summaryForeignKey>Order_Line_Item__c.Order__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Shipping_Manifest__c/Shipping_Manifest__c.object-meta.xml
<CustomObject>
    <description>Used in the generation of compliance document to enable retail delivery.</description>
    <label>Shipping Manifest</label>
    <nameField>
        <displayFormat>SM-{YYYY}-{MM}-{0000000000}</displayFormat>
        <label>Shipping Manifest</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipping Manifests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Shipping_Manifest__c/fields/Actual_Receiver_Name__c.field-meta.xml
<CustomField>
    <fullName>Actual_Receiver_Name__c</fullName>
    <label>Actual Receiver Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Shipping_Manifest__c/fields/Delivery_City__c.field-meta.xml
<CustomField>
    <fullName>Delivery_City__c</fullName>
    <formula>TEXT(Receiver_License__r.License_City__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Delivery City</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Shipping_Manifest__c/fields/Driver__c.field-meta.xml
<CustomField>
    <fullName>Driver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Driver</label>
    <referenceTo>Drivers__c</referenceTo>
    <relationshipLabel>Shipping Manifests</relationshipLabel>
    <relationshipName>Shipping_Manifests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipping_Manifest__c/fields/Metrc_Manifest__c.field-meta.xml
<CustomField>
    <fullName>Metrc_Manifest__c</fullName>
    <label>Metrc Manifest#</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Shipping_Manifest__c/fields/Order_Number__c.field-meta.xml
<CustomField>
    <fullName>Order_Number__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Order placed from Community portal</description>
    <inlineHelpText>Order placed from Community portal</inlineHelpText>
    <label>Order Number</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipName>Retail_Shipping_Manifests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipping_Manifest__c/fields/Ownership__c.field-meta.xml
<CustomField>
    <fullName>Ownership__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ownership</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Shipping Manifests as Ownership</relationshipLabel>
    <relationshipName>Shipping_Manifests3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipping_Manifest__c/fields/Payment_Terms__c.field-meta.xml
<CustomField>
    <fullName>Payment_Terms__c</fullName>
    <label>Payment Terms</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Payment_Terms</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Shipping_Manifest__c/fields/Receiver_Contact__c.field-meta.xml
<CustomField>
    <fullName>Receiver_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Receiver Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Shipping Manifests (Receiver Contact)</relationshipLabel>
    <relationshipName>Shipping_Manifests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipping_Manifest__c/fields/Slack_Notes__c.field-meta.xml
<CustomField>
    <fullName>Slack_Notes__c</fullName>
    <description>Used in Ship confirm console and posting msg to Slack Driver channel. DO NOT modify/enable in layout.</description>
    <label>Slack Notes</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Shipping_Manifest__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
            <value>
                <fullName>Shipment Pending</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Pending Delivery</fullName>
            </value>
            <value>
                <fullName>Shipment Complete</fullName>
            </value>
            <value>
                <fullName>In-Transit</fullName>
            </value>
            <value>
                <fullName>Received</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
                <isActive>false</isActive>
                <label>Submitted</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Shipping_Manifest__c/fields/Total_Line_Items__c.field-meta.xml
<CustomField>
    <fullName>Total_Line_Items__c</fullName>
    <label>Total Line Items</label>
    <summaryFilterItems>
        <field>Shipping_Manifest_Line__c.SMLine_Status__c</field>
        <operation>notEqual</operation>
        <value>Cancelled, Rejected</value>
    </summaryFilterItems>
    <summaryForeignKey>Shipping_Manifest_Line__c.Shipping_Manifest__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Shipping_Manifest__c/fields/Total_Price__c.field-meta.xml
<CustomField>
    <fullName>Total_Price__c</fullName>
    <label>Total Price</label>
    <summarizedField>Shipping_Manifest_Line__c.Line_Total_Price__c</summarizedField>
    <summaryFilterItems>
        <field>Shipping_Manifest_Line__c.SMLine_Status__c</field>
        <operation>notEqual</operation>
        <value>Cancelled, Rejected</value>
    </summaryFilterItems>
    <summaryForeignKey>Shipping_Manifest_Line__c.Shipping_Manifest__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Shipping_Manifest_Line__c/Shipping_Manifest_Line__c.object-meta.xml
<CustomObject>
    <label>Shipping Manifest Line</label>
    <nameField>
        <displayFormat>SML-{0000000000}</displayFormat>
        <label>SM Line</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipping Manifest Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Shipping_Manifest_Line__c/fields/Qty_Received__c.field-meta.xml
<CustomField>
    <fullName>Qty_Received__c</fullName>
    <label>Qty Received</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Shipping_Manifest_Line__c/fields/Shipment_Qty__c.field-meta.xml
<CustomField>
    <fullName>Shipment_Qty__c</fullName>
    <label>Shipment Qty</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Shipping_Manifest_Line__c/fields/Shipping_Manifest__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Manifest__c</fullName>
    <label>Shipping Manifest</label>
    <referenceTo>Shipping_Manifest__c</referenceTo>
    <relationshipLabel>Shipping Manifest Lines</relationshipLabel>
    <relationshipName>Shipping_Manifest_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Shipping_Manifest_Line__c/fields/SMLine_Status__c.field-meta.xml
<CustomField>
    <fullName>SMLine_Status__c</fullName>
    <label>SMLine Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Shipment Complete</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PublishShippingManifestToSlack.cls
public class PublishShippingManifestToSlack {
    
    public Static String CRM_Redirect_URL{
        get{
            return String.isNotBlank(CRM_Redirect_URL) ? CRM_Redirect_URL : FiligreenConfigurationUtility.getConfigValueByObjectAndKey('Order','CRM_Redirect_URL');
        }set;
    }       
    public Static String Shipping_Manifest_LineStatus_Rejected{
        get{
            return String.isNotBlank(Shipping_Manifest_LineStatus_Rejected) ? Shipping_Manifest_LineStatus_Rejected: FiligreenConfigurationUtility.getConfigValueByObjectAndKey('Shipping Manifest Line','Shipping_Manifest_LineStatus_Rejected');
        }set;
    }
    
    public Static String SHIPPING_MANIFEST_LINE_RECORDTYPE_PRODUCT_TSM_LINE {
        get{
            return String.isNotBlank(SHIPPING_MANIFEST_LINE_RECORDTYPE_PRODUCT_TSM_LINE) ? SHIPPING_MANIFEST_LINE_RECORDTYPE_PRODUCT_TSM_LINE: FiligreenConfigurationUtility.getConfigValueByObjectAndKey('Shipping Manifest Line','SM_Line_RecordType_Product_TSM_Line');
        }set;
    } 
    // sending slack message After ShipmentComplete or Reject 

    @InvocableMethod 
    public static void publishToSlack(List<Id> smIds) {
        system.debug('smIds >>>>' + smIds);
        String ShipManifestlackMsg = '';
        String SMLstatus = 'No';
        for(Shipping_Manifest__c SM : [select Id, Name, Status__c,Slack_Notes__c, Receiver_Contact__r.Name, Receiver_DBA__c, Delivery_City__c,Supplier_DBA__c, 
                                       Order_Number__r.Account_DBA__c,RecordType.Name, Total_Line_Items__c,Ownership__c,Ownership__r.Name,Ownership__r.DBA__c, 
                                       Total_Price__c, Order_Number__r.Total__c,  Metrc_Manifest__c, Payment_Terms__c, Actual_Receiver_Name__c, Driver__r.Name,
									   (select id, name, SMLine_Status__c, Shipment_Qty__c, Qty_Received__c,RecordType.Name from Shipping_Manifest_Lines__r) from Shipping_Manifest__c  where id IN: smIds]){
                                           
        	for(Shipping_Manifest_Line__c sml: SM.Shipping_Manifest_Lines__r){
            	If(sml.SMLine_Status__c == Shipping_Manifest_LineStatus_Rejected || sml.Shipment_Qty__c != sml.Qty_Received__c){ 
                    SMLstatus = 'Yes';
             		}
           	 }
                                           
			if(SM.Id != null){
                If(SM.Ownership__r.Name != null)ShipManifestlackMsg += 'Ownership DBA : ' + SM.Ownership__r.DBA__c + '\n';
                else ShipManifestlackMsg += 'Ownership DBA  : ' + '\n';
                If(SM.Driver__r.Name != null)ShipManifestlackMsg += 'Driver : ' + SM.Driver__r.Name+ '\n';
                else ShipManifestlackMsg += '\n';
                If(SM.Receiver_DBA__c != null)ShipManifestlackMsg += 'Receiver DBA : ' + SM.Receiver_DBA__c + '\n';
                else ShipManifestlackMsg += 'Receiver DBA : ' + '\n';
                ShipManifestlackMsg += 'Delivery City : ' + SM.Delivery_City__c + '\n';
                ShipManifestlackMsg += 'Payment Terms : ' + SM.Payment_Terms__c + '\n';
                If(SM.Total_Line_Items__c != null)ShipManifestlackMsg += 'Total Lines : ' + SM.Total_Line_Items__c + '\n';
                else ShipManifestlackMsg += 'Total Lines : ' + '\n';
                If(SM.Status__c != null) ShipManifestlackMsg += 'Status : ' + SM.Status__c + '\n';
                else ShipManifestlackMsg += 'Status : ' + '\n';
                ShipManifestlackMsg += 'Partial Rejection : ' + SMLstatus + '\n';
                If(SM.Metrc_Manifest__c != null) ShipManifestlackMsg += 'Metrc Manifest : ' + SM.Metrc_Manifest__c + '\n';
                else ShipManifestlackMsg += 'Metrc Manifest : ' + '\n';
                ShipManifestlackMsg += 'Shipping Manifest : <' + CRM_Redirect_URL + '/lightning/r/Shipping_Manifest__c/' + SM.Id + '/view|' + SM.Name  + '>';
                ShipManifestlackMsg += ' - ' + SM.RecordType.Name + '\n';
                If(SM.Slack_Notes__c != null) ShipManifestlackMsg += 'Slack Notes : ' + SM.Slack_Notes__c  + ' \n';
                else ShipManifestlackMsg += 'Slack Notes : ' + '\n';
            }
        }  
        if(ShipManifestlackMsg != ''){
            	ShipManifestlackMsg = ShipManifestlackMsg.removeEnd('\n');
            	SlackIntegrationController.postMessage('Shipping Manifest', ShipManifestlackMsg);
        }
    }

}