force-app/main/default/objects/Site__c/Site__c.object-meta.xml
<CustomObject>
    <description>All objects must have a Site Name and License Class or A or M. For separate sales and inventory record.</description>
    <label>Site</label>
    <nameField>
        <label>Site</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Site__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active ?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Strain__c/Strain__c.object-meta.xml
<CustomObject>
    <label>Strain</label>
    <nameField>
        <label>Strain</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Strains</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Strain__c/fields/CbdLevel__c.field-meta.xml
<CustomField>
    <fullName>CbdLevel__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Cbd Level</label>
    <precision>8</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Strain__c/fields/IndicaPercentage__c.field-meta.xml
<CustomField>
    <fullName>IndicaPercentage__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Indica Percentage</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Strain__c/fields/SativaPercentage__c.field-meta.xml
<CustomField>
    <fullName>SativaPercentage__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Sativa Percentage</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Strain__c/fields/ThcLevel__c.field-meta.xml
<CustomField>
    <fullName>ThcLevel__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Thc Level</label>
    <precision>8</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TTGS_Strain__c/TTGS_Strain__c.object-meta.xml
<CustomObject>
    <label>TTGS Strain</label>
    <nameField>
        <displayFormat>TTGSS-{MMYY}-{000000}</displayFormat>
        <label>TTGS Strain</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TTGS Strains</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TTGS_Strain__c/fields/CBD_Level__c.field-meta.xml
<CustomField>
    <fullName>CBD_Level__c</fullName>
    <label>CBD Level</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TTGS_Strain__c/fields/Indica_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Indica_Percentage__c</fullName>
    <label>Indica Percentage</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TTGS_Strain__c/fields/Sativa_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Sativa_Percentage__c</fullName>
    <label>Sativa Percentage</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TTGS_Strain__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site</label>
    <referenceTo>Site__c</referenceTo>
    <relationshipLabel>TTGS Strains</relationshipLabel>
    <relationshipName>TTGS_Strains</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TTGS_Strain__c/fields/Strain__c.field-meta.xml
<CustomField>
    <fullName>Strain__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Strain</label>
    <referenceTo>Strain__c</referenceTo>
    <relationshipLabel>TTGS Strains</relationshipLabel>
    <relationshipName>TTGS_Strains</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TTGS_Strain__c/fields/THC_Level__c.field-meta.xml
<CustomField>
    <fullName>THC_Level__c</fullName>
    <label>THC Level</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/TTGS_DuplicateSIte_Validation_Helper.cls
public class TTGS_DuplicateSIte_Validation_Helper {
    

    public static void beforeUpdate(List<TTGS_Strain__c> lstTTGSStrain,Map<Id,TTGS_Strain__c> oldMap){
            
      
        
        set<id>duplicatesites = new set<id>(); 
        set<id>strainids = new set<id>(); 
        set<id>sites = new set<id>();
        
        
        
        for(TTGS_Strain__c TTGSObj :lstTTGSStrain )  { if(TTGSObj.Active__c != oldMap.get(TTGSObj.Id).Active__c){
            if(TTGSObj.Active__c == true)
            {
                strainids.add(TTGSObj.Strain__c);    
                sites.add(TTGSObj.Site__c);   
            }
              }
        }
        
        
        List<TTGS_Strain__c> ttgslist =[select id,name,Active__c,Site__c from TTGS_Strain__c where Strain__c =:strainids];   
        
        for(TTGS_Strain__c TTGSObj :ttgslist )  {
            if(sites.contains(TTGSObj.Site__c) && TTGSObj.Active__c == true )  { duplicatesites.add(TTGSObj.Site__c); 
            }
        }
        system.debug('duplicatesites>>'+duplicatesites);
                system.debug('duplicatesites>>'+duplicatesites.size());

        for(TTGS_Strain__c TTGSObj :lstTTGSStrain)
        {
            if(duplicatesites.size()>0){  TTGSObj.adderror('Please deactivate existing active Strains and try creating/updating active Strain.');  
            }
        }
        
    }
    public static void beforeInsert(List<TTGS_Strain__c> lstTTGSStrain){
            
      
        
        set<id>duplicatesites = new set<id>(); 
        set<id>strainids = new set<id>(); 
        set<id>sites = new set<id>();
        
        
        
        for(TTGS_Strain__c TTGSObj :lstTTGSStrain )  {
            
                
            
            if(TTGSObj.Active__c == true)
            {
                strainids.add(TTGSObj.Strain__c);    
                sites.add(TTGSObj.Site__c);   
            }
             
        }
        
        
        List<TTGS_Strain__c> ttgslist =[select id,name,Active__c,Site__c from TTGS_Strain__c where Strain__c =:strainids];   
        
        for(TTGS_Strain__c TTGSObj :ttgslist )  { if(sites.contains(TTGSObj.Site__c) && TTGSObj.Active__c == true )
            {
                duplicatesites.add(TTGSObj.Site__c); 
            }
        }
        system.debug('duplicatesites>>'+duplicatesites);
                system.debug('duplicatesites>>'+duplicatesites.size());

        for(TTGS_Strain__c TTGSObj :lstTTGSStrain)
        {
            if(duplicatesites.size()>0){   TTGSObj.adderror('Please deactivate existing active Strains and try creating/updating active Strain.');  
            }
        }
        
    } 
    
     public static void GetVlaueFromParentInsert(List<TTGS_Strain__c> lstTTGSStrain){
       List<TTGS_Strain__c> ttgslist = new  List<TTGS_Strain__c> ();
       set<id>strainid = new set<id>(); 
       for(TTGS_Strain__c TTGSObj :lstTTGSStrain )  {
           
           strainid.add(TTGSObj.Strain__c);    
           
       }
       
       Strain__c strainobj =[select id,SativaPercentage__c,IndicaPercentage__c,CbdLevel__c,ThcLevel__c,name from Strain__c where Id =:strainid];   
       for(TTGS_Strain__c TTGSObj :lstTTGSStrain )  {
           if(TTGSObj.Sativa_Percentage__c == null){
               TTGS_Strain__c ttgs = new TTGS_Strain__c();  
               ttgs.Id = TTGSObj.Id;
               ttgs.Sativa_Percentage__c = strainobj.SativaPercentage__c;
               ttgs.Indica_Percentage__c = strainobj.IndicaPercentage__c;
               ttgs.CBD_Level__c = strainobj.CbdLevel__c;
               ttgs.THC_Level__c = strainobj.ThcLevel__c;
               
               ttgslist.add(ttgs);   
               
           } 
       }
       system.debug('t+tgslist'+ttgslist);
       upsert  ttgslist;
       
       
       
       
   }
    
}