force-app/main/default/objects/Site__c/Site__c.object-meta.xml
<CustomObject>
    <description>All objects must have a Site Name and License Class or A or M. For separate sales and inventory record.</description>
    <label>Site</label>
    <nameField>
        <label>Site</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Site__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active ?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Site__c/fields/Warehouse_Name__c.field-meta.xml
<CustomField>
    <fullName>Warehouse_Name__c</fullName>
    <description>Name of the warehouse to display in UI. Example : Communities.</description>
    <label>Warehouse Name</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UID__c/UID__c.object-meta.xml
<CustomObject>
    <description>Unique Identifiers, RFID Tags from Track &amp; Trace</description>
    <label>UID</label>
    <nameField>
        <label>UID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>UIDs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UID__c/fields/IRR_UID__c.field-meta.xml
<CustomField>
    <fullName>IRR_UID__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Checkbox for Irrational Raccoon Source UID</inlineHelpText>
    <label>IRR UID</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/UID__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site</label>
    <referenceTo>Site__c</referenceTo>
    <relationshipLabel>UIDs</relationshipLabel>
    <relationshipName>UIDs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/MetrcTagUploadCtlrTest.cls
@isTest
public class MetrcTagUploadCtlrTest {
private static testmethod void runTest(){
    
    UID__c uid = new UID__c(); 
    uid.Active__c=true;
    uid.Name='1A4060300005F51000018211';
    uid.IRR_UID__c=true;
    insert uid;
    UID__c uid2 = new UID__c(); 
    uid2.Active__c=true;
    uid2.Name='1A4060300005F51000019963';
    uid2.IRR_UID__c=true;
    insert uid2;
     site__c siteId = new site__c();
        siteId.Name = '2089-3';
        siteId.Warehouse_Name__c = 'San Francisco, CA';
        insert siteId;
       MetrcTagUploadCtlr.getActiveSite('2089');
    String paymentsData = '[{"Tag":"'+uid.Name+'","Active":"'+uid.Active__c+'","IRR UID":"'+uid.IRR_UID__c+'"}]';
    MetrcTagUploadCtlr.gettags(paymentsData); 
    MetrcTagUploadCtlr.Savetags(paymentsData,'2089');
    String paymentsData2 = '[{"Tag":"'+uid2.Name+'","Active":"'+uid2.Active__c+'","IRR UID":"'+uid2.IRR_UID__c+'"}]';
    MetrcTagUploadCtlr.gettags(paymentsData2);
    MetrcTagUploadCtlr.Savetags(paymentsData2,'NHWCA');
 
    string message=MetrcTagUploadCtlr.ERR_MSG_UID_CHARCTER;
}
}