force-app/main/default/objects/Fulfillment_Rates_Table__c/Fulfillment_Rates_Table__c.object-meta.xml
<CustomObject>
    <description>Fulfilment Rate table used in Service fee calculation (CRM + MP)</description>
    <label>Fulfillment Rates Table</label>
    <nameField>
        <displayFormat>FRT-{YYYY}-{0000}</displayFormat>
        <label>Fulfillment Rates Table</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fulfillment Rates Tables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Fulfillment_Rates_Table__c/fields/Fulfillment_Services__c.field-meta.xml
<CustomField>
    <fullName>Fulfillment_Services__c</fullName>
    <label>Fulfillment Services</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Fulfillment_Services</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Fulfillment_Rates_Table__c/fields/List_Price__c.field-meta.xml
<CustomField>
    <fullName>List_Price__c</fullName>
    <label>List Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Fulfillment_Rates_Table__c/fields/Membership_Level__c.field-meta.xml
<CustomField>
    <fullName>Membership_Level__c</fullName>
    <label>Membership Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Membership_Level</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Fulfillment_Rates_Table__c/fields/MOQ__c.field-meta.xml
<CustomField>
    <fullName>MOQ__c</fullName>
    <label>Units per Case (MOQ)</label>
    <precision>12</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Fulfillment_Rates_Table__c/fields/Rate_Effective_From__c.field-meta.xml
<CustomField>
    <fullName>Rate_Effective_From__c</fullName>
    <label>Rate Effective From</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Fulfillment_Rates_Table__c/fields/Rate_Effective_To__c.field-meta.xml
<CustomField>
    <fullName>Rate_Effective_To__c</fullName>
    <label>Rate Effective To</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Fulfillment_Rates_Table__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site</label>
    <referenceTo>Site__c</referenceTo>
    <relationshipLabel>Fulfillment Rates Tables</relationshipLabel>
    <relationshipName>Fulfillment_Rates_Tables</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Fulfillment_Rates_Table__c/fields/Weight_lbs__c.field-meta.xml
<CustomField>
    <fullName>Weight_lbs__c</fullName>
    <label>Weight (lbs)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <displayFormat>O-{000000}</displayFormat>
        <label>Order #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Brand Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Default_Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Default_Warehouse__c</fullName>
    <formula>State_License__r.Default_Warehouse__r.Warehouse_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Default Warehouse</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Order_Date__c.field-meta.xml
<CustomField>
    <fullName>Order_Date__c</fullName>
    <label>Order Date</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site</label>
    <referenceTo>Site__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/State_License__c.field-meta.xml
<CustomField>
    <fullName>State_License__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>State License</label>
    <referenceTo>State_Licenses__c</referenceTo>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Cancelled by Customer</fullName>
            </value>
            <value>
                <fullName>Cancelled by WOVN</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Payment</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Returned</fullName>
            </value>
            <value>
                <fullName>Shipped</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/recordTypes/Retailer.recordType-meta.xml
<RecordType>
    <fullName>Retailer</fullName>
    <active>true</active>
    <description>Used when origin of order is from Retailer</description>
    <label>Retailer</label>
</RecordType>

force-app/main/default/objects/Shipping_Rates_Table__c/Shipping_Rates_Table__c.object-meta.xml
<CustomObject>
    <description>Shipping Rate table used in Service fee calculation (CRM + MP)</description>
    <label>Shipping Rates Table</label>
    <nameField>
        <displayFormat>SRT-{YYYY}-{000}</displayFormat>
        <label>Shipping Rates Table</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipping Rates Tables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Shipping_Rates_Table__c/fields/Membership_Level__c.field-meta.xml
<CustomField>
    <fullName>Membership_Level__c</fullName>
    <label>Membership Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Membership_Level</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Shipping_Rates_Table__c/fields/Rate_Effective_From__c.field-meta.xml
<CustomField>
    <fullName>Rate_Effective_From__c</fullName>
    <label>Rate Effective From</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Shipping_Rates_Table__c/fields/Rate_Effective_To__c.field-meta.xml
<CustomField>
    <fullName>Rate_Effective_To__c</fullName>
    <label>Rate Effective To</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Shipping_Rates_Table__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site</label>
    <referenceTo>Site__c</referenceTo>
    <relationshipName>Shipping_Rates_Tables</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Site__c/Site__c.object-meta.xml
<CustomObject>
    <description>All objects must have a Site Name and License Class or A or M. For separate sales and inventory record.</description>
    <label>Site</label>
    <nameField>
        <label>Site</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Site__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active ?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/State_Licenses__c/State_Licenses__c.object-meta.xml
<CustomObject>
    <description>Object within the Account to track number of license and address as part of ship to.</description>
    <label>State License</label>
    <nameField>
        <displayFormat>SLID-{YYYY}-{MM}-{0000000000}</displayFormat>
        <label>License</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>State Licenses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/State_Licenses__c/fields/Default_Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Default_Warehouse__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Default Warehouse</label>
    <referenceTo>Site__c</referenceTo>
    <relationshipLabel>State Licenses</relationshipLabel>
    <relationshipName>State_Licenses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/OpportunityLineItemsHandlerTest.cls
@isTest
public class OpportunityLineItemsHandlerTest { 
    @isTest
    public static void testOLIUpdate(){
        TestUtilData.skipTrigger = true;
        TestUtilData.createTestData();
        TestUtilData.skipTrigger = false;
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new StateLicense_MockResponseTest()); 
        OpportunityLineItem oli = [SELECT Id,Quantity,MOQ__c,OpportunityId,Product2Id FROM OpportunityLineItem LIMIT 1];
        Opportunity opp = [SELECT Id, Order__c FROM Opportunity WHERE Id =: oli.OpportunityId];
        State_Licenses__c sl = [SELECT Id,Default_Warehouse__c FROM State_Licenses__c LIMIT 1];
        
        Account acc = [SELECT Id,Membership_Level__c FROM Account LIMIT 1];
        acc.Membership_Level__c = 'Boutique';
        update acc;
        
        Order__c ord= new Order__c();
        ord.Status__c='Approved';
        ord.Order_Date__c=Date.today();
        ord.State_License__c = sl.Id;
        ord.Account__c = acc.Id;
        ord.RecordTypeId = Schema.SObjectType.Order__c.getRecordTypeInfosByName().get('Retailer').getRecordTypeId();
        insert ord;
        //Order__c order = [SELECT Id FROM Order__c LIMIT 1];
        opp.Order__c = ord.Id;
        update opp;
        
        Fulfillment_Rates_Table__c fullfillRateTable = new Fulfillment_Rates_Table__c();
        fullfillRateTable.Active__c = true;
        fullfillRateTable.Rate_Effective_From__c = Date.Today().addMonths(-3);
        fullfillRateTable.Site__c = sl.Default_Warehouse__c;
        fullfillRateTable.Rate_Effective_To__c = Date.Today().addMonths(3);
        fullfillRateTable.Weight_lbs__c = 10;
        fullfillRateTable.Fulfillment_Services__c = 'Pick & Pack';
        fullfillRateTable.List_Price__c = 10;
        fullfillRateTable.Membership_Level__c = 'Boutique';
        insert fullfillRateTable;
        
        Shipping_Rates_Table__c ShippingRateTable = new Shipping_Rates_Table__c();
        ShippingRateTable.Rate_Effective_From__c = Date.Today().addMonths(-3);
        ShippingRateTable.Site__c = sl.Default_Warehouse__c;
        ShippingRateTable.Rate_Effective_To__c = Date.Today().addMonths(3);
        ShippingRateTable.Membership_Level__c = 'Boutique';
        insert ShippingRateTable;
        
        Fulfillment_Rates_Table__c fullfillRateTable2 = fullfillRateTable.clone();
        fullfillRateTable2.Fulfillment_Services__c = 'Schedule & Dispatch';
        insert fullfillRateTable2;
        
        Fulfillment_Rates_Table__c fullfillRateTable3 = fullfillRateTable.clone();
        fullfillRateTable3.Fulfillment_Services__c = 'Stage & Manifest';
        insert fullfillRateTable3;
        
        Fulfillment_Rates_Table__c fullfillRateTable4 = fullfillRateTable.clone();
        fullfillRateTable4.Fulfillment_Services__c = 'Order Booking';
        insert fullfillRateTable4;
        
        Fulfillment_Rates_Table__c fullfillRateTable5 = fullfillRateTable.clone();
        fullfillRateTable5.Fulfillment_Services__c = 'QA Review';
        insert fullfillRateTable5;
        
        Fulfillment_Rates_Table__c fullfillRateTable6 = fullfillRateTable.clone();
        fullfillRateTable6.Fulfillment_Services__c = 'Pack-Out';
        insert fullfillRateTable6;
        
        oli.Quantity = 2;
        oli.Ownership_Code__c=acc.Id;
        update oli;
        
        List<OpportunityLineItem> lstOli = new List<OpportunityLineItem>();
        lstOli.add(oli);
        
        OpportunityLineItemsHandler.mapOwnershipCode(lstOli);
        
        Test.stopTest();
    }
}