force-app/main/default/objects/Fulfillment_Rates_Table__c/Fulfillment_Rates_Table__c.object-meta.xml
<CustomObject>
    <description>Fulfilment Rate table used in Service fee calculation (CRM + MP)</description>
    <label>Fulfillment Rates Table</label>
    <nameField>
        <displayFormat>FRT-{YYYY}-{0000}</displayFormat>
        <label>Fulfillment Rates Table</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fulfillment Rates Tables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Fulfillment_Rates_Table__c/fields/Bracket_Price__c.field-meta.xml
<CustomField>
    <fullName>Bracket_Price__c</fullName>
    <formula>Bracket_Cost__c + (Bracket_Cost__c * Bracket_Mark_Up__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Bracket Price</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Fulfillment_Rates_Table__c/fields/Fulfillment_Services__c.field-meta.xml
<CustomField>
    <fullName>Fulfillment_Services__c</fullName>
    <label>Fulfillment Services</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Fulfillment_Services</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Fulfillment_Rates_Table__c/fields/Membership_Level__c.field-meta.xml
<CustomField>
    <fullName>Membership_Level__c</fullName>
    <label>Membership Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Membership_Level</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Fulfillment_Rates_Table__c/fields/MOQ__c.field-meta.xml
<CustomField>
    <fullName>MOQ__c</fullName>
    <label>Units per Case (MOQ)</label>
    <precision>12</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Fulfillment_Rates_Table__c/fields/Rate_Effective_From__c.field-meta.xml
<CustomField>
    <fullName>Rate_Effective_From__c</fullName>
    <label>Rate Effective From</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Fulfillment_Rates_Table__c/fields/Rate_Effective_To__c.field-meta.xml
<CustomField>
    <fullName>Rate_Effective_To__c</fullName>
    <label>Rate Effective To</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Fulfillment_Rates_Table__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site</label>
    <referenceTo>Site__c</referenceTo>
    <relationshipLabel>Fulfillment Rates Tables</relationshipLabel>
    <relationshipName>Fulfillment_Rates_Tables</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Fulfillment_Rates_Table__c/fields/Weight_lbs__c.field-meta.xml
<CustomField>
    <fullName>Weight_lbs__c</fullName>
    <label>Weight (lbs)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Service_Ticket__c/Service_Ticket__c.object-meta.xml
<CustomObject>
    <description>Service ticket object in Community</description>
    <label>Service Ticket</label>
    <nameField>
        <displayFormat>ST-{YYYY}-{MM}-{00000}</displayFormat>
        <label>Service Ticket #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Tickets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Ticket__c/fields/Brand_Name__c.field-meta.xml
<CustomField>
    <fullName>Brand_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Brand Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Service Tickets</relationshipLabel>
    <relationshipName>Service_Tickets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_Ticket__c/fields/Destination_Site__c.field-meta.xml
<CustomField>
    <fullName>Destination_Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Destination Site</label>
    <referenceTo>Site__c</referenceTo>
    <relationshipLabel>Service Tickets</relationshipLabel>
    <relationshipName>Service_Tickets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_Ticket__c/fields/Licensed_Premise__c.field-meta.xml
<CustomField>
    <fullName>Licensed_Premise__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Licensed Premise</label>
    <referenceTo>State_Licenses__c</referenceTo>
    <relationshipLabel>Service Tickets</relationshipLabel>
    <relationshipName>Service_Tickets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_Ticket__c/fields/Total_Weight_lbs__c.field-meta.xml
<CustomField>
    <fullName>Total_Weight_lbs__c</fullName>
    <label>Total Weight (lbs)</label>
    <summarizedField>Service_Ticket_Line__c.Total_Weight_lbs__c</summarizedField>
    <summaryFilterItems>
        <field>Service_Ticket_Line__c.Status__c</field>
        <operation>notEqual</operation>
        <value>Cancelled</value>
    </summaryFilterItems>
    <summaryForeignKey>Service_Ticket_Line__c.Service_Ticket__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Service_Ticket_Line__c/Service_Ticket_Line__c.object-meta.xml
<CustomObject>
    <description>Service ticket object in Community</description>
    <label>Service Ticket Line</label>
    <nameField>
        <displayFormat>STL-{0000000}</displayFormat>
        <label>Service Ticket Line #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Ticket Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Ticket_Line__c/fields/New_Packaged_Product__c.field-meta.xml
<CustomField>
    <fullName>New_Packaged_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Select the new product name, which product will become.</inlineHelpText>
    <label>New Packaged Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Service Ticket Lines (New Packaged Product)</relationshipLabel>
    <relationshipName>Service_Ticket_Lines1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_Ticket_Line__c/fields/Service_Ticket__c.field-meta.xml
<CustomField>
    <fullName>Service_Ticket__c</fullName>
    <label>Service Ticket</label>
    <referenceTo>Service_Ticket__c</referenceTo>
    <relationshipLabel>Service Ticket Lines</relationshipLabel>
    <relationshipName>Service_Ticket_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Service_Ticket_Line__c/fields/Total_Units__c.field-meta.xml
<CustomField>
    <fullName>Total_Units__c</fullName>
    <inlineHelpText>Please enter the total qty of units to transfer</inlineHelpText>
    <label>Total Units</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Shipping_Rates_Table__c/Shipping_Rates_Table__c.object-meta.xml
<CustomObject>
    <description>Shipping Rate table used in Service fee calculation (CRM + MP)</description>
    <label>Shipping Rates Table</label>
    <nameField>
        <displayFormat>SRT-{YYYY}-{000}</displayFormat>
        <label>Shipping Rates Table</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipping Rates Tables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Shipping_Rates_Table__c/fields/Fixed_Mileage_Amount__c.field-meta.xml
<CustomField>
    <fullName>Fixed_Mileage_Amount__c</fullName>
    <description>Fixed Mileage amount to apply based based on Fixed mileage fee flag.</description>
    <label>Fixed Mileage Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Shipping_Rates_Table__c/fields/Fixed_Mileage_Fee__c.field-meta.xml
<CustomField>
    <fullName>Fixed_Mileage_Fee__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Fixed Mileage fee flag to apply fixed mileage amount Vs Mileage bracket amount</description>
    <label>Fixed Mileage Fee</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Shipping_Rates_Table__c/fields/Fixed_Weight_Amount__c.field-meta.xml
<CustomField>
    <fullName>Fixed_Weight_Amount__c</fullName>
    <description>Fixed Weight amount to apply based based on Fixed weight fee flag.</description>
    <label>Fixed Weight Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Shipping_Rates_Table__c/fields/Fixed_Weight_Fee__c.field-meta.xml
<CustomField>
    <fullName>Fixed_Weight_Fee__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Fixed Weight fee flag to apply fixed weight amount Vs weight bracket amount</description>
    <label>Fixed Weight Fee</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Shipping_Rates_Table__c/fields/Membership_Level__c.field-meta.xml
<CustomField>
    <fullName>Membership_Level__c</fullName>
    <label>Membership Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Membership_Level</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Shipping_Rates_Table__c/fields/Mileage_Bracket__c.field-meta.xml
<CustomField>
    <fullName>Mileage_Bracket__c</fullName>
    <inlineHelpText>Mileage Bracket used to Calculate Shipment Cost and Pricing</inlineHelpText>
    <label>Mileage Bracket</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Shipping_Rates_Table__c/fields/Mileage_Bracket_Price__c.field-meta.xml
<CustomField>
    <fullName>Mileage_Bracket_Price__c</fullName>
    <formula>( Mileage_Bracket_Cost__c *  Mileage_Bracket_Mark_Up__c ) + Mileage_Bracket_Cost__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Mileage Bracket Price</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Shipping_Rates_Table__c/fields/Rate_Effective_From__c.field-meta.xml
<CustomField>
    <fullName>Rate_Effective_From__c</fullName>
    <label>Rate Effective From</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Shipping_Rates_Table__c/fields/Rate_Effective_To__c.field-meta.xml
<CustomField>
    <fullName>Rate_Effective_To__c</fullName>
    <label>Rate Effective To</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Shipping_Rates_Table__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site</label>
    <referenceTo>Site__c</referenceTo>
    <relationshipName>Shipping_Rates_Tables</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipping_Rates_Table__c/fields/Weight_Bracket__c.field-meta.xml
<CustomField>
    <fullName>Weight_Bracket__c</fullName>
    <inlineHelpText>Dimensional (DIM) or Gross Weight Bracket used to Calculate Cost and Price</inlineHelpText>
    <label>Weight Bracket</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Shipping_Rates_Table__c/fields/Weight_Bracket_Price__c.field-meta.xml
<CustomField>
    <fullName>Weight_Bracket_Price__c</fullName>
    <formula>(Weight_Bracket_Cost__c *  Weight_Bracket_Mark_Up__c ) + Weight_Bracket_Cost__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Weight Bracket Price</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Site__c/Site__c.object-meta.xml
<CustomObject>
    <description>All objects must have a Site Name and License Class or A or M. For separate sales and inventory record.</description>
    <label>Site</label>
    <nameField>
        <label>Site</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Site__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active ?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/State_Licenses__c/State_Licenses__c.object-meta.xml
<CustomObject>
    <description>Object within the Account to track number of license and address as part of ship to.</description>
    <label>State License</label>
    <nameField>
        <displayFormat>SLID-{YYYY}-{MM}-{0000000000}</displayFormat>
        <label>License</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>State Licenses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/State_Licenses__c/fields/Default_Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Default_Warehouse__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Default Warehouse</label>
    <referenceTo>Site__c</referenceTo>
    <relationshipLabel>State Licenses</relationshipLabel>
    <relationshipName>State_Licenses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/State_Licenses__c/fields/Total_Miles__c.field-meta.xml
<CustomField>
    <fullName>Total_Miles__c</fullName>
    <defaultValue>0.00</defaultValue>
    <description>Total driving distance between default warehouse and licensee address</description>
    <inlineHelpText>Total driving distance between default warehouse and licensee address</inlineHelpText>
    <label>Total Miles</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/UpdateFeeQueueable.cls
public class UpdateFeeQueueable implements Database.Batchable<sObject>, Database.Stateful, Database.AllowsCallouts, Schedulable {
    public Set<Id> serviceTicketIds{set;get;}
    public UpdateFeeQueueable(Set<Id> serviceTicketIds){
        this.serviceTicketIds = serviceTicketIds;
    }
    public Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator([SELECT Id,Destination_Site__c,Brand_Name__c,Brand_Name__r.Membership_Level__c,Licensed_Premise__c,Licensed_Premise__r.Default_Warehouse__c,
				(SELECT Id,Total_Units__c,New_Packaged_Product__c,New_Packaged_Product__r.Unit_Shipping_Weight_lbs__c,New_Packaged_Product__r.MOQ__c,New_Packaged_Product__r.Case_Shipping_Weight_lbs__c FROM Service_Ticket_Lines__r) From Service_Ticket__c WHERE  Id In : serviceTicketIds]);   
    }
    public void execute(SchedulableContext sc) {
        Database.executeBatch(new UpdateFeeQueueable(serviceTicketIds));
    }
	public void execute(Database.BatchableContext bc, List<Service_Ticket__c> records){
        /*list<Service_Ticket__c> stList = [SELECT Id,Destination_Site__c,Brand_Name__c,Brand_Name__r.Membership_Level__c,Licensed_Premise__c,Licensed_Premise__r.Default_Warehouse__c,
				(SELECT Id,Total_Units__c,New_Packaged_Product__c,New_Packaged_Product__r.Unit_Shipping_Weight_lbs__c,New_Packaged_Product__r.MOQ__c,New_Packaged_Product__r.Case_Shipping_Weight_lbs__c FROM Service_Ticket_Lines__r) From Service_Ticket__c WHERE  Id In : serviceTicketIds];*/
        list<Service_Ticket_Line__c>stlList = new List<Service_Ticket_Line__c>();
        for(Service_Ticket__c st : records){
            system.debug('st.Licensed_Premise__c '+st.Licensed_Premise__c);
        	String siteId = st.Destination_Site__c != null ? st.Destination_Site__c : st.Licensed_Premise__c != null ? st.Licensed_Premise__r.Default_Warehouse__c : null;
            if(siteId != null){
                String membershipLevel = st.Brand_Name__c != null ? st.Brand_Name__r.Membership_Level__c : '';
                Decimal serviceBookingFee = 0;
                Decimal serviceSchedulingFee = 0;
                Decimal serviceStagingFee = 0;
                Decimal totalWeightFee = 0;
                Decimal totalMileageFee = 0;
                Decimal totalOrderWeight = 0;
                Decimal totalMiles = ServiceTicketTriggerHandler.getTotalMiles(siteId,st.Licensed_Premise__c);
            
                State_Licenses__c stateLicense= [SELECT Id, Default_Warehouse__c,Total_Miles__c FROM State_Licenses__c where Id =: st.Licensed_Premise__c];            
        
                for(Service_Ticket_Line__c stl: st.Service_Ticket_Lines__r){
                    Decimal totalWeight = 0;
                    if(stl.New_Packaged_Product__c != null){
                        Decimal shippingWeight = 0;
                        if(stl.New_Packaged_Product__r.MOQ__c == 1){
                        	shippingWeight = stl.New_Packaged_Product__r.Unit_Shipping_Weight_lbs__c;    
                        }else if(stl.New_Packaged_Product__r.MOQ__c > 1){
                        	shippingWeight = stl.New_Packaged_Product__r.Case_Shipping_Weight_lbs__c;        
                        }
                        totalWeight = ( stl.Total_Units__c / stl.New_Packaged_Product__r.MOQ__c ) * shippingWeight;
                    }                    
                    stl.Total_Weight_lbs__c = totalWeight;
                    totalOrderWeight += totalWeight;
                    stlList.add(stl);
                }
        
                Fulfillment_Rates_Table__c [] FRTList = [SELECT Id, Active__c, Fulfillment_Services__c,Bracket_Price__c ,Rate_Effective_From__c ,Rate_Effective_To__c, Site__c,MOQ__c ,Weight_lbs__c,Membership_Level__c
                                                     FROM Fulfillment_Rates_Table__c 
                                                     WHERE Site__c = :siteId
                                                     AND Active__c = true
                                                     AND Rate_Effective_From__c <= :System.today()
                                                     AND Rate_Effective_To__c >= :System.today()
                                                     AND Membership_Level__c = :membershipLevel
                                                     ORDER BY Weight_lbs__c DESC, MOQ__c DESC];
                Shipping_Rates_Table__c [] weightSRTList = [SELECT Id, Active__c, Mileage_Bracket__c, Mileage_Bracket_Price__c,Rate_Effective_From__c,Rate_Effective_To__c, Membership_Level__c,
                                                    Weight_Bracket__c, Weight_Bracket_Price__c,Fixed_Mileage_Amount__c , Fixed_Mileage_Fee__c , Fixed_Weight_Amount__c ,Fixed_Weight_Fee__c 
                                                    FROM Shipping_Rates_Table__c 
                                                    WHERE Site__c = :siteId
                                                    AND Active__c = true
                                                    AND Rate_Effective_From__c <= :System.today()
                                                    AND Rate_Effective_To__c >= :System.today()
                                                    AND Membership_Level__c = :membershipLevel
                                                    Order By Weight_Bracket__c];
        		Shipping_Rates_Table__c [] mileageSRTList = [SELECT Id, Active__c, Mileage_Bracket__c, Mileage_Bracket_Price__c,Rate_Effective_From__c,Rate_Effective_To__c, Membership_Level__c,
                                                     Weight_Bracket__c, Weight_Bracket_Price__c,Fixed_Mileage_Amount__c , Fixed_Mileage_Fee__c , Fixed_Weight_Amount__c ,Fixed_Weight_Fee__c 
                                                     FROM Shipping_Rates_Table__c 
                                                     WHERE Site__c = :siteId
                                                     AND Active__c = true
                                                     AND Rate_Effective_From__c <= :System.today()
                                                     AND Rate_Effective_To__c >= :System.today()
                                                     AND Membership_Level__c = :membershipLevel
                                                     Order By Mileage_Bracket__c];
        
                Map<String,Fulfillment_Rates_Table__c []> serviceBasedFRTMap = new Map<String,Fulfillment_Rates_Table__c []>();
                if(!FRTList.isEmpty()){
                    for(Fulfillment_Rates_Table__c FRT:FRTList){
                        if(serviceBasedFRTMap.containsKey(FRT.Fulfillment_Services__c)){
                            serviceBasedFRTMap.get(FRT.Fulfillment_Services__c).add(FRT);
                        }else{
                            serviceBasedFRTMap.put(FRT.Fulfillment_Services__c,new Fulfillment_Rates_Table__c[]{FRT});
                        }
                    }
                }
        
                if(serviceBasedFRTMap.containsKey(ServiceTicketTriggerHandler.FULFILLMENT_SERVICE_BOOKING)){
                    Fulfillment_Rates_Table__c [] FRTs = serviceBasedFRTMap.get(ServiceTicketTriggerHandler.FULFILLMENT_SERVICE_BOOKING);
                    system.debug('FRTs '+FRTs);
                    if(!FRTs.isEmpty()){
                        System.debug('###FRT for Order Booking:'+FRTs[0]);
                        serviceBookingFee = FRTs[0].Bracket_Price__c;
                    }
                }
                if(serviceBasedFRTMap.containsKey(ServiceTicketTriggerHandler.FULFILLMENT_SERVICE_SCHEDULING)){
                    Fulfillment_Rates_Table__c [] FRTs = serviceBasedFRTMap.get(ServiceTicketTriggerHandler.FULFILLMENT_SERVICE_SCHEDULING);
                    system.debug('FRTs '+FRTs);
                    if(!FRTs.isEmpty()){
                        System.debug('###FRT for Order Booking:'+FRTs[0]);
                        serviceSchedulingFee = FRTs[0].Bracket_Price__c;
                    }
                }
                if(serviceBasedFRTMap.containsKey(ServiceTicketTriggerHandler.FULFILLMENT_SERVICE_STAGING)){
                    Fulfillment_Rates_Table__c [] FRTs = serviceBasedFRTMap.get(ServiceTicketTriggerHandler.FULFILLMENT_SERVICE_STAGING);
                    system.debug('FRTs '+FRTs);
                    if(!FRTs.isEmpty()){
                        System.debug('###FRT for Order Booking:'+FRTs[0]);
                        serviceStagingFee = FRTs[0].Bracket_Price__c;
                    }
                }
            
                if(!weightSRTList.isEmpty()){
                    for(Shipping_Rates_Table__c SRT: weightSRTList){
                        if(totalOrderWeight <= SRT.Weight_Bracket__c){
                            System.debug('###SRT for Weight:'+SRT);
                            if(SRT.Fixed_Weight_Fee__c){
                                totalWeightFee = SRT.Fixed_Weight_Amount__c != null ? SRT.Fixed_Weight_Amount__c : 0;
                            }else{
                                totalWeightFee = SRT.Weight_Bracket_Price__c * totalOrderWeight; 
                            }
                            break;
                        }
                    }   
                }
        
                if(!mileageSRTList.isEmpty() && stateLicense.Total_Miles__c != null){
                    for(Shipping_Rates_Table__c SRT: mileageSRTList){
                        if(totalMiles <= SRT.Mileage_Bracket__c){
                            System.debug('###SRT for Mileage Fee:'+SRT);
                            if(SRT.Fixed_Mileage_Fee__c){
                                totalMileageFee = SRT.Fixed_Mileage_Amount__c != null ? SRT.Fixed_Mileage_Amount__c:0;
                            }else{
                                totalMileageFee = SRT.Mileage_Bracket_Price__c * totalMiles; 
                            }
                            
                            break;
                        }
                    }    
                }
        
                st.Total_Mileage_Fee__c = totalMileageFee;
                st.Total_Weight_Fee__c = totalWeightFee;            
                st.Service_Booking_Fee__c = serviceBookingFee;
                st.Service_Scheduling_Fee__c = serviceSchedulingFee;
                st.Service_Staging_Fee__c  = serviceStagingFee;
            }
		}
        ServiceTicketTriggerHandler.feesCalulated =true;
        update records;
        update stlList; 
        
    }
    public void finish(Database.BatchableContext BC){
        // Get the ID of the AsyncApexJob representing this batch job from Database.BatchableContext.
        // Query the AsyncApexJob object to retrieve the current job's information.
        AsyncApexJob a = [SELECT Id FROM AsyncApexJob WHERE Id =  :BC.getJobId()];
        
        //then use the active job id and abort it
        system.abortJob(a.id);
    }
}