force-app/main/default/objects/Fulfillment_Rates_Table__c/Fulfillment_Rates_Table__c.object-meta.xml
<CustomObject>
    <description>Fulfilment Rate table used in Service fee calculation (CRM + MP)</description>
    <label>Fulfillment Rates Table</label>
    <nameField>
        <displayFormat>FRT-{YYYY}-{0000}</displayFormat>
        <label>Fulfillment Rates Table</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fulfillment Rates Tables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Fulfillment_Rates_Table__c/fields/Bracket_Price__c.field-meta.xml
<CustomField>
    <fullName>Bracket_Price__c</fullName>
    <formula>Bracket_Cost__c + (Bracket_Cost__c * Bracket_Mark_Up__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Bracket Price</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Fulfillment_Rates_Table__c/fields/Fulfillment_Services__c.field-meta.xml
<CustomField>
    <fullName>Fulfillment_Services__c</fullName>
    <label>Fulfillment Services</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Fulfillment_Services</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Fulfillment_Rates_Table__c/fields/Membership_Level__c.field-meta.xml
<CustomField>
    <fullName>Membership_Level__c</fullName>
    <label>Membership Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Membership_Level</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Fulfillment_Rates_Table__c/fields/MOQ__c.field-meta.xml
<CustomField>
    <fullName>MOQ__c</fullName>
    <label>Units per Case (MOQ)</label>
    <precision>12</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Fulfillment_Rates_Table__c/fields/Rate_Effective_From__c.field-meta.xml
<CustomField>
    <fullName>Rate_Effective_From__c</fullName>
    <label>Rate Effective From</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Fulfillment_Rates_Table__c/fields/Rate_Effective_To__c.field-meta.xml
<CustomField>
    <fullName>Rate_Effective_To__c</fullName>
    <label>Rate Effective To</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Fulfillment_Rates_Table__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site</label>
    <referenceTo>Site__c</referenceTo>
    <relationshipLabel>Fulfillment Rates Tables</relationshipLabel>
    <relationshipName>Fulfillment_Rates_Tables</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Fulfillment_Rates_Table__c/fields/Size_Classification__c.field-meta.xml
<CustomField>
    <fullName>Size_Classification__c</fullName>
    <label>Size Classification</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Fulfillment_Services__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Size_Classification</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Fulfillment_Rates_Table__c/fields/Weight_lbs__c.field-meta.xml
<CustomField>
    <fullName>Weight_lbs__c</fullName>
    <label>Weight (lbs)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Shipping_Rates_Table__c/Shipping_Rates_Table__c.object-meta.xml
<CustomObject>
    <description>Shipping Rate table used in Service fee calculation (CRM + MP)</description>
    <label>Shipping Rates Table</label>
    <nameField>
        <displayFormat>SRT-{YYYY}-{000}</displayFormat>
        <label>Shipping Rates Table</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipping Rates Tables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Shipping_Rates_Table__c/fields/Fixed_Mileage_Amount__c.field-meta.xml
<CustomField>
    <fullName>Fixed_Mileage_Amount__c</fullName>
    <description>Fixed Mileage amount to apply based based on Fixed mileage fee flag.</description>
    <label>Fixed Mileage Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Shipping_Rates_Table__c/fields/Fixed_Mileage_Fee__c.field-meta.xml
<CustomField>
    <fullName>Fixed_Mileage_Fee__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Fixed Mileage fee flag to apply fixed mileage amount Vs Mileage bracket amount</description>
    <label>Fixed Mileage Fee</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Shipping_Rates_Table__c/fields/Fixed_Weight_Amount__c.field-meta.xml
<CustomField>
    <fullName>Fixed_Weight_Amount__c</fullName>
    <description>Fixed Weight amount to apply based based on Fixed weight fee flag.</description>
    <label>Fixed Weight Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Shipping_Rates_Table__c/fields/Fixed_Weight_Fee__c.field-meta.xml
<CustomField>
    <fullName>Fixed_Weight_Fee__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Fixed Weight fee flag to apply fixed weight amount Vs weight bracket amount</description>
    <label>Fixed Weight Fee</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Shipping_Rates_Table__c/fields/Membership_Level__c.field-meta.xml
<CustomField>
    <fullName>Membership_Level__c</fullName>
    <label>Membership Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Membership_Level</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Shipping_Rates_Table__c/fields/Mileage_Bracket__c.field-meta.xml
<CustomField>
    <fullName>Mileage_Bracket__c</fullName>
    <inlineHelpText>Mileage Bracket used to Calculate Shipment Cost and Pricing</inlineHelpText>
    <label>Mileage Bracket</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Shipping_Rates_Table__c/fields/Mileage_Bracket_Price__c.field-meta.xml
<CustomField>
    <fullName>Mileage_Bracket_Price__c</fullName>
    <formula>( Mileage_Bracket_Cost__c *  Mileage_Bracket_Mark_Up__c ) + Mileage_Bracket_Cost__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Mileage Bracket Price</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Shipping_Rates_Table__c/fields/Rate_Effective_From__c.field-meta.xml
<CustomField>
    <fullName>Rate_Effective_From__c</fullName>
    <label>Rate Effective From</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Shipping_Rates_Table__c/fields/Rate_Effective_To__c.field-meta.xml
<CustomField>
    <fullName>Rate_Effective_To__c</fullName>
    <label>Rate Effective To</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Shipping_Rates_Table__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site</label>
    <referenceTo>Site__c</referenceTo>
    <relationshipName>Shipping_Rates_Tables</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipping_Rates_Table__c/fields/Weight_Bracket__c.field-meta.xml
<CustomField>
    <fullName>Weight_Bracket__c</fullName>
    <inlineHelpText>Dimensional (DIM) or Gross Weight Bracket used to Calculate Cost and Price</inlineHelpText>
    <label>Weight Bracket</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Shipping_Rates_Table__c/fields/Weight_Bracket_Price__c.field-meta.xml
<CustomField>
    <fullName>Weight_Bracket_Price__c</fullName>
    <formula>(Weight_Bracket_Cost__c *  Weight_Bracket_Mark_Up__c ) + Weight_Bracket_Cost__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Weight Bracket Price</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Site__c/Site__c.object-meta.xml
<CustomObject>
    <description>All objects must have a Site Name and License Class or A or M. For separate sales and inventory record.</description>
    <label>Site</label>
    <nameField>
        <label>Site</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Site__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active ?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Site__c/fields/Warehouse_Name__c.field-meta.xml
<CustomField>
    <fullName>Warehouse_Name__c</fullName>
    <description>Name of the warehouse to display in UI. Example : Communities.</description>
    <label>Warehouse Name</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RatesController.cls
public without sharing class RatesController {
    private static String FULFILLMENT_SERVICE_QA_REVIEW{
        get{
            return String.isNotBlank(FULFILLMENT_SERVICE_QA_REVIEW) ? FULFILLMENT_SERVICE_QA_REVIEW : FiligreenConfigurationUtility.getConfigValueByObjectAndKey('Fulfillment Rates Table','Fulfillment_Service_QA_Review');
        }set;
    }
    private static String FULFILLMENT_SERVICE_PICK_PACK{
        get{
            return String.isNotBlank(FULFILLMENT_SERVICE_PICK_PACK) ? FULFILLMENT_SERVICE_PICK_PACK : FiligreenConfigurationUtility.getConfigValueByObjectAndKey('Fulfillment Rates Table','Fulfillment_Service_Pick_Pack');
        }set;
    }
    private static String FULFILLMENT_SERVICE_RECEIVING{
        get{
            return String.isNotBlank(FULFILLMENT_SERVICE_RECEIVING) ? FULFILLMENT_SERVICE_RECEIVING : FiligreenConfigurationUtility.getConfigValueByObjectAndKey('Fulfillment Rates Table','Fulfillment_Service_Receiving_Fee');
        }set;
    }
    public Map<String,List<FRTRateDetail>> FRTRateDetailPrint{set;get;}
    public Set<Decimal> MOQSet {get;set;}
    public String UserId {get;set;}
    public String ratesType {get;set;}
    public Integer MOQLength {get;set;}
    public boolean isOtherFRT {get;set;}
    public boolean isSRT {get;set;}
    public String headingName {get;set;}
    public List<Fulfillment_Rates_Table__c> printOthersFRTList {get;set;}
    public Map<String,List<Shipping_Rates_Table__c>> printSRTDetails {get;set;}
    public RatesController(){
        UserId = ApexPages.currentPAge().getParameters().get('recordId');
        ratesType = ApexPages.currentPAge().getParameters().get('Type');
        if(ratesType == 'SRTRates'){
            headingName='Shipping Rates Table Detail';
            isSRT = true;
            AuraResponse r = RatesController.getSRTRates(UserId);
            printSRTDetails =( Map<String,List<Shipping_Rates_Table__c>>)r.data.get('SRT');
        }else{
            headingName='Fulfillment Rates Table Detail';
            isSRT = false;
            AuraResponse r = RatesController.getFRTRates(UserId,ratesType);
            if(ratesType == 'Others'){
                isOtherFRT=true;
                printOthersFRTList =( List<Fulfillment_Rates_Table__c>)r.data.get('FRT');
                System.debug('###printOthersFRTList :'+printOthersFRTList);
            }else{
                isOtherFRT=false;
                FRTRateDetailPrint = ( Map<String,List<FRTRateDetail>>)r.data.get('FRT');
                MOQSet =(Set<Decimal>)r.data.get('MOQsHeader');
                MOQLength= MOQSet.size();
            }
        }
    }
    @AuraEnabled
    public static AuraResponse getSRTRates(String loginId){
        AuraResponse r = new AuraResponse('RatesController.getSRTRates()');
        User u =[SELECT Id, IsActive,AccountId, Contact.Account.Name,Contact.Primary_Contact__c ,Account.Membership_Level__c,  Phone, MobilePhone FROM User WHERE Id = :loginId];

        List<Shipping_Rates_Table__c> SRTList =[SELECT Id, Active__c, Mileage_Bracket__c, Mileage_Bracket_Price__c,Rate_Effective_From__c,Rate_Effective_To__c, Membership_Level__c,
                                              Weight_Bracket__c, Weight_Bracket_Price__c,Site__r.Active__c,Site__c,Site__r.Name,Site__r.Warehouse_Name__c,Fixed_Mileage_Amount__c , Fixed_Mileage_Fee__c , Fixed_Weight_Amount__c ,Fixed_Weight_Fee__c 
                                              FROM Shipping_Rates_Table__c 
                                              WHERE Active__c = true 
                                              AND Rate_Effective_From__c <= :System.today() 
                                              AND Rate_Effective_To__c >= :System.today()
                                              AND Membership_Level__c =:u.Account.Membership_Level__c
                                               AND Site__r.Active__c = true
                                               Order By Site__r.Warehouse_Name__c,Mileage_Bracket__c];
        
        Map<String,List<Shipping_Rates_Table__c>> SRTMap = new Map<String,List<Shipping_Rates_Table__c>>();
        for(Shipping_Rates_Table__c srt : SRTList){
            if(SRTMap.containsKey(srt.Site__r.Warehouse_Name__c)){
                List<Shipping_Rates_Table__c> SRTs = SRTMap.get(srt.Site__r.Warehouse_Name__c);
                SRTs.add(srt);
                SRTMap.put(srt.Site__r.Warehouse_Name__c, SRTs);
            } else {
                SRTMap.put(srt.Site__r.Warehouse_Name__c, new List<Shipping_Rates_Table__c> { srt });
            }
        }
        r.data.put('SRT', SRTMap); 
        return r;
    }
    public static List<sObject> getFRTRecord(String FRTServiceType,User u){
        List<Fulfillment_Rates_Table__c> FRTList = new List<Fulfillment_Rates_Table__c>();
        String FRTService ='';
        if(FRTServiceType == 'Receiving'){
            FRTService =FULFILLMENT_SERVICE_RECEIVING;
        }else if(FRTServiceType == 'QAReview'){
             FRTService =FULFILLMENT_SERVICE_QA_REVIEW;
        }else if(FRTServiceType == 'PickPack'){
             FRTService =FULFILLMENT_SERVICE_PICK_PACK;
        }else{
             FRTService ='';
        }
        if(FRTService != ''){
            FRTList = [SELECT Id, Active__c, Fulfillment_Services__c,Size_Classification__c,Bracket_Price__c ,Site__r.Active__c,Site__r.Warehouse_Name__c,Site__r.Name,Rate_Effective_From__c ,Rate_Effective_To__c, Site__c,MOQ__c ,Weight_lbs__c ,Membership_Level__c
                           FROM Fulfillment_Rates_Table__c 
                           WHERE /*Site__c IN :warehouseIds AND Membership_Level__c =:u.Account.Membership_Level__c*/
                           Active__c = true
                           AND Rate_Effective_From__c <= :System.today()
                           AND Rate_Effective_To__c >= :System.today()
                           AND Fulfillment_Services__c=:FRTService
                       	   AND Membership_Level__c =:u.Account.Membership_Level__c
                       	   AND Site__r.Active__c = true
                       	ORDER BY Membership_Level__c, Weight_lbs__c, MOQ__c
                      ];
        }else{
            FRTList = [SELECT Id, Active__c, Fulfillment_Services__c,Size_Classification__c,Bracket_Price__c,Site__r.Active__c ,Site__r.Warehouse_Name__c,Rate_Effective_From__c ,Rate_Effective_To__c, Site__c,Site__r.Name,MOQ__c ,Weight_lbs__c ,Membership_Level__c
                                                 FROM Fulfillment_Rates_Table__c 
                                                 WHERE /*Site__c IN :warehouseIds AND Membership_Level__c =:u.Account.Membership_Level__c*/
                                                 Active__c = true
                                                 AND Rate_Effective_From__c <= :System.today()
                                                 AND Rate_Effective_To__c >= :System.today()
                       							 AND Membership_Level__c =:u.Account.Membership_Level__c
                                                 AND Fulfillment_Services__c NOT IN (:FULFILLMENT_SERVICE_RECEIVING,:FULFILLMENT_SERVICE_QA_REVIEW,:FULFILLMENT_SERVICE_PICK_PACK)
                       							AND Site__r.Active__c = true
                      ORDER BY Site__c,Fulfillment_Services__c, Weight_lbs__c, MOQ__c];
        }
        	
        return FRTList;
    }
    @AuraEnabled
    public static AuraResponse getFRTRates(String loginId,String FRTServiceType){
         AuraResponse r = new AuraResponse('RatesController.getFRTRates()');
        System.debug('###FRTServiceType :'+FRTServiceType);
        User u =[SELECT Id, IsActive,AccountId, Contact.Account.Name,Contact.Primary_Contact__c ,Account.Membership_Level__c,  Phone, MobilePhone FROM User WHERE Id = :loginId];
        List<Fulfillment_Rates_Table__c> FRTList = new List<Fulfillment_Rates_Table__c>();
        
        FRTList =getFRTRecord(FRTServiceType,u);
        Map<String,Map<String,Map<Decimal,Map<Decimal,Decimal>>>> siteMembershipWeightMOQPriceMap = new Map<String,Map<String,Map<Decimal,Map<Decimal,Decimal>>>>();
       List<FRTRateDetail> FRTRateDetails = new List<FRTRateDetail>();
        
        if(FRTServiceType == 'Others'){
                r.data.put('FRT', FRTList);
        }else{
            Set<Decimal> MOQs = new Set<Decimal>();
            for(Fulfillment_Rates_Table__c frt : FRTList){
                Map<String,Map<Decimal,Map<Decimal,Decimal>>> membershipWeightMOQPriceMap = new Map<String,Map<Decimal,Map<Decimal,Decimal>>>();
                if(siteMembershipWeightMOQPriceMap.containsKey(frt.Site__r.Warehouse_Name__c)){
                    membershipWeightMOQPriceMap = siteMembershipWeightMOQPriceMap.get(frt.Site__r.Warehouse_Name__c);
                }
                Map<Decimal,Map<Decimal,Decimal>> WeightMOQPriceMap = new Map<Decimal,Map<Decimal,Decimal>>();
                if(membershipWeightMOQPriceMap.containsKey(frt.Size_Classification__c)){
                    WeightMOQPriceMap = membershipWeightMOQPriceMap.get(frt.Size_Classification__c);
                }
                Map<Decimal,Decimal> MOQPriceMap = new Map<Decimal,Decimal>();
                if(WeightMOQPriceMap.containsKey(frt.Weight_lbs__c)){
                    MOQPriceMap = WeightMOQPriceMap.get(frt.Weight_lbs__c);
                }
                MOQs.add(frt.MOQ__c);
                MOQPriceMap.put(frt.MOQ__c,frt.Bracket_Price__c);
                WeightMOQPriceMap.put(frt.Weight_lbs__c,MOQPriceMap);
                membershipWeightMOQPriceMap.put(frt.Size_Classification__c,WeightMOQPriceMap);
                siteMembershipWeightMOQPriceMap.put(frt.Site__r.Warehouse_Name__c,membershipWeightMOQPriceMap);
            }
            
            Map<String,List<FRTRateDetail>> FRTRateDetailsBySite = new Map<String,List<FRTRateDetail>>();
            for(String site: siteMembershipWeightMOQPriceMap.keySet()){
                FRTRateDetails = new List<FRTRateDetail>();
                Map<String,Map<Decimal,Map<Decimal,Decimal>>> membershipWeightMOQPriceMap = siteMembershipWeightMOQPriceMap.get(site);
                for(String MSLevel: membershipWeightMOQPriceMap.keySet()){
                    Map<Decimal,Map<Decimal,Decimal>> WeightMOQPriceMap = membershipWeightMOQPriceMap.get(MSLevel);
                    if(WeightMOQPriceMap != NULL && WeightMOQPriceMap.size() > 0){
                        for(Decimal weight: WeightMOQPriceMap.keySet()){
                            Map<Decimal,Decimal> MOQPriceMap = WeightMOQPriceMap.get(weight);
                            FRTRateDetails.add(new FRTRateDetail(MSLevel,weight,MOQs,MOQPriceMap));
                        }
                    }
                    
                }
                FRTRateDetailsBySite.put(site,FRTRateDetails);
            }
            System.debug('###FRTRateDetailsBySite :'+FRTRateDetailsBySite);
            r.data.put('MOQsHeader', MOQs);
            r.data.put('FRT',FRTRateDetailsBySite);
        }
        
        
        return r;
    }
    public class FRTRateDetail{
        @AuraEnabled
        public String MembershipLevel{set;get;}
        @AuraEnabled
        public Decimal weight{set;get;}
        @AuraEnabled
        public Decimal[] bracketPriceList{set;get;}
        public FRTRateDetail(String MembershipLevel, Decimal weight,Set<Decimal> MOQs,Map<Decimal,Decimal> MOQPriceMap){
            this.MembershipLevel = MembershipLevel;
            this.weight = weight;
            this.bracketPriceList = new Decimal[] {};
            for(Decimal MOQ: MOQs){
                if(MOQPriceMap.containsKey(MOQ)){
                    this.bracketPriceList.add(MOQPriceMap.get(MOQ));
                }else{
                    this.bracketPriceList.add(-1);
                }
            }
            //this.bracketPriceList = bracketPriceList;
        }
    }   
}