force-app/main/default/objects/Brand_Discount__c/Brand_Discount__c.object-meta.xml
<CustomObject>
    <description>Manage all brands and product discounts.</description>
    <label>Brand Discount</label>
    <nameField>
        <displayFormat>BD-{YYYY}-{MM}-{0000000000}</displayFormat>
        <label>Brand Discount Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Brand Discounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Brand_Discount__c/fields/Discount_Active__c.field-meta.xml
<CustomField>
    <fullName>Discount_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Discount Active?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Brand_Discount__c/fields/Discount_End_DateTime__c.field-meta.xml
<CustomField>
    <fullName>Discount_End_DateTime__c</fullName>
    <label>Discount End DateTime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Brand_Discount__c/fields/Discount_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Discount_Percentage__c</fullName>
    <inlineHelpText>Discount to be applied in products list price</inlineHelpText>
    <label>Discount Percentage</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Brand_Discount__c/fields/Discount_Start_DateTime__c.field-meta.xml
<CustomField>
    <fullName>Discount_Start_DateTime__c</fullName>
    <inlineHelpText>Date/Time where Discount to be Applied/Activated</inlineHelpText>
    <label>Discount Start DateTime</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/BatchToUpdateBrandDiscountsActiveTest.cls
@isTest
public class BatchToUpdateBrandDiscountsActiveTest {
    private static testmethod void runTest(){
        Brand_Discount__c bd = new Brand_Discount__c(Discount_Active__c = true, Discount_Start_DateTime__c = Date.today(),Discount_End_DateTime__c  = System.now().addDays(2), Discount_Percentage__c = 10);
        insert bd;
        Database.executeBatch(new BatchToUpdateBrandDiscountsActive());
        
        BatchToUpdateBrandDiscountsActive sh1 = new BatchToUpdateBrandDiscountsActive();
        
        String sch = '0 0 23 * * ?'; 
        system.schedule('Test BatchToUpdateBrandDiscountsActive', sch, sh1);
    }
}