force-app/main/default/objects/Brand_Discount__c/Brand_Discount__c.object-meta.xml
<CustomObject>
    <description>Manage all brands and product discounts.</description>
    <label>Brand Discount</label>
    <nameField>
        <displayFormat>BD-{YYYY}-{MM}-{0000000000}</displayFormat>
        <label>Brand Discount Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Brand Discounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Brand_Discount__c/fields/Discount_Active__c.field-meta.xml
<CustomField>
    <fullName>Discount_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Discount Active?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Brand_Discount__c/fields/Discount_End_DateTime__c.field-meta.xml
<CustomField>
    <fullName>Discount_End_DateTime__c</fullName>
    <label>Discount End DateTime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Brand_Discount__c/fields/Discount_Start_DateTime__c.field-meta.xml
<CustomField>
    <fullName>Discount_Start_DateTime__c</fullName>
    <inlineHelpText>Date/Time where Discount to be Applied/Activated</inlineHelpText>
    <label>Discount Start DateTime</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/BatchToUpdateBrandDiscountsActive.cls
global class BatchToUpdateBrandDiscountsActive implements Database.Batchable<sObject>, Database.Stateful, Schedulable{
    global Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator([SELECT Id,Name,Discount_Active__c,Discount_Start_DateTime__c,Discount_End_DateTime__c FROM Brand_Discount__c 
                                                 WHERE DAY_ONLY(Discount_Start_DateTime__c) =: Date.today() OR DAY_ONLY(Discount_End_DateTime__c) =: Date.today()]); 
    }
    
    global void execute(Database.BatchableContext bc, List<Brand_Discount__c> records){
        for(Brand_Discount__c brand : records){
            if(brand.Discount_Start_DateTime__c.Date() == Date.today()){
                brand.Discount_Active__c = true;
            }
            if(brand.Discount_End_DateTime__c.Date() == Date.today()){
                brand.Discount_Active__c = false;
            }
        }
        update records;
    }
    
    global void execute(SchedulableContext sc){}
    
    global void finish(Database.BatchableContext bc){} 
}