force-app/main/default/objects/Bill_Pay__c/Bill_Pay__c.object-meta.xml
<CustomObject>
    <label>Bill Pay</label>
    <nameField>
        <displayFormat>PAY-{YYYY}-{MM}-{000000}</displayFormat>
        <label>Bill Pay</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bill Pays</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Bill_Pay__c/fields/Payment_Amount__c.field-meta.xml
<CustomField>
    <fullName>Payment_Amount__c</fullName>
    <label>Payment Amount</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Bill_Pay__c/fields/Purchase_Order__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Order__c</fullName>
    <formula>Supplier_Bill__r.Purchase_Order__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Purchase Order</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Brand_Quote__c/Brand_Quote__c.object-meta.xml
<CustomObject>
    <description>Buy Quote to Purchase from Brands. Sell Quotes to Sell to Dispensaries</description>
    <label>Brand Quote</label>
    <nameField>
        <displayFormat>BQ-{0000000000}</displayFormat>
        <label>Brand Quote</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Brand Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Brand_Quote__c/fields/Last_Payment_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Payment_Date__c</fullName>
    <inlineHelpText>Last Payment Date from Invoice PB</inlineHelpText>
    <label>Last Payment Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>IN-{0000000000}</displayFormat>
        <label>Invoice</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Brand_Quote__c.field-meta.xml
<CustomField>
    <fullName>Brand_Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Brand Quote</label>
    <referenceTo>Brand_Quote__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Collections_Status__c.field-meta.xml
<CustomField>
    <fullName>Collections_Status__c</fullName>
    <inlineHelpText>Auto updated based on payment received and due dates.</inlineHelpText>
    <label>Collections Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Past Due</fullName>
            </value>
            <value>
                <fullName>Partial Payment</fullName>
            </value>
            <value>
                <fullName>Paid in Full</fullName>
            </value>
            <value>
                <fullName>Not Collectable</fullName>
            </value>
            <value>
                <fullName>Brand Collections</fullName>
            </value>
            <value>
                <fullName>Charge-off</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Invoice_Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Due_Date__c</fullName>
    <label>Invoice Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/IsLocked__c.field-meta.xml
<CustomField>
    <fullName>IsLocked__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsLocked</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Last_Payment_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Payment_Date__c</fullName>
    <inlineHelpText>Date payment was last received and recorded.</inlineHelpText>
    <label>Last Payment Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Posted_Date__c.field-meta.xml
<CustomField>
    <fullName>Posted_Date__c</fullName>
    <label>Posted Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Purchase_Order__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Purchase Order</label>
    <referenceTo>Purchase_Order__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Total_Cultivation_Tax_Payments_Received__c.field-meta.xml
<CustomField>
    <fullName>Total_Cultivation_Tax_Payments_Received__c</fullName>
    <description>Calculates total payment amount of CULTIVATION TAX record type of related receive payment object</description>
    <label>Total Cultivation Tax Payments Received</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Total_Excise_Tax_Payments_Received__c.field-meta.xml
<CustomField>
    <fullName>Total_Excise_Tax_Payments_Received__c</fullName>
    <description>Calculates total payment amount of EXCISE TAX record type of related receive payment object</description>
    <label>Total Excise Tax Payments Received</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Total_Payments_Received__c.field-meta.xml
<CustomField>
    <fullName>Total_Payments_Received__c</fullName>
    <inlineHelpText>Automated roll-up of total payments received from payment records.</inlineHelpText>
    <label>Total Payments Received</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Total_Product_Payments_Received__c.field-meta.xml
<CustomField>
    <fullName>Total_Product_Payments_Received__c</fullName>
    <description>Calculates total payment amount of PRODUCT record type of related receive payment object.</description>
    <label>Total Product Payments Received</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice__c/recordTypes/Product.recordType-meta.xml
<RecordType>
    <fullName>Product</fullName>
    <active>true</active>
    <description>Use for all Product and Services</description>
    <label>Product</label>
</RecordType>

force-app/main/default/objects/Invoice__c/recordTypes/Tax.recordType-meta.xml
<RecordType>
    <fullName>Tax</fullName>
    <active>true</active>
    <description>Used for Cultivation Tax Invoices</description>
    <label>Tax</label>
</RecordType>

force-app/main/default/objects/Purchase_Order__c/Purchase_Order__c.object-meta.xml
<CustomObject>
    <label>Purchase Order</label>
    <nameField>
        <displayFormat>PO-{0000000000}</displayFormat>
        <label>Purchase Order</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Purchase_Order__c/fields/Brand_Quote__c.field-meta.xml
<CustomField>
    <fullName>Brand_Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Quote used to create PO</description>
    <label>Brand Quote</label>
    <referenceTo>Brand_Quote__c</referenceTo>
    <relationshipLabel>Purchase Orders</relationshipLabel>
    <relationshipName>Purchase_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/fields/Last_Payment_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Payment_Date__c</fullName>
    <formula>Brand_Quote__r.Last_Payment_Date__c</formula>
    <label>Last Payment Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/fields/Supplier_Payment_Settled_Date__c.field-meta.xml
<CustomField>
    <fullName>Supplier_Payment_Settled_Date__c</fullName>
    <inlineHelpText>Date Purchase Order Invoiced from Supplier Settled</inlineHelpText>
    <label>Supplier Payment Settled Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/fields/Total_Cost__c.field-meta.xml
<CustomField>
    <fullName>Total_Cost__c</fullName>
    <inlineHelpText>Total PPO Cost</inlineHelpText>
    <label>Total Cost</label>
    <summarizedField>Purchase_Order_Line__c.Line_Total_Cost__c</summarizedField>
    <summaryFilterItems>
        <field>Purchase_Order_Line__c.POLI_Status__c</field>
        <operation>notEqual</operation>
        <value>Cancelled, Rejected</value>
    </summaryFilterItems>
    <summaryForeignKey>Purchase_Order_Line__c.Purchase_Order__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/fields/Total_Payments_Made__c.field-meta.xml
<CustomField>
    <fullName>Total_Payments_Made__c</fullName>
    <inlineHelpText>Total amount of payments made to supplier from bill pay records.</inlineHelpText>
    <label>Total Payments Made</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/recordTypes/Product.recordType-meta.xml
<RecordType>
    <fullName>Product</fullName>
    <active>true</active>
    <description>Products Are For Buy Sell</description>
    <label>Product</label>
</RecordType>

force-app/main/default/objects/Receive_Payment__c/Receive_Payment__c.object-meta.xml
<CustomObject>
    <label>Receive Payment</label>
    <nameField>
        <displayFormat>RP-{YYYY}-{MM}-{000000}</displayFormat>
        <label>Transaction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Receive Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Receive_Payment__c/fields/Bill_Pay__c.field-meta.xml
<CustomField>
    <fullName>Bill_Pay__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Payment related to purchase order</description>
    <inlineHelpText>Payment related to purchase order</inlineHelpText>
    <label>Bill Pay</label>
    <referenceTo>Purchase_Order__c</referenceTo>
    <relationshipLabel>Bill Pay</relationshipLabel>
    <relationshipName>Receive_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Receive_Payment__c/fields/Credit_Memo__c.field-meta.xml
<CustomField>
    <fullName>Credit_Memo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Receive Payment Applied to Credit Memo</inlineHelpText>
    <label>Credit Memo</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Credits Applied</relationshipLabel>
    <relationshipName>Receive_Payments1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Receive_Payment__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Receive Payments</relationshipLabel>
    <relationshipName>Receive_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Receive_Payment__c/fields/Payment_Received_Date__c.field-meta.xml
<CustomField>
    <fullName>Payment_Received_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <inlineHelpText>Date in which payment was received. Default value is today.</inlineHelpText>
    <label>Transaction Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Receive_Payment__c/fields/Posted_Date__c.field-meta.xml
<CustomField>
    <fullName>Posted_Date__c</fullName>
    <inlineHelpText>Finance to enter date payment was reconciled and added to general fund.</inlineHelpText>
    <label>Posted Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Receive_Payment__c/fields/Total_Payments_Received__c.field-meta.xml
<CustomField>
    <fullName>Total_Payments_Received__c</fullName>
    <formula>Invoice__r.Total_Payments_Received__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Payments Received</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Receive_Payment__c/recordTypes/Product.recordType-meta.xml
<RecordType>
    <fullName>Product</fullName>
    <active>true</active>
    <description>Used for Product Payments</description>
    <label>Product</label>
</RecordType>

force-app/main/default/classes/ReceivePaymentTriggerHandler.cls
/**
 * Copyright (c) 2018 Filigreen Distro
 * All rights reserved.
 * ReceivePaymentTriggerHandler
 */
public class ReceivePaymentTriggerHandler{
    
    public static final string RP_RECORD_TYPE_EXCISE_TAX = 'Excise Tax';
    public static final string RP_RECORD_TYPE_PRODUCT = 'Product';
    public static final string RP_RECORD_TYPE_CULTIVATION_TAX = 'Cultivation Tax';
    public Static String RP_RecordType_CreditCard{
        get{
            return String.isNotBlank(RP_RecordType_CreditCard) ? RP_RecordType_CreditCard: FiligreenConfigurationUtility.getConfigValueByObjectAndKey('Receive Payments','RP_RecordType_CreditCard');
        }set;
    }
    private static String Invoice_Record_Type_Credit_Memo{
        get{
            return String.isNotBlank(Invoice_Record_Type_Credit_Memo) ? Invoice_Record_Type_Credit_Memo : FiligreenConfigurationUtility.getConfigValueByObjectAndKey('Invoice','Invoice_Record_Type_Credit_Memo');
        }set;
    }
    public Static String Validation_Msg_for_delete_RecePayment{
        get{
            return String.isNotBlank(Validation_Msg_for_delete_RecePayment) ? Validation_Msg_for_delete_RecePayment: FiligreenConfigurationUtility.getConfigValueByObjectAndKey('Receive Payments','Validation_Msg_for_delete_RecePayment');
        }set;
    }
     public Static String Validation_Msg_for_insert_update_RecePay{
        get{
            return String.isNotBlank(Validation_Msg_for_insert_update_RecePay) ? Validation_Msg_for_insert_update_RecePay: FiligreenConfigurationUtility.getConfigValueByObjectAndKey('Receive Payments','Validation_Msg_for_insert_update_RecePay');
        }set;
    }
    private static String INVOICE_COLLECTION_STATUS_PASTDUE{
        get{
            return String.isNotBlank(INVOICE_COLLECTION_STATUS_PASTDUE) ? INVOICE_COLLECTION_STATUS_PASTDUE : FiligreenConfigurationUtility.getConfigValueByObjectAndKey('Invoice','invoice_Collection_Status_PastDue');
        }set;
    }
    private static String INVOICE_COLLECTION_STATUS_PENDING{
        get{
            return String.isNotBlank(INVOICE_COLLECTION_STATUS_PENDING) ? INVOICE_COLLECTION_STATUS_PENDING : FiligreenConfigurationUtility.getConfigValueByObjectAndKey('Invoice','invoice_Collection_Status_Pending');
        }set;
    }
    private static String INVOICE_COLLECTION_STATUS_PARTIALPAYMENT{
        get{
            return String.isNotBlank(INVOICE_COLLECTION_STATUS_PARTIALPAYMENT) ? INVOICE_COLLECTION_STATUS_PARTIALPAYMENT : FiligreenConfigurationUtility.getConfigValueByObjectAndKey('Invoice','invoice_Collection_Status_partialPaymente');
        }set;
    }
    /**
     * Update invoice fields and Purchase Order fields related to roll up summary value of receive payments
     * Last Payment Date
     * Total Excise Tax Payments Received
     * Total Payments Received
     * Total Product Payments Received
     * @param receivePayments The trigger.new receive payment list
     */
    public static void updateInvoiceAttributesRelatedToReceivePayments(List<Receive_Payment__c> receivePayments,
                                                                       Map<Id, Receive_Payment__c> oldReceivePayments,
                                                                       Boolean isDeleteReceivePayment){
        Set<Id> invoiceIds = new Set<Id>();
        Set<Id> poIds = new Set<Id>();
                   // Date lastPaymentDate = null;
        // Retrieve all invoices
        for(Receive_Payment__c rpObj : receivePayments){
            if(rpObj.Invoice__c != null){
                invoiceIds.add(rpObj.Invoice__c);
            }else if(rpObj.Bill_Pay__c != null){
                poIds.add(rpObj.Bill_Pay__c);
            }
        }
        system.debug('rpObj'+receivePayments);
    
             
                                                                           
                                                                         
        // Calculate total fields of invoice
        if(invoiceIds.size() > 0){
            updateTotalFieldsOfInvoice(invoiceIds, oldReceivePayments, isDeleteReceivePayment);
        }
        
        // Calculate total fields of Purchase Order
        if(poIds.size() > 0){
            updateTotalFieldsOfPurchaseOrder(poIds, oldReceivePayments, isDeleteReceivePayment);
        }
    }
    public static void preventUpdatationOnLockedInvoice(List<Receive_Payment__c> newReceivePayments,List<Receive_Payment__c> oldReceivePayments){
        Set<Id> invoiceIds = new Set<Id>(); 
        if(Trigger.isDelete){
            for(Receive_Payment__c RP: oldReceivePayments){
                invoiceIds.add(RP.Invoice__c);
            }
        }else{
            for(Receive_Payment__c RP: newReceivePayments){
                invoiceIds.add(RP.Invoice__c);
            }
        }
        if(invoiceIds.size() > 0){
            List<Invoice__c> invoices = [SELECT Id FROM Invoice__c WHERE Id IN: invoiceIds AND IsLocked__c = true];
            if(invoices.size() > 0){
                if(Trigger.isDelete){
                    oldReceivePayments[0].addError(Validation_Msg_for_delete_RecePayment);
                    return;
                }else{
                    newReceivePayments[0].addError(Validation_Msg_for_insert_update_RecePay);
                    return;
                }
            }
        }
    }
    public static void updatePostedDate(List<Receive_Payment__c> receivePayments, Map<Id, Receive_Payment__c> oldReceivePayments){
        Set<Id> invIds = new Set<Id>();
          Map<Id,Date> Invlst = new Map<Id, Date>(); 
        for(Receive_Payment__c rpObj : receivePayments){
            if(rpObj.Invoice__c != null){
                if(Trigger.isInsert || (Trigger.isUpdate && rpObj.Posted_Date__c != oldReceivePayments.get(rpObj.Id).Posted_Date__c)){
                    invIds.add(rpObj.Invoice__c);
                     Invlst.put(rpObj.Invoice__c , rpObj.Posted_Date__c);  
                }
            }
        }
        List<Invoice__c> lstInvoice = [select Id,Posted_Date__c,(select Id,Posted_Date__c,Payment_Received_Date__c from Receive_Payments__r order by Posted_Date__c DESC nulls last) FROM Invoice__c WHERE ID IN : invIds AND Collections_Status__c = 'Paid in Full'];
        system.debug('lstInvoice>>'+lstInvoice);
        List<Invoice__c> updatedInvoice = new List<Invoice__c>();
       
        if(lstInvoice.size() > 0){
            for(Invoice__c inv : lstInvoice){
            	List<Receive_Payment__c> lstReceive = inv.Receive_Payments__r;
                system.debug('lstReceive>>'+lstReceive);
                if(lstReceive.size() > 0){
                    Boolean isHasRecords = true;
                    for(Receive_Payment__c rec : lstReceive){
                        if(rec.Posted_Date__c == null){
                        	isHasRecords = false;
                            break;
                        }    
                    }
                    if(isHasRecords){
                    	inv.Posted_Date__c = lstReceive[0].Posted_Date__c;
                        updatedInvoice.add(inv);    
                    }  
                }
            }
            
            if(updatedInvoice.size() > 0){
            	update updatedInvoice;    
            }
        }
    }  
    
    
    
    /**
     * Update invoice fields related to roll up summary value of receive payments
     * Last Payment Date
     * Total Excise Tax Payments Received
     * Total Payments Received
     * Total Product Payments Received
     * @param invoiceIds The set of invoice ids
     */
    private static void updateTotalFieldsOfInvoice(Set<Id> invoiceIds, 
                                                   Map<Id, Receive_Payment__c> oldReceivePayments,
                                                   Boolean isDeleteReceivePayment){
        if(invoiceIds.size() > 0){
            List<Invoice__c> invoicesToUpdate = [Select Last_Payment_Date__c,Invoice_Due_Date__c,Collections_Status__c,
                                                       Total_Excise_Tax_Payments_Received__c,
                                                       Total_Payments_Received__c,
                                                       Total_Product_Payments_Received__c,
                                                       Total_Cultivation_Tax_Payments_Received__c,
                                                       (Select Payment_Amount__c, Payment_Received_Date__c,Posted_Date__c, 
                                                        RecordType.Name From Receive_Payments__r Order BY Posted_Date__c DESC NULLS LAST,Payment_Received_Date__c DESC )
                                                From Invoice__c where Id IN: invoiceIds AND RecordType.Name !=: Invoice_Record_Type_Credit_Memo];
            system.debug('invoicesToUpdate'+invoicesToUpdate);
                
              //List<Receive_Payment__c> RPToUpdate = [Select Last_Payment_Date__c, 
          // Date lastPaymentDate = null;
            Decimal totalExciseTaxPayments;
            Decimal totalPaymentAmount;
            Decimal totalProductPaymentAmount;
            Decimal totalCultivationTaxAmount;
            Map<Id,Invoice__c> invoicesToUpdateMap = new Map<Id,Invoice__c>();
            // Iterate on all invoices - context from trigger
            for(Invoice__c invoiceSO : invoicesToUpdate){
                
                totalExciseTaxPayments = 0.0;
                totalPaymentAmount = 0.0;
                totalProductPaymentAmount = 0.0;
                totalCultivationTaxAmount = 0.0;
                

                if(invoiceSO.Invoice_Due_Date__c < Date.today() && invoiceSO.Receive_Payments__r.size() == 0){
                    invoiceSO.Collections_Status__c = INVOICE_COLLECTION_STATUS_PASTDUE;
                } else if(invoiceSO.Invoice_Due_Date__c >= Date.today() && invoiceSO.Receive_Payments__r.size() == 0){
                    invoiceSO.Collections_Status__c = INVOICE_COLLECTION_STATUS_PENDING;
                } else if(invoiceSO.Receive_Payments__r.size() > 0){
                    invoiceSO.Collections_Status__c = INVOICE_COLLECTION_STATUS_PARTIALPAYMENT;
                }
                
                if(invoiceSO.Receive_Payments__r.size() == 0){
                    invoiceSO.Last_Payment_Date__c = null;
                }
                
                if(invoiceSO.Receive_Payments__r.size() > 0){
                    invoiceSO.Last_Payment_Date__c = invoiceSO.Receive_Payments__r[0].Posted_Date__c != null ? invoiceSO.Receive_Payments__r[0].Posted_Date__c : invoiceSO.Receive_Payments__r[0].Payment_Received_Date__c;
                }
                
                
                // Iterate on all related receive payments
                for(Receive_Payment__c rpObj : invoiceSO.Receive_Payments__r){
                    // Calculate last payment date
                     /* if((!isDeleteReceivePayment || !oldReceivePayments.containsKey(rpObj.Id)) && 
                      (lastPaymentDate == null || lastPaymentDate < rpObj.Payment_Received_Date__c )){
                             // lastPaymentDate = rpObj.Payment_Received_Date__c; 
                    }*/
                    
                    // Calculate Total Excise Tax Payments Received
                    if(rpObj.RecordType.Name == RP_RECORD_TYPE_EXCISE_TAX){
                        if(!isDeleteReceivePayment || !oldReceivePayments.containsKey(rpObj.Id)){
                            totalExciseTaxPayments += rpObj.Payment_Amount__c;
                        }
                    }
                    
                    // Calculate Total Excise Tax Payments Received
                    if(rpObj.RecordType.Name == RP_RECORD_TYPE_PRODUCT){
                        if(!isDeleteReceivePayment || !oldReceivePayments.containsKey(rpObj.Id)){
                            totalProductPaymentAmount += rpObj.Payment_Amount__c;
                        }
                    }
                    
                    // Calculate Total Cultivation Tax Payments Received
                    if(rpObj.RecordType.Name == RP_RECORD_TYPE_CULTIVATION_TAX){
                        if(!isDeleteReceivePayment || !oldReceivePayments.containsKey(rpObj.Id)){
                            totalCultivationTaxAmount += rpObj.Payment_Amount__c;
                        }
                    }
                    
                    // Calculate Total Payments Received
                    if(!isDeleteReceivePayment || !oldReceivePayments.containsKey(rpObj.Id)){
                        totalPaymentAmount += rpObj.Payment_Amount__c;
                    }
                }
                
                // Assign values to invoices
               // invoiceSO.Last_Payment_Date__c = lastPaymentDate;
                invoiceSO.Total_Excise_Tax_Payments_Received__c = totalExciseTaxPayments;
                invoiceSO.Total_Product_Payments_Received__c = totalProductPaymentAmount;
                invoiceSO.Total_Cultivation_Tax_Payments_Received__c = totalCultivationTaxAmount;
                invoiceSO.Total_Payments_Received__c = totalPaymentAmount;
                invoicesToUpdateMap.put(invoiceSO.Id,invoiceSO);
            }
            
           update invoicesToUpdateMap.values();
        }
    }
    
    /**
     * Update "Total Payments Made" of Purchase Order related to receive payments
     * @param poIds The set of Purchase Order Ids
     */
    private static void updateTotalFieldsOfPurchaseOrder(Set<Id> poIds,  
                                                         Map<Id, Receive_Payment__c> oldReceivePayments,
                                                         Boolean isDeleteReceivePayment){
        if(poIds.size() > 0){
            List<Purchase_Order__c> posToUpdate = [Select Total_Payments_Made__c,Total_Cost__c,Supplier_Payment_Settled_Date__c,
                                                  (Select Payment_Amount__c, Payment_Received_Date__c,Posted_Date__c  From Receive_Payments__r)
                                                From Purchase_Order__c where Id IN: poIds];
            
            Decimal totalPaymentsMade;
            
            // Iterate on all invoices - context from trigger
            for(Purchase_Order__c poSO : posToUpdate){
                
                totalPaymentsMade = 0.0;
                Date latestTransactionDate;
                // Iterate on all related receive payments
                for(Receive_Payment__c rpObj : poSO.Receive_Payments__r){
                    if((!isDeleteReceivePayment || !oldReceivePayments.containsKey(rpObj.Id)) &&
                       (latestTransactionDate == null || rpObj.Payment_Received_Date__c > latestTransactionDate)){
                        latestTransactionDate = rpObj.Payment_Received_Date__c;
                    }
                    // Calculate Total Payments Made
                    if(!isDeleteReceivePayment || !oldReceivePayments.containsKey(rpObj.Id)){
                        totalPaymentsMade += rpObj.Payment_Amount__c;
                    }
                }
                
                // Assign values to invoices
                poSO.Total_Payments_Made__c = totalPaymentsMade;
                if(poSo.Total_Cost__c - totalPaymentsMade == 0){
                    poSo.Supplier_Payment_Settled_Date__c = latestTransactionDate;
                }else if(poSo.Total_Cost__c - totalPaymentsMade > 0){
                    poSo.Supplier_Payment_Settled_Date__c = null;
                }
            }
            update posToUpdate;
        }
    }
    
  public static void updateLastPaymentDate(List<Receive_Payment__c> receivePayments){
      system.debug('updateLastPaymentDate');
      system.debug('receivePayments'+receivePayments);
      Map<Id,Date> Invlst = new Map<Id, Date>(); 
      for(Receive_Payment__c RP:receivePayments) {
          if(RP.Posted_Date__c !=null)
          {
              Invlst.put(RP.Invoice__c , RP.Posted_Date__c);  
          }else{
              Invlst.put(RP.Invoice__c , RP.Payment_Received_Date__c);         
          }
          
      }  
      Map<Id,Date> InvlstBQ = new Map<Id, Date>(); 
      List<Invoice__c> listUpdatedinvpost = new List<Invoice__c>(); 
      for(Invoice__c acc:[Select id,Last_Payment_Date__c,Collections_Status__c,Posted_Date__c From Invoice__c Where Id IN :Invlst.Keyset()]) {
          if(Invlst.containsKey(acc.id)) {
              listUpdatedinvpost.add(new Invoice__c(Id = acc.id, Last_Payment_Date__c=Invlst.get(acc.id)));
              InvlstBQ.put(acc.id , acc.Last_Payment_Date__c);  
          }
      }
      List<Brand_Quote__c> listUpdatedBQLastPaymentDate = new List<Brand_Quote__c>(); 
      
      for(Brand_Quote__c BQ :[Select id,Last_Payment_Date__c From Brand_Quote__c Where Id IN :InvlstBQ.Keyset()])  
      { 
          if(InvlstBQ.containsKey(BQ.id)) {
              listUpdatedBQLastPaymentDate.add(new Brand_Quote__c(Id = BQ.id, Last_Payment_Date__c=InvlstBQ.get(BQ.id)));
          }  
      }
      // update listUpdatedBQLastPaymentDate;
      update listUpdatedinvpost;  
  }     
    
    public static void onDeleteCreditApplied(List<Receive_Payment__c> oldReceivePayments){
        Set<String> invIds = new Set<String>();
        Id creditMemoRecordTypeId = Schema.SObjectType.Receive_Payment__c.getRecordTypeInfosByName().get(RP_RecordType_CreditCard).getRecordTypeId();
        for(Receive_Payment__c rp : oldReceivePayments){
            if(rp.RecordTypeId == creditMemoRecordTypeId){
                invIds.add(rp.Invoice__c);
                if(rp.Credit_Memo__c != null) invIds.add(rp.Credit_Memo__c);
            }
        }
        
        if(invIds.size() >0 ){
            updateInvoiceCreditMemo(invIds);
        }        
    }
    
    public static void creditAppliedCount(List<Receive_Payment__c> receivePayments,Boolean isUpdate,Map<Id, Receive_Payment__c> oldReceivePayments){
        Set<String> invIds = new Set<String>();
        Set<String> rpIds = new Set<String>();
        for(Receive_Payment__c rp : receivePayments){
            rpIds.add(rp.id);
        }
        for(Receive_Payment__c rp : [SELECT id,RecordType.Name,Invoice__c,Credit_Memo__c FROM Receive_Payment__c WHERE Id IN : rpIds]){
            system.debug('## RecordType.Name'+rp.RecordType.Name);
            if(rp.RecordType.Name == RP_RecordType_CreditCard){
                if(isUpdate){
                    if(oldReceivePayments.get(rp.Id).Invoice__c != rp.Invoice__c || oldReceivePayments.get(rp.Id).Credit_Memo__c != rp.Credit_Memo__c){
                        invIds.add(oldReceivePayments.get(rp.Id).Invoice__c);
                		if(oldReceivePayments.get(rp.Id).Invoice__c != null) invIds.add(oldReceivePayments.get(rp.Id).Invoice__c);
                    }
                }
                invIds.add(rp.Invoice__c);
                if(rp.Credit_Memo__c != null) invIds.add(rp.Credit_Memo__c);
            }
        }
        system.debug('## invIds'+invIds);
        if(invIds.size() >0 ){
            updateInvoiceCreditMemo(invIds);
        }
    }
    
    public static void updateInvoiceCreditMemo(Set<String> invIds){
        List<Invoice__c> invUpdateList = new List<Invoice__c>();
        for(Invoice__c inv : [SELECT id,Total_Payments_Received__c,(SELECT Id,Payment_Amount__c FROM Receive_Payments1__r WHERE RecordType.Name =: RP_RecordType_CreditCard) FROM Invoice__c WHERE id IN : invIds AND RecordType.Name =: Invoice_Record_Type_Credit_Memo]){
            
            if(inv.Receive_Payments1__r.size() > 0){
                inv.Total_Payments_Received__c = 0;
                for(Receive_Payment__c rp : inv.Receive_Payments1__r){
                    inv.Total_Payments_Received__c += rp.Payment_Amount__c;
                }
                invUpdateList.add(inv);
            }else{
                inv.Total_Payments_Received__c = 0;
                invUpdateList.add(inv);
            }
        }
        if(invUpdateList.size() > 0){
            update invUpdateList;
        }
    }
}