force-app/main/default/objects/Inventory_Location__c/Inventory_Location__c.object-meta.xml
<CustomObject>
    <label>Inventory Location</label>
    <nameField>
        <label>Inventory Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inventory Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Inventory_Location__c/fields/Auto_Hold__c.field-meta.xml
<CustomField>
    <fullName>Auto_Hold__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Auto Hold</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Inventory_Position__c/Inventory_Position__c.object-meta.xml
<CustomObject>
    <label>Inventory Position</label>
    <nameField>
        <displayFormat>IP-{YYYY}-{MM}-{0000000000}</displayFormat>
        <label>Inventory Position</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventory Positions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Inventory_Position__c/fields/Hold__c.field-meta.xml
<CustomField>
    <fullName>Hold__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Inventory OnHOld for Order Allocation</inlineHelpText>
    <label>Hold</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Inventory_Position__c/fields/Inventory_Hold_Reason_Code__c.field-meta.xml
<CustomField>
    <fullName>Inventory_Hold_Reason_Code__c</fullName>
    <inlineHelpText>Must select reason code when inventory is on hold</inlineHelpText>
    <label>IP Hold Reason Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Inventory_Hold_Reason_Code</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Inventory_Position__c/fields/Inventory_Location__c.field-meta.xml
<CustomField>
    <fullName>Inventory_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Inventory Location</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Inventory_Location__c.Site_Name__c</field>
            <operation>equals</operation>
            <valueField>$Source.Site__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Inventory_Location__c</referenceTo>
    <relationshipLabel>Inventory Positions</relationshipLabel>
    <relationshipName>Inventory_Positions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/InventoryLocationsTriggerHandler.cls
public class InventoryLocationsTriggerHandler {
    public static void afterInsert(List<Inventory_Location__c> invLocations){
        Set<Id> locIds = new Set<Id>();
        for(Inventory_Location__c inv : invLocations){
            if(inv.Auto_Hold__c){
                locIds.add(inv.Id);
            }
        }
        if(locIds.size() > 0) updateIPRecordsHold(locIds);
    }
    
    public static void afterUpdate(List<Inventory_Location__c> invLocations, Map<Id,Inventory_Location__c> oldMap){
        Set<Id> locIds = new Set<Id>();
        for(Inventory_Location__c inv : invLocations){
            Inventory_Location__c oldIpLoc = oldMap.get(inv.Id);
            if(inv.Auto_Hold__c && inv.Auto_Hold__c != oldIpLoc.Auto_Hold__c){
                locIds.add(inv.Id);
            }
        }
        if(locIds.size() > 0) updateIPRecordsHold(locIds);
    }
    
    public static void updateIPRecordsHold(Set<Id> invLocationsIds){
        List<Inventory_Position__c> updatesToIP = new List<Inventory_Position__c>();
        for(Inventory_Position__c invPos : [SELECT Id,Inventory_Hold_Reason_Code__c,Hold__c,Inventory_Location__c FROM Inventory_Position__c WHERE Inventory_Location__c IN : invLocationsIds]){
        	invPos.Hold__c = true;
            invPos.Inventory_Hold_Reason_Code__c = 'Not Tested';
            updatesToIP.add(invPos);	    
        }
        if(updatesToIP.size()> 0) update updatesToIP;
    }
    
}