force-app/main/default/objects/Inventory_Location__c/Inventory_Location__c.object-meta.xml
<CustomObject>
    <label>Inventory Location</label>
    <nameField>
        <label>Inventory Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inventory Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Inventory_Location__c/fields/Available_for_Allocation__c.field-meta.xml
<CustomField>
    <fullName>Available_for_Allocation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Available for Allocation?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Inventory_Location__c/fields/Available_for_Lab_Allocation__c.field-meta.xml
<CustomField>
    <fullName>Available_for_Lab_Allocation__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flag to allocate inventory for Lab Orders</description>
    <inlineHelpText>Flag to allocate inventory Only for Lab Orders</inlineHelpText>
    <label>Available for Lab Allocation?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Inventory_Location__c/fields/Default_for_Site__c.field-meta.xml
<CustomField>
    <fullName>Default_for_Site__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Default for Site</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Inventory_Location__c/fields/Site_Name__c.field-meta.xml
<CustomField>
    <fullName>Site_Name__c</fullName>
    <label>Site Name</label>
    <referenceTo>Site__c</referenceTo>
    <relationshipLabel>Inventory Locations</relationshipLabel>
    <relationshipName>Inventory_Locations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Inventory_Position__c/Inventory_Position__c.object-meta.xml
<CustomObject>
    <label>Inventory Position</label>
    <nameField>
        <displayFormat>IP-{YYYY}-{MM}-{0000000000}</displayFormat>
        <label>Inventory Position</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventory Positions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Inventory_Position__c/fields/Hold__c.field-meta.xml
<CustomField>
    <fullName>Hold__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Inventory OnHOld for Order Allocation</inlineHelpText>
    <label>Hold</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Inventory_Position__c/fields/Inventory_Location__c.field-meta.xml
<CustomField>
    <fullName>Inventory_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Inventory Location</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Inventory_Location__c.Site_Name__c</field>
            <operation>equals</operation>
            <valueField>$Source.Site__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Inventory_Location__c</referenceTo>
    <relationshipLabel>Inventory Positions</relationshipLabel>
    <relationshipName>Inventory_Positions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Inventory_Position__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Name</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Inventory Positions</relationshipLabel>
    <relationshipName>Inventory_Positions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Inventory_Position__c/fields/Qty_Allocated__c.field-meta.xml
<CustomField>
    <fullName>Qty_Allocated__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Qty Allocated</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Inventory_Position__c/fields/Qty_On_Hand__c.field-meta.xml
<CustomField>
    <fullName>Qty_On_Hand__c</fullName>
    <label>Qty On Hand</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Inventory_Position__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <formula>HYPERLINK( Sales_Order_Line__r.Sales_Order__c  , Sales_Order_Line__r.Sales_Order__r.Name)</formula>
    <label>Sales Order</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Inventory_Position__c/fields/Sales_Order_Line__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Order Line</label>
    <referenceTo>Sales_Order_Line__c</referenceTo>
    <relationshipLabel>Inventory Positions</relationshipLabel>
    <relationshipName>Inventory_Positions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Inventory_Position__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site</label>
    <referenceTo>Site__c</referenceTo>
    <relationshipLabel>Inventory Positions</relationshipLabel>
    <relationshipName>Inventory_Positions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Inventory_Position__c/fields/SO_Status__c.field-meta.xml
<CustomField>
    <fullName>SO_Status__c</fullName>
    <formula>TEXT(Sales_Order_Line__r.Sales_Order__r.SO_Status__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SO Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Picklist__c/Picklist__c.object-meta.xml
<CustomObject>
    <description>Picklist is used for Warehouse Picking from inventory Positions</description>
    <label>Picklist</label>
    <nameField>
        <displayFormat>PL-{0000000000}</displayFormat>
        <label>Picklist</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Picklists</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Picklist__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <label>Sales Order</label>
    <referenceTo>Sales_Order__c</referenceTo>
    <relationshipLabel>Picklists</relationshipLabel>
    <relationshipName>Picklists</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Picklist__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site</label>
    <referenceTo>Site__c</referenceTo>
    <relationshipLabel>Picklists</relationshipLabel>
    <relationshipName>Picklists</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Picklist__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>QA Review</fullName>
            </value>
            <value>
                <fullName>QA Confirm</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Order__c/Sales_Order__c.object-meta.xml
<CustomObject>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>SO-{0000000000}</displayFormat>
        <label>Sales Order</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Order__c/fields/Account_Hold_Exception__c.field-meta.xml
<CustomField>
    <fullName>Account_Hold_Exception__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Override Account Hold to allocate and process the order.</inlineHelpText>
    <label>Account Hold Exception</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Sales_Order__c/fields/Allocated__c.field-meta.xml
<CustomField>
    <fullName>Allocated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Allocated?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Sales_Order__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site</label>
    <referenceTo>Site__c</referenceTo>
    <relationshipLabel>Sales Orders</relationshipLabel>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Order__c/fields/SO_Status__c.field-meta.xml
<CustomField>
    <fullName>SO_Status__c</fullName>
    <label>SO Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sales_Order_Line__c/Sales_Order_Line__c.object-meta.xml
<CustomObject>
    <label>Sales Order Line</label>
    <nameField>
        <displayFormat>SOLI-{0000000000}</displayFormat>
        <label>SO Line</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Order_Line__c/fields/Balance_Qty_to_Allocate__c.field-meta.xml
<CustomField>
    <fullName>Balance_Qty_to_Allocate__c</fullName>
    <formula>IF (ISPICKVAL(Status__c, &quot;Rejected&quot;) || ISPICKVAL(Status__c, &quot;Cancelled&quot;),0,Qty_Ordered__c  -  Qty_Allocated__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Balance Qty to Allocate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sales_Order_Line__c/fields/Ownership_Code__c.field-meta.xml
<CustomField>
    <fullName>Ownership_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ownership Code</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sales Order Lines</relationshipLabel>
    <relationshipName>Sales_Order_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Order_Line__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Name</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Sales Order Lines</relationshipLabel>
    <relationshipName>Sales_Order_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Order_Line__c/fields/Qty_Allocated__c.field-meta.xml
<CustomField>
    <fullName>Qty_Allocated__c</fullName>
    <label>Qty Allocated</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sales_Order_Line__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <label>Sales Order</label>
    <referenceTo>Sales_Order__c</referenceTo>
    <relationshipLabel>Sales Order Lines</relationshipLabel>
    <relationshipName>Sales_Order_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Sales_Order_Line__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <formula>Sales_Order__r.Site__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Site</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Order_Line__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Allocated</fullName>
            </value>
            <value>
                <fullName>Partially Allocated</fullName>
            </value>
            <value>
                <fullName>Back Ordered</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Shipment Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Site__c/Site__c.object-meta.xml
<CustomObject>
    <description>All objects must have a Site Name and License Class or A or M. For separate sales and inventory record.</description>
    <label>Site</label>
    <nameField>
        <label>Site</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Site__c/fields/Warehouse_Name__c.field-meta.xml
<CustomField>
    <fullName>Warehouse_Name__c</fullName>
    <description>Name of the warehouse to display in UI. Example : Communities.</description>
    <label>Warehouse Name</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AllocationProcessforSOTest.cls
/**************************************************************************************

*******************************************************************************/
@isTest
public class AllocationProcessforSOTest {
    static Sales_Order__c objSO;
      static Sales_Order_Line__c objSO2;
    static List<Sales_Order_Line__c> soLines;
    static List<Inventory_Position__c> invPositions;
     private static String SO_RecordType;

    @TestSetUp
        static void testDataSetUp(){
            TestUtilData.skipTrigger = True;
        TestUtilData.createTestData();
            Test.setMock(HttpCalloutMock.class, new StateLicense_MockResponseTest());
    }
  
    static testMethod void AllocationProcessforSOTest(){
        Test.startTest();
           TestUtilData.skipTrigger = True;
        retrieveData();
        ApexPages.StandardController stdController = new ApexPages.StandardController(objSO);
        AllocationProcessforSO controllerObj = new AllocationProcessforSO(stdController);
        AllocationProcessforSO.AllocationProcess(objSO.Id);
        controllerObj.AllocationProcess();
       // controllerObj.AllocationProcessforSO();
        AuraResponse r = new AuraResponse('AllocationProcessforSO.AllocationProcessLight()');
       
        AllocationProcessforSO.AllocationProcessLight(objSO.Id);
      
        controllerObj.goBack();
        
        list<Sales_Order_Line__c> lstSO = [select id, Status__c from Sales_Order_Line__c]; 
        system.debug('lstSO 0 status'+lstSO[0].Status__c);
        system.debug('lstSO 1 status'+lstSO[1].Status__c);
        system.debug('lstSO 2 status'+lstSO[2].Status__c);
        
        for(Inventory_Position__c invPositionObj : invPositions){
            invPositionObj.Qty_On_Hand__c = 0.0;
            invPositionObj.Qty_Allocated__c = 20.0;
        }
        invPositions[0].Sales_Order_Line__c = soLines[0].Id;
        invPositions[1].Sales_Order_Line__c = soLines[0].Id;
        invPositions[2].Sales_Order_Line__c = soLines[1].Id;
        update invPositions;
        
        System.assertEquals(3, soLines.size());
        soLines[0].Status__c = SalesOrderSupport.SO_LINE_STATUS_ALLOCATED;
        soLines[0].Qty_Allocated__c = 40;
        soLines[1].Status__c = SalesOrderSupport.SO_LINE_STATUS_ALLOCATED;
        soLines[1].Qty_Allocated__c = 20;
        soLines[2].Status__c = SalesOrderSupport.SO_LINE_STATUS_BACK_ORDERED;
        soLines[2].Qty_Allocated__c = 0;
       // soLines[2].Ownership_Code__c = 'Test 1'
        update soLines;
        
        System.assertNOTEquals(lstSO[1].Status__c,'Draft');
      Site__c s = new Site__c();
        s.Name ='2089';
        insert s;
        Inventory_Location__c il = new Inventory_Location__c ();
		il.Name='QA Review';
        il.Site_Name__c=s.Id;
        insert il;
 
        Decimal totalQty = 0.0;
       	Inventory_Position__c iv = new Inventory_Position__c();
        iv.Inventory_Location__c=il.id;
        iv.Site__c =s.Id;
        iv.Qty_On_Hand__c=0.2;
        totalQty = totalQty + iv.Qty_On_Hand__c;
        insert iv;
        list <Inventory_Position__c> ivlst = new list <Inventory_Position__c>();
        ivlst.add(iv);
        
        
         AllocationProcessforSO.calTotalQtyinHand(ivlst);
		AllocationProcessforSO.checkValidation(objSO);
        AllocationProcessforSO.AllocationProcessLight(objSO.Id);
 		 AllocationProcessforSO.calTotalQtyAllocated(ivlst, objSO.Id); 
       
        decimal tempQtyOrderd=9;
        decimal balanceQty=9;
       
     AllocationProcessforSO.getIPsNeededtoUpdate(ivlst, tempQtyOrderd, balanceQty, null, ivlst);   
      
Test.stopTest();
    }
     static testMethod void inventoryDetailsTestopen(){
Test.startTest();
            TestUtilData.skipTrigger = True;
        retrieveData();
        ApexPages.StandardController stdController = new ApexPages.StandardController(objSO);
        AllocationProcessforSO controllerObj = new AllocationProcessforSO(stdController);
        AllocationProcessforSO.AllocationProcess(objSO.Id);
        controllerObj.AllocationProcess();
        AuraResponse r = new AuraResponse('AllocationProcessforSO.AllocationProcessLight()');
       
        AllocationProcessforSO.AllocationProcessLight(objSO.Id);
        controllerObj.goBack();
       
        list<Sales_Order_Line__c> lstSO = [select id, Status__c from Sales_Order_Line__c]; 
        system.debug('lstSO 0 status'+lstSO[0].Status__c);
        system.debug('lstSO 1 status'+lstSO[1].Status__c);
        system.debug('lstSO 2 status'+lstSO[2].Status__c);
        
        for(Inventory_Position__c invPositionObj : invPositions){
            invPositionObj.Qty_On_Hand__c = 0.0;
            invPositionObj.Qty_Allocated__c = 20.0;
        }
        invPositions[0].Sales_Order_Line__c = soLines[0].Id;
        invPositions[1].Sales_Order_Line__c = soLines[0].Id;
        invPositions[2].Sales_Order_Line__c = soLines[1].Id;
        update invPositions;
        
        System.assertEquals(3, soLines.size());
        soLines[0].Status__c = SalesOrderSupport.SO_LINE_STATUS_OPEN;
        soLines[0].Qty_Allocated__c = 40;
        soLines[1].Status__c = SalesOrderSupport.SO_LINE_STATUS_OPEN;
        soLines[1].Qty_Allocated__c = 20;
        soLines[2].Status__c = SalesOrderSupport.SO_LINE_STATUS_OPEN;
        soLines[2].Qty_Allocated__c = 0;
        update soLines;
        
        System.assertNOTEquals(lstSO[1].Status__c,'Draft');
      Site__c s = new Site__c();
        s.Name ='2089';
        insert s;
        Inventory_Location__c il = new Inventory_Location__c ();
		il.Name='QA Review';
        il.Site_Name__c=s.Id;
        insert il;
 
        Decimal totalQty = 0.0;
       	Inventory_Position__c iv = new Inventory_Position__c();
        iv.Inventory_Location__c=il.id;
        iv.Site__c =s.Id;
        iv.Qty_On_Hand__c=0.2;
        totalQty = totalQty + iv.Qty_On_Hand__c;
        insert iv;
        list <Inventory_Position__c> ivlst = new list <Inventory_Position__c>();
        ivlst.add(iv);
       
        
         AllocationProcessforSO.calTotalQtyinHand(ivlst);
		AllocationProcessforSO.checkValidation(objSO);
        AllocationProcessforSO.AllocationProcessLight(objSO.Id);
 		 AllocationProcessforSO.calTotalQtyAllocated(ivlst, objSO.Id); 
        decimal tempQtyOrderd=9;
        decimal balanceQty=9;
       
     AllocationProcessforSO.getIPsNeededtoUpdate(ivlst, tempQtyOrderd, balanceQty, null, ivlst);   
       Test.stopTest();

    }
    
     static testMethod void inventoryDetailsTestopen2(){
            TestUtilData.skipTrigger = True;
        retrieveData();
       
        Test.startTest();
        list<Sales_Order_Line__c> lstSO = [select id, Status__c from Sales_Order_Line__c]; 
        system.debug('lstSO 0 status'+lstSO[0].Status__c);
        system.debug('lstSO 1 status'+lstSO[1].Status__c);
        system.debug('lstSO 2 status'+lstSO[2].Status__c);
        
        for(Inventory_Position__c invPositionObj : invPositions){
            invPositionObj.Qty_On_Hand__c = 0.0;
            invPositionObj.Qty_Allocated__c = 20.0;
        }
        invPositions[0].Sales_Order_Line__c = soLines[0].Id;
        invPositions[1].Sales_Order_Line__c = soLines[0].Id;
        invPositions[2].Sales_Order_Line__c = soLines[1].Id;
        update invPositions;
        
        System.assertEquals(3, soLines.size());
        soLines[0].Status__c = SalesOrderSupport.SO_LINE_STATUS_OPEN;
        soLines[0].Qty_Allocated__c = 40;
        soLines[1].Status__c = SalesOrderSupport.SO_LINE_STATUS_OPEN;
        soLines[1].Qty_Allocated__c = 20;
        soLines[2].Status__c = SalesOrderSupport.SO_LINE_STATUS_OPEN;
        soLines[2].Qty_Allocated__c = 0;
        update soLines;
        
        System.assertNOTEquals(lstSO[1].Status__c,'Draft');
      Site__c s = new Site__c();
        s.Name ='2089';
        insert s;
        Inventory_Location__c il = new Inventory_Location__c ();
		il.Name='QA Review';
        il.Site_Name__c=s.Id;
        insert il;
 
        Decimal totalQty = 0.0;
       	Inventory_Position__c iv = new Inventory_Position__c();
        iv.Inventory_Location__c=il.id;
        iv.Site__c =s.Id;
        iv.Qty_On_Hand__c=0.2;
        totalQty = totalQty + iv.Qty_On_Hand__c;
        insert iv;
        list <Inventory_Position__c> ivlst = new list <Inventory_Position__c>();
        ivlst.add(iv);
        ApexPages.StandardController stdController = new ApexPages.StandardController(objSO);
        AllocationProcessforSO controllerObj = new AllocationProcessforSO(stdController);
        AllocationProcessforSO.AllocationProcess(objSO.Id);
        controllerObj.AllocationProcess();
        controllerObj.goBack();
       Test.stopTest();

    }
    
    static testMethod void inventoryDetailsTest2(){
        Test.startTest();
           TestUtilData.skipTrigger = True;
       retrieveData();
        ApexPages.StandardController stdController = new ApexPages.StandardController(objSO);
        AllocationProcessforSO controllerObj = new AllocationProcessforSO(stdController);
         AuraResponse r = new AuraResponse('AllocationProcessforSO.AllocationProcessLight()');
        AllocationProcessforSO.AllocationProcessLight(objSO.Id);
        controllerObj.AllocationProcess();
        controllerObj.goBack();
        
        list<Sales_Order_Line__c> lstSO = [select id, Status__c from Sales_Order_Line__c]; 
        system.debug('lstSO 0 status'+lstSO[0].Status__c);
        system.debug('lstSO 1 status'+lstSO[1].Status__c);
        system.debug('lstSO 2 status'+lstSO[2].Status__c);
        
        for(Inventory_Position__c invPositionObj : invPositions){
            invPositionObj.Qty_On_Hand__c = 90;
            invPositionObj.Qty_Allocated__c = 20.0;
        }
        invPositions[0].Sales_Order_Line__c = soLines[0].Id;
        invPositions[1].Sales_Order_Line__c = soLines[0].Id;
        invPositions[2].Sales_Order_Line__c = soLines[1].Id;
        update invPositions;
        
        System.assertEquals(3, soLines.size());
        soLines[0].Status__c = SalesOrderSupport.SO_LINE_STATUS_ALLOCATED;
        soLines[0].Qty_Allocated__c = 90;
        soLines[1].Status__c = SalesOrderSupport.SO_LINE_STATUS_ALLOCATED;
        soLines[1].Qty_Allocated__c = 20;
        soLines[2].Status__c = SalesOrderSupport.SO_LINE_STATUS_BACK_ORDERED;
        soLines[2].Qty_Allocated__c = 0;
        //soLines[2].Balance_Qty_to_Allocate__c = 9;
        update soLines;
        
        System.assertNOTEquals(lstSO[1].Status__c,'Draft');
      Site__c s = new Site__c();
        s.Name ='2089';
        insert s;
        Inventory_Location__c il = new Inventory_Location__c ();
		il.Name='QA Review';
        il.Site_Name__c=s.Id;
        insert il;
 
         Decimal totalQty = 0.0;
       Inventory_Position__c iv = new Inventory_Position__c();
        iv.Inventory_Location__c=il.id;
        iv.Site__c =s.Id;
        iv.Qty_On_Hand__c=90;
         totalQty = totalQty + iv.Qty_On_Hand__c;
        insert iv;
        list <Inventory_Position__c> ivlst = new list <Inventory_Position__c>();
        ivlst.add(iv);
        
        
        
        
         Id productId = soLines[2].Product_Name__c;
            // if(soli.Balance_Qty_to_Allocate__c == sumofQtyinHand){
         map<Id,List<Inventory_Position__c>> mapofIPsbyProducId = new map<Id,List<Inventory_Position__c>> ();
         Map<Id,Decimal> availableForAllocation = new Map<Id,Decimal>();
          Decimal sumofQtyinHand = availableForAllocation.get(productId); 

         AllocationProcessforSO.calTotalQtyinHand(ivlst);
		AllocationProcessforSO.checkValidation(objSO);
        AllocationProcessforSO.AllocationProcessLight(objSO.Id);
        AllocationProcessforSO.checkValidationLight(objSO);
  		AllocationProcessforSO.calTotalQtyAllocated(ivlst, objSO.Id); 
        decimal tempQtyOrderd=9;
        decimal balanceQty=90;
      
       
         Map<Id,Sales_Order_Line__c> tempSOlinesMap = new Map<Id,Sales_Order_Line__c>();
         Id productId2 = soLines[0].Product_Name__c;
          map<ID,Sales_Order_Line__c> mapofSOlinebyProductID = new map<ID,Sales_Order_Line__c>();
			//set<Id> keyId= mapofSOlinebyProductID.Keyset();
                    Sales_Order_Line__c soli = mapofSOlinebyProductID.get(productId);
                     tempSOlinesMap.put(soLines[0].id,new Sales_Order_Line__c(id = soLines[0].id, 
                                                                              Status__c = 'Back Ordered', 
                                                                              Qty_Allocated__c = 0));
                update tempSOlinesMap.values();
     AllocationProcessforSO.getIPsNeededtoUpdate(ivlst, tempQtyOrderd, balanceQty, null, ivlst);   
          Decimal totalQtyAllocated =  AllocationProcessforSO.calTotalQtyAllocated(ivlst, objSO.Id); 
        Test.stopTest();

    }
    // Test allocation process for confirmed picklist
    static testMethod void testAllocationProcess_ForConfirmedPicklist(){
           TestUtilData.skipTrigger = True;
        // Get data created from setup
        retrieveData();
        
        // Create confirmed Picklist
        Picklist__c picklistObj = new Picklist__c();
        picklistObj.Sales_Order__c = objSO.Id;
        picklistObj.Site__c = objSO.Site__c;
        picklistObj.Status__c = 'Confirmed';
        insert picklistObj;
        
        List<Account> lstAcc = [SELECT Id,Hold__c from Account LIMIT 10];
        for(Account acc : lstAcc){
        	acc.Hold__c = true;  
        }
        update lstAcc;
        
        List<Sales_Order__c> sOrder = [SELECT Id,Account_Hold_Exception__c from Sales_Order__c LIMIT 10];
        for(Sales_Order__c so : sOrder){
        	so.Account_Hold_Exception__c = false;
            //so.Allocated__c = true;
        }
        update sOrder;
        
        Site__c objSite = new Site__c();
        objSite.Name = 'Test Site';
        objSite.Warehouse_Name__c='TestWarehouse1';
        insert objSite;
        
        List<Inventory_Location__c> inventoryLocations1 = new List<Inventory_Location__c>();
        Inventory_Location__c receivingInventoryLocation = new Inventory_Location__c();
        receivingInventoryLocation.Name = Label.Default_Inventory_Location;
        receivingInventoryLocation.Site_Name__c = objSite.id;
        receivingInventoryLocation.Default_for_Site__c = true;
        inventoryLocations1.add(receivingInventoryLocation);
        
        // New Test inventory location
        Inventory_Location__c newInventoryLocation = new Inventory_Location__c();
        newInventoryLocation.Name = 'Test Location';
        newInventoryLocation.Site_Name__c = objSite.id;
        inventoryLocations1.add(newInventoryLocation);

        insert inventoryLocations1;
        
        //System.assertEquals(3, invPositions.size(), 'Inventory positions size mis-match');
        
        // One SO line is related with two inventory position 
        // last SO line is not related with any inventory position
        for(Inventory_Position__c invPositionObj : invPositions){
            invPositionObj.Qty_On_Hand__c = 0.0;
            invPositionObj.Qty_Allocated__c = 20.0;
        }
        invPositions[0].Sales_Order_Line__c = soLines[0].Id;
        invPositions[1].Sales_Order_Line__c = soLines[0].Id;
        invPositions[2].Sales_Order_Line__c = soLines[1].Id;
        update invPositions;
        
        System.assertEquals(3, soLines.size());
        soLines[0].Status__c = SalesOrderSupport.SO_LINE_STATUS_ALLOCATED;
        soLines[0].Qty_Allocated__c = 40;
        soLines[1].Status__c = SalesOrderSupport.SO_LINE_STATUS_ALLOCATED;
        soLines[1].Qty_Allocated__c = 20;
        soLines[2].Status__c = SalesOrderSupport.SO_LINE_STATUS_BACK_ORDERED;
        soLines[2].Qty_Allocated__c = 0;
        update soLines;
        
        ApexPages.StandardController stdController = new ApexPages.StandardController(objSO);
        AllocationProcessforSO controllerObj = new AllocationProcessforSO(stdController);
        PageReference pageRef = controllerObj.AllocationProcess();
         AuraResponse r = new AuraResponse('AllocationProcessforSO.AllocationProcessLight()');
        AllocationProcessforSO.AllocationProcessLight(objSO.Id);
        System.assertEquals(null, pageRef, 'Page reference mis-match');
      //  AllocationProcessforSO.AllocationProcess(soid)
        // Verify validation messages
        List<ApexPages.Message> msgList = ApexPages.getMessages();
        System.assertEquals(1, msgList.size(), 'Number of Validation messages mis-match');
        //System.assert(msgList[0].getDetail().contains(Label.No_Allocation_For_Cancelled_SO), 'Validation message mis-match');
    }
    
    // Retrieve data created from data setup
    public static void retrieveData(){
        // TestUtilData.createTestData();
        objSO = new Sales_Order__c();
        objSO = [Select Id, SO_Status__c, Site__c from Sales_Order__c];
       // objSO.Site__c =
        system.debug('objSO'+objSO);
        
        List<Inventory_Location__c> inventoryLocations = [select Available_for_Allocation__c, Default_for_Site__c from Inventory_Location__c];
        
        for(Inventory_Location__c invLocationObj : inventoryLocations){
            invLocationObj.Default_for_Site__c =false;
            invLocationObj.Available_for_Allocation__c = true;
           invLocationObj.Available_for_Lab_Allocation__c = true;
            
        }
        update inventoryLocations;
        
        List<Inventory_Position__c> inventorypossitions = [select id, Qty_On_Hand__c from Inventory_Position__c];
        inventorypossitions[1].Qty_On_Hand__c = 90;
        inventorypossitions[2].Qty_On_Hand__c = 90;
        
        update inventorypossitions;
        
        
        invPositions = [Select Qty_On_Hand__c,
                               Qty_Allocated__c,
                               Sales_Order_Line__c
                               From Inventory_Position__c];
        soLines = new List<Sales_Order_Line__c>();
        soLines = [Select Status__c,Product_Name__c, Qty_Allocated__c From Sales_Order_Line__c];
     
       
    }

}