force-app/main/default/objects/Inventory_Location__c/Inventory_Location__c.object-meta.xml
<CustomObject>
    <label>Inventory Location</label>
    <nameField>
        <label>Inventory Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inventory Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Inventory_Location__c/fields/Available_for_Allocation__c.field-meta.xml
<CustomField>
    <fullName>Available_for_Allocation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Available for Allocation?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Inventory_Location__c/fields/Default_for_Site__c.field-meta.xml
<CustomField>
    <fullName>Default_for_Site__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Default for Site</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Inventory_Position__c/Inventory_Position__c.object-meta.xml
<CustomObject>
    <label>Inventory Position</label>
    <nameField>
        <displayFormat>IP-{YYYY}-{MM}-{0000000000}</displayFormat>
        <label>Inventory Position</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventory Positions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Inventory_Position__c/fields/Inventory_Location__c.field-meta.xml
<CustomField>
    <fullName>Inventory_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Inventory Location</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Inventory_Location__c.Site_Name__c</field>
            <operation>equals</operation>
            <valueField>$Source.Site__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Inventory_Location__c</referenceTo>
    <relationshipLabel>Inventory Positions</relationshipLabel>
    <relationshipName>Inventory_Positions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Inventory_Position__c/fields/Qty_On_Hand__c.field-meta.xml
<CustomField>
    <fullName>Qty_On_Hand__c</fullName>
    <label>Qty On Hand</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Inventory_Position__c/fields/Sales_Order_Line__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Order Line</label>
    <referenceTo>Sales_Order_Line__c</referenceTo>
    <relationshipLabel>Inventory Positions</relationshipLabel>
    <relationshipName>Inventory_Positions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Order_Line__c/Sales_Order_Line__c.object-meta.xml
<CustomObject>
    <label>Sales Order Line</label>
    <nameField>
        <displayFormat>SOLI-{0000000000}</displayFormat>
        <label>SO Line</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Order_Line__c/fields/Balance_Qty_to_Allocate__c.field-meta.xml
<CustomField>
    <fullName>Balance_Qty_to_Allocate__c</fullName>
    <formula>IF (ISPICKVAL(Status__c, &quot;Rejected&quot;) || ISPICKVAL(Status__c, &quot;Cancelled&quot;),0,Qty_Ordered__c  -  Qty_Allocated__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Balance Qty to Allocate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sales_Order_Line__c/fields/Qty_Ordered__c.field-meta.xml
<CustomField>
    <fullName>Qty_Ordered__c</fullName>
    <inlineHelpText>Qty per Case (MOQ) * Order Qty (Cases).</inlineHelpText>
    <label>Qty Ordered</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sales_Order_Line__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Allocated</fullName>
            </value>
            <value>
                <fullName>Partially Allocated</fullName>
            </value>
            <value>
                <fullName>Back Ordered</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Shipment Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AllocationProcessforSOLITest.cls
@isTest
public class AllocationProcessforSOLITest {
    static Sales_Order_Line__c objSOLI;
    
    
    @TestSetUp
    static void testDataSetUp(){
        TestUtilData.createTestData();
    }
    
    static testMethod void allocationTest(){
        objSOLI = new Sales_Order_Line__c();
        objSOLI = [Select Id, Status__c, Balance_Qty_to_Allocate__c  from Sales_Order_Line__c LIMIT 1];
        objSOLI.Status__c = 'Open';
        objSOLI.Qty_Ordered__c = 1;
        update objSOLI;
        //system.debug('objSO'+objSO);
        List<Inventory_Location__c> inventoryLocations = [select Available_for_Allocation__c, Default_for_Site__c from Inventory_Location__c];
        
        for(Inventory_Location__c invLocationObj : inventoryLocations){
            invLocationObj.Default_for_Site__c =false;
            invLocationObj.Available_for_Allocation__c = true;
        }
        update inventoryLocations;
        
        List<Inventory_Position__c> inventorypossitions = [select id, Qty_On_Hand__c from Inventory_Position__c];
        inventorypossitions[1].Qty_On_Hand__c = 1;
        inventorypossitions[2].Qty_On_Hand__c = 4;
        
        update inventorypossitions;
        ApexPages.StandardController stdController = new ApexPages.StandardController(objSOLI);
        AllocationProcessforSOLICtlr controllerObj = new AllocationProcessforSOLICtlr(stdController);
        controllerObj.AllocationProcess();
        controllerObj.goBack();
        list<Sales_Order_Line__c> lstSO = [select id, Status__c from Sales_Order_Line__c];
        System.assertNOTEquals(lstSO[1].Status__c,'Draft');
    }
    
    static testMethod void allocationTest1(){
        objSOLI = new Sales_Order_Line__c();
        objSOLI = [Select Id, Status__c, Balance_Qty_to_Allocate__c  from Sales_Order_Line__c LIMIT 1];
        objSOLI.Status__c = 'Open';
        update objSOLI;
        //system.debug('objSO'+objSO);
        List<Inventory_Location__c> inventoryLocations = [select Available_for_Allocation__c, Default_for_Site__c from Inventory_Location__c];
        
        for(Inventory_Location__c invLocationObj : inventoryLocations){
            invLocationObj.Default_for_Site__c =false;
            invLocationObj.Available_for_Allocation__c = true;
        }
        update inventoryLocations;
        
        List<Inventory_Position__c> inventorypossitions = [select id, Qty_On_Hand__c from Inventory_Position__c];
        inventorypossitions[1].Qty_On_Hand__c = 5;
        inventorypossitions[2].Qty_On_Hand__c = 5;
        
        update inventorypossitions;
        ApexPages.StandardController stdController = new ApexPages.StandardController(objSOLI);
        AllocationProcessforSOLICtlr controllerObj = new AllocationProcessforSOLICtlr(stdController);
        controllerObj.AllocationProcess();
        controllerObj.goBack();
        list<Sales_Order_Line__c> lstSO = [select id, Status__c from Sales_Order_Line__c];
        System.assertNOTEquals(lstSO[1].Status__c,'Draft');
    }
    
    static testMethod void allocationTest2(){
        objSOLI = new Sales_Order_Line__c();
        objSOLI = [Select Id, Status__c, Balance_Qty_to_Allocate__c  from Sales_Order_Line__c LIMIT 1];
        objSOLI.Status__c = 'Open';
        objSOLI.Qty_Ordered__c = 5;
        update objSOLI;
        //system.debug('objSO'+objSO);
        List<Inventory_Location__c> inventoryLocations = [select Available_for_Allocation__c, Default_for_Site__c from Inventory_Location__c];
        
        for(Inventory_Location__c invLocationObj : inventoryLocations){
            invLocationObj.Default_for_Site__c =false;
            invLocationObj.Available_for_Allocation__c = true;
        }
        update inventoryLocations;
        
        List<Inventory_Position__c> inventorypossitions = [select id, Qty_On_Hand__c from Inventory_Position__c];
        inventorypossitions[1].Qty_On_Hand__c = 11;
        inventorypossitions[2].Qty_On_Hand__c = 4;
        
        update inventorypossitions;
        
        ApexPages.StandardController stdController = new ApexPages.StandardController(objSOLI);
        AllocationProcessforSOLICtlr controllerObj = new AllocationProcessforSOLICtlr(stdController);
        controllerObj.AllocationProcess();
        controllerObj.goBack();
        list<Sales_Order_Line__c> lstSO = [select id, Status__c from Sales_Order_Line__c];
        System.assertNOTEquals(lstSO[1].Status__c,'Draft');
    }
    
}