force-app/main/default/objects/Line_Card__c/Line_Card__c.object-meta.xml
<CustomObject>
    <description>Junction Object of Named Accounts of Retailers and Brand&apos;s Have Sold Into or Bought From.</description>
    <label>Line Card</label>
    <nameField>
        <displayFormat>LC-{YYYY}-{MM}-{00000}</displayFormat>
        <label>Line Card</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Line Cards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Line_Card__c/fields/Brand_Name__c.field-meta.xml
<CustomField>
    <fullName>Brand_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Brand Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Retail Line Card</relationshipLabel>
    <relationshipName>Line_Cards</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Line_Card__c/fields/Retailer_Name__c.field-meta.xml
<CustomField>
    <fullName>Retailer_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Retailer Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Brand Line Card</relationshipLabel>
    <relationshipName>Line_Cards1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Line_Card__c/fields/Unique_Line_Card_Helper__c.field-meta.xml
<CustomField>
    <fullName>Unique_Line_Card_Helper__c</fullName>
    <label>Unique Line Card Helper</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Line_Card__c/recordTypes/Brand.recordType-meta.xml
<RecordType>
    <fullName>Brand</fullName>
    <active>true</active>
    <label>Brand</label>
</RecordType>

force-app/main/default/classes/LineCardTriggerHelper.cls
public class LineCardTriggerHelper {
    public static void dupicateLineCardCheck(List<Line_Card__c>newList,Map<Id,Line_Card__c> oldMap){
        Set<String> uniqueLCSet = new Set<String>();
        Set<Id> LCIds = new Set<Id>();
        for(Line_Card__c LC: newList){
            if(LC.Brand_Name__c != null && LC.Retailer_Name__c != null && (Trigger.isInsert || 
                (Trigger.isUpdate &&(LC.Brand_Name__c != oldMap.get(LC.Id).Brand_Name__c || 
                LC.Retailer_Name__c != oldMap.get(LC.Id).Retailer_Name__c)))){
                	String uniqueKey = LC.Brand_Name__c +''+ LC.Retailer_Name__c;
                    //LC.Unique_Line_Card_Helper__c = uniqueKey;
                    if(uniqueLCSet.contains(uniqueKey)){
                        //LC.addError('Duplicate Linecard with same Brand Name and Retailer Name.');
                        LC.addError('Duplicate Line card between Brand and Retailer.');

                    } else{
                        uniqueLCSet.add(uniqueKey);
                    }   
                    if(Trigger.isUpdate){
                        LCIds.add(LC.Id);
                    }
            }
        }
        if(!uniqueLCSet.isEmpty()){
            Set<String> existingUniqueLCs = new Set<String>();
            for(Line_Card__c LC: [SELECT Id, Name, Brand_Name__c, Retailer_Name__c, Unique_Line_Card_Helper__c FROM Line_Card__c WHERE Unique_Line_Card_Helper__c IN :uniqueLCSet AND Id NOT IN : LCIds]){
                existingUniqueLCs.add(LC.Unique_Line_Card_Helper__c);
            }
            System.debug('##existingUniqueLCs::'+existingUniqueLCs);
            for(Line_Card__c LC: newList){
                if(existingUniqueLCs.contains(LC.Brand_Name__c +''+ LC.Retailer_Name__c)){
                    LC.addError('Duplicate Line card between Brand and Retailer.');
                }
            }
        }
    }
}