force-app/main/default/objects/Shipping_Manifest__c/Shipping_Manifest__c.object-meta.xml
<CustomObject>
    <description>Used in the generation of compliance document to enable retail delivery.</description>
    <label>Shipping Manifest</label>
    <nameField>
        <displayFormat>SM-{YYYY}-{MM}-{0000000000}</displayFormat>
        <label>Shipping Manifest</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipping Manifests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Shipping_Manifest__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
            <value>
                <fullName>Shipment Pending</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Pending Delivery</fullName>
            </value>
            <value>
                <fullName>Shipment Complete</fullName>
            </value>
            <value>
                <fullName>In-Transit</fullName>
            </value>
            <value>
                <fullName>Received</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
                <isActive>false</isActive>
                <label>Submitted</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Shipping_Manifest__c/recordTypes/RSM.recordType-meta.xml
<RecordType>
    <fullName>RSM</fullName>
    <active>true</active>
    <description>Used for Retail Shipments - Ship Confirm to &quot;Delivered&quot; Inventory Location, Rename to &quot;Retail&quot;</description>
    <label>RSM</label>
</RecordType>

force-app/main/default/objects/Shipping_Manifest_Line__c/Shipping_Manifest_Line__c.object-meta.xml
<CustomObject>
    <label>Shipping Manifest Line</label>
    <nameField>
        <displayFormat>SML-{0000000000}</displayFormat>
        <label>SM Line</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipping Manifest Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Shipping_Manifest_Line__c/fields/Shipping_Manifest__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Manifest__c</fullName>
    <label>Shipping Manifest</label>
    <referenceTo>Shipping_Manifest__c</referenceTo>
    <relationshipLabel>Shipping Manifest Lines</relationshipLabel>
    <relationshipName>Shipping_Manifest_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Shipping_Manifest_Line__c/fields/SMLine_Status__c.field-meta.xml
<CustomField>
    <fullName>SMLine_Status__c</fullName>
    <label>SMLine Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Shipment Complete</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CancelRSMLineController.cls
/**
 * Copyright (c) 2018 Filigreen Distro
 * All rights reserved.
 * CancelRSMLineController
 */
public class CancelRSMLineController{

    private ApexPages.StandardController stdController;
    private Shipping_Manifest_Line__c rsmLineObj = null;
    
    private static final String STATUS_Cancelled = RSMSupport.STATUS_Cancelled; 
    private static final String STATUS_SHIPMENT_COMPLETE = RSMSupport.STATUS_SHIPMENT_COMPLETE; 
    
    // Constructor
    public CancelRSMLineController(ApexPages.StandardController controller) {
        this.stdController = controller;
        rsmLineObj = (Shipping_Manifest_Line__c)stdController.getRecord();
    }
    
    public class UserException extends Exception{ }
    
    /**
     * Change Status of RSMLine status update inventory location of inventory position to receiving inspection
     *
     * @return PageReference of RSMLine detail page
     */
    public PageReference cancelRSMLine() {
        PageReference pageRef = null;
        Savepoint savePoint;
        
        try {
            
            // Define save point for rollback
            savePoint = Database.setSavepoint();
            
            rsmLineObj = RSMSupport.retrieveRSMLine(rsmLineObj.Id);
            
            // Check validation if RSMLine status is not Received
            if(rsmLineObj.SMLine_Status__c == STATUS_Cancelled){
                ApexPages.Message msg = new ApexPages.Message(ApexPages.Severity.WARNING,
                                                              Label.Already_RSMLine_Cancelled);
                ApexPages.addMessage(msg);
                return null;
            } else if(rsmLineObj.Shipping_Manifest__r.Status__c == STATUS_SHIPMENT_COMPLETE){
                ApexPages.Message msg = new ApexPages.Message(ApexPages.Severity.WARNING,
                                                              Label.Cannot_Cancel_RSMLine);
                ApexPages.addMessage(msg);
                return null;
            }
            
            updateRSMLine();
        } 
        catch (Exception ex){
            Database.rollback(savePoint);
            ErrorLogs.log('CancelRSMLineController:cancelRSMLine()', 
                          ex.getStackTraceString(), ex.getMessage());
            ApexPages.Message msg = new ApexPages.Message(ApexPages.Severity.ERROR,ex.getMessage());
            ApexPages.addMessage(msg);
            return null;
        }
        return redirectToRSMLine();
    }

    /**
     * Change Status to RSMLine status, Actual Departure time of RSMLine
     */         
    public void updateRSMLine() {        
        rsmLineObj.SMLine_Status__c = STATUS_Cancelled;        
        update rsmLineObj;

        // Check if all RSM Lines related to RSM are cancelled or not. 
        // If cancelled then update RSM header as cancelled
        Shipping_Manifest__c rsmObj = RSMSupport.retrieveRSM(rsmLineObj.Shipping_Manifest__c);
        Boolean allCancelledRSMLine = true;
        if(rsmObj.Shipping_Manifest_Lines__r != null){
            for(Shipping_Manifest_Line__c smLine : rsmObj.Shipping_Manifest_Lines__r){
                if(smLine.SMLine_Status__c != STATUS_Cancelled){
                    allCancelledRSMLine = false;
                    break;
                }
            }
            if(allCancelledRSMLine){
                rsmObj.Status__c = STATUS_Cancelled;        
                update rsmObj;
            }
        }
        RSMSupport.updateInvPositionsAndSOLines(new List<Shipping_Manifest_Line__c>{rsmLineObj}, allCancelledRSMLine);
    }
    
    /**
     * Redirect to RSMLine detail page
     *
     * @return PageReference
     */         
    public PageReference redirectToRSMLine() {
        PageReference pageRef = stdController.view().setRedirect(true);
        return pageRef;
    }
}