force-app/main/default/objects/Shipping_Manifest__c/Shipping_Manifest__c.object-meta.xml
<CustomObject>
    <description>Used in the generation of compliance document to enable retail delivery.</description>
    <label>Shipping Manifest</label>
    <nameField>
        <displayFormat>SM-{YYYY}-{MM}-{0000000000}</displayFormat>
        <label>Shipping Manifest</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipping Manifests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Shipping_Manifest__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
            <value>
                <fullName>Shipment Pending</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Pending Delivery</fullName>
            </value>
            <value>
                <fullName>Shipment Complete</fullName>
            </value>
            <value>
                <fullName>In-Transit</fullName>
            </value>
            <value>
                <fullName>Received</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
                <isActive>false</isActive>
                <label>Submitted</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TSMSupport.cls
/**
 * Copyright (c) 2018 Filigreen Distro
 * All rights reserved.
 * TSMSupport
 */
public class TSMSupport{
    public static final string STATUS_RECEIVED = 'Received';
    public static final string STATUS_IN_TRASIT = 'In-Transit';
    
    /**
     * Change Status to TSM status, Actual Departure time of TSM
     * @param tsmList The list of TSMs to departConfirmTSM
     *
     * @return Updated TSM list
     */         
    public static List<Shipping_Manifest__c> departConfirmTSMs(List<Shipping_Manifest__c> tsmList) {
        for(Shipping_Manifest__c tsmObj : tsmList){
            tsmObj.Status__c = STATUS_IN_TRASIT;
            tsmObj.Actual_Departure_Date_Time__c = System.now();
        }
        return tsmList;
    }
}