force-app/main/default/objects/Company_Custom_Settings__c/Company_Custom_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Company Custom Settings</label>
</CustomObject>

force-app/main/default/objects/Company_Custom_Settings__c/fields/Driver_License_Expire_N1_Days_Notice__c.field-meta.xml
<CustomField>
    <fullName>Driver_License_Expire_N1_Days_Notice__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Driver License Expire N1 Days Notice</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Company_Custom_Settings__c/fields/Driver_License_Expire_N2_Days_Notice__c.field-meta.xml
<CustomField>
    <fullName>Driver_License_Expire_N2_Days_Notice__c</fullName>
    <defaultValue>15</defaultValue>
    <label>Driver License Expire N2 Days Notice</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Drivers__c/Drivers__c.object-meta.xml
<CustomObject>
    <label>Driver</label>
    <nameField>
        <label>Driver Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Drivers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Drivers__c/fields/Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiration_Date__c</fullName>
    <label>Expiration Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Drivers__c/fields/Notified_Before_N2_Days_License_Expire__c.field-meta.xml
<CustomField>
    <fullName>Notified_Before_N2_Days_License_Expire__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Notified Before N2 Days License Expire</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/DriverLicenseExpireNotificationBatchTest.cls
@isTest
public class DriverLicenseExpireNotificationBatchTest {
    @isTest
    public static void testDriverExpiration(){
        Test.startTest();
        Database.executeBatch(new DriverLicenseExpireNotificationBatch());
        Test.stopTest();
    }
    
    @TestSetUp
    static void testDataSetUp(){
        TestUtilData.createTestData();
        Drivers__c objDriver =TestUtilData.createDriver(false);
        objDriver.Expiration_Date__c = System.Today() + 7;
        objDriver.Notified_Before_N2_Days_License_Expire__c = false;
        insert objDriver;
        Company_Custom_Settings__c ccsObj = new Company_Custom_Settings__c();
        ccsObj.Driver_License_Expire_N1_Days_Notice__c = 15;
        ccsObj.Driver_License_Expire_N2_Days_Notice__c = 7;
        insert ccsObj;
    }
}