force-app/main/default/objects/Company_Custom_Settings__c/Company_Custom_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Company Custom Settings</label>
</CustomObject>

force-app/main/default/objects/Company_Custom_Settings__c/fields/Default_Distributor__c.field-meta.xml
<CustomField>
    <fullName>Default_Distributor__c</fullName>
    <description>Default distributor ID used in BQ</description>
    <inlineHelpText>Default distributor ID used in BQ</inlineHelpText>
    <label>Default Distributor</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Company_Custom_Settings__c/fields/Default_License__c.field-meta.xml
<CustomField>
    <fullName>Default_License__c</fullName>
    <description>Default state license ID used in BQ</description>
    <inlineHelpText>Default state license ID used in BQ</inlineHelpText>
    <label>Default License</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Company_Custom_Settings__c/fields/Driver_License_Expire_N1_Days_Notice__c.field-meta.xml
<CustomField>
    <fullName>Driver_License_Expire_N1_Days_Notice__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Driver License Expire N1 Days Notice</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Company_Custom_Settings__c/fields/Driver_License_Expire_N2_Days_Notice__c.field-meta.xml
<CustomField>
    <fullName>Driver_License_Expire_N2_Days_Notice__c</fullName>
    <defaultValue>15</defaultValue>
    <label>Driver License Expire N2 Days Notice</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Company_Custom_Settings__c/fields/LateFee__c.field-meta.xml
<CustomField>
    <fullName>LateFee__c</fullName>
    <label>Late Fee %</label>
    <precision>4</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Company_Custom_Settings__c/fields/Route_Destination_Address__c.field-meta.xml
<CustomField>
    <fullName>Route_Destination_Address__c</fullName>
    <description>Used in Google route calculation</description>
    <label>Route Destination Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Company_Custom_Settings__c/fields/Route_Origin_Address__c.field-meta.xml
<CustomField>
    <fullName>Route_Origin_Address__c</fullName>
    <label>Route Origin Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/Purchase_Order__c.object-meta.xml
<CustomObject>
    <label>Purchase Order</label>
    <nameField>
        <displayFormat>PO-{0000000000}</displayFormat>
        <label>Purchase Order</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Purchase_Order__c/fields/Distributor_Name__c.field-meta.xml
<CustomField>
    <fullName>Distributor_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Distributor Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Purchase Orders as Distributor</relationshipLabel>
    <relationshipName>Purchase_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/fields/Ownership__c.field-meta.xml
<CustomField>
    <fullName>Ownership__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ownership</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Purchase Orders as Ownership</relationshipLabel>
    <relationshipName>Purchase_Orders3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/fields/PO_Status__c.field-meta.xml
<CustomField>
    <fullName>PO_Status__c</fullName>
    <label>PO Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Partially Received</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site</label>
    <referenceTo>Site__c</referenceTo>
    <relationshipLabel>Purchase Orders</relationshipLabel>
    <relationshipName>Purchase_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/fields/Supplier_License__c.field-meta.xml
<CustomField>
    <fullName>Supplier_License__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Supplier License</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>State_Licenses__c.State_License_Holder__c</field>
            <operation>equals</operation>
            <valueField>$Source.Supplier_Name__c</valueField>
        </filterItems>
        <filterItems>
            <field>State_Licenses__c.License_Name__c</field>
            <operation>equals</operation>
            <valueField>$Source.Supplier_Name__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>State_Licenses__c</referenceTo>
    <relationshipLabel>Purchase Orders</relationshipLabel>
    <relationshipName>Purchase_Orders2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/fields/Supplier_Name__c.field-meta.xml
<CustomField>
    <fullName>Supplier_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Supplier Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Purchase Orders as Supplier</relationshipLabel>
    <relationshipName>Purchase_Orders2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Site__c/Site__c.object-meta.xml
<CustomObject>
    <description>All objects must have a Site Name and License Class or A or M. For separate sales and inventory record.</description>
    <label>Site</label>
    <nameField>
        <label>Site</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Site__c/fields/License_Class__c.field-meta.xml
<CustomField>
    <fullName>License_Class__c</fullName>
    <formula>TEXT(License_ID__r.License_Class__c)</formula>
    <label>License Class</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site__c/fields/License_Name__c.field-meta.xml
<CustomField>
    <fullName>License_Name__c</fullName>
    <formula>License_ID__r.License_Name__r.Name</formula>
    <label>License Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site__c/fields/License_Number__c.field-meta.xml
<CustomField>
    <fullName>License_Number__c</fullName>
    <formula>License_ID__r.License_Number__c</formula>
    <label>License Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/State_Licenses__c/State_Licenses__c.object-meta.xml
<CustomObject>
    <description>Object within the Account to track number of license and address as part of ship to.</description>
    <label>State License</label>
    <nameField>
        <displayFormat>SLID-{YYYY}-{MM}-{0000000000}</displayFormat>
        <label>License</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>State Licenses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/State_Licenses__c/fields/Default_Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Default_Warehouse__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Default Warehouse</label>
    <referenceTo>Site__c</referenceTo>
    <relationshipLabel>State Licenses</relationshipLabel>
    <relationshipName>State_Licenses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/State_Licenses__c/fields/License_Address__c.field-meta.xml
<CustomField>
    <fullName>License_Address__c</fullName>
    <label>License Address</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/State_Licenses__c/fields/License_City__c.field-meta.xml
<CustomField>
    <fullName>License_City__c</fullName>
    <label>License City</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Delivery_Cities</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/State_Licenses__c/fields/License_Class__c.field-meta.xml
<CustomField>
    <fullName>License_Class__c</fullName>
    <inlineHelpText>License Classification:
Adult Use = A-License
Medicinal Use = M-License</inlineHelpText>
    <label>License Class</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A-License</fullName>
            </value>
            <value>
                <fullName>M-License</fullName>
            </value>
            <value>
                <fullName>AM-License</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/State_Licenses__c/fields/License_Country__c.field-meta.xml
<CustomField>
    <fullName>License_Country__c</fullName>
    <label>License Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>US</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/State_Licenses__c/fields/License_Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>License_Expiration_Date__c</fullName>
    <inlineHelpText>License Expiration Date</inlineHelpText>
    <label>License Expiration Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/State_Licenses__c/fields/License_Name__c.field-meta.xml
<CustomField>
    <fullName>License_Name__c</fullName>
    <label>License Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>State Licenses</relationshipLabel>
    <relationshipName>State_Licenses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/State_Licenses__c/fields/License_Number__c.field-meta.xml
<CustomField>
    <fullName>License_Number__c</fullName>
    <inlineHelpText>State License Number</inlineHelpText>
    <label>License Number</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/State_Licenses__c/fields/License_State__c.field-meta.xml
<CustomField>
    <fullName>License_State__c</fullName>
    <label>License State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>States</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/State_Licenses__c/fields/License_Status__c.field-meta.xml
<CustomField>
    <fullName>License_Status__c</fullName>
    <inlineHelpText>License Status from State</inlineHelpText>
    <label>License Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
            <value>
                <fullName>Revoked</fullName>
            </value>
            <value>
                <fullName>Terminated</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/State_Licenses__c/fields/License_Type__c.field-meta.xml
<CustomField>
    <fullName>License_Type__c</fullName>
    <label>License Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>License_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/State_Licenses__c/fields/License_Zip__c.field-meta.xml
<CustomField>
    <fullName>License_Zip__c</fullName>
    <label>License Zip</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/State_Licenses__c/fields/Total_Miles__c.field-meta.xml
<CustomField>
    <fullName>Total_Miles__c</fullName>
    <defaultValue>0.00</defaultValue>
    <description>Total driving distance between default warehouse and licensee address</description>
    <inlineHelpText>Total driving distance between default warehouse and licensee address</inlineHelpText>
    <label>Total Miles</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/poSnapshotControllerTest.cls
@isTest
public class poSnapshotControllerTest {
    
  static testMethod void testShipConfirmRSM() {
       test.startTest();
        TestUtilData.skipTrigger = true;
        Test.setMock(HttpCalloutMock.class, new StateLicense_MockResponseTest());
        Google_Distance_Matrix_API__c[] GDMIs = new Google_Distance_Matrix_API__c[]{new Google_Distance_Matrix_API__c(Name='GMaps_Endpoint',Value__c = 'https://maps.googleapis.com/maps/api/distancematrix/json?'),new Google_Distance_Matrix_API__c(Name='Gmaps_APIKey',Value__c = 'gjhghj3232342jkhj')};
            insert GDMIs;
         TestUtilData.createTestData();
        Site__c s =[SELECT Id From Site__c Limit 1];
        Account acc =[SELECT Id From Account WHERE Name=:'Test Account1' Limit 1];
        
       /* State_Licenses__c sl = new State_Licenses__c();
        sl.License_Name__c = acc.Id;
        sl.License_Class__c = 'A-License';
        sl.License_Type__c = 'Type 11';
        sl.License_Number__c = 'A11-18-0000054-TEMP';
        sl.License_Status__c = 'Active';
        sl.License_Expiration_Date__c = System.today().addDays(60);
        sl.License_Address__c = '44650 101 Hwy N, Suite F';
        sl.License_City__c = 'Lafayette';
        sl.License_State__c = 'California';
        sl.License_Zip__c = '95454';
        sl.License_Country__c = 'US';
        sl.Default_Warehouse__c = s.Id;
        sl.Total_Miles__c=1;
        insert sl; */
        
        //Company_Custom_Settings__c ccs = new Company_Custom_Settings__c (Driver_License_Expire_N2_Days_Notice__c=2,Driver_License_Expire_N1_Days_Notice__c=2,Default_Distributor__c  = acc.Id,Default_License__c = sl.Id,LateFee__c = 0.020,Route_Origin_Address__c = '2089 Ingalls St. Unit 3 San Francisco, CA 94124 US',Route_Destination_Address__c = '2089 Ingalls St. Unit 3 San Francisco, CA 94124 US');
        //insert ccs;
        Purchase_Order__c  po = [Select Id,PO_Status__c,Site__c,Ownership__c,Supplier_Name__c,Supplier_License__c,Distributor_Name__c
                                 ,Distributor_License__c,Receiver_Name__c,Receiver_License__c from Purchase_Order__c LIMIT 1];
        po.PO_Status__c='Closed';
        po.Total_Weight_Fee__c =1;
        po.Goods_Receipt_Date__c=system.today();
        update po;
        poSnapshotController.runPOSnapshot(po.Id);
      	Database.executeBatch(new batchToRunPoSnapshot());
        
        Test.stopTest();
    }
}