force-app/main/default/objects/Bank_Register__c/Bank_Register__c.object-meta.xml
<CustomObject>
    <label>Bank Register</label>
    <nameField>
        <label>Bank Register</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bank Registers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Bank_Register__c/fields/Old_Balance__c.field-meta.xml
<CustomField>
    <fullName>Old_Balance__c</fullName>
    <label>Old Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Chart_of_Account__c/Chart_of_Account__c.object-meta.xml
<CustomObject>
    <description>Chart of Accounts for book keeping.</description>
    <label>Chart of Account</label>
    <nameField>
        <label>Chart of Accounts</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Chart of Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Register_Entry_Line__c/Register_Entry_Line__c.object-meta.xml
<CustomObject>
    <label>Register Entry Line</label>
    <nameField>
        <displayFormat>REL-{YYYY}-{MM}-{000000}</displayFormat>
        <label>Register Entry Line</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Register Entry Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Register_Entry_Line__c/fields/Bank_Register__c.field-meta.xml
<CustomField>
    <fullName>Bank_Register__c</fullName>
    <label>Bank Register</label>
    <referenceTo>Bank_Register__c</referenceTo>
    <relationshipLabel>Register Entry Lines</relationshipLabel>
    <relationshipName>Register_Entry_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Register_Entry_Line__c/fields/Chart_of_Account__c.field-meta.xml
<CustomField>
    <fullName>Chart_of_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Chart of Account</label>
    <referenceTo>Chart_of_Account__c</referenceTo>
    <relationshipLabel>Register Entry Lines</relationshipLabel>
    <relationshipName>Register_Entry_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Register_Entry_Line__c/fields/Debit_Amount__c.field-meta.xml
<CustomField>
    <fullName>Debit_Amount__c</fullName>
    <label>Debit Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Register_Entry_Line__c/fields/Entry_Date__c.field-meta.xml
<CustomField>
    <fullName>Entry_Date__c</fullName>
    <defaultValue>Today()</defaultValue>
    <label>Entry Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Register_Entry_Line__c/fields/Entry_Memo__c.field-meta.xml
<CustomField>
    <fullName>Entry_Memo__c</fullName>
    <label>Entry Memo</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Register_Entry_Line__c/fields/Payee__c.field-meta.xml
<CustomField>
    <fullName>Payee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payee or Payor</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Register Entry Lines</relationshipLabel>
    <relationshipName>Register_Entry_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Register_Entry_Line__c/fields/Running_Balance__c.field-meta.xml
<CustomField>
    <fullName>Running_Balance__c</fullName>
    <formula>( Debit_Amount__c + Credit_Amount__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Running Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Register_Entry_Line__c/fields/Transaction_Amount__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Amount__c</fullName>
    <formula>( Debit_Amount__c - Credit_Amount__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Transaction Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/CustomRegisterEntriesCtlr.cls
public class CustomRegisterEntriesCtlr {
	@AuraEnabled(cacheable=true)
    public static List<Register_Entry_Line__c> getLimitedAccounts(String selectedCriteria,String parentId){
        String query = 'SELECT Name, Entry_Date__c, Entry_Memo__c ,Payee__r.Name,Credit_Amount__c ,Debit_Amount__c,Old_Balance__c,Transaction_Amount__c,Running_Balance__c ,Chart_of_Account__r.Name FROM Register_Entry_Line__c WHERE Bank_Register__c =:parentId ';
        if(String.isBlank(selectedCriteria)){
            selectedCriteria = 'THIS_MONTH';
        }
        if(selectedCriteria.equalsIgnoreCase('60') || selectedCriteria.equalsIgnoreCase('90')){
            query += 'AND Entry_Date__c = LAST_N_DAYS:'+selectedCriteria +' ORDER BY Entry_Date__c DESC,Name DESC';
        	return Database.query(query);
        }else if(selectedCriteria.equalsIgnoreCase('THIS_MONTH')){
            query += 'AND Entry_Date__c = '+ selectedCriteria+' ORDER BY Entry_Date__c DESC,Name DESC';
            return Database.query(query);
        }else if(selectedCriteria.equalsIgnoreCase('all1')){
            query += ' ORDER BY Entry_Date__c DESC,Name DESC';
            return Database.query(query);
        }
        return null;
    }
}