force-app/main/default/objects/Bank_Register__c/Bank_Register__c.object-meta.xml
<CustomObject>
    <label>Bank Register</label>
    <nameField>
        <label>Bank Register</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bank Registers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Bank_Register__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bank Registers</relationshipLabel>
    <relationshipName>Bank_Registers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Bank_Register__c/fields/Bank_Name__c.field-meta.xml
<CustomField>
    <fullName>Bank_Name__c</fullName>
    <label>Bank Name</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Register_Entry_Line__c/Register_Entry_Line__c.object-meta.xml
<CustomObject>
    <label>Register Entry Line</label>
    <nameField>
        <displayFormat>REL-{YYYY}-{MM}-{000000}</displayFormat>
        <label>Register Entry Line</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Register Entry Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Register_Entry_Line__c/fields/Bank_Register__c.field-meta.xml
<CustomField>
    <fullName>Bank_Register__c</fullName>
    <label>Bank Register</label>
    <referenceTo>Bank_Register__c</referenceTo>
    <relationshipLabel>Register Entry Lines</relationshipLabel>
    <relationshipName>Register_Entry_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Register_Entry_Line__c/fields/Entry_Date__c.field-meta.xml
<CustomField>
    <fullName>Entry_Date__c</fullName>
    <defaultValue>Today()</defaultValue>
    <label>Entry Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Register_Entry_Line__c/fields/Payee__c.field-meta.xml
<CustomField>
    <fullName>Payee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payee or Payor</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Register Entry Lines</relationshipLabel>
    <relationshipName>Register_Entry_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CustomRegisterEntriesTest.cls
@IsTest 
public class CustomRegisterEntriesTest {
    @testSetup static void setup() {
        Account acc = new Account(Name='Test Account');
        insert acc;
        Bank_Register__c br = new Bank_Register__c(Account__c =acc.Id,Bank_Name__c = 'Test Bank');
        insert br;
        Date dt = Date.newInstance(2019, 03, 05);
        Date dt1 = Date.newInstance(2019, 02, 05);
        Register_Entry_Line__c rel = new Register_Entry_Line__c(Bank_Register__c = br.Id,
                                                                Payee__c = acc.Id,
                                                                Entry_Date__c = dt);
        insert rel;
        
        Register_Entry_Line__c rel1 = new Register_Entry_Line__c(Bank_Register__c = br.Id,
                                                                Payee__c = acc.Id,
                                                                Entry_Date__c = System.today());
        insert rel1;
    }
    
    @isTest
    public static void testListViewLightning(){
        Bank_Register__c br = [SELECT Id FROM Bank_Register__c LIMIT 1];
        List<Register_Entry_Line__c> items = CustomRegisterEntriesCtlr.getLimitedAccounts('THIS_MONTH',br.Id);
        System.assertEquals(1, items.size());
        
        items = CustomRegisterEntriesCtlr.getLimitedAccounts('60',br.Id);
        System.assertEquals(2, items.size());
        
        items = CustomRegisterEntriesCtlr.getLimitedAccounts('all',br.Id);
        System.assertEquals(null, items);
    }
}