force-app/main/default/objects/Bank_Register__c/Bank_Register__c.object-meta.xml
<CustomObject>
    <label>Bank Register</label>
    <nameField>
        <label>Bank Register</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bank Registers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Bank_Register__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bank Registers</relationshipLabel>
    <relationshipName>Bank_Registers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Bank_Register__c/fields/Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Account_Number__c</fullName>
    <label>Account Number</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bank_Register__c/fields/Bank_Name__c.field-meta.xml
<CustomField>
    <fullName>Bank_Name__c</fullName>
    <label>Bank Name</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bank_Register__c/fields/Register_Type__c.field-meta.xml
<CustomField>
    <fullName>Register_Type__c</fullName>
    <label>Register Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Current Assets</fullName>
            </value>
            <value>
                <fullName>Long Term Assets</fullName>
            </value>
            <value>
                <fullName>Current Liabilities</fullName>
            </value>
            <value>
                <fullName>Long Term Liabilities</fullName>
            </value>
            <value>
                <fullName>Equity</fullName>
            </value>
            <value>
                <fullName>Revenue</fullName>
            </value>
            <value>
                <fullName>Cost of Goods Sold</fullName>
            </value>
            <value>
                <fullName>Expenses</fullName>
            </value>
            <value>
                <fullName>Clearing Account</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Bank_Register__c/fields/Routing_Number__c.field-meta.xml
<CustomField>
    <fullName>Routing_Number__c</fullName>
    <label>Routing Number</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bank_Register__c/fields/Total_Running_Balance_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Running_Balance_Amount__c</fullName>
    <label>Total Running Balance</label>
    <summarizedField>Register_Entry_Line__c.Transaction_Amount__c</summarizedField>
    <summaryForeignKey>Register_Entry_Line__c.Bank_Register__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Bill_Pay__c/Bill_Pay__c.object-meta.xml
<CustomObject>
    <label>Bill Pay</label>
    <nameField>
        <displayFormat>PAY-{YYYY}-{MM}-{000000}</displayFormat>
        <label>Bill Pay</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bill Pays</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Bill_Pay__c/fields/Payment_Amount__c.field-meta.xml
<CustomField>
    <fullName>Payment_Amount__c</fullName>
    <label>Payment Amount</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Bill_Pay__c/fields/Payment_Date__c.field-meta.xml
<CustomField>
    <fullName>Payment_Date__c</fullName>
    <label>Payment Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Bill_Pay__c/fields/Payment_Form__c.field-meta.xml
<CustomField>
    <fullName>Payment_Form__c</fullName>
    <label>Payment Form</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cash</fullName>
            </value>
            <value>
                <fullName>Check</fullName>
            </value>
            <value>
                <fullName>Credit Card</fullName>
            </value>
            <value>
                <fullName>Debit Card</fullName>
            </value>
            <value>
                <fullName>ACH</fullName>
            </value>
            <value>
                <fullName>Clearing Account</fullName>
            </value>
            <value>
                <fullName>Wire</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Bill_Pay__c/fields/Payment_Memo__c.field-meta.xml
<CustomField>
    <fullName>Payment_Memo__c</fullName>
    <label>Payment Memo</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Bill_Pay__c/fields/Post_Date__c.field-meta.xml
<CustomField>
    <fullName>Post_Date__c</fullName>
    <label>Post Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Bill_Pay__c/fields/Purchase_Order__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Order__c</fullName>
    <formula>Supplier_Bill__r.Purchase_Order__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Purchase Order</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bill_Pay__c/fields/Reconciliation_Notes__c.field-meta.xml
<CustomField>
    <fullName>Reconciliation_Notes__c</fullName>
    <label>Reconciliation Notes</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Bill_Pay__c/fields/Supplier_Bill__c.field-meta.xml
<CustomField>
    <fullName>Supplier_Bill__c</fullName>
    <label>Supplier Bill</label>
    <referenceTo>Supplier_Bill__c</referenceTo>
    <relationshipLabel>Bill Pays</relationshipLabel>
    <relationshipName>Bill_Pays</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/Purchase_Order__c.object-meta.xml
<CustomObject>
    <label>Purchase Order</label>
    <nameField>
        <displayFormat>PO-{0000000000}</displayFormat>
        <label>Purchase Order</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Register_Entry_Line__c/Register_Entry_Line__c.object-meta.xml
<CustomObject>
    <label>Register Entry Line</label>
    <nameField>
        <displayFormat>REL-{YYYY}-{MM}-{000000}</displayFormat>
        <label>Register Entry Line</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Register Entry Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Register_Entry_Line__c/fields/Bank_Register__c.field-meta.xml
<CustomField>
    <fullName>Bank_Register__c</fullName>
    <label>Bank Register</label>
    <referenceTo>Bank_Register__c</referenceTo>
    <relationshipLabel>Register Entry Lines</relationshipLabel>
    <relationshipName>Register_Entry_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Register_Entry_Line__c/fields/Bill_Pay__c.field-meta.xml
<CustomField>
    <fullName>Bill_Pay__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bill Pay</label>
    <referenceTo>Bill_Pay__c</referenceTo>
    <relationshipLabel>Register Entry Lines</relationshipLabel>
    <relationshipName>Register_Entry_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Register_Entry_Line__c/fields/Supplier_Bill__c.field-meta.xml
<CustomField>
    <fullName>Supplier_Bill__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Supplier Bill</label>
    <referenceTo>Supplier_Bill__c</referenceTo>
    <relationshipLabel>Register Entry Lines</relationshipLabel>
    <relationshipName>Register_Entry_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Supplier_Bill__c/Supplier_Bill__c.object-meta.xml
<CustomObject>
    <label>Supplier Bill</label>
    <nameField>
        <displayFormat>BILL-{YYYY}-{MM}-{000000}</displayFormat>
        <label>Supplier Bill</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Supplier Bills</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Supplier_Bill__c/fields/Purchase_Order__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Purchase Order</label>
    <referenceTo>Purchase_Order__c</referenceTo>
    <relationshipLabel>Supplier Bills</relationshipLabel>
    <relationshipName>Supplier_Bills</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/billPayNewAndEditCtrl.cls
public class billPayNewAndEditCtrl {
          public Map<String, String> getPaymentformStatusData { get; set; }

    private static final String SAVE = 'Save';
    private string rpPrefix;
    private ApexPages.StandardController stdController;
    public Bill_Pay__c billPayObj {get; set;}  public Supplier_Bill__c invoiceObj {get; set;}
    public List<Supplier_Bill__c> lstinvoice {get; set;}
    public List<BankDetailsWrapper> bankDetails {get; set;}
    public Id selectedBankRegisterId {get; set;}
    public Bank_Register__c associatedBank {get; set;}
    public String actionType {get; set;}
    public static String message;
    
      public Static String RECEIVE_PAYMENTS_ERR_PROVIDE_PAYMENT_FORM{

         get{
            return String.isNotBlank(RECEIVE_PAYMENTS_ERR_PROVIDE_PAYMENT_FORM) ? RECEIVE_PAYMENTS_ERR_PROVIDE_PAYMENT_FORM : FiligreenConfigurationUtility.getConfigValueByObjectAndKey('Receive Payments','RP_Err_Provide_Payment_Form');
        }set;
    }
     public Static String RECEIVE_PAYMENTS_ERR_SELECT_BANK_AVAILABLE_RECONCILE{
        get{
            return String.isNotBlank(RECEIVE_PAYMENTS_ERR_SELECT_BANK_AVAILABLE_RECONCILE) ? RECEIVE_PAYMENTS_ERR_SELECT_BANK_AVAILABLE_RECONCILE : FiligreenConfigurationUtility.getConfigValueByObjectAndKey('Receive Payments','RP_Err_Select_Bank_Available_Reconcile');
        }set;
    }
    public Static String RECEIVE_PAYMENTS_ERR_PROVIDE_RECONCILATION_DATE_AND_INFORMATION {
        get{
            return String.isNotBlank(RECEIVE_PAYMENTS_ERR_PROVIDE_RECONCILATION_DATE_AND_INFORMATION) ? RECEIVE_PAYMENTS_ERR_PROVIDE_RECONCILATION_DATE_AND_INFORMATION : FiligreenConfigurationUtility.getConfigValueByObjectAndKey('Receive Payments','RP_Err_Reconciliatio_Posted_Date');
        }set;
    }
     public Static String RECEIVE_PAYMENTS_ERR_PROVIDE_INVOICE_NUMBER {
        get{
            return String.isNotBlank(RECEIVE_PAYMENTS_ERR_PROVIDE_INVOICE_NUMBER) ? RECEIVE_PAYMENTS_ERR_PROVIDE_INVOICE_NUMBER : FiligreenConfigurationUtility.getConfigValueByObjectAndKey('Receive Payments','RP_Err_Provide_Invoice_Number');
        }set;
    }
    
    public Static String RECEIVE_PAYMENTS_ERR_SELECT_BANK_REGISTER{
        get{
            return String.isNotBlank(RECEIVE_PAYMENTS_ERR_SELECT_BANK_REGISTER) ? RECEIVE_PAYMENTS_ERR_SELECT_BANK_REGISTER : FiligreenConfigurationUtility.getConfigValueByObjectAndKey('Receive Payments','RP_Err_Select_Bank_Register');
        }set;
    }
       
    public Static String Validation_Msg_for_insert_update_RecePay{
        get{
            return String.isNotBlank(Validation_Msg_for_insert_update_RecePay) ? Validation_Msg_for_insert_update_RecePay: FiligreenConfigurationUtility.getConfigValueByObjectAndKey('Receive Payments','Validation_Msg_for_insert_update_RecePay');
        }set;
    }
    
    
     public Static String OBJECT_BILL_PAY {
        get{
            return String.isNotBlank(OBJECT_BILL_PAY) ? OBJECT_BILL_PAY : FiligreenConfigurationUtility.getConfigValueByObjectAndKey('Receive Payments','Obj_Name_BillPay');
        }set;
    }
  Private Static String RECEIVE_PAYMENTS_FIELD_PAYMENTFORM{
        get{
            return String.isNotBlank(RECEIVE_PAYMENTS_FIELD_PAYMENTFORM) ? RECEIVE_PAYMENTS_FIELD_PAYMENTFORM : FiligreenConfigurationUtility.getConfigValueByObjectAndKey('Receive Payments','ReceivePayment_Field_PaymentForm');
        }set;
    }
     public Static String PO_OBJ_NAME{
        get{
            return String.isNotBlank(PO_OBJ_NAME) ? PO_OBJ_NAME : FiligreenConfigurationUtility.getConfigValueByObjectAndKey('Purchase Order','Purchase_Order_Obj_Name');
        }set;
    }
      
    Private Static String RECEIVE_PAYMENTS_PAYMENT_FORM_CASH{
        get{
            return String.isNotBlank(RECEIVE_PAYMENTS_PAYMENT_FORM_CASH) ? RECEIVE_PAYMENTS_PAYMENT_FORM_CASH : FiligreenConfigurationUtility.getConfigValueByObjectAndKey('Receive Payments','RP_Payment_Form_Cash');
        }set;
    }
    Private Static String RECEIVE_PAYMENTS_PAYMENT_FORM_CREDIT_CARD{
        get{
            return String.isNotBlank(RECEIVE_PAYMENTS_PAYMENT_FORM_CREDIT_CARD) ? RECEIVE_PAYMENTS_PAYMENT_FORM_CREDIT_CARD : FiligreenConfigurationUtility.getConfigValueByObjectAndKey('Receive Payments','RP_Payment_Form_CreditCard');
        }set;
    }
    Private Static String RECEIVE_PAYMENTS_PAYMENT_FORM_CHECK{
        get{
            return String.isNotBlank(RECEIVE_PAYMENTS_PAYMENT_FORM_CHECK) ? RECEIVE_PAYMENTS_PAYMENT_FORM_CHECK : FiligreenConfigurationUtility.getConfigValueByObjectAndKey('Receive Payments','RP_Payment_Form_Check');
        }set;
    }
    Private Static String RECEIVE_PAYMENTS_PAYMENT_FORM_DEBIT_CARD{
        get{
            return String.isNotBlank(RECEIVE_PAYMENTS_PAYMENT_FORM_DEBIT_CARD) ? RECEIVE_PAYMENTS_PAYMENT_FORM_DEBIT_CARD : FiligreenConfigurationUtility.getConfigValueByObjectAndKey('Receive Payments','RP_Payment_Form_DebitCard');
        }set;
    }
    Private Static String RECEIVE_PAYMENTS_PAYMENT_FORM_CLEARING_ACCOUNT{
        get{
            return String.isNotBlank(RECEIVE_PAYMENTS_PAYMENT_FORM_CLEARING_ACCOUNT) ? RECEIVE_PAYMENTS_PAYMENT_FORM_CLEARING_ACCOUNT : FiligreenConfigurationUtility.getConfigValueByObjectAndKey('Receive Payments','RP_Payment_Form_Clearing_Account');
        }set;
    }
    Private Static String RECEIVE_PAYMENTS_PAYMENT_FORM_ACH{
        get{
            return String.isNotBlank(RECEIVE_PAYMENTS_PAYMENT_FORM_ACH) ? RECEIVE_PAYMENTS_PAYMENT_FORM_ACH : FiligreenConfigurationUtility.getConfigValueByObjectAndKey('Receive Payments','RP_Payment_Form_ACH');
        }set;
    }
     Private Static String RECEIVE_PAYMENTS_PAYMENT_FORM_WIRE{
        get{
            return String.isNotBlank(RECEIVE_PAYMENTS_PAYMENT_FORM_WIRE) ? RECEIVE_PAYMENTS_PAYMENT_FORM_WIRE : FiligreenConfigurationUtility.getConfigValueByObjectAndKey('Receive Payments','RP_Payment_Form_Wire');
        }set;
    }
    Private Static String RECEIVE_PAYMENTS_PAYMENT_FORM_EXCISETAX_DEPOSIT{
        get{
            return String.isNotBlank(RECEIVE_PAYMENTS_PAYMENT_FORM_EXCISETAX_DEPOSIT) ? RECEIVE_PAYMENTS_PAYMENT_FORM_EXCISETAX_DEPOSIT : FiligreenConfigurationUtility.getConfigValueByObjectAndKey('Receive Payments','RP_Payment_Form_ExciseTax');
        }set;
    }
    
   
     public Static String RECEIVE_PAYMENTS_RECORD_TYPE_CLEARING_ACCOUNT{
        get{
            return String.isNotBlank(RECEIVE_PAYMENTS_RECORD_TYPE_CLEARING_ACCOUNT) ? RECEIVE_PAYMENTS_RECORD_TYPE_CLEARING_ACCOUNT : FiligreenConfigurationUtility.getConfigValueByObjectAndKey('Receive Payments','RP_RecordType_ClearingAccount');
        }set;
    }
     public Static String RECEIVE_PAYMENTS_RECORD_TYPE_CUTIVATION_TAX{
        get{
            return String.isNotBlank(RECEIVE_PAYMENTS_RECORD_TYPE_CUTIVATION_TAX) ? RECEIVE_PAYMENTS_RECORD_TYPE_CUTIVATION_TAX : FiligreenConfigurationUtility.getConfigValueByObjectAndKey('Receive Payments','RP_RecordType_Cultivation_Tax');
        }set;
    }
     public Static String RECEIVE_PAYMENTS_RECORD_TYPE_EXCISETAX{
        get{
            return String.isNotBlank(RECEIVE_PAYMENTS_RECORD_TYPE_EXCISETAX) ? RECEIVE_PAYMENTS_RECORD_TYPE_EXCISETAX : FiligreenConfigurationUtility.getConfigValueByObjectAndKey('Receive Payments','RP_RecordType_ExciseTax');
        }set;
    }
     public Static String RECEIVE_PAYMENTS_RECORD_TYPE_FACTORING{
        get{
            return String.isNotBlank(RECEIVE_PAYMENTS_RECORD_TYPE_FACTORING) ? RECEIVE_PAYMENTS_RECORD_TYPE_FACTORING : FiligreenConfigurationUtility.getConfigValueByObjectAndKey('Receive Payments','RP_RecordType_Factoring');
        }set;
    }
     public Static String RECEIVE_PAYMENTS_RECORD_TYPE_LATECHARGE{
        get{
            return String.isNotBlank(RECEIVE_PAYMENTS_RECORD_TYPE_LATECHARGE) ? RECEIVE_PAYMENTS_RECORD_TYPE_LATECHARGE : FiligreenConfigurationUtility.getConfigValueByObjectAndKey('Receive Payments','RP_RecordType_LateCharge');
        }set;
    }	
     public Static String RECEIVE_PAYMENTS_RECORD_TYPE_LOCAL_CANNABIS_TAX{
        get{
            return String.isNotBlank(RECEIVE_PAYMENTS_RECORD_TYPE_LOCAL_CANNABIS_TAX) ? RECEIVE_PAYMENTS_RECORD_TYPE_LOCAL_CANNABIS_TAX : FiligreenConfigurationUtility.getConfigValueByObjectAndKey('Receive Payments','RP_RecordType_LocalCannabisTax');
        }set;
    }
    public Static String RECEIVE_PAYMENTS_RECORD_TYPE_PRODUCT{
        get{
            return String.isNotBlank(RECEIVE_PAYMENTS_RECORD_TYPE_PRODUCT) ? RECEIVE_PAYMENTS_RECORD_TYPE_PRODUCT : FiligreenConfigurationUtility.getConfigValueByObjectAndKey('Receive Payments','RP_RecordType_Product');
        }set;
    }
    public Static String RECEIVE_PAYMENTS_RECORD_TYPE_RETURNCHECK{
        get{
            return String.isNotBlank(RECEIVE_PAYMENTS_RECORD_TYPE_RETURNCHECK) ? RECEIVE_PAYMENTS_RECORD_TYPE_RETURNCHECK : FiligreenConfigurationUtility.getConfigValueByObjectAndKey('Receive Payments','RP_RecordType_ReturnCheck');
        }set;
    }	
     public Static String RECEIVE_PAYMENTS_RECORD_TYPE_SERVICE{
        get{
            return String.isNotBlank(RECEIVE_PAYMENTS_RECORD_TYPE_SERVICE) ? RECEIVE_PAYMENTS_RECORD_TYPE_SERVICE : FiligreenConfigurationUtility.getConfigValueByObjectAndKey('Receive Payments','RP_RecordType_Service');
        }set;
    }
    public Static String RECEIVE_PAYMENTS_RECORD_TYPE_WIREOFF{
        get{
            return String.isNotBlank(RECEIVE_PAYMENTS_RECORD_TYPE_WIREOFF) ? RECEIVE_PAYMENTS_RECORD_TYPE_WIREOFF : FiligreenConfigurationUtility.getConfigValueByObjectAndKey('Receive Payments','RP_RecordType_wireoff');
        }set;
    }
    public billPayNewAndEditCtrl(){}
    
    @AuraEnabled
    public static AuraResponse billPayNewAndEdit(String recordId,String SBIds){
        AuraResponse r = new AuraResponse('billPayNewAndEditCtrl.billPayNewAndEdit()'); 
        billPayNewAndEditCtrl receive  = new billPayNewAndEditCtrl();
        List<Supplier_Bill__c> lstinvoice = [SELECT id, Name ,Purchase_Order__r.Name FROM Supplier_Bill__c where id=:SBIds];
        
        if(recordId != null && !String.isBlank(recordId)){
            List<Bill_Pay__c> lstbillpay = [select id,Name,Supplier_Bill__c,Payment_Form__c,Purchase_Order__c,Payment_Memo__c,Payment_Amount__c,Payment_Date__c,Reconciliation_Notes__c
                                                   from Bill_Pay__c where id =: recordId];
            
            
            
            if(lstbillpay.size() > 0)
                receive.billPayObj = lstbillpay[0];    
        } else {
            receive.billPayObj = new Bill_Pay__c();  
           
            if(SBIds != null && SBIds != ''){ List<Supplier_Bill__c> lstsb= [select Id,Name ,Purchase_Order__r.Name from Supplier_Bill__c where Id =: SBIds];
                if(lstsb.size() > 0){ receive.billPayObj.Supplier_Bill__c = lstsb[0].Id;
                    receive.billPayObj.Supplier_Bill__r = lstsb[0];
                }
            }
         
        }
        receive.init();
        receive.retrieveBankDetails();
        
        List<Map<String, String>> paymentForm = Utility.getPicklistItems(OBJECT_BILL_PAY,RECEIVE_PAYMENTS_FIELD_PAYMENTFORM);
      
        r.data.put('records',receive.billPayObj);
         receive.getPaymentformStatusData =getLabStatus();
       r.data.put('paymentForm', receive.getPaymentformStatusData);
        r.data.put('lstinvoice',lstinvoice);
        r.data.put('Validation_Msg_for_insert_update_RecePay',Validation_Msg_for_insert_update_RecePay);
        r.data.put('associatedBank',receive.associatedBank);
        r.data.put('bankDetails',receive.bankDetails);
        r.data.put('selectedBankRegisterId',receive.selectedBankRegisterId);
        r.data.put('rpPrefix',receive.rpPrefix);
        
        return r;
    }
    
 @AuraEnabled
    public static Map<String, String> getLabStatus(){
        Map<String, String> options = new Map<String, String>();
        options.put(RECEIVE_PAYMENTS_PAYMENT_FORM_ACH,RECEIVE_PAYMENTS_PAYMENT_FORM_ACH);
        options.put(RECEIVE_PAYMENTS_PAYMENT_FORM_CASH,RECEIVE_PAYMENTS_PAYMENT_FORM_CASH);
        options.put(RECEIVE_PAYMENTS_PAYMENT_FORM_CHECK,RECEIVE_PAYMENTS_PAYMENT_FORM_CHECK);
        options.put(RECEIVE_PAYMENTS_PAYMENT_FORM_CLEARING_ACCOUNT,RECEIVE_PAYMENTS_PAYMENT_FORM_CLEARING_ACCOUNT);
        options.put(RECEIVE_PAYMENTS_PAYMENT_FORM_CREDIT_CARD,RECEIVE_PAYMENTS_PAYMENT_FORM_CREDIT_CARD);
        options.put(RECEIVE_PAYMENTS_PAYMENT_FORM_DEBIT_CARD,RECEIVE_PAYMENTS_PAYMENT_FORM_DEBIT_CARD);
        options.put(RECEIVE_PAYMENTS_PAYMENT_FORM_EXCISETAX_DEPOSIT,RECEIVE_PAYMENTS_PAYMENT_FORM_EXCISETAX_DEPOSIT);
        options.put(RECEIVE_PAYMENTS_PAYMENT_FORM_WIRE,RECEIVE_PAYMENTS_PAYMENT_FORM_WIRE);
        return options;
    }        
    
    
    /**
* Initialize the constructor for standard and standard set controller
*/
    public void init(){
        bankDetails = new List<BankDetailsWrapper>();
        associatedBank = new Bank_Register__c();
        actionType = SAVE;
        rpPrefix = getObjectPrefix(OBJECT_BILL_PAY);
    }
    
    public class UserException extends Exception {}
    
    /**
* Retrieve all bank register details
*/
    public PageReference retrieveBankDetails() {
        
        PageReference pageRef;
  
        
        Boolean isSelected = true;
        for(Bank_Register__c bankRegisterSO : [Select Account__r.dBA__c, 
                                               Bank_Name__c, 
                                               Register_Type__c,
                                               Account_Number__c,
                                               Routing_Number__c,Account__r.Name,Total_Running_Balance_Amount__c,
                                               (Select Id From Register_Entry_Lines__r
                                                Where Bill_Pay__c =: billPayObj.Id LIMIT 1)
                                               From Bank_Register__c
                                               Where Active__c = true]){
                                                   BankDetailsWrapper bankDetailsWrapper = new BankDetailsWrapper(bankRegisterSO);
                                                   
                                                   if(billPayObj != null && billPayObj.Id != null && 
                                                      bankRegisterSO.Register_Entry_Lines__r.size() == 1){  associatedBank = bankRegisterSO;
                                                          selectedBankRegisterId = bankRegisterSO.Id;
                                                      }
                                                   bankDetails.add(bankDetailsWrapper);
                                               }
        return pageRef;
    }
    
    /**
* Save Receive Payment and related bank register entry Light
*/
   @AuraEnabled
    public static AuraResponse doSaveActionLight(Bill_Pay__c billPayObj,Id selectedBankRegisterId) {
        AuraResponse r = new AuraResponse('billPayNewAndEditCtrl.doSaveActionLight()'); 
        
        billPayNewAndEditCtrl receive  = new billPayNewAndEditCtrl();
           
         if(validateInputLight(billPayObj,selectedBankRegisterId)){
            r.data.put('Error', message);
            return r;
        }

        
        Savepoint savePoint;
        try{
            // Define save point for rollback
            savePoint = Database.setSavepoint();
            
            upsert billPayObj;
           
              String parentObjectName = PO_OBJ_NAME;
            if(selectedBankRegisterId != null){BankRegisterSupport.generateBankEntryRelatedToBillPay(billPayObj.Id, selectedBankRegisterId,parentObjectName);
               }
            r.data.put('record', billPayObj);
            return r;
            
            
        }catch(Exception ex){Database.rollback(savePoint);message = 'Exception occured while updating Receive Payment record: ' + ex.getMessage();
           r.data.put('Error', message); return r;
        }
    }
    
    
    public class BankDetailsWrapper{
        @AuraEnabled public Bank_Register__c bankRegisterSO {get; set;}
        
        public BankDetailsWrapper(Bank_Register__c bankRegisterSO){
            this.bankRegisterSO = bankRegisterSO;
        }
    }
    
     public static Boolean validateInputLight(Bill_Pay__c billPayObj,Id selectedBankRegisterId){
        Boolean hasValidationError = false;
      

        if(billPayObj.Payment_Form__c == null){
            message = RECEIVE_PAYMENTS_ERR_PROVIDE_PAYMENT_FORM;
            hasValidationError = true;
        }
         if(billPayObj.Payment_Form__c == null){
            message = RECEIVE_PAYMENTS_ERR_PROVIDE_PAYMENT_FORM;
            hasValidationError = true;
        }
        // Check if bank register is selected while reconciliation date is not null
        else if(billPayObj.Post_Date__c != null && selectedBankRegisterId == null){
            message = RECEIVE_PAYMENTS_ERR_SELECT_BANK_AVAILABLE_RECONCILE;hasValidationError = true;
        }
        // Check if reconciliation dates and notes provided while selected bank register is not null
        else if(billPayObj.Post_Date__c == null && selectedBankRegisterId != null){message =RECEIVE_PAYMENTS_ERR_PROVIDE_RECONCILATION_DATE_AND_INFORMATION;
            hasValidationError = true;
        }
     
      
        
        return hasValidationError;
        
    }
  
    /**

  
    /**
* Get object prefix
* @param objectName The name of object
* @return The 3 digit prefix of object
*/
    public String getObjectPrefix(String objectName) {
        return Schema.getGlobalDescribe().get(objectName).getDescribe().getKeyPrefix();
    }
    

    /**
* Edit existing bank register entry related to Receive payment
* @param receivePaymentSO The Receive Payment record
* @param registerEntrySO The Register entry line record
*/
    public static Id getRecordTypeId(String objectAPIName, String recordTypeName){ Schema.DescribeSObjectResult sobjectResult = Schema.getGlobalDescribe().get(objectAPIName).getDescribe();
        return sobjectResult.getRecordTypeInfosByName().get(recordTypeName).getRecordTypeId();
    }
}