force-app/main/default/objects/Delivery_Window__c/Delivery_Window__c.object-meta.xml
<CustomObject>
    <label>Delivery Window</label>
    <nameField>
        <displayFormat>DW-{00000000}</displayFormat>
        <label>Delivery Window Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Windows</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Shipping_Manifest__c/Shipping_Manifest__c.object-meta.xml
<CustomObject>
    <description>Used in the generation of compliance document to enable retail delivery.</description>
    <label>Shipping Manifest</label>
    <nameField>
        <displayFormat>SM-{YYYY}-{MM}-{0000000000}</displayFormat>
        <label>Shipping Manifest</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipping Manifests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Shipping_Manifest__c/fields/Planned_Ship_Transfer_Date__c.field-meta.xml
<CustomField>
    <fullName>Planned_Ship_Transfer_Date__c</fullName>
    <inlineHelpText>Date in which the products are to be delivered</inlineHelpText>
    <label>Planned Ship/Transfer Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Shipping_Manifest__c/fields/Receiver_Name__c.field-meta.xml
<CustomField>
    <fullName>Receiver_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Receiver Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Shipping Manifests as Receiver</relationshipLabel>
    <relationshipName>Shipping_Manifests1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipping_Manifest__c/recordTypes/RSM.recordType-meta.xml
<RecordType>
    <fullName>RSM</fullName>
    <active>true</active>
    <description>Used for Retail Shipments - Ship Confirm to &quot;Delivered&quot; Inventory Location, Rename to &quot;Retail&quot;</description>
    <label>RSM</label>
</RecordType>

force-app/main/default/classes/RSMDeliveryWindowController.cls
/**
 * Copyright (c) 2018 Filigreen Distro
 * All rights reserved.
 * RSMDeliveryWindowController
 */
public class RSMDeliveryWindowController{

    private ApexPages.StandardController stdController;
    private Shipping_Manifest__c rsmObj = null;
    public String recommendedTime{get; set;}
    public Boolean recommendedTimeMessageFlag {get; set;}
    public String recommendedTimeMessage {get; set;}
    
    // Constructor
    public RSMDeliveryWindowController(ApexPages.StandardController controller) {
        this.stdController = controller;
        rsmObj = (Shipping_Manifest__c)stdController.getRecord();
        recommendedTime = '';
        recommendedTimeMessage = '';
        recommendedTimeMessageFlag = false;
    }
    
    /**
     * Get recommended delivery time from delivery window records of related receiver account
     */
    public void getDeliveryTime() {
        if(rsmObj != null){
            
            // Get receiver name from RSM
            rsmObj = [Select Planned_Ship_Transfer_Date__c, Receiver_Name__c from Shipping_Manifest__c Where Id =: rsmObj.Id];
            
            Date plannedShipDate = rsmObj.Planned_Ship_Transfer_Date__c;
            
            // If planned ship date is not provided then do early exit
            if(plannedShipDate == null){
                recommendedTimeMessageFlag = true;
                recommendedTimeMessage = Label.Planned_ship_date_is_not_provided;
                return;
            }
            
            // If planned ship date is past date then do early exit
            if(plannedShipDate < System.Today()){
                recommendedTimeMessageFlag = true;
                recommendedTimeMessage = Label.Planned_ship_transfer_date_is_past_date;
                return;
            }
            
            // If no receiver found then do early exit
            if(rsmObj.Receiver_Name__c == null){
                recommendedTimeMessageFlag = true;
                recommendedTimeMessage = Label.Receiver_Account_Is_Not_Provided;
                return;
            }
            
            // Get delivery windows from receiver account
            List<Delivery_Window__c> deliveryWindows = DeliveryWindowSupport.getDeliveryWindows(rsmObj.Receiver_Name__c);
                                     
            // If no delivery windows found then do early exit
            if(deliveryWindows.size() == 0){
                recommendedTimeMessageFlag = true;
                recommendedTimeMessage = Label.No_delivery_window_found;
                return;
            }
            
            recommendedTime = DeliveryWindowSupport.getDeliveryTime(plannedShipDate, deliveryWindows);
        }
    }
}