force-app/main/default/objects/Delivery_Window__c/Delivery_Window__c.object-meta.xml
<CustomObject>
    <label>Delivery Window</label>
    <nameField>
        <displayFormat>DW-{00000000}</displayFormat>
        <label>Delivery Window Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Windows</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Delivery_Window__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Delivery_Slots</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Delivery_Window__c/fields/Delivery_Day__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Day__c</fullName>
    <label>Delivery Day</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Monday</fullName>
            </value>
            <value>
                <fullName>Tuesday</fullName>
            </value>
            <value>
                <fullName>Wednesday</fullName>
            </value>
            <value>
                <fullName>Thursday</fullName>
            </value>
            <value>
                <fullName>Friday</fullName>
            </value>
            <value>
                <fullName>Saturday</fullName>
            </value>
            <value>
                <fullName>Sunday</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Delivery_Window__c/fields/Earliest_Delivery_Window__c.field-meta.xml
<CustomField>
    <fullName>Earliest_Delivery_Window__c</fullName>
    <label>Earliest Delivery Window</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>06:00 AM PST</fullName>
            </value>
            <value>
                <fullName>06:30 AM PST</fullName>
            </value>
            <value>
                <fullName>07:00 AM PST</fullName>
            </value>
            <value>
                <fullName>07:30 AM PST</fullName>
            </value>
            <value>
                <fullName>08:00 AM PST</fullName>
            </value>
            <value>
                <fullName>08:30 AM PST</fullName>
            </value>
            <value>
                <fullName>09:00 AM PST</fullName>
            </value>
            <value>
                <fullName>09:30 AM PST</fullName>
            </value>
            <value>
                <fullName>10:00 AM PST</fullName>
            </value>
            <value>
                <fullName>10:30 AM PST</fullName>
            </value>
            <value>
                <fullName>11:00 AM PST</fullName>
            </value>
            <value>
                <fullName>11:30 AM PST</fullName>
            </value>
            <value>
                <fullName>12:00 Noon</fullName>
            </value>
            <value>
                <fullName>12:30 PM PST</fullName>
            </value>
            <value>
                <fullName>01:00 PM PST</fullName>
            </value>
            <value>
                <fullName>01:30 PM PST</fullName>
            </value>
            <value>
                <fullName>02:00 PM PST</fullName>
            </value>
            <value>
                <fullName>02:30 PM PST</fullName>
            </value>
            <value>
                <fullName>03:00 PM PST</fullName>
            </value>
            <value>
                <fullName>03:30 PM PST</fullName>
            </value>
            <value>
                <fullName>04:00 PM PST</fullName>
            </value>
            <value>
                <fullName>04:30 PM PST</fullName>
            </value>
            <value>
                <fullName>05:00 PM PST</fullName>
            </value>
            <value>
                <fullName>05:30 PM PST</fullName>
            </value>
            <value>
                <fullName>06:00 PM PST</fullName>
            </value>
            <value>
                <fullName>06:30 PM PST</fullName>
            </value>
            <value>
                <fullName>07:00 PM PST</fullName>
            </value>
            <value>
                <fullName>07:30 PM PST</fullName>
            </value>
            <value>
                <fullName>08:00 PM PST</fullName>
            </value>
            <value>
                <fullName>08:30 PM PST</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Delivery_Window__c/fields/Full_Day_Delivery__c.field-meta.xml
<CustomField>
    <fullName>Full_Day_Delivery__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Any time delivery between 5AM PST - 10PM PST</description>
    <inlineHelpText>Any time delivery between 5AM PST - 10PM PST</inlineHelpText>
    <label>Full Day Delivery</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Delivery_Window__c/fields/Last_Delivery_Window__c.field-meta.xml
<CustomField>
    <fullName>Last_Delivery_Window__c</fullName>
    <label>Last Delivery Window</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>06:00 AM PST</fullName>
            </value>
            <value>
                <fullName>06:30 AM PST</fullName>
            </value>
            <value>
                <fullName>07:00 AM PST</fullName>
            </value>
            <value>
                <fullName>07:30 AM PST</fullName>
            </value>
            <value>
                <fullName>08:00 AM PST</fullName>
            </value>
            <value>
                <fullName>08:30 AM PST</fullName>
            </value>
            <value>
                <fullName>09:00 AM PST</fullName>
            </value>
            <value>
                <fullName>09:30 AM PST</fullName>
            </value>
            <value>
                <fullName>10:00 AM PST</fullName>
            </value>
            <value>
                <fullName>10:30 AM PST</fullName>
            </value>
            <value>
                <fullName>11:00 AM PST</fullName>
            </value>
            <value>
                <fullName>11:30 AM PST</fullName>
            </value>
            <value>
                <fullName>12:00 Noon</fullName>
            </value>
            <value>
                <fullName>12:30 PM PST</fullName>
            </value>
            <value>
                <fullName>01:00 PM PST</fullName>
            </value>
            <value>
                <fullName>01:30 PM PST</fullName>
            </value>
            <value>
                <fullName>02:00 PM PST</fullName>
            </value>
            <value>
                <fullName>02:30 PM PST</fullName>
            </value>
            <value>
                <fullName>03:00 PM PST</fullName>
            </value>
            <value>
                <fullName>03:30 PM PST</fullName>
            </value>
            <value>
                <fullName>04:00 PM PST</fullName>
            </value>
            <value>
                <fullName>04:30 PM PST</fullName>
            </value>
            <value>
                <fullName>05:00 PM PST</fullName>
            </value>
            <value>
                <fullName>05:30 PM PST</fullName>
            </value>
            <value>
                <fullName>06:00 PM PST</fullName>
            </value>
            <value>
                <fullName>06:30 PM PST</fullName>
            </value>
            <value>
                <fullName>07:00 PM PST</fullName>
            </value>
            <value>
                <fullName>07:30 PM PST</fullName>
            </value>
            <value>
                <fullName>08:00 PM PST</fullName>
            </value>
            <value>
                <fullName>08:30 PM PST</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DeliveryWindowSupport.cls
/**
 * Copyright (c) 2018 Filigreen Distro
 * All rights reserved.
 * DeliveryWindowSupport
 */
public class DeliveryWindowSupport{

    /**
     * Get delivery windows related to account
     *
     * @param accountId The account id to get related delivery windows
     *
     * @return The list of delivery windows
     */
    public static List<Delivery_Window__c> getDeliveryWindows(Id accountId){
        List<Delivery_Window__c> deliveryWindows = new List<Delivery_Window__c>();
        deliveryWindows = [Select Delivery_Day__c,
                                  Earliest_Delivery_Window__c,
                                  Full_Day_Delivery__c,
                                  Last_Delivery_Window__c
                                  From Delivery_Window__c
                                  Where Account__c =:accountId ORDER by Name];
        return deliveryWindows;
    }
    
    /**
     * Get recommended delivery time from delivery window records of related account
     * plannedShipDate - The planned date to deliver
     * deliveryWindows - The list of delivery windows to display recommended delivery time
     *
     * @return recommended delivery time
     */
    public static List<DeliveryWindowSupport.DeliveryWindowWrapper> getDeliveryTime(Date plannedShipDate, List<Delivery_Window__c> deliveryWindows) {
        String recommendedTime = '';
        
        Map<Integer, String> dayMap = new Map<Integer, String>();
        dayMap.put(0, 'Monday');
        dayMap.put(1, 'Tuesday');
        dayMap.put(2, 'Wednesday');
        dayMap.put(3, 'Thursday');
        dayMap.put(4, 'Friday');
        dayMap.put(5, 'Saturday');
        dayMap.put(6, 'Sunday');

        Map<String, Integer> dayNumberMap = new Map<String, Integer>();
        dayNumberMap.put('Monday', 0);
        dayNumberMap.put('Tuesday', 1);
        dayNumberMap.put('Wednesday', 2);
        dayNumberMap.put('Thursday', 3);
        dayNumberMap.put('Friday', 4);
        dayNumberMap.put('Saturday', 5);
        dayNumberMap.put('Sunday', 6);
        
        Datetime dt = DateTime.newInstance(plannedShipDate, Time.newInstance(0, 0, 0, 0));
        String dayOfPlannedShipDate = dt.format('EEEE');
        Integer plannedShipDayNumber = dayNumberMap.get(dayOfPlannedShipDate);
        Set<Id> matchingDeliveryWindows = new Set<Id>();
        Boolean infoFlag = false;
        
        List<DeliveryWindowWrapper> orderedDeliveryWindowList = new List<DeliveryWindowWrapper>();
        List<DeliveryWindowWrapper> finalOrderedDeliveryWindowList = new List<DeliveryWindowWrapper>();
        
        List<Holiday> holidays = [Select Name, 
                                         ActivityDate, 
                                         IsAllDay, 
                                         IsRecurrence, 
                                         RecurrenceDayOfMonth, 
                                         RecurrenceDayOfWeekMask, 
                                         RecurrenceEndDateOnly, 
                                         RecurrenceInstance, 
                                         RecurrenceInterval, 
                                         RecurrenceMonthOfYear, 
                                         RecurrenceStartDate, 
                                         RecurrenceType 
                                  FROM Holiday
                                  WHERE IsRecurrence = true OR ActivityDate = THIS_YEAR];
        
        // Sort delivery windows based on day - Monday, Tuesday etc.
        for(Integer dayKey : dayMap.keySet()){
            for(Delivery_Window__c deliveryWindowSO : deliveryWindows){
                if(dayMap.get(dayKey) == deliveryWindowSO.Delivery_Day__c){
                    DeliveryWindowWrapper deliveryWindowObj = new DeliveryWindowWrapper();
                    deliveryWindowObj.orderedDay = deliveryWindowSO.Delivery_Day__c;
                    deliveryWindowObj.orderedNumber = dayKey;
                    deliveryWindowObj.orderedDate = plannedShipDate;
                    deliveryWindowObj.deliveryWindowSO = deliveryWindowSO;
                    orderedDeliveryWindowList.add(deliveryWindowObj);
                }
            }
        }
        // Prepare list to display delivery windows based on following order
        // i.e. Planned ship date is Wednesday
        // Matching delivery window first - Wednesday
        // Future delivery window - Thursday, Friday etc.
        // Past delivery window - Monday, Tuesday
        
        Boolean matchingDeliveryWindowFound = false;
     
        // Prepare text to display delivery window
        for(DeliveryWindowWrapper deliveryWindowWrapperObj : orderedDeliveryWindowList){
                
            if(!deliveryWindowWrapperObj.matchingDeliveryWindow && !infoFlag){
                recommendedTime += '<b>Additional Delivery windows:</b> <br/><br/>';
                infoFlag = true;
            }
            
            recommendedTime += deliveryWindowWrapperObj.orderedDate.format();
            recommendedTime += '(' + deliveryWindowWrapperObj.orderedDay + ') - ';
            
            if(deliveryWindowWrapperObj.deliveryWindowSO.Full_Day_Delivery__c){
                recommendedTime += '5 AM PST To 10 PM PST';
            }else{
                recommendedTime += deliveryWindowWrapperObj.deliveryWindowSO.Earliest_Delivery_Window__c;
                recommendedTime += ' To ';
                recommendedTime += deliveryWindowWrapperObj.deliveryWindowSO.Last_Delivery_Window__c;
            }
            
            if(deliveryWindowWrapperObj.isHoliday){
                recommendedTime += ' (' + deliveryWindowWrapperObj.holidayName + ' - Holiday)';
            }
            recommendedTime += '<br/><br/>'; 
        }
        return orderedDeliveryWindowList;
    }
    
    // Wrapper class for delivery window parameters
    public class DeliveryWindowWrapper{
        public Integer orderedNumber {get; set;}
        public String orderedDay {get; set;}
        public Date orderedDate {get; set;}
        public Boolean isHoliday {get; set;}
        public String holidayName {get; set;}
        public Boolean matchingDeliveryWindow {get; set;}
        public Delivery_Window__c deliveryWindowSO;
        
        public DeliveryWindowWrapper(){
            isHoliday = false;
            matchingDeliveryWindow = false;
        }
    }
}