force-app/main/default/objects/Delivery_Window__c/Delivery_Window__c.object-meta.xml
<CustomObject>
    <label>Delivery Window</label>
    <nameField>
        <displayFormat>DW-{00000000}</displayFormat>
        <label>Delivery Window Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Delivery Windows</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Shipping_Manifest__c/Shipping_Manifest__c.object-meta.xml
<CustomObject>
    <description>Used in the generation of compliance document to enable retail delivery.</description>
    <label>Shipping Manifest</label>
    <nameField>
        <displayFormat>SM-{YYYY}-{MM}-{0000000000}</displayFormat>
        <label>Shipping Manifest</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipping Manifests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Shipping_Manifest__c/fields/Planned_Ship_Transfer_Date__c.field-meta.xml
<CustomField>
    <fullName>Planned_Ship_Transfer_Date__c</fullName>
    <inlineHelpText>Date in which the products are to be delivered</inlineHelpText>
    <label>Planned Ship/Transfer Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Shipping_Manifest__c/fields/Supplier_Name__c.field-meta.xml
<CustomField>
    <fullName>Supplier_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Supplier Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Shipping Manifests as Supplier</relationshipLabel>
    <relationshipName>Shipping_Manifests2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipping_Manifest__c/recordTypes/Transfer.recordType-meta.xml
<RecordType>
    <fullName>Transfer</fullName>
    <active>true</active>
    <description>Used for Outbound Transfer Non-Retail Channel - Ship Confirm to &quot;Transferred&quot; Inventory Location</description>
    <label>Transfer</label>
</RecordType>

force-app/main/default/classes/TSMDeliveryWindowController.cls
/**
 * Copyright (c) 2018 Filigreen Distro
 * All rights reserved.
 * TSMDeliveryWindowController
 */
public class TSMDeliveryWindowController{

    private ApexPages.StandardController stdController;
    private Shipping_Manifest__c tsmObj = null;
    public String recommendedTime{get; set;}
    public Boolean recommendedTimeMessageFlag {get; set;}
    public String recommendedTimeMessage {get; set;}
    
    // Constructor
    public TSMDeliveryWindowController(ApexPages.StandardController controller) {
        this.stdController = controller;
        tsmObj = (Shipping_Manifest__c)stdController.getRecord();
        recommendedTime = '';
        recommendedTimeMessage = '';
        recommendedTimeMessageFlag = false;
    }
    
    /**
     * Get recommended delivery time from delivery window records of related supplier account
     */
    public void getDeliveryTime() {
        if(tsmObj != null){
            
            // Get supplier name from TSM
            tsmObj = [Select Planned_Ship_Transfer_Date__c, Supplier_Name__c from Shipping_Manifest__c Where Id =: tsmObj.Id];
            
            Date plannedTrasferDate = tsmObj.Planned_Ship_Transfer_Date__c;
            
            // If planned transfer date is not provided then do early exit
            if(plannedTrasferDate == null){
                recommendedTimeMessageFlag = true;
                recommendedTimeMessage = Label.Planned_transfer_date_is_not_provided;
                return;
            }
            
            // If planned transfer date is past date then do early exit
            if(plannedTrasferDate < System.Today()){
                recommendedTimeMessageFlag = true;
                recommendedTimeMessage = Label.Planned_ship_transfer_date_is_past_date;
                return;
            }
            
            // If no supplier found then do early exit
            if(tsmObj.Supplier_Name__c == null){
                recommendedTimeMessageFlag = true;
                recommendedTimeMessage = Label.Supplier_Account_Is_Not_Provided;
                return;
            }
            
            // Get delivery windows from supplier account
            List<Delivery_Window__c> deliveryWindows = DeliveryWindowSupport.getDeliveryWindows(tsmObj.Supplier_Name__c);
                                     
            // If no delivery windows found then do early exit
            if(deliveryWindows.size() == 0){
                recommendedTimeMessageFlag = true;
                recommendedTimeMessage = Label.No_delivery_window_found;
                return;
            }
            
            recommendedTime = DeliveryWindowSupport.getDeliveryTime(plannedTrasferDate, deliveryWindows);
        }
    }
}