force-app/main/default/objects/Expense_Number__c/Expense_Number__c.object-meta.xml
<CustomObject>
    <label>Expense</label>
    <nameField>
        <displayFormat>EXP-{YYYY}-{MM}-{0000000000}</displayFormat>
        <label>Expense Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Expense_Number__c/fields/Approver__c.field-meta.xml
<CustomField>
    <fullName>Approver__c</fullName>
    <formula>Owner:User.Manager.FirstName  &amp; &apos; &apos;&amp; Owner:User.Manager.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Approver</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Expense_Number__c/fields/ExpenseName__c.field-meta.xml
<CustomField>
    <fullName>ExpenseName__c</fullName>
    <inlineHelpText>Expense Name</inlineHelpText>
    <label>Expense Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Expense_Number__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Expenses</relationshipLabel>
    <relationshipName>Expenses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Expense_Number__c/fields/Reimbursed__c.field-meta.xml
<CustomField>
    <fullName>Reimbursed__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>True if Approved and Reimbured</inlineHelpText>
    <label>Reimbursed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Expense_Number__c/fields/Reimbursed_Date__c.field-meta.xml
<CustomField>
    <fullName>Reimbursed_Date__c</fullName>
    <inlineHelpText>Reimbursed Pay Period</inlineHelpText>
    <label>Reimbursed Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Expense_Number__c/fields/TotalExpenseAmount__c.field-meta.xml
<CustomField>
    <fullName>TotalExpenseAmount__c</fullName>
    <inlineHelpText>Total Amount to be reimbursed</inlineHelpText>
    <label>Total Expense Amount</label>
    <summarizedField>Expense_Line__c.Line_Total_Amount__c</summarizedField>
    <summaryForeignKey>Expense_Line__c.ExpenseNumber__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Expense_Number__c/recordTypes/Expense.recordType-meta.xml
<RecordType>
    <fullName>Expense</fullName>
    <active>true</active>
    <description>New Expense for Review/Approval</description>
    <label>Expense</label>
</RecordType>

force-app/main/default/classes/UpdateExpenseController.cls
public without sharing class UpdateExpenseController {
    @AuraEnabled
    public static Expense_Number__c getExpenseRecord(String recordId){
        Expense_Number__c expense;
        if(String.isNotBlank(recordId)){
            Expense_Number__c[] expesnes = [SELECT Id, Name, OwnerId,Owner.Name,ExpenseName__c, Reimbursed__c, Reimbursed_Date__c, Approver__c, Project__c , Project__r.Name, TotalExpenseAmount__c      FROM Expense_Number__c WHERE Id =:recordId];
            
            if(!expesnes.isEmpty()){
                expense =  expesnes[0];
            }
        }
        return expense;
    }
    @AuraEnabled
    public static Map<String,Object> updateExpenseRecord(String expenseJSON){
        Map<String,Object> r = new Map<String,Object>();
        Expense_Number__c expense = (Expense_Number__c) JSON.deserialize(expenseJSON, Expense_Number__c.class);
        if(expense.Id != null ){
            UserRecordAccess URA = [SELECT RecordId, HasEditAccess FROM UserRecordAccess WHERE UserId = :UserInfo.getUserId() AND RecordId = :expense.Id];
            if(URA.HasEditAccess){
                Boolean isLocked = Approval.isLocked(expense);
                System.debug('##isLocked::'+isLocked);
                if(isLocked){
                    Approval.UnlockResult unlockedRersult = Approval.unlock(expense);
                    // Iterate through each returned result
                    if (unlockedRersult.isSuccess()) {
                        update expense;
                        r.put('success','Expense '+expense.Name+' updated successfully');
                       Approval.lock(expense);
                    }
                    else {
                        String error = '';
                        // Operation failed, so get all errors                
                        for(Database.Error err : unlockedRersult.getErrors()) {                  
                            error += err.getMessage();
                        }
                        r.put('error',error);
                    }
                }
            }else{
                r.put('error','User don\'t have edit access on the record');
            }
            
        }
        return r;
    }
    
}