force-app/main/default/objects/UID__c/UID__c.object-meta.xml
<CustomObject>
    <description>Unique Identifiers, RFID Tags from Track &amp; Trace</description>
    <label>UID</label>
    <nameField>
        <label>UID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>UIDs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UID__c/fields/Available_Qty__c.field-meta.xml
<CustomField>
    <fullName>Available_Qty__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Exclude Location:  CannaWaste, Delivered, Packaged, Quarantine, Test Sampled, Transferred</inlineHelpText>
    <label>Available Qty</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/UID__c/fields/Available_Qty_in_METRC__c.field-meta.xml
<CustomField>
    <fullName>Available_Qty_in_METRC__c</fullName>
    <label>Available Qty in METRC</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/UID__c/fields/Batch_ID__c.field-meta.xml
<CustomField>
    <fullName>Batch_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Batch ID</label>
    <referenceTo>Harvest_Batch_Code__c</referenceTo>
    <relationshipLabel>UIDs</relationshipLabel>
    <relationshipName>UIDs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UID__c/fields/Finished_Date__c.field-meta.xml
<CustomField>
    <fullName>Finished_Date__c</fullName>
    <inlineHelpText>Package finished date in Metrc.</inlineHelpText>
    <label>Finished Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/UID__c/fields/METRC_Lab_Status__c.field-meta.xml
<CustomField>
    <fullName>METRC_Lab_Status__c</fullName>
    <label>METRC Lab Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NotSubmitted</fullName>
                <default>true</default>
                <label>NotSubmitted</label>
            </value>
            <value>
                <fullName>SubmittedForTesting</fullName>
            </value>
            <value>
                <fullName>TestPassed</fullName>
            </value>
            <value>
                <fullName>TestFailed</fullName>
            </value>
            <value>
                <fullName>TestingInProgress</fullName>
            </value>
            <value>
                <fullName>NotRequired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/UID__c/fields/METRC_Status__c.field-meta.xml
<CustomField>
    <fullName>METRC_Status__c</fullName>
    <label>METRC Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Unfinished</fullName>
                <default>true</default>
                <label>Unfinished</label>
            </value>
            <value>
                <fullName>Finished</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/UID__c/fields/METRC_Sync_status__c.field-meta.xml
<CustomField>
    <fullName>METRC_Sync_status__c</fullName>
    <label>METRC Sync status</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/UID__c/fields/Received_Qty__c.field-meta.xml
<CustomField>
    <fullName>Received_Qty__c</fullName>
    <label>Received Qty</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/MetrcSynUIDController.cls
public class MetrcSynUIDController {

	@AuraEnabled
    public static String synData(String recordId){
		
        Map<String,Object> respMap = new  Map<String,Object>();
        List<UID__c> uidList = new List<UID__c>();
        String responseMessage= '';
        UID__c uid = [SELECT Available_Qty_in_METRC__c,Available_Qty__c,Batch_ID__c,Id,METRC_Status__c,	Finished_Date__c, METRC_Lab_Status__c, METRC_Sync_status__c,Name,Received_Qty__c FROM UID__c where Id=: recordId];
        
            respMap = Metrc_HttpCalloutHelper.getSinglePackage(uid.Name);
            if(respMap.get('Quantity')!=null){
                uid.Available_Qty_in_METRC__c = Integer.valueof(respMap.get('Quantity'));
                uid.METRC_Lab_Status__c = String.valueof(respMap.get('LabTestingState'));
                upsert uid; 
            }else{
                responseMessage = 'NOT FOUND';
            }

        if(respMap.get('Quantity')==0 && respMap.get('FinishedDate') !=null){
            if(uid.Available_Qty_in_METRC__c == 0 && uid.Available_Qty__c == 0 && uid.Received_Qty__c> 0){
                if(uid.METRC_Status__c=='Unfinished'){
                    uid.METRC_Status__c = 'Finished';
                }
                if(uid.Finished_Date__c==null){
                    uid.Finished_Date__c = System.today();
                }
                upsert uid;
                responseMessage = 'success';
            } 
        } else if(respMap.get('Quantity')==0 && respMap.get('FinishedDate') ==null)
        {
            if(uid.Available_Qty_in_METRC__c == 0 && uid.Available_Qty__c == 0 && uid.Received_Qty__c> 0){
                DateTime actualDate = Datetime.now();
                String dateOutput = actualDate.format('yyyy-MM-dd');
                Metrc_HttpCalloutHelper.createPackageFinish(uid.Name,dateOutput);
                responseMessage = 'success';
            }
        }
        
        
      return responseMessage;
        
    }
}