force-app/main/default/objects/UID__c/UID__c.object-meta.xml
<CustomObject>
    <description>Unique Identifiers, RFID Tags from Track &amp; Trace</description>
    <label>UID</label>
    <nameField>
        <label>UID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>UIDs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UID__c/fields/Available_Qty__c.field-meta.xml
<CustomField>
    <fullName>Available_Qty__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Exclude Location:  CannaWaste, Delivered, Packaged, Quarantine, Test Sampled, Transferred</inlineHelpText>
    <label>Available Qty</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/UID__c/fields/Available_Qty_in_METRC__c.field-meta.xml
<CustomField>
    <fullName>Available_Qty_in_METRC__c</fullName>
    <label>Available Qty in METRC</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/UID__c/fields/Received_Qty__c.field-meta.xml
<CustomField>
    <fullName>Received_Qty__c</fullName>
    <label>Received Qty</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ScheduleUIDFinishTest.cls
@isTest(SeeAllData=false)
public class ScheduleUIDFinishTest {
    static testmethod void uidFinishTest() 
    {
        /*String CRON_EXP = '0 0 0 15 3 ? *';
        
        // Create your test data
       

        Test.startTest();
        UID__c  uid   = new UID__c();
        uid.Name ='1A4FF0300000029000000083';
        uid.Available_Qty_in_METRC__c = 0;
        uid.Active__c = true;
        uid.Available_Qty__c = 0;
        uid.Received_Qty__c = 20;
        insert uid;
        String jobId = System.schedule('ScheduleUIDFinishTest',  CRON_EXP, new ScheduleUIDFinish());
        CronTrigger ct = [SELECT Id, CronExpression, TimesTriggered, NextFireTime FROM CronTrigger WHERE id = :jobId];
        System.assertEquals(CRON_EXP, ct.CronExpression);
        System.assertEquals(0, ct.TimesTriggered);
        
        Test.stopTest();
        // Add assert here to validate result*/
    }
}