force-app/main/default/objects/Driver__c/Driver__c.object-meta.xml
<CustomObject>
    <label>driver</label>
    <nameField>
        <label>Driver Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>drivers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Shipping_Manifest__c/Shipping_Manifest__c.object-meta.xml
<CustomObject>
    <description>Used in the generation of compliance document to enable retail delivery.</description>
    <label>Shipping Manifest</label>
    <nameField>
        <displayFormat>SM-{YYYY}-{MM}-{0000000000}</displayFormat>
        <label>Shipping Manifest</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipping Manifests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Shipping_Manifest__c/fields/Actual_Arrival_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Actual_Arrival_Date_Time__c</fullName>
    <label>Actual Arrival Date &amp; Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Shipping_Manifest__c/fields/Driver__c.field-meta.xml
<CustomField>
    <fullName>Driver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Driver</label>
    <referenceTo>Drivers__c</referenceTo>
    <relationshipLabel>Shipping Manifests</relationshipLabel>
    <relationshipName>Shipping_Manifests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipping_Manifest__c/fields/Planned_Ship_Transfer_Date__c.field-meta.xml
<CustomField>
    <fullName>Planned_Ship_Transfer_Date__c</fullName>
    <inlineHelpText>Date in which the products are to be delivered</inlineHelpText>
    <label>Planned Ship/Transfer Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Shipping_Manifest__c/fields/Receiver_Acceptance_Date__c.field-meta.xml
<CustomField>
    <fullName>Receiver_Acceptance_Date__c</fullName>
    <inlineHelpText>Date Which Receiver Accepted Retail Shipment</inlineHelpText>
    <label>Receiver Acceptance Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Shipping_Manifest__c/fields/Route_Miles__c.field-meta.xml
<CustomField>
    <fullName>Route_Miles__c</fullName>
    <description>(Distance(Distributor_License__r.License_Location__c , Receiver_License__r.License_Location__c , &apos;mi&apos;)*1.3)</description>
    <formula>Total_Route_Miles__c *2</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Round Trip Miles</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Shipping_Manifest__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
            <value>
                <fullName>Shipment Pending</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Pending Delivery</fullName>
            </value>
            <value>
                <fullName>Shipment Complete</fullName>
            </value>
            <value>
                <fullName>In-Transit</fullName>
            </value>
            <value>
                <fullName>Received</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
                <isActive>false</isActive>
                <label>Submitted</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Shipping_Manifest__c/fields/Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Vehicle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vehicle</label>
    <referenceTo>Vehicles__c</referenceTo>
    <relationshipLabel>Shipping Manifests</relationshipLabel>
    <relationshipName>Shipping_Manifests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipping_Manifest__c/fields/Vehicle_Model__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Model__c</fullName>
    <formula>TEXT(Vehicle__r.Vehicle_Model__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Vehicle Model</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Shipping_Manifest__c/recordTypes/RSM.recordType-meta.xml
<RecordType>
    <fullName>RSM</fullName>
    <active>true</active>
    <description>Used for Retail Shipments - Ship Confirm to &quot;Delivered&quot; Inventory Location, Rename to &quot;Retail&quot;</description>
    <label>RSM</label>
</RecordType>

force-app/main/default/objects/Shipping_Manifest_Line__c/Shipping_Manifest_Line__c.object-meta.xml
<CustomObject>
    <label>Shipping Manifest Line</label>
    <nameField>
        <displayFormat>SML-{0000000000}</displayFormat>
        <label>SM Line</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipping Manifest Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Shipping_Manifest_Line__c/fields/Shipping_Manifest__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Manifest__c</fullName>
    <label>Shipping Manifest</label>
    <referenceTo>Shipping_Manifest__c</referenceTo>
    <relationshipLabel>Shipping Manifest Lines</relationshipLabel>
    <relationshipName>Shipping_Manifest_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Vehicles__c/Vehicles__c.object-meta.xml
<CustomObject>
    <label>Vehicle</label>
    <nameField>
        <label>Vehicle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehicles__c/fields/Vehicle_Cubic_Volume_Capacity__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Cubic_Volume_Capacity__c</fullName>
    <formula>Vehicle_Height__c *  Vehicle_Width__c *  Vehicle_Length__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Vehicle Cubic Volume Capacity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Vehicles__c/fields/Vehicle_Height__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Height__c</fullName>
    <label>Vehicle Height</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Vehicles__c/fields/Vehicle_in_Use__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_in_Use__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Vehicle in Use</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Vehicles__c/fields/Vehicle_Length__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Length__c</fullName>
    <label>Vehicle Length</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Vehicles__c/fields/Vehicle_License_Plate_Number__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_License_Plate_Number__c</fullName>
    <label>Vehicle LPN</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehicles__c/fields/Vehicle_Make__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Make__c</fullName>
    <label>Vehicle Make</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Chevrolet</fullName>
            </value>
            <value>
                <fullName>Dodge</fullName>
            </value>
            <value>
                <fullName>Ford</fullName>
            </value>
            <value>
                <fullName>Generic</fullName>
            </value>
            <value>
                <fullName>GM</fullName>
            </value>
            <value>
                <fullName>Isuzu</fullName>
            </value>
            <value>
                <fullName>Mercedes</fullName>
            </value>
            <value>
                <fullName>Nissan</fullName>
            </value>
            <value>
                <fullName>Subaru</fullName>
            </value>
            <value>
                <fullName>Toyota</fullName>
            </value>
            <value>
                <fullName>Zenith</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vehicles__c/fields/Vehicle_Model__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Model__c</fullName>
    <label>Vehicle Model</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Chevy Express</fullName>
            </value>
            <value>
                <fullName>Connect</fullName>
            </value>
            <value>
                <fullName>F150</fullName>
            </value>
            <value>
                <fullName>Forester XT</fullName>
            </value>
            <value>
                <fullName>Generic</fullName>
            </value>
            <value>
                <fullName>NV200</fullName>
            </value>
            <value>
                <fullName>Prius Hybrid</fullName>
            </value>
            <value>
                <fullName>ProMaster 1500</fullName>
            </value>
            <value>
                <fullName>Sprinter</fullName>
            </value>
            <value>
                <fullName>T1500</fullName>
            </value>
            <value>
                <fullName>Transit</fullName>
            </value>
            <value>
                <fullName>GMC 1500</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vehicles__c/fields/Vehicle_Width__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Width__c</fullName>
    <label>Vehicle Width</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/AssignVehicleController.cls
/**
 * Copyright (c) 2018 Filigreen Distro
 * All rights reserved.
 * AssignVehicleController
 */
public class AssignVehicleController{

    private ApexPages.StandardController stdController;
    public Shipping_Manifest__c rsmObj {get; set;}
    public List<Shipping_Manifest__c> rsmList {get; set;}
    public List<Shipping_Manifest__c> tsmList {get; set;}
    public Vehicles__c vehicleObj {get; set;}
    public Integer totalProduct {get; set;}
    private Id rsmRecordTypeId;
    private Id tsmRecordTypeId;
    
    // Standard controller constructor
    public AssignVehicleController(ApexPages.StandardController controller) {
        this.stdController = controller;
        rsmObj = (Shipping_Manifest__c)stdController.getRecord();
        rsmRecordTypeId = ShippinManifestSupport.getRSMRecordTypeId();
        tsmRecordTypeId = ShippinManifestSupport.getTSMRecordTypeId();
        reset();
    }
    
    //  Default constructor
    public AssignVehicleController() {
        reset();
    }
    
    // reset variables
    public void reset(){
        if(rsmObj == null){
            rsmObj = new Shipping_Manifest__c();
        }
        rsmList = new List<Shipping_Manifest__c>();
        tsmList = new List<Shipping_Manifest__c>();
        vehicleObj = new Vehicles__c();
    }
    public class UserException extends Exception{ }
    
    /**
     * Assign Vehicle to RSM
     *
     * @return PageReference of RSM detail page
     */
    public PageReference assignVehicle() {
        
        PageReference pageRef = null;
        
        // Perform validations for required field Vehicle
        if(checkValidation()){
            return pageRef;
        }
        
        try {
            
            // Set status as shipment pending if both vehicle and driver are assigned to SM
            // Otherwise set status as Draft
            if(rsmObj.Status__c != RSMSupport.STATUS_SHIPMENT_COMPLETE){
                if(rsmObj.Driver__c != null && rsmObj.Vehicle__c != null){
                    // RSM status should not be In Transit
                    if(rsmObj.Status__c != RSMSupport.STATUS_IN_TRANSIT){
                        rsmObj.Status__c = RSMSupport.STATUS_SHIPMENT_PENDING;
                    }
                }else{
                    rsmObj.Status__c = RSMSupport.STATUS_DRAFT;
                }
            }
            update rsmObj;
        } 
        catch (Exception ex){
            ErrorLogs.log('AssignVehicleController:assignVehicle()', 
                          ex.getStackTraceString(), ex.getMessage());
            ApexPages.Message msg = new ApexPages.Message(ApexPages.Severity.ERROR,ex.getMessage());
            ApexPages.addMessage(msg);
            return null;
        }
        return redirectToRSM();
    }

    /**
     * Retrieve RSM with lines record
     *
     * @return blank page reference
     */         
    public PageReference doPrepare() {
        if(rsmObj != null && rsmObj.Id != null){
            
            // Retrieve RSM details
            rsmObj = [Select Name,
                             Vehicle__c,
                             Driver__c,
                             Planned_Ship_Transfer_Date__c,
                             Status__c,
                             (Select Id from Shipping_Manifest_Lines__r) 
                      From Shipping_Manifest__c
                      Where Id =: rsmObj.Id];
            totalProduct = rsmObj.Shipping_Manifest_Lines__r.size();
            retrieveVehicleAndRelatedRSMs();
        }
        return null;
    }
    
    /**
     * Retrieve Vehicle details and list of RSMs associated with Vehicle
     *
     * @return blank page reference
     */         
    public PageReference retrieveVehicleAndRelatedRSMs() {
        reset();
        if(rsmObj.Vehicle__c != null){
            vehicleObj = [Select Name, 
                                Vehicle_Cubic_Volume_Capacity__c,
                                Vehicle_Height__c,
                                Vehicle_in_Use__c,
                                Vehicle_Length__c,
                                Vehicle_License_Plate_Number__c,
                                Vehicle_Make__c,
                                Vehicle_Model__c,
                                Vehicle_Width__c
                        From Vehicles__c
                        Where Id =: rsmObj.Vehicle__c];
                        
            Date plannedDate = rsmObj.Planned_Ship_Transfer_Date__c;
            Id vehicleObjId = vehicleObj.Id;
            
            String rsmQuery = 'Select Name, ' +
                                   'Vehicle__c,Driver__c, ' +
                                   'Planned_Ship_Transfer_Date__c, ' +
                                   'Status__c, Route_Miles__c,' +
                                   'Actual_Departure_Date_Time__c, ' +
                                   'Receiver_Acceptance_Date__c ' +
                              'From Shipping_Manifest__c ' +
                              'Where Vehicle__c =: vehicleObjId ' +
                              'AND RecordTypeId =: rsmRecordTypeId ';
            if(rsmObj.Id != null){
                rsmQuery += 'AND Planned_Ship_Transfer_Date__c =: plannedDate ';
            }
            rsmQuery += 'Order By Receiver_Acceptance_Date__c DESC NULLS FIRST';
            rsmList = Database.query(rsmQuery);
            
            String tsmQuery = 'Select Name, ' +
                                   'Vehicle__c,Driver__c, ' +
                                   'Planned_Ship_Transfer_Date__c, ' +
                                   'Status__c, Route_Miles__c,' +
                                   'Actual_Departure_Date_Time__c, ' +
                                   'Actual_Arrival_Date_Time__c ' +
                              'From Shipping_Manifest__c ' +
                              'Where Vehicle__c =: vehicleObjId ' +
                              'AND RecordTypeId =: tsmRecordTypeId ';
            if(rsmObj.Id != null){
                tsmQuery += 'AND Planned_Ship_Transfer_Date__c =: plannedDate ';
            }
            tsmQuery += 'Order By Actual_Arrival_Date_Time__c DESC NULLS FIRST';
            tsmList = Database.query(tsmQuery);
        }
        return null;
    }
    
    /**
     * Check validation to create invoice
     *
     * @return Boolean flag to indicate if any validation fails
     */
    public Boolean checkValidation(){
        
        ApexPages.Message message;
        Boolean hasValidationError = false;
        
        // Check for Vehicle value
        if(rsmObj.Id != null && rsmObj.Vehicle__c == null){
            hasValidationError = true;
            message = new ApexPages.Message(ApexPages.Severity.ERROR, Label.Select_Vehicle);
            ApexPages.addMessage(message);
        }
        return hasValidationError;
    }
    
    /**
     * Cancel action - Redirect to RSM detail page
     *
     * @return PageReference
     */
    public PageReference cancelAction() {
        return redirectToRSM();
    }
    
    /**
     * Redirect to RSM detail page
     *
     * @return PageReference
     */         
    public PageReference redirectToRSM() {
        PageReference pageRef = null;
        if(stdController != null){
            pageRef = stdController.view().setRedirect(true);
        }
        return pageRef;
    }
}