force-app/main/default/objects/Driver__c/Driver__c.object-meta.xml
<CustomObject>
    <label>driver</label>
    <nameField>
        <label>Driver Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>drivers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Drivers__c/Drivers__c.object-meta.xml
<CustomObject>
    <label>Driver</label>
    <nameField>
        <label>Driver Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Drivers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Shipping_Manifest__c/Shipping_Manifest__c.object-meta.xml
<CustomObject>
    <description>Used in the generation of compliance document to enable retail delivery.</description>
    <label>Shipping Manifest</label>
    <nameField>
        <displayFormat>SM-{YYYY}-{MM}-{0000000000}</displayFormat>
        <label>Shipping Manifest</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipping Manifests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Shipping_Manifest__c/fields/Driver__c.field-meta.xml
<CustomField>
    <fullName>Driver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Driver</label>
    <referenceTo>Drivers__c</referenceTo>
    <relationshipLabel>Shipping Manifests</relationshipLabel>
    <relationshipName>Shipping_Manifests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipping_Manifest__c/fields/drivers__c.field-meta.xml
<CustomField>
    <fullName>drivers__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>driver</label>
    <referenceTo>Driver__c</referenceTo>
    <relationshipLabel>Shipping Manifests</relationshipLabel>
    <relationshipName>Shipping_Manifests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipping_Manifest__c/fields/Metrc_Manifest__c.field-meta.xml
<CustomField>
    <fullName>Metrc_Manifest__c</fullName>
    <label>Metrc Manifest#</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Shipping_Manifest__c/fields/Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Vehicle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vehicle</label>
    <referenceTo>Vehicles__c</referenceTo>
    <relationshipLabel>Shipping Manifests</relationshipLabel>
    <relationshipName>Shipping_Manifests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipping_Manifest_Line__c/Shipping_Manifest_Line__c.object-meta.xml
<CustomObject>
    <label>Shipping Manifest Line</label>
    <nameField>
        <displayFormat>SML-{0000000000}</displayFormat>
        <label>SM Line</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipping Manifest Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Shipping_Manifest_Line__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Name</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Shipping Manifest Lines</relationshipLabel>
    <relationshipName>Shipping_Manifest_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipping_Manifest_Line__c/fields/Shipment_Qty__c.field-meta.xml
<CustomField>
    <fullName>Shipment_Qty__c</fullName>
    <label>Shipment Qty</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Shipping_Manifest_Line__c/fields/Shipping_Manifest__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Manifest__c</fullName>
    <label>Shipping Manifest</label>
    <referenceTo>Shipping_Manifest__c</referenceTo>
    <relationshipLabel>Shipping Manifest Lines</relationshipLabel>
    <relationshipName>Shipping_Manifest_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Vehicles__c/Vehicles__c.object-meta.xml
<CustomObject>
    <label>Vehicle</label>
    <nameField>
        <label>Vehicle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/AssignDriverVehicleToSMCtlrTest.cls
@isTest
public class AssignDriverVehicleToSMCtlrTest {
    static Drivers__c driverObj;
    static Vehicles__c vehicleObj;
    static Shipping_Manifest__c sm;
    static Shipping_Manifest_Line__c sml;
    @TestSetUp
    static void testDataSetUp(){
        Test.setMock(HttpCalloutMock.class, new StateLicense_MockResponseTest());
        TestUtilData.skipTrigger = true;
        TestUtilData.createTestData();
    }
	@isTest
    private static void runTest(){
        updateAndCreateData();
        
        ApexPages.StandardController sc = new ApexPages.StandardController(sm);
        AssignDriverVehicleToSMCtlr assignDriverVehicleSM = new AssignDriverVehicleToSMCtlr(sc);
        assignDriverVehicleSM.cancelAction();
        
        
        AssignDriverVehicleToSMCtlr.init(sm.Id);
        AssignDriverVehicleToSMCtlr.assignDriverVehicle(sm,'08:00AM','08:00PM');
        AssignDriverVehicleToSMCtlr.retrieveDriverVehicleAndRelated(sm,vehicleObj.id,driverObj.id,''+System.today());
    }
    public static void updateAndCreateData(){
        sm = new Shipping_Manifest__c();
        sm.Metrc_Manifest__c= '1234';
        insert sm;
        sml = new Shipping_Manifest_Line__c();
        sml.Shipment_Qty__c= 20.89;
        sml.Shipping_Manifest__c =sm.Id;
        insert sml;
        List<Shipping_Manifest_Line__c> line = new List<Shipping_Manifest_Line__c>();
        Product2 prd = [select id from Product2 limit 1];
        for(Integer i=0; i <28 ; i++) {
            Shipping_Manifest_Line__c smLine = new Shipping_Manifest_Line__c();
            smLine.Product_Name__c	= prd.Id;
            smLine.Shipment_Qty__c = i;
            smLine.Shipping_Manifest__c = sm.Id;
            line.add(smLine);
            
        }
        insert line;
        // Create Vehicle
        vehicleObj = TestUtilData.createVehicle(true);
        
        // Create Driver
        driverObj = TestUtilData.createDriver(true);
        sm.Vehicle__c=vehicleObj.id;
        sm.Driver__c=driverObj.Id;
        update sm;
    }
}