force-app/main/default/objects/Order_Revision__c/Order_Revision__c.object-meta.xml
<CustomObject>
    <label>Order Revision</label>
    <nameField>
        <displayFormat>OR-{000000}</displayFormat>
        <label>Order Revision Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Revisions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Revision__c/fields/Revision_Reason__c.field-meta.xml
<CustomField>
    <fullName>Revision_Reason__c</fullName>
    <label>Revision Reason</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/PublishOrderRevisonsToSlackTest.cls
@isTest
public class PublishOrderRevisonsToSlackTest {
 @isTest
    private static void runTest(){
        Test.setMock(HttpCalloutMock.class, new StateLicense_MockResponseTest());  
        TestUtilData.skipTrigger = true;
        TestUtilData.createTestData();
       
    List<Id>Lstord = new List<Id>();
        Order_Revision__c ord = new Order_Revision__c();
        ord.Revision_Reason__c = ' Reschedule by Customer';
        insert ord;
        Lstord.add(ord.id);
        PublishOrderRevisonsToSlack.publishToSlack(Lstord);
    }
}