force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <displayFormat>O-{000000}</displayFormat>
        <label>Order #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Order_Type__c.field-meta.xml
<CustomField>
    <fullName>Order_Type__c</fullName>
    <description>Type of order created from community</description>
    <inlineHelpText>Order from Community</inlineHelpText>
    <label>Order Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Order_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/Retailer__c.field-meta.xml
<CustomField>
    <fullName>Retailer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Retailer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Retailer_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Retailer_DBA__c.field-meta.xml
<CustomField>
    <fullName>Retailer_DBA__c</fullName>
    <formula>Retailer__r.DBA__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Retailer DBA</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Cancelled by Customer</fullName>
            </value>
            <value>
                <fullName>Cancelled by WOVN</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Payment</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Returned</fullName>
            </value>
            <value>
                <fullName>Shipped</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/Total__c.field-meta.xml
<CustomField>
    <fullName>Total__c</fullName>
    <label>Total Price</label>
    <summarizedField>Order_Line_Item__c.Total__c</summarizedField>
    <summaryForeignKey>Order_Line_Item__c.Order__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Total_Line_Items__c.field-meta.xml
<CustomField>
    <fullName>Total_Line_Items__c</fullName>
    <label>Total Line Items</label>
    <summaryForeignKey>Order_Line_Item__c.Order__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Order_Line_Item__c/Order_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Order Line Item</label>
    <nameField>
        <displayFormat>OLI-{0000000}</displayFormat>
        <label>Order Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Line_Item__c/fields/Line_Total_Qty__c.field-meta.xml
<CustomField>
    <fullName>Line_Total_Qty__c</fullName>
    <formula>MOQ__c * Quantity_Cases__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Line Total Qty</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order_Line_Item__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Order Line Items</relationshipLabel>
    <relationshipName>Order_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order_Line_Item__c/fields/Order_Type__c.field-meta.xml
<CustomField>
    <fullName>Order_Type__c</fullName>
    <formula>Order__r.RecordType.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Order Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Line_Item__c/fields/OrderLine_Status__c.field-meta.xml
<CustomField>
    <fullName>OrderLine_Status__c</fullName>
    <label>OrderLine Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Shipment Complete</fullName>
            </value>
            <value>
                <fullName>Cancelled by WOVN</fullName>
            </value>
            <value>
                <fullName>Cancelled by Customer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order_Line_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order_Line_Item__c/fields/Total__c.field-meta.xml
<CustomField>
    <fullName>Total__c</fullName>
    <formula>Line_Total_Cost__c +  Line_Total_Excise_Tax__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Line Total Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/AutoCancelOrdersEmailTemplateController.cls
public class AutoCancelOrdersEmailTemplateController {
    
    public List<Order__c> orders {set;get;}
    
    String statusDraft = FiligreenConfigurationUtility.getConfigValueByObjectAndKey('Order','Order_Status_Draft');
    String statusPending = FiligreenConfigurationUtility.getConfigValueByObjectAndKey('Order','Order_Status_Pending');
    private static Integer AUTO_CANCEL_DAYS_DRAFT{
        get{
            return AUTO_CANCEL_DAYS_DRAFT != null ? AUTO_CANCEL_DAYS_DRAFT : Integer.valueOf(FiligreenConfigurationUtility.getConfigValueByObjectAndKey('Order','Auto_Cancel_Days_Draft'));
        }set;
    }
    private static Integer AUTO_CANCEL_DAYS_PENDING{
        get{
            return AUTO_CANCEL_DAYS_PENDING != null ? AUTO_CANCEL_DAYS_PENDING : Integer.valueOf(FiligreenConfigurationUtility.getConfigValueByObjectAndKey('Order','Auto_Cancel_Days_Pending'));
        }set;
    }
    
    public AutoCancelOrdersEmailTemplateController(){
        orders = new List<Order__c>();
        List<Order__c> lstOrd = [SELECT Id,lastmodifieddate,Status__c,Name,Retailer__r.Name,Retailer_DBA__c,
                                 Order_Type__c,Total__c,Total_Line_Items__c,
                                 (SELECT Id,Name,OrderLine_Status__c,Line_Total_Qty__c FROM Order_Line_Items__r)
                                 FROM Order__c WHERE Status__c IN (:statusDraft,:statusPending) ORDER BY createdDate ASC];
        if(lstOrd.size() > 0){
            List<string>holidayList = new List<string>();
            for(Holiday  businessHolidDay : [SELECT IsRecurrence,ActivityDate,RecurrenceMonthOfYear,RecurrenceEndDateOnly,RecurrenceInstance,RecurrenceDayOfWeekMask,RecurrenceInterval,RecurrenceType FROM Holiday]){
                if(businessHolidDay.IsRecurrence){
                    holidayList.addAll(BatchToAutoCancelOrders.getAllRecurrenceHoliday(businessHolidDay));
                }else{
                    holidayList.add(String.valueOf(businessHolidDay.ActivityDate)/*getDateStr(businessHolidDay.ActivityDate)*/);   
                }    
            }
            
            List<Order__c> updateOrderList = new LIst<Order__c>();
            List<Order_Line_Item__c> updateOLIList = new LIst<Order_Line_Item__c>();
                
            for(Order__c ord: lstOrd){
                Integer allDaysBetween = ord.lastmodifieddate.Date().daysBetween(Date.today());
                Integer allWorkingDays = 0;
                for(Integer k=0;k<allDaysBetween ;k++ ){
                    if(checkifItisWorkingDay(ord.lastmodifieddate.Date().addDays(k),holidayList)){
                        allWorkingDays++;
                    }
                }
                if(ord.Status__c == statusDraft && allWorkingDays > AUTO_CANCEL_DAYS_DRAFT){
                    orders.add(ord);
                } else if(ord.Status__c == statusPending && allWorkingDays > AUTO_CANCEL_DAYS_PENDING){
                    orders.add(ord);
                } 
            }
        }
    }
    
    public boolean checkifItisWorkingDay(Date currentDate,List<String> holidays){
        Date weekStart  = currentDate.toStartofWeek();
        for(String hDay : holidays){
            if(currentDate.daysBetween(Date.valueOf(hDay)) == 0){
                return false;
            }
        }
        if(weekStart.daysBetween(currentDate) ==0 || weekStart.daysBetween(currentDate) == 6){
            return false;
        } else
            return true;
    }
}