force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <displayFormat>O-{000000}</displayFormat>
        <label>Order #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Order_Date__c.field-meta.xml
<CustomField>
    <fullName>Order_Date__c</fullName>
    <label>Order Date</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Request_Ship_Date__c.field-meta.xml
<CustomField>
    <fullName>Request_Ship_Date__c</fullName>
    <label>Request Ship Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Requested_Delivery_Earliest_Time__c.field-meta.xml
<CustomField>
    <fullName>Requested_Delivery_Earliest_Time__c</fullName>
    <label>Requested Delivery Earliest Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Requested_Delivery_Latest_Time__c.field-meta.xml
<CustomField>
    <fullName>Requested_Delivery_Latest_Time__c</fullName>
    <label>Requested Delivery Latest Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Cancelled by Customer</fullName>
            </value>
            <value>
                <fullName>Cancelled by WOVN</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Payment</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Returned</fullName>
            </value>
            <value>
                <fullName>Shipped</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/recordTypes/Brand.recordType-meta.xml
<RecordType>
    <fullName>Brand</fullName>
    <active>true</active>
    <description>Used when origin of order is from Brand</description>
    <label>Brand</label>
</RecordType>

force-app/main/default/classes/BatchToDeleteDraftOrdersTest.cls
@isTest
public class BatchToDeleteDraftOrdersTest {
	 @isTest
    Public static void Check(){
        list<Order__c> oList = new list<Order__c>();
        
        Id productRecordTypeId = Schema.SObjectType.Order__c.getRecordTypeInfosByDeveloperName()
                          .get('Brand').getRecordTypeId();
        
        
        Order__c o = new Order__c();
        o.Status__c='Draft';
        o.RecordTypeId = productRecordTypeId;
        o.Order_Date__c =system.today();
        DateTime dt = System.now();
        Time myTime = Time.newInstance(dt.hour(), dt.minute(), dt.second(), dt.millisecond());
        o.Requested_Delivery_Earliest_Time__c=myTime;
        o.Requested_Delivery_Latest_Time__c=myTime;
        o.Request_Ship_Date__c=system.today();
        oList.add(o);
         
        insert oList;
       
        
        Test.startTest();
        BatchToDeleteDraftOrders obj =new BatchToDeleteDraftOrders();
        DataBase.executeBatch(obj); 
        //obj.execute();
        String sch = '0 0 23 * * ?';
        system.schedule('Test status Check', sch, obj );
        Test.stopTest();
    }
}