force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <displayFormat>O-{000000}</displayFormat>
        <label>Order #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/recordTypes/Brand.recordType-meta.xml
<RecordType>
    <fullName>Brand</fullName>
    <active>true</active>
    <description>Used when origin of order is from Brand</description>
    <label>Brand</label>
</RecordType>

force-app/main/default/objects/Order_Revision__c/Order_Revision__c.object-meta.xml
<CustomObject>
    <label>Order Revision</label>
    <nameField>
        <displayFormat>OR-{000000}</displayFormat>
        <label>Order Revision Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Revisions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Revision__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Order Revisions</relationshipLabel>
    <relationshipName>Order_Revisions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Revision__c/fields/Reason_code__c.field-meta.xml
<CustomField>
    <fullName>Reason_code__c</fullName>
    <label>Reason Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Missed Delivery Window</fullName>
            </value>
            <value>
                <fullName>Invoice Collection Issue</fullName>
            </value>
            <value>
                <fullName>Retailer Requests Reschedule</fullName>
            </value>
            <value>
                <fullName>Requires METRC Adjustments</fullName>
            </value>
            <value>
                <fullName>Brand Requests Reschedule</fullName>
            </value>
            <value>
                <fullName>Route Compromised</fullName>
            </value>
            <value>
                <fullName>Clerical Error</fullName>
            </value>
            <value>
                <fullName>Incorrectly Entered Order</fullName>
            </value>
            <value>
                <fullName>Incorrectly Packed Order</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order_Revision__c/fields/Shipping_Manifest__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Manifest__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Shipping Manifest</label>
    <referenceTo>Shipping_Manifest__c</referenceTo>
    <relationshipLabel>Order Revisions</relationshipLabel>
    <relationshipName>Order_Revisions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipping_Manifest__c/Shipping_Manifest__c.object-meta.xml
<CustomObject>
    <description>Used in the generation of compliance document to enable retail delivery.</description>
    <label>Shipping Manifest</label>
    <nameField>
        <displayFormat>SM-{YYYY}-{MM}-{0000000000}</displayFormat>
        <label>Shipping Manifest</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipping Manifests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Shipping_Manifest__c/fields/Actual_Arrival_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Actual_Arrival_Date_Time__c</fullName>
    <label>Actual Arrival Date &amp; Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Shipping_Manifest__c/fields/Ownership__c.field-meta.xml
<CustomField>
    <fullName>Ownership__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ownership</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Shipping Manifests as Ownership</relationshipLabel>
    <relationshipName>Shipping_Manifests3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/PublishOrderRevisonsToSlack.cls
public class PublishOrderRevisonsToSlack{
    public Static String CRM_Redirect_URL{
        get{
            return String.isNotBlank(CRM_Redirect_URL) ? CRM_Redirect_URL : FiligreenConfigurationUtility.getConfigValueByObjectAndKey('Order','CRM_Redirect_URL');
        }set;
    }   
    @InvocableMethod 
    public static void publishToSlack(List<Id> OrderRevisionId) {
        system.debug('OrderRevisionId'+OrderRevisionId);
        Set<id>smids = new set<id>();
        for(Order_Revision__c OrdRevR : [select Id,Order__r.name,Shipping_Manifest__r.Ownership__r.DBA__c,Shipping_Manifest__r.Receiver_City_State_Zip__c,
                                         Name,Order__c,Shipping_Manifest__r.Ownership__r.Name,Shipping_Manifest__r.Receiver_DBA__c,Shipping_Manifest__c,Notes__c,
                                         Shipping_Manifest__r.Ownership__c,Shipping_Manifest__r.Name,Shipping_Manifest__r.Actual_Departure_Date_Time__c,
                                         Shipping_Manifest__r.Actual_Arrival_Date_Time__c,	Reason_code__c	from Order_Revision__c where id IN: OrderRevisionId]){
                                             smids.add(OrdRevR.Shipping_Manifest__c);      
                                             
                                         }
        string depart; 
        List<Shipping_Manifest__History> SHM = [SELECT ParentId, OldValue, NewValue FROM Shipping_Manifest__History  where parentId =:smids AND Field = 'Actual_Departure_Date_Time__c'  ORDER BY CreatedDate DESC  Limit 1];
        
            
        
        for(Shipping_Manifest__History ss :SHM){
            if(ss.NewValue != null){
             datetime dt = datetime.valueOf(ss.NewValue);
            depart =dt.format('MM/dd/yyyy HH:mm a', 'PST');
            }
           
        }
        
        string OrderRevisionSlackMsg = '';
        for(Order_Revision__c ord : [select Id,Order__r.name,Shipping_Manifest__r.Ownership__r.DBA__c,Shipping_Manifest__r.Receiver_City_State_Zip__c, Name,Order__c,Shipping_Manifest__r.Ownership__r.Name,Shipping_Manifest__r.Receiver_DBA__c,Shipping_Manifest__c,Notes__c,Shipping_Manifest__r.Ownership__c,Shipping_Manifest__r.Name,Shipping_Manifest__r.Actual_Departure_Date_Time__c,Shipping_Manifest__r.Actual_Arrival_Date_Time__c,	Reason_code__c	from Order_Revision__c where id IN: OrderRevisionId]){
           
            OrderRevisionSlackMsg += 'Order Revision: <' + CRM_Redirect_URL + '/lightning/r/Order_Revision__c/' + ord.Id + '/view|' + ord.Name  + '>' + '\n';
            OrderRevisionSlackMsg += 'Order Number: <' + CRM_Redirect_URL + '/lightning/r/Order__c/' + ord.Order__r.Id + '/view|' + ord.Order__r.name  + '>' + '\n';
            OrderRevisionSlackMsg += 'Receiver DBA: ' +  ord.Shipping_Manifest__r.Receiver_DBA__c+ '\n';
            OrderRevisionSlackMsg += 'City: ' +  ord.Shipping_Manifest__r.Receiver_City_State_Zip__c+ '\n';
            OrderRevisionSlackMsg += 'Brand DBA: ' +ord.Shipping_Manifest__r.Ownership__r.DBA__c + '\n';
            if(depart !=null ){
                OrderRevisionSlackMsg += 'Last Depart Confirm: ' + depart + '\n';
            }  else{
                OrderRevisionSlackMsg += 'Last Depart Confirm: ' +  + '\n';
                
            }
            if(ord.Shipping_Manifest__r.Id  != null){
                OrderRevisionSlackMsg += 'Shipping Manifest: <' + CRM_Redirect_URL + '/lightning/r/Shipping_Manifest__c/' + ord.Shipping_Manifest__r.Id + '/view|' + ord.Shipping_Manifest__r.Name  + '>' + '\n';
                
            }else{
                OrderRevisionSlackMsg += 'Shipping Manifest: '+ + '\n';
                
            }if( ord.Reason_code__c !=null){
                OrderRevisionSlackMsg += 'Reason Code: ' + ord.Reason_code__c+ '\n';
                
            }else{
                OrderRevisionSlackMsg += 'Reason Code: ' + + '\n';
                
            }
            if( ord.Notes__c !=null){
                OrderRevisionSlackMsg += 'Notes: ' + ord.Notes__c+ '\n';
                
            }else{
                OrderRevisionSlackMsg += 'Notes: ' + + '\n';
                
            }
            
        }
        if(OrderRevisionSlackMsg != ''){
            OrderRevisionSlackMsg = OrderRevisionSlackMsg.removeEnd('\n');
            SlackIntegrationController.postMessage('Order Revision', OrderRevisionSlackMsg);
        }
      
   
}
}