force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <displayFormat>O-{000000}</displayFormat>
        <label>Order #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Cancelled by Customer</fullName>
            </value>
            <value>
                <fullName>Cancelled by WOVN</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Payment</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Returned</fullName>
            </value>
            <value>
                <fullName>Shipped</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AcceptRetailerOrderController.cls
//created Date : XXXXXXX

public class AcceptRetailerOrderController {
    public boolean isOrderUpdated{set;get;}
    public String message{set;get;}
    public AcceptRetailerOrderController(){
        isOrderUpdated = false;
    }
    public void acceptOrder(){
        String orderId = ApexPages.currentPage().getParameters().get('id');
        String objPrefix = Schema.getGlobalDescribe().get('Order__c').getDescribe().getKeyPrefix();
        if(String.isBlank(orderId) || !orderId.startsWith(objPrefix)){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'Order Id is not correct'));
        }else{
            try{
                if([SELECT Id, Status__c FROM Order__c WHERE Id = :orderId AND Status__c  IN ('Approved','Shipped')].size() > 0){
                    ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO,'Order is already Accepted.'));
                    return;
                }
                Order__c o = new Order__c(Id = orderId, Status__c  = 'Approved');
                update o;
                isOrderUpdated = true;
                message = 'Thanks for Approving the Order. To View Order Status and Shipment Tracking, log in to <a href="https://www.filigreen.com/b2b" target="_Blank">Filigreen</a>';
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO,message));
            }catch(Exception e){
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,e.getMessage()));
            }
        }
    }
}