force-app/main/default/objects/Brand_Quote__c/Brand_Quote__c.object-meta.xml
<CustomObject>
    <description>Buy Quote to Purchase from Brands. Sell Quotes to Sell to Dispensaries</description>
    <label>Brand Quote</label>
    <nameField>
        <displayFormat>BQ-{0000000000}</displayFormat>
        <label>Brand Quote</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Brand Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Brand_Quote__c/fields/BQ_Status__c.field-meta.xml
<CustomField>
    <fullName>BQ_Status__c</fullName>
    <inlineHelpText>Status will auto-updated based on workflow defined.</inlineHelpText>
    <label>BQ Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Shipped</fullName>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Brand_Quote__c/fields/Distributor_Contact__c.field-meta.xml
<CustomField>
    <fullName>Distributor_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Distributor Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Brand Quotes (Distributor Contact)</relationshipLabel>
    <relationshipName>Brand_Quotes2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Brand_Quote__c/fields/Distributor_License__c.field-meta.xml
<CustomField>
    <fullName>Distributor_License__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Distributor License</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>State_Licenses__c.License_Name__c</field>
            <operation>equals</operation>
            <valueField>$Source.Distributor_Name__c</valueField>
        </filterItems>
        <filterItems>
            <field>State_Licenses__c.State_License_Holder__c</field>
            <operation>equals</operation>
            <valueField>$Source.Distributor_Name__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>State_Licenses__c</referenceTo>
    <relationshipLabel>Brand Quotes (Distributor License)</relationshipLabel>
    <relationshipName>Brand_Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Brand_Quote__c/fields/Distributor_Name__c.field-meta.xml
<CustomField>
    <fullName>Distributor_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Distributor Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Brand Quotes as Distributor</relationshipLabel>
    <relationshipName>Brand_Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Brand_Quote__c/fields/Receiver_Contact__c.field-meta.xml
<CustomField>
    <fullName>Receiver_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Receiver Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Receiver_Name__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Brand Quotes (Receiver Contact)</relationshipLabel>
    <relationshipName>Brand_Quotes1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Brand_Quote__c/fields/Receiver_License__c.field-meta.xml
<CustomField>
    <fullName>Receiver_License__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Receiver License</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>State_Licenses__c.License_Name__c</field>
            <operation>equals</operation>
            <valueField>$Source.Receiver_Name__c</valueField>
        </filterItems>
        <filterItems>
            <field>State_Licenses__c.State_License_Holder__c</field>
            <operation>equals</operation>
            <valueField>$Source.Receiver_Name__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>State_Licenses__c</referenceTo>
    <relationshipLabel>Brand Sell Quotes</relationshipLabel>
    <relationshipName>Brand_Quotes1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Brand_Quote__c/fields/Receiver_Name__c.field-meta.xml
<CustomField>
    <fullName>Receiver_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Receiver Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Brand Quotes as Receiver</relationshipLabel>
    <relationshipName>Brand_Quotes2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Brand_Quote__c/fields/Supplier_Contact__c.field-meta.xml
<CustomField>
    <fullName>Supplier_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Supplier Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Brand Quotes</relationshipLabel>
    <relationshipName>Brand_Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Brand_Quote__c/fields/Supplier_License__c.field-meta.xml
<CustomField>
    <fullName>Supplier_License__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Supplier License</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>State_Licenses__c.License_Name__c</field>
            <operation>equals</operation>
            <valueField>$Source.Supplier_Name__c</valueField>
        </filterItems>
        <filterItems>
            <field>State_Licenses__c.State_License_Holder__c</field>
            <operation>equals</operation>
            <valueField>$Source.Supplier_Name__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>State_Licenses__c</referenceTo>
    <relationshipLabel>Brand Quotes</relationshipLabel>
    <relationshipName>Brand_Quotes2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Brand_Quote__c/fields/Supplier_Name__c.field-meta.xml
<CustomField>
    <fullName>Supplier_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Supplier Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Brand Quotes as Supplier</relationshipLabel>
    <relationshipName>Brand_Quotes1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/State_Licenses__c/State_Licenses__c.object-meta.xml
<CustomObject>
    <description>Object within the Account to track number of license and address as part of ship to.</description>
    <label>State License</label>
    <nameField>
        <displayFormat>SLID-{YYYY}-{MM}-{0000000000}</displayFormat>
        <label>License</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>State Licenses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/State_Licenses__c/fields/License_Name__c.field-meta.xml
<CustomField>
    <fullName>License_Name__c</fullName>
    <label>License Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>State Licenses</relationshipLabel>
    <relationshipName>State_Licenses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/State_Licenses__c/fields/License_Status__c.field-meta.xml
<CustomField>
    <fullName>License_Status__c</fullName>
    <inlineHelpText>License Status from State</inlineHelpText>
    <label>License Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
            <value>
                <fullName>Revoked</fullName>
            </value>
            <value>
                <fullName>Terminated</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DataCRUDUtility.cls
public class DataCRUDUtility{
    @Auraenabled
    public static String getRecordName(Id recordId){
        String objName = recordId.getSObjectType().getDescribe().getName();
        System.debug(objName);
        String q = 'SELECT Name FROM ' + objName + ' WHERE Id=\'' + recordId + '\'';
        List<SObject> records = Database.query(q);
        if(records.size()>0){
            return (String) (records[0].get('Name'));
        }
        return '';
    }
    @AuraEnabled
    public static StatusWithError getBQStatus(String recordId){
        Boolean isCancelled = false;
        Brand_Quote__c bq = [SELECT Id, BQ_Status__c,Name,
                             Distributor_Name__r.Id,Distributor_License__r.License_Name__r.Id,
                             Receiver_Name__r.Id,Receiver_License__r.License_Name__r.Id,
                             Supplier_Name__r.Id,Supplier_License__r.License_Name__r.Id,
                             Receiver_License__r.License_Status__c,Supplier_License__r.License_Status__c,
                             Distributor_License__r.License_Status__c,
                             Distributor_Contact__c,Receiver_Contact__c,Supplier_Contact__c,
                             Distributor_Contact__r.Active__c ,
                             Receiver_Contact__r.Active__c ,
                             Supplier_Contact__r.Active__c 
                             FROM Brand_Quote__c WHERE Id=:recordId];
        
        String misMatchData = '';
        if(String.isBlank(bq.Distributor_Name__c)){misMatchData = 'BlankDistributorName';}
        else if(String.isBlank(bq.Receiver_Name__c)){misMatchData = 'BlankReceiverName';}
        else if(String.isBlank(bq.Supplier_Name__c)){misMatchData = 'BlankSupplierName';}
        else if(String.isBlank(bq.Distributor_License__c)){misMatchData = 'BlankDistributorLC';}
        else if(String.isBlank(bq.Receiver_License__c)){misMatchData = 'BlankReceiverLC';}
        else if(String.isBlank(bq.Supplier_License__c)){misMatchData = 'BlankSupplierLC';}
        else if(bq.Distributor_Name__r.Id != bq.Distributor_License__r.License_Name__r.Id){misMatchData = 'Distributor';}
        else if(bq.Receiver_Name__r.Id != bq.Receiver_License__r.License_Name__r.Id){misMatchData = 'Receiver';}
        else if(bq.Supplier_Name__r.Id != bq.Supplier_License__r.License_Name__r.Id){misMatchData = 'Supplier';}
        else if(bq.BQ_Status__c != 'Approved' && bq.Distributor_License__r.License_Status__c  == 'Expired' ){misMatchData = 'DLInactive';}
        else if(bq.BQ_Status__c != 'Approved' && bq.Receiver_License__r.License_Status__c  == 'Expired' ){misMatchData = 'RLInactive';}
        else if(bq.BQ_Status__c != 'Approved' && bq.Supplier_License__r.License_Status__c  == 'Expired' ){misMatchData = 'SLInactive';}
        else if(bq.Distributor_Contact__c != null && bq.Distributor_Contact__r.Active__c == false){misMatchData = 'DCBlank';}
        else if(bq.Receiver_Contact__c != null && bq.Receiver_Contact__r.Active__c == false) {misMatchData = 'RCBlank';}
        else if(bq.Supplier_Contact__c != null && bq.Supplier_Contact__r.Active__c == false) {misMatchData = 'SCBlank';}
        else if(bq.BQ_Status__c == 'Cancelled'){ misMatchData = 'Status'; }
        
        StatusWithError wrpData = new StatusWithError();
        wrpData.misMatchData = misMatchData;
        wrpData.status = bq.BQ_Status__c;
        wrpData.recordName = bq.Name;

        return wrpData;
    }
    
    public class StatusWithError{
        @AuraEnabled public String misMatchData{set;get;}
        @AuraEnabled public String status{set;get;}
        @AuraEnabled public String recordName{set;get;}
        
        public StatusWithError(){
            this.misMatchData = '';
            this.status = '';
            this.recordName = '';
        }
    }
}