force-app/main/default/objects/Brand_Quote__c/Brand_Quote__c.object-meta.xml
<CustomObject>
    <description>Buy Quote to Purchase from Brands. Sell Quotes to Sell to Dispensaries</description>
    <label>Brand Quote</label>
    <nameField>
        <displayFormat>BQ-{0000000000}</displayFormat>
        <label>Brand Quote</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Brand Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Brand_Quote__c/fields/Planned_Ship_Date__c.field-meta.xml
<CustomField>
    <fullName>Planned_Ship_Date__c</fullName>
    <inlineHelpText>Planned Ship Date is based on Receiver Acceptance Date. Sell Quote approved before 10:00AM PST will ship next day. Sell Quotes approved after 10:00AM will ship next 48 hours.</inlineHelpText>
    <label>Planned Ship Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Brand_Quote_Line__c/Brand_Quote_Line__c.object-meta.xml
<CustomObject>
    <label>Brand Quote Line</label>
    <nameField>
        <displayFormat>BQLI-{0000000000}</displayFormat>
        <label>BQ Line</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Brand Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Brand_Quote_Line__c/fields/Brand_Quote_Number__c.field-meta.xml
<CustomField>
    <fullName>Brand_Quote_Number__c</fullName>
    <label>Brand Quote Number</label>
    <referenceTo>Brand_Quote__c</referenceTo>
    <relationshipLabel>Brand Quote Lines</relationshipLabel>
    <relationshipName>Brand_Quote_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Brand_Quote_Line__c/fields/MOQ__c.field-meta.xml
<CustomField>
    <fullName>MOQ__c</fullName>
    <description>MOQ - Minimum Order Quantity</description>
    <inlineHelpText>Minimum Order Quantity</inlineHelpText>
    <label>Qty per Case (MOQ)</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Brand_Quote_Line__c/fields/Retail_Wholesale_Price__c.field-meta.xml
<CustomField>
    <fullName>Retail_Wholesale_Price__c</fullName>
    <label>Retail Wholesale Price</label>
    <precision>16</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>IN-{0000000000}</displayFormat>
        <label>Invoice</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Brand_Quote__c.field-meta.xml
<CustomField>
    <fullName>Brand_Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Brand Quote</label>
    <referenceTo>Brand_Quote__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Invoice_Date__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Date__c</fullName>
    <defaultValue>Today()</defaultValue>
    <label>Invoice Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Order</label>
    <referenceTo>Sales_Order__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Subtotal_Local_Cannabis_Tax__c.field-meta.xml
<CustomField>
    <fullName>Subtotal_Local_Cannabis_Tax__c</fullName>
    <label>Subtotal Local Cannabis Tax</label>
    <summarizedField>Invoice_Line__c.Subtotal_Local_Cannabis_Tax__c</summarizedField>
    <summaryFilterItems>
        <field>Invoice_Line__c.InvoiceLine_Status__c</field>
        <operation>notEqual</operation>
        <value>Cancelled, Rejected</value>
    </summaryFilterItems>
    <summaryForeignKey>Invoice_Line__c.Invoice__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Invoice_Line__c/Invoice_Line__c.object-meta.xml
<CustomObject>
    <label>Invoice Line</label>
    <nameField>
        <displayFormat>INLI-{0000000000}</displayFormat>
        <label>Invoice Line</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_Line__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Invoice Lines</relationshipLabel>
    <relationshipName>Invoice_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice_Line__c/fields/Invoice_Qty__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Qty__c</fullName>
    <label>Invoice Qty</label>
    <precision>16</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Invoice_Line__c/fields/Line_Total_Product_Price__c.field-meta.xml
<CustomField>
    <fullName>Line_Total_Product_Price__c</fullName>
    <formula>if(TEXT( InvoiceLine_Status__c )  &lt;&gt; &apos;Rejected&apos;  &amp;&amp;  TEXT( InvoiceLine_Status__c )  &lt;&gt; &apos;Cancelled&apos;
, Retail_Wholesale_Price__c *  Invoice_Qty__c , 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Line Total Product Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice_Line__c/fields/MOQ__c.field-meta.xml
<CustomField>
    <fullName>MOQ__c</fullName>
    <formula>Sales_Order_Line__r.MOQ__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>MOQ</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Invoice_Line__c/fields/Quantity_Cases__c.field-meta.xml
<CustomField>
    <fullName>Quantity_Cases__c</fullName>
    <formula>Sales_Order_Line__r.Quantity_Cases__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Quantity or Cases</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Invoice_Line__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <formula>Sales_Order_Line__r.Sales_Order__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sales Order</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice_Line__c/fields/Sales_Order_Line__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Order Line</label>
    <referenceTo>Sales_Order_Line__c</referenceTo>
    <relationshipLabel>Invoice Lines</relationshipLabel>
    <relationshipName>Invoice_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice_Line__c/fields/Subtotal_Local_Cannabis_Tax__c.field-meta.xml
<CustomField>
    <fullName>Subtotal_Local_Cannabis_Tax__c</fullName>
    <label>Subtotal Local Cannabis Tax</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Sales_Order__c/Sales_Order__c.object-meta.xml
<CustomObject>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>SO-{0000000000}</displayFormat>
        <label>Sales Order</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Order__c/fields/Brand_Quote__c.field-meta.xml
<CustomField>
    <fullName>Brand_Quote__c</fullName>
    <label>Brand Quote</label>
    <referenceTo>Brand_Quote__c</referenceTo>
    <relationshipLabel>Sales Orders</relationshipLabel>
    <relationshipName>Sales_Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Sales_Order__c/fields/Delivery_City__c.field-meta.xml
<CustomField>
    <fullName>Delivery_City__c</fullName>
    <formula>Text(Receiver_License__r.License_City__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Delivery City</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Order__c/fields/Planned_Ship_Date__c.field-meta.xml
<CustomField>
    <fullName>Planned_Ship_Date__c</fullName>
    <inlineHelpText>Date in which the products are to be delivered</inlineHelpText>
    <label>Planned Ship Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Sales_Order_Line__c/Sales_Order_Line__c.object-meta.xml
<CustomObject>
    <label>Sales Order Line</label>
    <nameField>
        <displayFormat>SOLI-{0000000000}</displayFormat>
        <label>SO Line</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Order_Line__c/fields/Brand_Quote_Line__c.field-meta.xml
<CustomField>
    <fullName>Brand_Quote_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Brand Quote Line</label>
    <referenceTo>Brand_Quote_Line__c</referenceTo>
    <relationshipLabel>Sales Order Lines</relationshipLabel>
    <relationshipName>Sales_Order_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Order_Line__c/fields/MOQ__c.field-meta.xml
<CustomField>
    <fullName>MOQ__c</fullName>
    <formula>Brand_Quote_Line__r.MOQ__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Qty per Case (MOQ)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sales_Order_Line__c/fields/Qty_Ordered__c.field-meta.xml
<CustomField>
    <fullName>Qty_Ordered__c</fullName>
    <inlineHelpText>Qty per Case (MOQ) * Order Qty (Cases).</inlineHelpText>
    <label>Qty Ordered</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sales_Order_Line__c/fields/Quantity_Cases__c.field-meta.xml
<CustomField>
    <fullName>Quantity_Cases__c</fullName>
    <formula>Brand_Quote_Line__r.Quantity_Cases__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Order Qty (Cases)</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sales_Order_Line__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <label>Sales Order</label>
    <referenceTo>Sales_Order__c</referenceTo>
    <relationshipLabel>Sales Order Lines</relationshipLabel>
    <relationshipName>Sales_Order_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Tax_Table__c/Tax_Table__c.object-meta.xml
<CustomObject>
    <label>Tax Table</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>Tax Table Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tax Tables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tax_Table__c/fields/Actual_Tax_Rate_on_Product_Rev__c.field-meta.xml
<CustomField>
    <fullName>Actual_Tax_Rate_on_Product_Rev__c</fullName>
    <label>Actual Tax Rate on Product Rev</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Tax_Table__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Delivery_Cities</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Tax_Table__c/fields/Tax_Due_Rate__c.field-meta.xml
<CustomField>
    <fullName>Tax_Due_Rate__c</fullName>
    <label>Tax Due Rate</label>
    <precision>4</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Tax_Table__c/fields/Taxable_Gross_Receipts_Rate__c.field-meta.xml
<CustomField>
    <fullName>Taxable_Gross_Receipts_Rate__c</fullName>
    <label>Taxable Gross Receipts Rate</label>
    <precision>4</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/classes/LocalTaxCalculateHelper.cls
public class LocalTaxCalculateHelper {
    public static Map<String, Tax_Table__c > cityTaxMap{
        get{
            if(cityTaxMap == null){
                cityTaxMap = new Map<String, Tax_Table__c >();
                for(Tax_Table__c tt: [SELECT Id,Active__c ,Actual_Tax_Rate_on_Product_Rev__c ,City__c, End_Date__c , Start_Date__c , Taxable_Gross_Receipts_Rate__c, Tax_Due_Rate__c  FROM Tax_Table__c WHERE Active__c = true]){
                    cityTaxMap.put(tt.City__c,tt);
                }
            }
            return cityTaxMap;
        }set;
    }
    /*public static void calculateTaxOnCity(Sales_Order_Line__c [] newList, Map<Id,Sales_Order_Line__c > oldSOLineMap){
        Set<Id> SOIds = new Set<Id>();
        Map<Id,Sales_Order_Line__c[]>SOLinesMap = new Map<Id,Sales_Order_Line__c[]>();
        for(Sales_Order_Line__c SOL: newList){
            if(Trigger.isInsert || (Trigger.isUpdate && (SOL.Qty_Ordered__c  != oldSOLineMap.get(SOL.Id).Qty_Ordered__c  || SOL.Retail_Wholesale_Price__c  != oldSOLineMap.get(SOL.Id).Retail_Wholesale_Price__c))){
                if(SOLinesMap.containsKey(SOL.Sales_Order__c)){
                    SOLinesMap.get(SOL.Sales_Order__c ).add(SOL);
                }else{
                    SOLinesMap.put(SOL.Sales_Order__c , new Sales_Order_Line__c[]{SOL});
                }
                SOIds.add(SOL.Sales_Order__c);
            }
        }
        if(!SOIds.isEmpty()){
            Sales_Order__c[] SOrders = [SELECT Delivery_City__c, Planned_Ship_Date__c FROM Sales_Order__c WHERE Id IN:SOIds];
            for(Sales_Order__c SO: SOrders){
                Sales_Order_Line__c[] items  = SOLinesMap.get(SO.Id);
                if(cityTaxMap.containsKey(SO.Delivery_City__c)){
                    Tax_Table__c tt = cityTaxMap.get(SO.Delivery_City__c);
                    System.debug('###Tax_Table__c:::'+tt);
                    Decimal subTotal = 0;
                    decimal taxRateOnProd = tt.Actual_Tax_Rate_on_Product_Rev__c != null?tt.Actual_Tax_Rate_on_Product_Rev__c/100:0;
                    decimal taxableGrossReceiptsRate = tt.Taxable_Gross_Receipts_Rate__c != null?tt.Taxable_Gross_Receipts_Rate__c/100:0; 
                    decimal taxDueRate = tt.Tax_Due_Rate__c != null?tt.Tax_Due_Rate__c/100:0;
                    
                    if(!items.isEmpty() && tt != null && tt.End_Date__c >= SO.Planned_Ship_Date__c){
                        for(Sales_Order_Line__c SOL: items){
                            subTotal = SOL.Qty_Ordered__c * SOL.Retail_Wholesale_Price__c * taxableGrossReceiptsRate * taxDueRate;
                            if(taxRateOnProd > 0){
                                subTotal = subTotal * taxRateOnProd;
                            }
                            SOL.Subtotal_Local_Cannabis_Tax__c = subTotal;
                        }
                        
                    }else{
                        for(Sales_Order_Line__c SOL: items){
                            SOL.Subtotal_Local_Cannabis_Tax__c = 0;
                        }
                    }
                    
                }else{
                    for(Sales_Order_Line__c SOL: items){
                        SOL.Subtotal_Local_Cannabis_Tax__c = 0;
                    }
                }
            }
        }
    }
    public static void calculateTaxOnCity(Brand_Quote_Line__c[] newList, Map<Id,Brand_Quote_Line__c> oldBQLineMap){
        Set<Id> BQIds = new Set<Id>();
        Map<Id,Brand_Quote_Line__c[]>BQLinesMap = new Map<Id,Brand_Quote_Line__c[]>();
        for(Brand_Quote_Line__c BQL: newList){
            if(Trigger.isInsert || (Trigger.isUpdate && (BQL.MOQ__c != oldBQLineMap.get(BQL.Id).MOQ__c || BQL.Retail_Wholesale_Price__c  != oldBQLineMap.get(BQL.Id).Retail_Wholesale_Price__c || BQL.Quantity_Cases__c != oldBQLineMap.get(BQL.Id).Quantity_Cases__c ))){
                if(BQLinesMap.containsKey(BQL.Brand_Quote_Number__c)){
                    BQLinesMap.get(BQL.Brand_Quote_Number__c).add(BQL);
                }else{
                    BQLinesMap.put(BQL.Brand_Quote_Number__c, new Brand_Quote_Line__c[]{BQL});
                }
                BQIds.add(BQL.Brand_Quote_Number__c);
            }
        }
        if(!BQIds.isEmpty()){
            Brand_Quote__c [] BQs = [SELECT Delivery_City__c , Planned_Ship_Date__c FROM Brand_Quote__c WHERE Id IN :BQIds];
            for(Brand_Quote__c BQ: BQs){
                Brand_Quote_Line__c[] items = BQLinesMap.get(BQ.Id);
                if(cityTaxMap.containsKey(BQ.Delivery_City__c)){
                    Tax_Table__c tt = cityTaxMap.get(BQ.Delivery_City__c);
                    System.debug('###Tax_Table__c:::'+tt);
                    Decimal subTotal = 0;
                    decimal taxRateOnProd = tt.Actual_Tax_Rate_on_Product_Rev__c != null?tt.Actual_Tax_Rate_on_Product_Rev__c/100:0;
                    decimal taxableGrossReceiptsRate = tt.Taxable_Gross_Receipts_Rate__c != null?tt.Taxable_Gross_Receipts_Rate__c/100:0; 
                    decimal taxDueRate = tt.Tax_Due_Rate__c != null?tt.Tax_Due_Rate__c/100:0;
                    
                    if(!items.isEmpty() && tt != null && tt.End_Date__c >= BQ.Planned_Ship_Date__c){
                        for(Brand_Quote_Line__c BQL: items){
                            subTotal = BQL.MOQ__c * BQL.Quantity_Cases__c * BQL.Retail_Wholesale_Price__c  * taxableGrossReceiptsRate * taxDueRate;
                            if(taxRateOnProd > 0){
                                subTotal = subTotal * taxRateOnProd;
                            }
                            BQL.Subtotal_Local_Cannabis_Tax__c = subTotal;
                        }
                        
                    }else{
                        for(Brand_Quote_Line__c BQL: items){
                            BQL.Subtotal_Local_Cannabis_Tax__c = 0;
                        }
                    }
                    
                }else{
                    for(Brand_Quote_Line__c BQL: items){
                        BQL.Subtotal_Local_Cannabis_Tax__c = 0;
                    }
                }
            }
        }
        //MOQ__c * Quantity_Cases__c * Retail_Wholesale_Price__c 
    }
	*/
    public static void calculateTaxOnCity(Invoice_Line__c[] newList, Map<Id,Invoice_Line__c> oldInvoiceLineMap){
        Set<Id> invoiceIds = new Set<Id>();
        Map<Id,Invoice_Line__c[]>invoiceLinesMap = new Map<Id,Invoice_Line__c[]>();
        for(Invoice_Line__c IL: newList){
            if(Trigger.isInsert || (Trigger.isUpdate && (IL.Invoice_Qty__c !=  oldInvoiceLineMap.get(IL.Id).Invoice_Qty__c || IL.Retail_Wholesale_Price__c  !=  oldInvoiceLineMap.get(IL.Id).Retail_Wholesale_Price__c ))){
                if(invoiceLinesMap.containsKey(IL.Invoice__c)){
                    invoiceLinesMap.get(IL.Invoice__c).add(IL);
                }else{
                    invoiceLinesMap.put(IL.Invoice__c, new Invoice_Line__c[]{IL});
                }
                invoiceIds.add(IL.Invoice__c);
            }
        }
        if(!invoiceIds.isEmpty()){
            
            Invoice__c[] invoices = [SELECT Id, Invoice_Date__c ,Delivery_City__c FROM Invoice__c WHERE Id IN: invoiceIds];
            
            for(Invoice__c inv: invoices){
                Invoice_Line__c[] items = invoiceLinesMap.get(inv.Id);
                if(cityTaxMap.containsKey(inv.Delivery_City__c)){
                    Tax_Table__c tt = cityTaxMap.get(inv.Delivery_City__c);
                    System.debug('###Tax_Table__c:::'+tt);
                    Decimal subTotal = 0;
                    decimal taxRateOnProd = tt.Actual_Tax_Rate_on_Product_Rev__c != null?tt.Actual_Tax_Rate_on_Product_Rev__c/100:0;
                    decimal taxableGrossReceiptsRate = tt.Taxable_Gross_Receipts_Rate__c != null?tt.Taxable_Gross_Receipts_Rate__c/100:0; 
                    decimal taxDueRate = tt.Tax_Due_Rate__c != null?tt.Tax_Due_Rate__c/100:0;
                    
                    if(!items.isEmpty() && tt != null && tt.End_Date__c >= inv.Invoice_Date__c){
                        for(Invoice_Line__c invLine: items){
                            subTotal = invLine.Line_Total_Product_Price__c * taxableGrossReceiptsRate * taxDueRate;
                            if(taxRateOnProd > 0){
                                subTotal = subTotal * taxRateOnProd;
                            }
                            invLine.Subtotal_Local_Cannabis_Tax__c = subTotal;
                        }
                        
                    }else{
                        for(Invoice_Line__c invLine: items){
                            invLine.Subtotal_Local_Cannabis_Tax__c = 0;
                        }
                    }
                    
                }else{
                    for(Invoice_Line__c invLine: items){
                        invLine.Subtotal_Local_Cannabis_Tax__c = 0;
                    }
                }
            }
        }
        
    }
}