force-app/main/default/objects/Brand_Quote__c/Brand_Quote__c.object-meta.xml
<CustomObject>
    <description>Buy Quote to Purchase from Brands. Sell Quotes to Sell to Dispensaries</description>
    <label>Brand Quote</label>
    <nameField>
        <displayFormat>BQ-{0000000000}</displayFormat>
        <label>Brand Quote</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Brand Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Brand_Quote__c/fields/Distributor_Contact__c.field-meta.xml
<CustomField>
    <fullName>Distributor_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Distributor Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Brand Quotes (Distributor Contact)</relationshipLabel>
    <relationshipName>Brand_Quotes2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Brand_Quote__c/fields/Distributor_License__c.field-meta.xml
<CustomField>
    <fullName>Distributor_License__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Distributor License</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>State_Licenses__c.License_Name__c</field>
            <operation>equals</operation>
            <valueField>$Source.Distributor_Name__c</valueField>
        </filterItems>
        <filterItems>
            <field>State_Licenses__c.State_License_Holder__c</field>
            <operation>equals</operation>
            <valueField>$Source.Distributor_Name__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>State_Licenses__c</referenceTo>
    <relationshipLabel>Brand Quotes (Distributor License)</relationshipLabel>
    <relationshipName>Brand_Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Brand_Quote__c/fields/Distributor_Name__c.field-meta.xml
<CustomField>
    <fullName>Distributor_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Distributor Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Brand Quotes as Distributor</relationshipLabel>
    <relationshipName>Brand_Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Brand_Quote__c/fields/Opportunity_Name__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Name</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Brand_Quote__c/fields/Ownership__c.field-meta.xml
<CustomField>
    <fullName>Ownership__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ownership</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Brand Quotes as Ownership</relationshipLabel>
    <relationshipName>Brand_Quotes3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Brand_Quote__c/fields/Receiver_License__c.field-meta.xml
<CustomField>
    <fullName>Receiver_License__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Receiver License</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>State_Licenses__c.License_Name__c</field>
            <operation>equals</operation>
            <valueField>$Source.Receiver_Name__c</valueField>
        </filterItems>
        <filterItems>
            <field>State_Licenses__c.State_License_Holder__c</field>
            <operation>equals</operation>
            <valueField>$Source.Receiver_Name__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>State_Licenses__c</referenceTo>
    <relationshipLabel>Brand Sell Quotes</relationshipLabel>
    <relationshipName>Brand_Quotes1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Brand_Quote__c/fields/Receiver_Name__c.field-meta.xml
<CustomField>
    <fullName>Receiver_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Receiver Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Brand Quotes as Receiver</relationshipLabel>
    <relationshipName>Brand_Quotes2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Brand_Quote__c/fields/Sample_Order__c.field-meta.xml
<CustomField>
    <fullName>Sample_Order__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If checked, result will be (.0001) in cost and price for all downstream objects</inlineHelpText>
    <label>Sample Order</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Cultivation_Tax_Receipt__c/Cultivation_Tax_Receipt__c.object-meta.xml
<CustomObject>
    <description>Used in the generation of Cultivation Tax Receipt as proof of remittance by supplier.</description>
    <label>Cultivation Tax Receipt</label>
    <nameField>
        <displayFormat>CTR-{YYYY}-{MM}-{0000000000}</displayFormat>
        <label>Cultivation Tax Receipt</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cultivation Tax Receipts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Cultivation_Tax_Receipt__c/fields/Distributor_Contact__c.field-meta.xml
<CustomField>
    <fullName>Distributor_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Distributor Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cultivation Tax Receipts (Distributor Contact)</relationshipLabel>
    <relationshipName>Cultivation_Tax_Receipts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cultivation_Tax_Receipt__c/fields/Distributor_License__c.field-meta.xml
<CustomField>
    <fullName>Distributor_License__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Distributor License</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>State_Licenses__c.License_Name__c</field>
            <operation>equals</operation>
            <valueField>$Source.Distributor_Name__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>State_Licenses__c</referenceTo>
    <relationshipLabel>Cultivation Tax Receipts (Distributor License)</relationshipLabel>
    <relationshipName>Cultivation_Tax_Receipts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cultivation_Tax_Receipt__c/fields/Distributor_Name__c.field-meta.xml
<CustomField>
    <fullName>Distributor_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Distributor Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cultivation Tax Receipts (Distributor Name)</relationshipLabel>
    <relationshipName>Cultivation_Tax_Receipts2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cultivation_Tax_Receipt__c/fields/Opportunity_Name__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Name</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Cultivation Tax Receipts</relationshipLabel>
    <relationshipName>Cultivation_Tax_Receipts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cultivation_Tax_Receipt__c/fields/Ownership__c.field-meta.xml
<CustomField>
    <fullName>Ownership__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ownership</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cultivation Tax Receipts (Ownership)</relationshipLabel>
    <relationshipName>Cultivation_Tax_Receipts3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cultivation_Tax_Receipt__c/fields/Receiver_Name__c.field-meta.xml
<CustomField>
    <fullName>Receiver_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Receiver Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cultivation Tax Receipts (Receiver Name)</relationshipLabel>
    <relationshipName>Cultivation_Tax_Receipts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cultivation_Tax_Receipt__c/fields/Sample_Order__c.field-meta.xml
<CustomField>
    <fullName>Sample_Order__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sample Order</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Cultivation_Tax_Receipt__c/fields/Shipping_Manifest__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Manifest__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Shipping Manifest</label>
    <referenceTo>Shipping_Manifest__c</referenceTo>
    <relationshipLabel>Cultivation Tax Receipts</relationshipLabel>
    <relationshipName>Cultivation_Tax_Receipts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cultivation_Tax_Receipt_Line__c/Cultivation_Tax_Receipt_Line__c.object-meta.xml
<CustomObject>
    <label>Cultivation Tax Receipt Line</label>
    <nameField>
        <displayFormat>CTRL-{0000000000}</displayFormat>
        <label>CTR Line</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cultivation Tax Receipt Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Cultivation_Tax_Receipt_Line__c/fields/Cultivation_Tax_Receipt__c.field-meta.xml
<CustomField>
    <fullName>Cultivation_Tax_Receipt__c</fullName>
    <label>Cultivation Tax Receipt</label>
    <referenceTo>Cultivation_Tax_Receipt__c</referenceTo>
    <relationshipLabel>Cultivation Tax Receipt Lines</relationshipLabel>
    <relationshipName>Cultivation_Tax_Receipt_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Shipping_Manifest__c/Shipping_Manifest__c.object-meta.xml
<CustomObject>
    <description>Used in the generation of compliance document to enable retail delivery.</description>
    <label>Shipping Manifest</label>
    <nameField>
        <displayFormat>SM-{YYYY}-{MM}-{0000000000}</displayFormat>
        <label>Shipping Manifest</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipping Manifests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Shipping_Manifest__c/fields/Distributor_Contact__c.field-meta.xml
<CustomField>
    <fullName>Distributor_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Distributor Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Shipping Manifests (Distributor Contact)</relationshipLabel>
    <relationshipName>Shipping_Manifests1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipping_Manifest__c/fields/Distributor_License__c.field-meta.xml
<CustomField>
    <fullName>Distributor_License__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Distributor License</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>State_Licenses__c.License_Name__c</field>
            <operation>equals</operation>
            <valueField>$Source.Distributor_Name__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>State_Licenses__c</referenceTo>
    <relationshipLabel>Shipping Manifests (Distributor License)</relationshipLabel>
    <relationshipName>Shipping_Manifests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipping_Manifest__c/fields/Distributor_Name__c.field-meta.xml
<CustomField>
    <fullName>Distributor_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Distributor Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Shipping Manifests as Distributor</relationshipLabel>
    <relationshipName>Shipping_Manifests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipping_Manifest__c/fields/Opportunity_Name__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Name</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Shipping Manifests</relationshipLabel>
    <relationshipName>Shipping_Manifests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipping_Manifest__c/fields/Ownership__c.field-meta.xml
<CustomField>
    <fullName>Ownership__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ownership</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Shipping Manifests as Ownership</relationshipLabel>
    <relationshipName>Shipping_Manifests3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipping_Manifest__c/fields/Receiver_Name__c.field-meta.xml
<CustomField>
    <fullName>Receiver_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Receiver Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Shipping Manifests as Receiver</relationshipLabel>
    <relationshipName>Shipping_Manifests1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipping_Manifest__c/fields/Sample_Order__c.field-meta.xml
<CustomField>
    <fullName>Sample_Order__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Inherited: If checked, result will be (.0001) in cost and price for all downstream objects</inlineHelpText>
    <label>Sample Order</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Shipping_Manifest_Line__c/Shipping_Manifest_Line__c.object-meta.xml
<CustomObject>
    <label>Shipping Manifest Line</label>
    <nameField>
        <displayFormat>SML-{0000000000}</displayFormat>
        <label>SM Line</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipping Manifest Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Shipping_Manifest_Line__c/fields/Shipping_Manifest__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Manifest__c</fullName>
    <label>Shipping Manifest</label>
    <referenceTo>Shipping_Manifest__c</referenceTo>
    <relationshipLabel>Shipping Manifest Lines</relationshipLabel>
    <relationshipName>Shipping_Manifest_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/CreateCTRfromTSM.cls
/*
    Copyright (c) 2018 Filigreen Distro
    All rights reserved.
     
•  Test class  Name:  CreateRLfromPOlineTest
*/
public class CreateCTRfromTSM{

    private ApexPages.StandardController stdController;
    private Shipping_Manifest__c tsm= null;

    
    public CreateCTRfromTSM(ApexPages.StandardController controller) {
        this.stdController = controller;
        System.debug('stdController ' + stdController);
        System.assertNotEquals(null, controller, 'controller is null');
        tsm = ((Shipping_Manifest__c)stdController.getRecord());
        System.assertNotEquals(null, tsm, 'tsm record is null');
    }

     public PageReference createCTR() {
        PageReference retPage = null;
        try {
            List<Cultivation_Tax_Receipt__c> objects = [Select id from Cultivation_Tax_Receipt__c where Shipping_Manifest__c =: tsm.Id];
            if (objects.size() >= 1) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.ERROR,'CTR has already been created'));
                        return retPage ;
          }                        
            retPage = createOrder(tsm.Id);
            retPage.setRedirect(true);
        } catch (Exception ex){

            ErrorLogs.log('CreateCTRfromCTR',ex.getStackTraceString(), ex.getMessage());
            ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR,ex.getMessage());
            ApexPages.addMessage(myMsg);
        }
        return retPage;
    }

    public static PageReference createOrder(Id tsmoldId)
     {
        PageReference retPage = null;
        ID tsmID = tsmoldId;
        Shipping_Manifest__c objTSM= [select id ,name
                ,Sample_Order__c
                ,Ownership__c
                ,Opportunity_Name__c
                ,Distributor_Name__c
                ,Distributor_License__c
                ,Distributor_Contact__c
                ,Receiver_Name__c
                ,Receiver_License__c
                ,Receiver_Contact__c
                ,Supplier_Name__c
                ,Supplier_License__c
                ,Supplier_Contact__c
                ,Brand_Quote__c
                ,Payment_Terms__c
                ,Site__c
                ,Shipping_Method__c
                ,Shipping_Terms__c       
                from Shipping_Manifest__c where id =: tsmID AND RecordTypeId =: ShippinManifestSupport.getTSMRecordTypeId()];

        //if (quote.fieldnameTBD != null){
            //throw new CustomerQuotationException('Brand Quote has already been converted to a Purchase Order.  You can only have one purchase order for a quote.');
        //}
        List<Shipping_Manifest_Line__c> tsmLines= [select id
                    ,name
                    ,Shipping_Manifest__c
                    ,Product_Name__c
                    ,Product_Title__c
                    ,Product_Name__r.Cultivation_Tax_Amount__c
                    ,Qty_Ordered__c
                    from Shipping_Manifest_Line__c
                    where Shipping_Manifest__c =: tsmID];


        Cultivation_Tax_Receipt__c newCTR = new Cultivation_Tax_Receipt__c();
        newCTR.Shipping_Manifest__c= tsmID;
        newCTR.Site__c = objTSM.Site__c;
        newCTR.Shipping_Method__c = objTSM.Shipping_Method__c;
        newCTR.Shipping_Terms__c = objTSM.Shipping_Terms__c;
        newCTR.Payment_Terms__c = objTSM.Payment_Terms__c;
        newCTR.Ownership__c = objTSM.Ownership__c;
        newCTR.Sample_Order__c = objTSM.Sample_Order__c;
        newCTR.Brand_Quote__c = objTSM.Brand_Quote__c;
        newCTR.Opportunity_Name__c = objTSM.Opportunity_Name__c;
        newCTR.Distributor_Name__c = objTSM.Distributor_Name__c;
        newCTR.Distributor_License__c = objTSM.Distributor_License__c;
        newCTR.Distributor_Contact__c = objTSM.Distributor_Contact__c;
        newCTR.Supplier_Name__c = objTSM.Supplier_Name__c;
        newCTR.Supplier_License__c = objTSM.Supplier_License__c;
        newCTR.Supplier_Contact__c = objTSM.Supplier_Contact__c;
        newCTR.Receiver_Name__c = objTSM.Receiver_Name__c;
        newCTR.Receiver_License__c = objTSM.Receiver_License__c;
        newCTR.Receiver_Contact__c = objTSM.Receiver_Contact__c;
        insert newCTR;
        
        List<Cultivation_Tax_Receipt_Line__c> CTRLineItems = new List<Cultivation_Tax_Receipt_Line__c>();
        For (Shipping_Manifest_Line__c objTSMlines: tsmLines)
        {
            Cultivation_Tax_Receipt_Line__c CTRLineItem = new Cultivation_Tax_Receipt_Line__c();
            CTRLineItem.Shipping_Manifest_Line__c= objTSMlines.Id;
            CTRLineItem.Product_Name__c = objTSMlines.Product_Name__c;
            CTRLineItem.Product_Title__c = objTSMlines.Product_Title__c;
            CTRLineItem.Qty_Ordered__c = objTSMlines.Qty_Ordered__c;
            CTRLineItem.Line_Total_CT_Amount__c = objTSMlines.Qty_Ordered__c * objTSMlines.Product_Name__r.Cultivation_Tax_Amount__c;
            CTRLineItem.Cultivation_Tax_Receipt__c = newCTR.Id;
            CTRLineItems.add(CTRLineItem);
        }
        insert CTRLineItems;
        
        retPage =new PageReference('/'+newCTR.Id);
        return retPage;
     }

     public PageReference goBack() {
            return stdController.view().setRedirect(true);
    }

}