force-app/main/default/objects/Brand_Quote__c/Brand_Quote__c.object-meta.xml
<CustomObject>
    <description>Buy Quote to Purchase from Brands. Sell Quotes to Sell to Dispensaries</description>
    <label>Brand Quote</label>
    <nameField>
        <displayFormat>BQ-{0000000000}</displayFormat>
        <label>Brand Quote</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Brand Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Brand_Quote__c/fields/Apply_Excise_Tax__c.field-meta.xml
<CustomField>
    <fullName>Apply_Excise_Tax__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Include Excise tax calculation</description>
    <label>Apply Excise Tax ?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Brand_Quote__c/fields/BQ_Status__c.field-meta.xml
<CustomField>
    <fullName>BQ_Status__c</fullName>
    <inlineHelpText>Status will auto-updated based on workflow defined.</inlineHelpText>
    <label>BQ Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Shipped</fullName>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Brand_Quote__c/fields/Distributor_Contact__c.field-meta.xml
<CustomField>
    <fullName>Distributor_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Distributor Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Brand Quotes (Distributor Contact)</relationshipLabel>
    <relationshipName>Brand_Quotes2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Brand_Quote__c/fields/Distributor_License__c.field-meta.xml
<CustomField>
    <fullName>Distributor_License__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Distributor License</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>State_Licenses__c.License_Name__c</field>
            <operation>equals</operation>
            <valueField>$Source.Distributor_Name__c</valueField>
        </filterItems>
        <filterItems>
            <field>State_Licenses__c.State_License_Holder__c</field>
            <operation>equals</operation>
            <valueField>$Source.Distributor_Name__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>State_Licenses__c</referenceTo>
    <relationshipLabel>Brand Quotes (Distributor License)</relationshipLabel>
    <relationshipName>Brand_Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Brand_Quote__c/fields/Distributor_Name__c.field-meta.xml
<CustomField>
    <fullName>Distributor_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Distributor Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Brand Quotes as Distributor</relationshipLabel>
    <relationshipName>Brand_Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Brand_Quote__c/fields/Opportunity_Name__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Name</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Brand_Quote__c/fields/Ownership__c.field-meta.xml
<CustomField>
    <fullName>Ownership__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ownership</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Brand Quotes as Ownership</relationshipLabel>
    <relationshipName>Brand_Quotes3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Brand_Quote__c/fields/Payment_Terms__c.field-meta.xml
<CustomField>
    <fullName>Payment_Terms__c</fullName>
    <defaultValue>(&quot;COD&quot;)</defaultValue>
    <label>Payment Terms</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Payment_Terms</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Brand_Quote__c/fields/Receiver_Contact__c.field-meta.xml
<CustomField>
    <fullName>Receiver_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Receiver Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Receiver_Name__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Brand Quotes (Receiver Contact)</relationshipLabel>
    <relationshipName>Brand_Quotes1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Brand_Quote__c/fields/Receiver_Name__c.field-meta.xml
<CustomField>
    <fullName>Receiver_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Receiver Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Brand Quotes as Receiver</relationshipLabel>
    <relationshipName>Brand_Quotes2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Brand_Quote__c/fields/Sales_Origin__c.field-meta.xml
<CustomField>
    <fullName>Sales_Origin__c</fullName>
    <label>Sales Origin</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sales_Origin</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Brand_Quote__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site</label>
    <referenceTo>Site__c</referenceTo>
    <relationshipLabel>Brand Quotes</relationshipLabel>
    <relationshipName>Brand_Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Brand_Quote__c/fields/Supplier_Name__c.field-meta.xml
<CustomField>
    <fullName>Supplier_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Supplier Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Brand Quotes as Supplier</relationshipLabel>
    <relationshipName>Brand_Quotes1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Brand_Quote__c/recordTypes/Buy_Quote.recordType-meta.xml
<RecordType>
    <fullName>Buy_Quote</fullName>
    <active>true</active>
    <description>Used for incoming inventory from Brands, Sites, Internal Packaging, Consumables, Bulk Buys</description>
    <label>Buy Quote</label>
</RecordType>

force-app/main/default/objects/Brand_Quote__c/recordTypes/Sell_Quote.recordType-meta.xml
<RecordType>
    <fullName>Sell_Quote</fullName>
    <active>true</active>
    <description>Used for selling to Receiver, Invoice and Purchase Order will be issued to Brand or Lab</description>
    <label>Sell Quote</label>
</RecordType>

force-app/main/default/objects/Brand_Quote__c/recordTypes/Service_Quote.recordType-meta.xml
<RecordType>
    <fullName>Service_Quote</fullName>
    <active>true</active>
    <description>Used for packaging and transport services, No Purchase Order</description>
    <label>Service Quote</label>
</RecordType>

force-app/main/default/objects/Brand_Quote_Line__c/Brand_Quote_Line__c.object-meta.xml
<CustomObject>
    <label>Brand Quote Line</label>
    <nameField>
        <displayFormat>BQLI-{0000000000}</displayFormat>
        <label>BQ Line</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Brand Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Brand_Quote_Line__c/fields/Apply_Excise_Tax__c.field-meta.xml
<CustomField>
    <fullName>Apply_Excise_Tax__c</fullName>
    <description>IF(TExt(Product_Name__r.Apply_Excise_Tax__c) = &apos;Yes&apos;  &amp;&amp;  Brand_Quote_Number__r.Apply_Excise_Tax__c  = true, 
TEXT(Product_Name__r.Apply_Excise_Tax__c), &apos;No&apos;)</description>
    <formula>IF(TExt(Product_Name__r.Apply_Excise_Tax__c) = &apos;Yes&apos;  &amp;&amp;  Brand_Quote_Number__r.Apply_Excise_Tax__c  = true, 
&apos;Yes&apos;, &apos;No&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Apply Excise Tax?</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Brand_Quote_Line__c/fields/Brand_Quote_Number__c.field-meta.xml
<CustomField>
    <fullName>Brand_Quote_Number__c</fullName>
    <label>Brand Quote Number</label>
    <referenceTo>Brand_Quote__c</referenceTo>
    <relationshipLabel>Brand Quote Lines</relationshipLabel>
    <relationshipName>Brand_Quote_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Brand_Quote_Line__c/fields/Disty_Discount_Per_Unit__c.field-meta.xml
<CustomField>
    <fullName>Disty_Discount_Per_Unit__c</fullName>
    <label>Disty Discount Per Unit</label>
    <precision>16</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Brand_Quote_Line__c/fields/MOQ__c.field-meta.xml
<CustomField>
    <fullName>MOQ__c</fullName>
    <description>MOQ - Minimum Order Quantity</description>
    <inlineHelpText>Minimum Order Quantity</inlineHelpText>
    <label>Qty per Case (MOQ)</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Brand_Quote_Line__c/fields/Opportunity_Name__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Name__c</fullName>
    <formula>Brand_Quote_Number__r.Opportunity_Name__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Opportunity Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Brand_Quote_Line__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <formula>Brand_Quote_Number__r.Opportunity_Name__r.Order__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Order #</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Brand_Quote_Line__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Name</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Product2.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Brand Quote Lines</relationshipLabel>
    <relationshipName>Brand_Quote_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Brand_Quote_Line__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <formula>Brand_Quote_Number__r.Site__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Site</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Company_Custom_Settings__c/Company_Custom_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Company Custom Settings</label>
</CustomObject>

force-app/main/default/objects/Company_Custom_Settings__c/fields/Default_Contact__c.field-meta.xml
<CustomField>
    <fullName>Default_Contact__c</fullName>
    <description>Default distributor contact ID used in BQ</description>
    <inlineHelpText>Default distributor contact ID used in BQ</inlineHelpText>
    <label>Default Contact</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Company_Custom_Settings__c/fields/Default_Distributor__c.field-meta.xml
<CustomField>
    <fullName>Default_Distributor__c</fullName>
    <description>Default distributor ID used in BQ</description>
    <inlineHelpText>Default distributor ID used in BQ</inlineHelpText>
    <label>Default Distributor</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Company_Custom_Settings__c/fields/Default_License__c.field-meta.xml
<CustomField>
    <fullName>Default_License__c</fullName>
    <description>Default state license ID used in BQ</description>
    <inlineHelpText>Default state license ID used in BQ</inlineHelpText>
    <label>Default License</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <displayFormat>O-{000000}</displayFormat>
        <label>Order #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Exclude_Excise_Tax__c.field-meta.xml
<CustomField>
    <fullName>Exclude_Excise_Tax__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Exclude Excise Tax</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Payment_Terms__c.field-meta.xml
<CustomField>
    <fullName>Payment_Terms__c</fullName>
    <label>Payment Terms</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Payment_Terms</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/Retailer__c.field-meta.xml
<CustomField>
    <fullName>Retailer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Retailer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Retailer_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Retailer_Contact__c.field-meta.xml
<CustomField>
    <fullName>Retailer_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Retailer Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site</label>
    <referenceTo>Site__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CreateQuote.cls
/*
    Copyright (c) 2018 Filigreen Distro
    All rights reserved.

•  Test class  Name:  CreateRLfromPOlineTest
*/
public class CreateQuote  {

    private ApexPages.StandardController stdController;
    Opportunity bq;
    private ID oppID;
	String OppRecordType;

    public CreateQuote(ApexPages.StandardController controller) {
        System.debug('inside the constructor ' + controller);
        this.stdController = controller;
        System.debug('stdController ' + stdController);
        System.assertNotEquals(null, controller, 'controller is null');
        bq = ((Opportunity)stdController.getRecord());
        oppID = bq.Id;       
        //System.assertNotEquals(null, cq, 'quote record is null');   
    }

    public PageReference createSellQuote() {
        PageReference retPage = null;
        try                
        {                   
            //Id newSQ = createQuote('sell_quote');
			OppRecordType = [select RecordType.DeveloperName from Opportunity where id =: oppID].RecordType.DeveloperName;
			Id newSQ;
			if(OppRecordType == 'Service_Opportunity')
				newSQ = createQuote('Service_Quote');
			else
				newSQ = createQuote('sell_quote');
            retPage =new PageReference('/'+newSQ);
            retPage.setRedirect(true);                        
        }
        catch (Exception ex)
        {
            ErrorLogs.log('CreateQuote:createSellQuote()',ex.getStackTraceString(), ex.getMessage());
            ApexPages.Message errMsg = new ApexPages.Message(ApexPages.Severity.ERROR,ex.getMessage());
            ApexPages.addMessage(errMsg);
        }
        return retPage;
    }

    public PageReference createBuyQuote() 
    {
        PageReference retPage = null;
        try
        {
            Id newBQ = createQuote('buy_quote');            
            retPage =new PageReference('/'+newBQ);
            retPage.setRedirect(true);

        }
        catch (Exception ex)
        {
            ErrorLogs.log('CreateQuote:createBuyQuote()',ex.getStackTraceString(), ex.getMessage());
            ApexPages.Message errMsg = new ApexPages.Message(ApexPages.Severity.ERROR,ex.getMessage());
            ApexPages.addMessage(errMsg);
        }
        return retPage;
    }

    public Id createQuote(String quoteType)
    {
        Brand_Quote__c newQuote = new Brand_Quote__c();
        newQuote.Opportunity_Name__c = oppID;
        List<Company_Custom_Settings__c> defaultIDs = [select Default_Distributor__c,Default_License__c,Default_Contact__c from Company_Custom_Settings__c];
        if(defaultIDs.size() >0)
        {
            if(defaultIDs[0].Default_Distributor__c != null)
                newQuote.Distributor_Name__c = defaultIDs[0].Default_Distributor__c;
            if(defaultIDs[0].Default_License__c != null)
                newQuote.Distributor_License__c = defaultIDs[0].Default_License__c;
            if(defaultIDs[0].Default_Contact__c != null)
                newQuote.Distributor_Contact__c = defaultIDs[0].Default_Contact__c;
        }
        //newQuote.Distributor_Contact__c = user.Id;
        newQuote.BQ_Status__c = 'Draft';
        system.debug('****'+oppID);
        newQuote.Ownership__c = [select Ownership__c from Opportunity where id =: oppID].Ownership__c;
        newQuote.Sales_Origin__c = [select Sales_Origin__c from Opportunity where id =: oppID].Sales_Origin__c;
        newQuote.Site__c = [select Site_Name__c from Opportunity where id =: oppID].Site_Name__c;
        //newQuote.Payment_Terms__c = [select Payment_Terms__c from Opportunity where id =: oppID].Payment_Terms__c;
        id recTypeID = getRecordType(quoteType);
        newQuote.RecordTypeId = recTypeID;
        system.debug('**$$$**'+newQuote);
        
        if(quoteType =='sell_quote')
        {
            newQuote.Payment_Terms__c = [select Payment_Terms__c from Opportunity where id =: oppID].Payment_Terms__c;
			Opportunity opp = [select Order__c,Order__r.Retailer_Contact__c,Order__r.Retailer__c,Order__r.Exclude_Excise_Tax__c,  Order__r.Customer__r.ContactId from Opportunity where id =: oppID];
            if(opp.Order__c != null){
                newQuote.Apply_Excise_Tax__c = (opp.Order__r.Exclude_Excise_Tax__c == false);
                newQuote.Receiver_Name__c = opp.Order__r.Retailer__c;
				newQuote.Receiver_Contact__c =  opp.Order__r.Retailer_Contact__c;// opp.Order__r.Customer__r.ContactId;
            }  
            /*Opportunity opp = [select Order__c, Order__r.Customer__r.ContactId from Opportunity where id =: oppID];
            if(opp.Order__c != null){
            system.debug('**$$$123**'+opp.Order__r.Customer__r.ContactId);
                newQuote.Receiver_Contact__c =  opp.Order__r.Customer__r.ContactId;
            }
            */
            //newQuote.Receiver_Name__c = [select AccountId from Opportunity where id =: oppID].AccountId;
            //newQuote.Supplier_Name__c = [select Ownership__c from Opportunity where id =: oppID].Ownership__c;
        }
        try{ insert newQuote;}
        catch(Exception ex)
        {
            ErrorLogs.log('CreateQuote:createQuote()',ex.getStackTraceString(), ex.getMessage());
        }
        createQuoteLines(newQuote.Id, quoteType);
        return newQuote.Id;
    }
    public void createQuoteLines(Id bqID, String quoteType)
    {
        List<Brand_Quote_Line__c> bqLineItems = new List<Brand_Quote_Line__c>();
        Opportunity oppty = [SELECT Id, Name, Account.Name, 
                                    (SELECT Quantity,MOQ__c, Product_Title__c, UnitPrice, ListPrice, PricebookEntry.Disty_Discount_Per_Unit__c, TotalPrice, Product2Id, PricebookEntryId, PricebookEntry.Name,
                                        PricebookEntry.PriceBook2ID, PricebookEntry.Product2ID, PricebookEntry.Product2.Family,
                                        PricebookEntry.DistyMargin__c , Disty_Discount_Per_Unit__c
                                        FROM OpportunityLineItems) FROM Opportunity where id =: oppID];
        
		id bqLIrecordtypeID;
		If(quoteType == 'buy_quote')
			bqLIrecordtypeID = Schema.SObjectType.Brand_Quote_Line__c.getRecordTypeInfosByName().get('Buy Quote Line').getRecordTypeId();
		else
		{
			If(quoteType == 'sell_quote')
				bqLIrecordtypeID = Schema.SObjectType.Brand_Quote_Line__c.getRecordTypeInfosByName().get('Sell Quote Line').getRecordTypeId();
			else
			{
				If(quoteType == 'Service_Quote')
				bqLIrecordtypeID = Schema.SObjectType.Brand_Quote_Line__c.getRecordTypeInfosByName().get('Service Line').getRecordTypeId();
			}
		}

		for (OpportunityLineItem  opptyLineItems:oppty.OpportunityLineItems)
        {
            Brand_Quote_Line__c newQuoteLineItems = new Brand_Quote_Line__c();
            newQuoteLineItems.Brand_Quote_Number__c = bqID;
            newQuoteLineItems.Product_Name__c = opptyLineItems.Product2Id;
            newQuoteLineItems.Price_Book__c = opptyLineItems.PricebookEntry.PriceBook2ID;
            newQuoteLineItems.Disty_Margin__c = opptyLineItems.PricebookEntry.DistyMargin__c;
            newQuoteLineItems.MOQ__c = opptyLineItems.MOQ__c;
            newQuoteLineItems.Product_Title__c = opptyLineItems.Product_Title__c;
            newQuoteLineItems.Quantity_Cases__c = opptyLineItems.Quantity;
            newQuoteLineItems.Disty_Discount_Per_Unit__c = opptyLineItems.Disty_Discount_Per_Unit__c; //opptyLineItems.PricebookEntry.Disty_Discount_Per_Unit__c;
            newQuoteLineItems.Retail_Wholesale_Price__c = opptyLineItems.UnitPrice;
			newQuoteLineItems.RecordTypeId = bqLIrecordtypeID;
            bqLineItems.add(newQuoteLineItems);
        }
        try{
            insert bqLineItems;
            }
            catch (Exception ex)
            { 
                ErrorLogs.log('CreateQuote','Quote Id:'+bqID + ' - '+ ex.getStackTraceString(), ex.getMessage());
            }
    }
    public ID getRecordType(String recTypeName)
    {
        recordtype recTypeID = [select id from recordtype where DeveloperName =:recTypeName limit 1];
        return recTypeID.Id;
    }
    public PageReference goBack() {
            return stdController.view().setRedirect(true);
    }
}