force-app/main/default/objects/Brand_Quote__c/Brand_Quote__c.object-meta.xml
<CustomObject>
    <description>Buy Quote to Purchase from Brands. Sell Quotes to Sell to Dispensaries</description>
    <label>Brand Quote</label>
    <nameField>
        <displayFormat>BQ-{0000000000}</displayFormat>
        <label>Brand Quote</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Brand Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Brand_Quote__c/fields/Ownership__c.field-meta.xml
<CustomField>
    <fullName>Ownership__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ownership</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Brand Quotes as Ownership</relationshipLabel>
    <relationshipName>Brand_Quotes3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Brand_Quote__c/fields/Payment_Terms__c.field-meta.xml
<CustomField>
    <fullName>Payment_Terms__c</fullName>
    <defaultValue>(&quot;COD&quot;)</defaultValue>
    <label>Payment Terms</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Payment_Terms</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Brand_Quote__c/fields/Shipping_Terms__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Terms__c</fullName>
    <label>Shipping Terms</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Shipping_Terms</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/Purchase_Order__c.object-meta.xml
<CustomObject>
    <label>Purchase Order</label>
    <nameField>
        <displayFormat>PO-{0000000000}</displayFormat>
        <label>Purchase Order</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Purchase_Order__c/fields/Brand_Quote__c.field-meta.xml
<CustomField>
    <fullName>Brand_Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Quote used to create PO</description>
    <label>Brand Quote</label>
    <referenceTo>Brand_Quote__c</referenceTo>
    <relationshipLabel>Purchase Orders</relationshipLabel>
    <relationshipName>Purchase_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/fields/Chart_of_Account__c.field-meta.xml
<CustomField>
    <fullName>Chart_of_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Chart of Account</label>
    <referenceTo>Chart_of_Account__c</referenceTo>
    <relationshipLabel>Purchase Orders</relationshipLabel>
    <relationshipName>Purchase_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/fields/Ownership__c.field-meta.xml
<CustomField>
    <fullName>Ownership__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ownership</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Purchase Orders as Ownership</relationshipLabel>
    <relationshipName>Purchase_Orders3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/fields/Payment_Terms__c.field-meta.xml
<CustomField>
    <fullName>Payment_Terms__c</fullName>
    <label>Payment Terms</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Payment_Terms</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/fields/Shipping_Terms__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Terms__c</fullName>
    <inlineHelpText>Incoterms</inlineHelpText>
    <label>Shipping Terms</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Shipping_Terms</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Supplier_Bill__c/Supplier_Bill__c.object-meta.xml
<CustomObject>
    <label>Supplier Bill</label>
    <nameField>
        <displayFormat>BILL-{YYYY}-{MM}-{000000}</displayFormat>
        <label>Supplier Bill</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Supplier Bills</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Supplier_Bill__c/fields/Bill_Amount__c.field-meta.xml
<CustomField>
    <fullName>Bill_Amount__c</fullName>
    <label>Bill Amount</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Supplier_Bill__c/fields/Bill_Closing_Date__c.field-meta.xml
<CustomField>
    <fullName>Bill_Closing_Date__c</fullName>
    <label>Bill Closing Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Supplier_Bill__c/fields/Bill_Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Bill_Due_Date__c</fullName>
    <label>Bill Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Supplier_Bill__c/fields/Bill_Opening_Date__c.field-meta.xml
<CustomField>
    <fullName>Bill_Opening_Date__c</fullName>
    <label>Bill Opening Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Supplier_Bill__c/fields/Bill_Settled_Date__c.field-meta.xml
<CustomField>
    <fullName>Bill_Settled_Date__c</fullName>
    <label>Bill Settled Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Supplier_Bill__c/fields/Brand_Quote__c.field-meta.xml
<CustomField>
    <fullName>Brand_Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Brand Quote</label>
    <referenceTo>Brand_Quote__c</referenceTo>
    <relationshipLabel>Supplier Bills</relationshipLabel>
    <relationshipName>Supplier_Bills</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Supplier_Bill__c/fields/Chart_of_Account__c.field-meta.xml
<CustomField>
    <fullName>Chart_of_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Chart of Account</label>
    <referenceTo>Chart_of_Account__c</referenceTo>
    <relationshipLabel>Supplier Bills</relationshipLabel>
    <relationshipName>Supplier_Bills</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Supplier_Bill__c/fields/Is_Brand__c.field-meta.xml
<CustomField>
    <fullName>Is_Brand__c</fullName>
    <formula>$User.AccountId__c = Supplier_Name__r.Account_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Brand</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Supplier_Bill__c/fields/Order_or_Service__c.field-meta.xml
<CustomField>
    <fullName>Order_or_Service__c</fullName>
    <label>Order or Service #</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Supplier_Bill__c/fields/Outstanding_Balance__c.field-meta.xml
<CustomField>
    <fullName>Outstanding_Balance__c</fullName>
    <formula>Bill_Amount__c -  Total_Payments__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Outstanding Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Supplier_Bill__c/fields/Ownership__c.field-meta.xml
<CustomField>
    <fullName>Ownership__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ownership</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Supplier Bills</relationshipLabel>
    <relationshipName>Supplier_Bills1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Supplier_Bill__c/fields/Payment_Hold__c.field-meta.xml
<CustomField>
    <fullName>Payment_Hold__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Payment Hold</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Supplier_Bill__c/fields/PO_Settled_Date__c.field-meta.xml
<CustomField>
    <fullName>PO_Settled_Date__c</fullName>
    <formula>Purchase_Order__r.Supplier_Payment_Settled_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>PO Settled Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Supplier_Bill__c/fields/Purchase_Order__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Purchase Order</label>
    <referenceTo>Purchase_Order__c</referenceTo>
    <relationshipLabel>Supplier Bills</relationshipLabel>
    <relationshipName>Supplier_Bills</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Supplier_Bill__c/fields/Reference__c.field-meta.xml
<CustomField>
    <fullName>Reference__c</fullName>
    <label>Reference #</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Supplier_Bill__c/fields/Requestor_Name__c.field-meta.xml
<CustomField>
    <fullName>Requestor_Name__c</fullName>
    <formula>CreatedBy.Alias</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Requestor Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Supplier_Bill__c/fields/Shipping_Terms__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Terms__c</fullName>
    <inlineHelpText>INCOTERMS2010</inlineHelpText>
    <label>Shipping Terms</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Shipping_Terms</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Supplier_Bill_Snapshot__c/Supplier_Bill_Snapshot__c.object-meta.xml
<CustomObject>
    <label>Supplier Bill Snapshot</label>
    <nameField>
        <displayFormat>SBS-{00000000}</displayFormat>
        <label>Supplier Bill Snapshot Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Supplier Bill Snapshot</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Supplier_Bill_Snapshot__c/fields/Bill_Amount__c.field-meta.xml
<CustomField>
    <fullName>Bill_Amount__c</fullName>
    <label>Bill Amount</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Supplier_Bill_Snapshot__c/fields/Bill_Closing_Date__c.field-meta.xml
<CustomField>
    <fullName>Bill_Closing_Date__c</fullName>
    <label>Bill Closing Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Supplier_Bill_Snapshot__c/fields/Bill_Opening_Date__c.field-meta.xml
<CustomField>
    <fullName>Bill_Opening_Date__c</fullName>
    <label>Bill Opening Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Supplier_Bill_Snapshot__c/fields/Bill_Settled_Date__c.field-meta.xml
<CustomField>
    <fullName>Bill_Settled_Date__c</fullName>
    <label>Bill Settled Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Supplier_Bill_Snapshot__c/fields/Brand_Quote__c.field-meta.xml
<CustomField>
    <fullName>Brand_Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Brand Quote</label>
    <referenceTo>Brand_Quote__c</referenceTo>
    <relationshipLabel>Supplier Bill Snapshot</relationshipLabel>
    <relationshipName>Supplier_Bill_Snapshot</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Supplier_Bill_Snapshot__c/fields/Chart_of_Account__c.field-meta.xml
<CustomField>
    <fullName>Chart_of_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Chart of Account</label>
    <referenceTo>Chart_of_Account__c</referenceTo>
    <relationshipLabel>Supplier Bill Snapshot</relationshipLabel>
    <relationshipName>Supplier_Bill_Snapshot</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Supplier_Bill_Snapshot__c/fields/Is_Brand__c.field-meta.xml
<CustomField>
    <fullName>Is_Brand__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Brand</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Supplier_Bill_Snapshot__c/fields/Order_or_Service__c.field-meta.xml
<CustomField>
    <fullName>Order_or_Service__c</fullName>
    <label>Order or Service</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Supplier_Bill_Snapshot__c/fields/Outstanding_Balance__c.field-meta.xml
<CustomField>
    <fullName>Outstanding_Balance__c</fullName>
    <label>Outstanding Balance</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Supplier_Bill_Snapshot__c/fields/Payment_Hold__c.field-meta.xml
<CustomField>
    <fullName>Payment_Hold__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Payment Hold</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Supplier_Bill_Snapshot__c/fields/Payment_Terms__c.field-meta.xml
<CustomField>
    <fullName>Payment_Terms__c</fullName>
    <label>Payment Terms</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Supplier_Bill_Snapshot__c/fields/PO_Settled_Date__c.field-meta.xml
<CustomField>
    <fullName>PO_Settled_Date__c</fullName>
    <label>PO Settled Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Supplier_Bill_Snapshot__c/fields/Purchase_Order__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Purchase Order</label>
    <referenceTo>Purchase_Order__c</referenceTo>
    <relationshipLabel>Supplier Bill Snapshot</relationshipLabel>
    <relationshipName>Supplier_Bill_Snapshot</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Supplier_Bill_Snapshot__c/fields/Reference__c.field-meta.xml
<CustomField>
    <fullName>Reference__c</fullName>
    <label>Reference #</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Supplier_Bill_Snapshot__c/fields/Requestor_Name__c.field-meta.xml
<CustomField>
    <fullName>Requestor_Name__c</fullName>
    <label>Requestor Name</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Supplier_Bill_Snapshot__c/fields/Shipping_Terms__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Terms__c</fullName>
    <label>Shipping Terms</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/runSupplierBillSnapshot.cls
public class runSupplierBillSnapshot {
     private static String SUPPLIER_SNAPSHOT_TO_ADDRESS{ 
        get{
            return String.isNotBlank(SUPPLIER_SNAPSHOT_TO_ADDRESS) ? SUPPLIER_SNAPSHOT_TO_ADDRESS : FiligreenConfigurationUtility.getConfigValueByObjectAndKey('Invoice','Supplier_Snapshot_TOAddress');
        }set;
    }

      @AuraEnabled
    public static AuraResponse runSupplierBillSnapshot(String recordId){
        AuraResponse r = new AuraResponse('runSupplierBillSnapshot.runSupplierBillSnapshot()');
        

            
        List<Supplier_Bill__c> supplierBillList = new List<Supplier_Bill__c>([SELECT Bill_Amount__c,Bill_Closing_Date__c,Ownership__c,Bill_Due_Date__c,Bill_Opening_Date__c,Bill_Settled_Date__c,Brand_Quote__c,
                                                                              Chart_of_Account__c,Id,Is_Brand__c,Name,Order_or_Service__c,Outstanding_Balance__c,Payment_Hold__c,Payment_Terms__c,
                                                                              PO_Settled_Date__c,Purchase_Order__c ,Reference__c,Requestor_Name__c,Shipping_Terms__c,
                                                                              Ship_Confirmation_Date__c,Site__c,Sold_to_Party__c,Status__c,Supplier_Address__c,
                                                                              Supplier_Bill_Date__c,Supplier_Name__c,Total_Payments__c FROM Supplier_Bill__c WHERE Id =:recordId AND Outstanding_Balance__c  > 0 ]);
        
        List<Supplier_Bill_Snapshot__c> sBillSnap = new List<Supplier_Bill_Snapshot__c>();
        
        Integer IPSCount = 0;
        Integer errorCount = 0;
        String errorsDetails = '';

         
        if(supplierBillList.size() > 0){
        	
            for(Supplier_Bill__c res : supplierBillList){
                Supplier_Bill_Snapshot__c sbillSnapList = new Supplier_Bill_Snapshot__c();
                if(res.Bill_Amount__c != null) sbillSnapList.Bill_Amount__c = res.Bill_Amount__c;
                if(res.Bill_Closing_Date__c != null) sbillSnapList.Bill_Closing_Date__c = res.Bill_Closing_Date__c;
                if(res.Bill_Due_Date__c != null) sbillSnapList.Bill_Due_Date__c = res.Bill_Due_Date__c;
                if(res.Bill_Settled_Date__c != null) sbillSnapList.Bill_Settled_Date__c = res.Bill_Settled_Date__c;
                if(res.Brand_Quote__c != null) sbillSnapList.Brand_Quote__c = res.Brand_Quote__c; 
                if(res.Chart_of_Account__c != null) sbillSnapList.Chart_of_Account__c = res.Chart_of_Account__c; 
               if(res.Is_Brand__c != null) sbillSnapList.Is_Brand__c = res.Is_Brand__c;
                if(res.Order_or_Service__c != null) sbillSnapList.Order_or_Service__c = res.Order_or_Service__c;
                if(res.Outstanding_Balance__c != null) sbillSnapList.Outstanding_Balance__c = res.Outstanding_Balance__c;
                if(res.Payment_Hold__c != null) sbillSnapList.Payment_Hold__c = res.Payment_Hold__c; 
                if(res.Payment_Terms__c != null) sbillSnapList.Payment_Terms__c = res.Payment_Terms__c;
                if(res.PO_Settled_Date__c != null) sbillSnapList.PO_Settled_Date__c = res.PO_Settled_Date__c;
                 if(res.Purchase_Order__c != null) sbillSnapList.Purchase_Order__c = res.Purchase_Order__c;
                 if(res.Ownership__c != null) sbillSnapList.Ownerids__c = res.Ownership__c;
                if(res.Reference__c != null) sbillSnapList.Reference__c = res.Reference__c; 
                if(res.Requestor_Name__c != null) sbillSnapList.Requestor_Name__c = res.Requestor_Name__c; 
                if(res.Shipping_Terms__c != null) sbillSnapList.Shipping_Terms__c = res.Shipping_Terms__c;
                 if(res.Ship_Confirmation_Date__c != null) sbillSnapList.Ship_Confirmation_Date__c = res.Ship_Confirmation_Date__c;
                 if(res.Site__c != null) sbillSnapList.Site__c = res.Site__c;
                if(res.Sold_to_Party__c != null) sbillSnapList.Sold_to_Party__c = res.Sold_to_Party__c; 
                if(res.Status__c != null) sbillSnapList.Status__c = res.Status__c;
                if(res.Supplier_Address__c != null) sbillSnapList.Supplier_Address__c = res.Supplier_Address__c;
				if(res.Supplier_Bill_Date__c != null) sbillSnapList.Supplier_Bill_Date__c = res.Supplier_Bill_Date__c;
				if(res.Supplier_Name__c != null) sbillSnapList.Supplier_Name__c = res.Supplier_Name__c;
				if(res.Total_Payments__c != null) sbillSnapList.Total_Payments__c = res.Total_Payments__c;
              
               sBillSnap.add(sbillSnapList);
            }
            
            if(sBillSnap.size() > 0){
            	//insert invSnap; 
                Database.SaveResult[] lsr = Database.insert(sBillSnap,false);
                for (Database.SaveResult SR : lsr) { 
                    if (!SR.isSuccess()) {
                        errorCount +=1;
                        errorsDetails += errorCount+'. ';
                        for(Database.Error err : sr.getErrors()) {
                            errorsDetails += err.getStatusCode() + ': ' + err.getMessage();
                            errorsDetails += err.getFields();
                            System.debug('Error - '+err.getMessage() + '\nStatus Code : '+err.getStatusCode()+'\n Fields : '+err.getFields());
                        }
                        errorsDetails += '<br>';
                        /*Database.Error error = SR.getErrors().get(0);
                    	String failedDML = error.getMessage();
                        errorsDetails += errorCount +'. '+failedDML +;
                    	System.debug('failedDML = '+failedDML);*/
                    } else {
                        IPSCount +=1;
                    }
                }
            }
        }
        
        Messaging.SingleEmailMessage[] emails = new Messaging.SingleEmailMessage[]{};
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        
        String jobDate = '';
        Date todayDate  = Date.today();
        jobDate = todayDate.month()+'/'+todayDate.day()+'/'+todayDate.year();
        
        String htmlBody = 'Hello, <br><br>Salesforce supplier Bill Snapshot Status';
        htmlBody += '<br><ul><li>Snapshot Run Date: '+jobDate+'</li>';
      //  htmlBody += '<li>Total Inventory Position records: '+invPosList.size()+'</li>';
        htmlBody += '<li>Total Snapshot record created: '+IPSCount+'</li>';
       	htmlBody += '<li>Error records: '+errorCount+'</li></ul>';
        if(errorsDetails != ''){
        	htmlBody += 'Error Details: '+ errorsDetails;
        }
        htmlBody += '<br>Thanks<br>IT Support';
        List<String> bccAddresss = label.Brand_BCC_Addresses.split(',');
        mail.setToAddresses(bccAddresss);
        List<String> lstToadd= SUPPLIER_SNAPSHOT_TO_ADDRESS.split(',');
        mail.setToAddresses(lstToadd);
        mail.setSaveAsActivity(false);
        mail.setHtmlBody(htmlBody);
        mail.setSubject('Supplier Bill Records created for '); 
        emails.add(mail);
        Messaging.sendEmail(emails);
        
        return r;
	}
    

}