force-app/main/default/objects/Brand_Quote__c/Brand_Quote__c.object-meta.xml
<CustomObject>
    <description>Buy Quote to Purchase from Brands. Sell Quotes to Sell to Dispensaries</description>
    <label>Brand Quote</label>
    <nameField>
        <displayFormat>BQ-{0000000000}</displayFormat>
        <label>Brand Quote</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Brand Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Brand_Quote__c/fields/Ship_Confirmation_Date__c.field-meta.xml
<CustomField>
    <fullName>Ship_Confirmation_Date__c</fullName>
    <inlineHelpText>Field is auto updated from Shipping Manifest. If Service Quote, updated from PWO as date completed.</inlineHelpText>
    <label>Ship Confirmation Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Brand_Quote__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site</label>
    <referenceTo>Site__c</referenceTo>
    <relationshipLabel>Brand Quotes</relationshipLabel>
    <relationshipName>Brand_Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Chart_of_Account__c/Chart_of_Account__c.object-meta.xml
<CustomObject>
    <description>Chart of Accounts for book keeping.</description>
    <label>Chart of Account</label>
    <nameField>
        <label>Chart of Accounts</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Chart of Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Google_Distance_Matrix_API__c/Google_Distance_Matrix_API__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Google_Distance_Matrix_API</label>
</CustomObject>

force-app/main/default/objects/Site__c/Site__c.object-meta.xml
<CustomObject>
    <description>All objects must have a Site Name and License Class or A or M. For separate sales and inventory record.</description>
    <label>Site</label>
    <nameField>
        <label>Site</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Supplier_Bill__c/Supplier_Bill__c.object-meta.xml
<CustomObject>
    <label>Supplier Bill</label>
    <nameField>
        <displayFormat>BILL-{YYYY}-{MM}-{000000}</displayFormat>
        <label>Supplier Bill</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Supplier Bills</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Supplier_Bill__c/fields/Bill_Amount__c.field-meta.xml
<CustomField>
    <fullName>Bill_Amount__c</fullName>
    <label>Bill Amount</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Supplier_Bill__c/fields/Bill_Closing_Date__c.field-meta.xml
<CustomField>
    <fullName>Bill_Closing_Date__c</fullName>
    <label>Bill Closing Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Supplier_Bill__c/fields/Bill_Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Bill_Due_Date__c</fullName>
    <label>Bill Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Supplier_Bill__c/fields/Bill_Opening_Date__c.field-meta.xml
<CustomField>
    <fullName>Bill_Opening_Date__c</fullName>
    <label>Bill Opening Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Supplier_Bill__c/fields/Bill_Settled_Date__c.field-meta.xml
<CustomField>
    <fullName>Bill_Settled_Date__c</fullName>
    <label>Bill Settled Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Supplier_Bill__c/fields/Brand_Quote__c.field-meta.xml
<CustomField>
    <fullName>Brand_Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Brand Quote</label>
    <referenceTo>Brand_Quote__c</referenceTo>
    <relationshipLabel>Supplier Bills</relationshipLabel>
    <relationshipName>Supplier_Bills</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Supplier_Bill__c/fields/Chart_of_Account__c.field-meta.xml
<CustomField>
    <fullName>Chart_of_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Chart of Account</label>
    <referenceTo>Chart_of_Account__c</referenceTo>
    <relationshipLabel>Supplier Bills</relationshipLabel>
    <relationshipName>Supplier_Bills</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Supplier_Bill__c/fields/Ship_Confirmation_Date__c.field-meta.xml
<CustomField>
    <fullName>Ship_Confirmation_Date__c</fullName>
    <formula>Purchase_Order__r.Ship_Confirmation_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Ship Confirmation Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Supplier_Bill__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site</label>
    <referenceTo>Site__c</referenceTo>
    <relationshipLabel>Supplier Bills</relationshipLabel>
    <relationshipName>Supplier_Bills</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Supplier_Bill__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/runSupplierBillSnapshotTest.cls
@isTest
public class runSupplierBillSnapshotTest {
static testMethod void testShipConfirmRSM() {
    test.startTest();
    TestUtilData.skipTrigger = true;
    Test.setMock(HttpCalloutMock.class, new StateLicense_MockResponseTest());
    Google_Distance_Matrix_API__c[] GDMIs = new Google_Distance_Matrix_API__c[]{new Google_Distance_Matrix_API__c(Name='GMaps_Endpoint',Value__c = 'https://maps.googleapis.com/maps/api/distancematrix/json?'),new Google_Distance_Matrix_API__c(Name='Gmaps_APIKey',Value__c = 'gjhghj3232342jkhj')};
        insert GDMIs;
    TestUtilData.createTestData();
    Site__c s =[SELECT Id From Site__c Limit 1];
    Account acc =[SELECT Id From Account WHERE Name=:'Test Account1' Limit 1];
    Supplier_Bill__c PO = new Supplier_Bill__c();
    PO.Status__c = 'Approved';
    insert PO;
    Supplier_Bill__c  SB = [SELECT Bill_Amount__c,Bill_Closing_Date__c,Bill_Due_Date__c,Bill_Opening_Date__c,Bill_Settled_Date__c,Brand_Quote__c,
                            Chart_of_Account__c FROM Supplier_Bill__c where id =:PO.Id];
    SB.Bill_Closing_Date__c=system.today();
    //  SB.Ship_Confirmation_Date__c =system.today();
    SB.Bill_Amount__c=200;
    update SB;
    runSupplierBillSnapshot.runSupplierBillSnapshot(SB.Id);
    Database.executeBatch(new batchToRunSupplierBillSnapshot());
    
    Test.stopTest();
}
}