force-app/main/default/objects/Brand_Quote__c/Brand_Quote__c.object-meta.xml
<CustomObject>
    <description>Buy Quote to Purchase from Brands. Sell Quotes to Sell to Dispensaries</description>
    <label>Brand Quote</label>
    <nameField>
        <displayFormat>BQ-{0000000000}</displayFormat>
        <label>Brand Quote</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Brand Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Brand_Quote__c/fields/Distributor_Contact__c.field-meta.xml
<CustomField>
    <fullName>Distributor_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Distributor Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Brand Quotes (Distributor Contact)</relationshipLabel>
    <relationshipName>Brand_Quotes2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Brand_Quote__c/fields/Distributor_License__c.field-meta.xml
<CustomField>
    <fullName>Distributor_License__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Distributor License</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>State_Licenses__c.License_Name__c</field>
            <operation>equals</operation>
            <valueField>$Source.Distributor_Name__c</valueField>
        </filterItems>
        <filterItems>
            <field>State_Licenses__c.State_License_Holder__c</field>
            <operation>equals</operation>
            <valueField>$Source.Distributor_Name__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>State_Licenses__c</referenceTo>
    <relationshipLabel>Brand Quotes (Distributor License)</relationshipLabel>
    <relationshipName>Brand_Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Brand_Quote__c/fields/Distributor_Name__c.field-meta.xml
<CustomField>
    <fullName>Distributor_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Distributor Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Brand Quotes as Distributor</relationshipLabel>
    <relationshipName>Brand_Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Brand_Quote__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site</label>
    <referenceTo>Site__c</referenceTo>
    <relationshipLabel>Brand Quotes</relationshipLabel>
    <relationshipName>Brand_Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Order__c/Sales_Order__c.object-meta.xml
<CustomObject>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>SO-{0000000000}</displayFormat>
        <label>Sales Order</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Order__c/fields/Brand_Quote__c.field-meta.xml
<CustomField>
    <fullName>Brand_Quote__c</fullName>
    <label>Brand Quote</label>
    <referenceTo>Brand_Quote__c</referenceTo>
    <relationshipLabel>Sales Orders</relationshipLabel>
    <relationshipName>Sales_Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Sales_Order__c/fields/Distributor_Contact__c.field-meta.xml
<CustomField>
    <fullName>Distributor_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Distributor Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Sales Orders (Distributor Contact)</relationshipLabel>
    <relationshipName>Sales_Orders1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Order__c/fields/Distributor_License__c.field-meta.xml
<CustomField>
    <fullName>Distributor_License__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Distributor License</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>State_Licenses__c.License_Name__c</field>
            <operation>equals</operation>
            <valueField>$Source.Distributor_Name__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>State_Licenses__c</referenceTo>
    <relationshipLabel>Sales Orders (Distributor License)</relationshipLabel>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Order__c/fields/Distributor_Name__c.field-meta.xml
<CustomField>
    <fullName>Distributor_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Distributor Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sales Orders as Distributor</relationshipLabel>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Order__c/fields/Driver__c.field-meta.xml
<CustomField>
    <fullName>Driver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Driver</label>
    <referenceTo>Drivers__c</referenceTo>
    <relationshipLabel>Sales Orders</relationshipLabel>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Order__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site</label>
    <referenceTo>Site__c</referenceTo>
    <relationshipLabel>Sales Orders</relationshipLabel>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Order__c/fields/Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Vehicle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vehicle</label>
    <referenceTo>Vehicles__c</referenceTo>
    <relationshipLabel>Sales Orders</relationshipLabel>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipping_Manifest__c/Shipping_Manifest__c.object-meta.xml
<CustomObject>
    <description>Used in the generation of compliance document to enable retail delivery.</description>
    <label>Shipping Manifest</label>
    <nameField>
        <displayFormat>SM-{YYYY}-{MM}-{0000000000}</displayFormat>
        <label>Shipping Manifest</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipping Manifests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Shipping_Manifest__c/fields/Brand_Quote__c.field-meta.xml
<CustomField>
    <fullName>Brand_Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Brand Quote</label>
    <referenceTo>Brand_Quote__c</referenceTo>
    <relationshipLabel>Shipping Manifests</relationshipLabel>
    <relationshipName>Shipping_Manifests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipping_Manifest__c/fields/Distributor_Contact__c.field-meta.xml
<CustomField>
    <fullName>Distributor_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Distributor Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Shipping Manifests (Distributor Contact)</relationshipLabel>
    <relationshipName>Shipping_Manifests1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipping_Manifest__c/fields/Distributor_License__c.field-meta.xml
<CustomField>
    <fullName>Distributor_License__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Distributor License</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>State_Licenses__c.License_Name__c</field>
            <operation>equals</operation>
            <valueField>$Source.Distributor_Name__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>State_Licenses__c</referenceTo>
    <relationshipLabel>Shipping Manifests (Distributor License)</relationshipLabel>
    <relationshipName>Shipping_Manifests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipping_Manifest__c/fields/Distributor_Name__c.field-meta.xml
<CustomField>
    <fullName>Distributor_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Distributor Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Shipping Manifests as Distributor</relationshipLabel>
    <relationshipName>Shipping_Manifests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipping_Manifest__c/fields/Driver__c.field-meta.xml
<CustomField>
    <fullName>Driver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Driver</label>
    <referenceTo>Drivers__c</referenceTo>
    <relationshipLabel>Shipping Manifests</relationshipLabel>
    <relationshipName>Shipping_Manifests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipping_Manifest__c/fields/drivers__c.field-meta.xml
<CustomField>
    <fullName>drivers__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>driver</label>
    <referenceTo>Driver__c</referenceTo>
    <relationshipLabel>Shipping Manifests</relationshipLabel>
    <relationshipName>Shipping_Manifests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipping_Manifest__c/fields/Planned_Ship_Transfer_Date__c.field-meta.xml
<CustomField>
    <fullName>Planned_Ship_Transfer_Date__c</fullName>
    <inlineHelpText>Date in which the products are to be delivered</inlineHelpText>
    <label>Planned Ship/Transfer Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Shipping_Manifest__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Order</label>
    <referenceTo>Sales_Order__c</referenceTo>
    <relationshipLabel>Shipping Manifests</relationshipLabel>
    <relationshipName>Shipping_Manifests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipping_Manifest__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site</label>
    <referenceTo>Site__c</referenceTo>
    <relationshipLabel>Shipping Manifests</relationshipLabel>
    <relationshipName>Shipping_Manifests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipping_Manifest__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
            <value>
                <fullName>Shipment Pending</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Pending Delivery</fullName>
            </value>
            <value>
                <fullName>Shipment Complete</fullName>
            </value>
            <value>
                <fullName>In-Transit</fullName>
            </value>
            <value>
                <fullName>Received</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
                <isActive>false</isActive>
                <label>Submitted</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Shipping_Manifest__c/fields/Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Vehicle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vehicle</label>
    <referenceTo>Vehicles__c</referenceTo>
    <relationshipLabel>Shipping Manifests</relationshipLabel>
    <relationshipName>Shipping_Manifests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipping_Manifest_Line__c/Shipping_Manifest_Line__c.object-meta.xml
<CustomObject>
    <label>Shipping Manifest Line</label>
    <nameField>
        <displayFormat>SML-{0000000000}</displayFormat>
        <label>SM Line</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipping Manifest Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Shipping_Manifest_Line__c/fields/Shipping_Manifest__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Manifest__c</fullName>
    <label>Shipping Manifest</label>
    <referenceTo>Shipping_Manifest__c</referenceTo>
    <relationshipLabel>Shipping Manifest Lines</relationshipLabel>
    <relationshipName>Shipping_Manifest_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/AssignVehicleToTSMControllerTest.cls
/**
 * Copyright (c) 2018 Filigreen Distro
 * All rights reserved.
 * AssignVehicleToTSMControllerTest
 */
@isTest(OnInstall=false SeeAllData=false)
public class AssignVehicleToTSMControllerTest{
    
    static Vehicles__c vehicleObj;
    static Sales_Order__c salesOrderObj;
    static Shipping_Manifest__c tsmObj;
    static List<Product2> products;
    
    // Test loading of Assign Vehicle page from TSM detail page
    static testMethod void testLoadVehicleAndTSMDetails_FromTSMPage(){
        
        // Get data created from setup
        retrieveData();
        
        // Update and create necessary data
        updateAndCreateData();
        
        PageReference pageRef = Page.AssignVehicle;
        pageRef.getParameters().put('id', tsmObj.Id);
        Test.setCurrentPage(pageRef);
        
        ApexPages.StandardController stdController = new ApexPages.StandardController(tsmObj);
        AssignVehicleToTSMController controllerObj = new AssignVehicleToTSMController(stdController);
        
        pageRef = controllerObj.doPrepare();
        System.assertEquals(null, pageRef, 'Page reference mis-match');
        System.assertEquals(tsmObj.Id, controllerObj.tsmObj.Id, 'TSM mis-match');
        System.assertEquals(1, controllerObj.totalProduct, 'TSM Line mis-match');
        System.assertEquals(vehicleObj.Id, controllerObj.vehicleObj.Id, 'Vehicle mis-match');
        System.assertEquals(1, controllerObj.TSMList.size(), 'TSM List mis-match');
        
        pageRef = controllerObj.cancelAction();
        System.assertEquals('/'+String.valueOf(tsmObj.Id).subString(0, 15), pageRef.getURL(), 'Page reference mis-match');
    }
    
    // Test update Vehicle of TSM
    static testMethod void testAssignVehicleToTSM(){
        
        // Get data created from setup
        retrieveData();
        
        // Update and create necessary data
        updateAndCreateData();
        
        PageReference pageRef = Page.AssignVehicle;
        pageRef.getParameters().put('id', tsmObj.Id);
        Test.setCurrentPage(pageRef);
        
        ApexPages.StandardController stdController = new ApexPages.StandardController(tsmObj);
        AssignVehicleToTSMController controllerObj = new AssignVehicleToTSMController(stdController);
        
        pageRef = controllerObj.doPrepare();
        System.assertEquals(null, pageRef, 'Page reference mis-match');
        System.assertEquals(tsmObj.Id, controllerObj.tsmObj.Id, 'TSM mis-match');
        System.assertEquals(1, controllerObj.totalProduct, 'TSM Line mis-match');
        System.assertEquals(vehicleObj.Id, controllerObj.vehicleObj.Id, 'Vehicle mis-match');
        System.assertEquals(1, controllerObj.tsmList.size(), 'TSM List mis-match');
        
        Test.startTest();
        
        // Set TSM vehicle to null to throw validation
        controllerObj.tsmObj.Vehicle__c = null;
        pageRef = controllerObj.assignVehicle();
        System.assertEquals(null, pageRef, 'Page reference mis-match');
        
        // Verify validation messages
        List<ApexPages.Message> msgList = ApexPages.getMessages();
        System.assertEquals(1, msgList.size(), 'Number of Validation messages mis-match');
        System.assert(msgList[0].getDetail().contains(Label.Select_Vehicle), 'Validation message mis-match');
        
        // Assign new vehicle and planned ship date to TSM
        Vehicles__c newVehicleObj = TestUtilData.createVehicle(false);
        insert newVehicleObj;
        
        controllerObj.tsmObj.Vehicle__c = newVehicleObj.Id;
        controllerObj.tsmObj.Planned_Ship_Transfer_Date__c = System.Today() + 13;
        pageRef = controllerObj.assignVehicle();
        System.assertEquals('/'+String.valueOf(tsmObj.Id).subString(0, 15), pageRef.getURL(), 'Page reference mis-match');
        
        // verify TSM vehicle and planned ship date
        tsmObj = [Select Status__c, Planned_Ship_Transfer_Date__c, Vehicle__c From Shipping_Manifest__c Where Id =: tsmObj.Id AND RecordTypeId =: ShippinManifestSupport.getTSMRecordTypeId()];
        System.assertEquals(newVehicleObj.Id, tsmObj.Vehicle__c, 'Vehicle mis-match');
        System.assertEquals(System.Today() + 13, tsmObj.Planned_Ship_Transfer_Date__c, 'Planned ship date mis-match');
        System.assertEquals(RSMSupport.STATUS_DRAFT, tsmObj.Status__c, 'TSM Status mis-match');
        
        Test.stopTest();
    }
    
    // Test update Vehicle of TSM
    static testMethod void testUpdateTSMStatusToShipmentPending_DriverAndVehicleAssignedToTSM(){
        
        // Get data created from setup
        retrieveData();
        
        // Update and create necessary data
        updateAndCreateData();
        
        // Create Driver record
        Drivers__c driverObj = TestUtilData.createDriver(true);
        tsmObj.Driver__c = driverObj.Id;
        update tsmObj;
        
        PageReference pageRef = Page.AssignVehicle;
        pageRef.getParameters().put('id', tsmObj.Id);
        Test.setCurrentPage(pageRef);
        
        ApexPages.StandardController stdController = new ApexPages.StandardController(tsmObj);
        AssignVehicleToTSMController controllerObj = new AssignVehicleToTSMController(stdController);
        
        pageRef = controllerObj.doPrepare();
        System.assertEquals(null, pageRef, 'Page reference mis-match');
        System.assertEquals(tsmObj.Id, controllerObj.tsmObj.Id, 'TSM mis-match');
        System.assertEquals(1, controllerObj.totalProduct, 'TSM Line mis-match');
        System.assertEquals(vehicleObj.Id, controllerObj.vehicleObj.Id, 'Vehicle mis-match');
        System.assertEquals(1, controllerObj.tsmList.size(), 'TSM List mis-match');
        
        Test.startTest();
        
        // Set TSM vehicle to null to throw validation
        controllerObj.tsmObj.Vehicle__c = null;
        pageRef = controllerObj.assignVehicle();
        System.assertEquals(null, pageRef, 'Page reference mis-match');
        
        // Verify validation messages
        List<ApexPages.Message> msgList = ApexPages.getMessages();
        System.assertEquals(1, msgList.size(), 'Number of Validation messages mis-match');
        System.assert(msgList[0].getDetail().contains(Label.Select_Vehicle), 'Validation message mis-match');
        
        // Assign new vehicle and planned ship date to TSM
        Vehicles__c newVehicleObj = TestUtilData.createVehicle(false);
        insert newVehicleObj;
        
        controllerObj.tsmObj.Vehicle__c = newVehicleObj.Id;
        controllerObj.tsmObj.Planned_Ship_Transfer_Date__c = System.Today() + 13;
        pageRef = controllerObj.assignVehicle();
        System.assertEquals('/'+String.valueOf(tsmObj.Id).subString(0, 15), pageRef.getURL(), 'Page reference mis-match');
        
        // verify TSM vehicle and planned ship date
        tsmObj = [Select Status__c, Planned_Ship_Transfer_Date__c, Vehicle__c From Shipping_Manifest__c Where Id =: tsmObj.Id AND RecordTypeId =: ShippinManifestSupport.getTSMRecordTypeId()];
        System.assertEquals(newVehicleObj.Id, tsmObj.Vehicle__c, 'Vehicle mis-match');
        System.assertEquals(System.Today() + 13, tsmObj.Planned_Ship_Transfer_Date__c, 'Planned ship date mis-match');
        System.assertEquals(RSMSupport.STATUS_SHIPMENT_PENDING, tsmObj.Status__c, 'TSM Status mis-match');
        
        Test.stopTest();
    }
    
    // Test update Driver of TSM - Status should not be changed if it is already In-Transit
    static testMethod void testDoNotUpdateTSMStatusToShipmentPending_ExistingStatusInTransit_DriverAndVehicleAssignedToTSM(){
        
        // Get data created from setup
        retrieveData();
        
        // Update and create necessary data
        updateAndCreateData();
        
        // Create Driver record
        Drivers__c driverObj = TestUtilData.createDriver(true);
        tsmObj.Driver__c = driverObj.Id;
        tsmObj.Status__c = RSMSupport.STATUS_IN_TRANSIT;
        update tsmObj;
        
        PageReference pageRef = Page.AssignVehicle;
        pageRef.getParameters().put('id', tsmObj.Id);
        Test.setCurrentPage(pageRef);
        
        ApexPages.StandardController stdController = new ApexPages.StandardController(tsmObj);
        AssignVehicleToTSMController controllerObj = new AssignVehicleToTSMController(stdController);
        
        pageRef = controllerObj.doPrepare();
        System.assertEquals(null, pageRef, 'Page reference mis-match');
        System.assertEquals(tsmObj.Id, controllerObj.tsmObj.Id, 'TSM mis-match');
        System.assertEquals(1, controllerObj.totalProduct, 'TSM Line mis-match');
        System.assertEquals(vehicleObj.Id, controllerObj.vehicleObj.Id, 'Vehicle mis-match');
        System.assertEquals(1, controllerObj.tsmList.size(), 'TSM List mis-match');
        
        Test.startTest();
        
        // Assign new vehicle and planned ship date to TSM
        Vehicles__c newVehicleObj = TestUtilData.createVehicle(false);
        insert newVehicleObj;
        
        controllerObj.tsmObj.Vehicle__c = newVehicleObj.Id;
        controllerObj.tsmObj.Planned_Ship_Transfer_Date__c = System.Today() + 13;
        pageRef = controllerObj.assignVehicle();
        System.assertEquals('/'+String.valueOf(tsmObj.Id).subString(0, 15), pageRef.getURL(), 'Page reference mis-match');
        
        // verify TSM vehicle and planned ship date
        tsmObj = [Select Status__c, Planned_Ship_Transfer_Date__c, Vehicle__c From Shipping_Manifest__c Where Id =: tsmObj.Id AND RecordTypeId =: ShippinManifestSupport.getTSMRecordTypeId()];
        System.assertEquals(newVehicleObj.Id, tsmObj.Vehicle__c, 'Vehicle mis-match');
        System.assertEquals(System.Today() + 13, tsmObj.Planned_Ship_Transfer_Date__c, 'Planned ship date mis-match');
        System.assertEquals(RSMSupport.STATUS_IN_TRANSIT, tsmObj.Status__c, 'TSM Status mis-match');
        
        Test.stopTest();
    }
    
    // Test update Vehicle of TSM - Status should not be changed if it is already shipment complete
    static testMethod void testVehicleAssignedToTSM_AfterStatusChangedToShipmentComplete(){
        
        // Get data created from setup
        retrieveData();
        
        // Update and create necessary data
        updateAndCreateData();
        
        tsmObj.Status__c = RSMSupport.STATUS_SHIPMENT_COMPLETE;
        update tsmObj;
        
        PageReference pageRef = Page.AssignVehicle;
        pageRef.getParameters().put('id', tsmObj.Id);
        Test.setCurrentPage(pageRef);
        
        ApexPages.StandardController stdController = new ApexPages.StandardController(tsmObj);
        AssignVehicleToTSMController controllerObj = new AssignVehicleToTSMController(stdController);
        
        pageRef = controllerObj.doPrepare();
        System.assertEquals(null, pageRef, 'Page reference mis-match');
        System.assertEquals(tsmObj.Id, controllerObj.tsmObj.Id, 'TSM mis-match');
        System.assertEquals(1, controllerObj.totalProduct, 'TSM Line mis-match');
        System.assertEquals(vehicleObj.Id, controllerObj.vehicleObj.Id, 'Vehicle mis-match');
        System.assertEquals(1, controllerObj.tsmList.size(), 'TSM List mis-match');
        
        Test.startTest();
        
        // Set TSM vehicle to null to throw validation
        controllerObj.tsmObj.Vehicle__c = null;
        pageRef = controllerObj.assignVehicle();
        System.assertEquals(null, pageRef, 'Page reference mis-match');
        
        // Verify validation messages
        List<ApexPages.Message> msgList = ApexPages.getMessages();
        System.assertEquals(1, msgList.size(), 'Number of Validation messages mis-match');
        System.assert(msgList[0].getDetail().contains(Label.Select_Vehicle), 'Validation message mis-match');
        
        // Assign new vehicle and planned ship date to TSM
        Vehicles__c newVehicleObj = TestUtilData.createVehicle(false);
        insert newVehicleObj;
        
        controllerObj.tsmObj.Vehicle__c = newVehicleObj.Id;
        controllerObj.tsmObj.Planned_Ship_Transfer_Date__c = System.Today() + 13;
        pageRef = controllerObj.assignVehicle();
        System.assertEquals('/'+String.valueOf(tsmObj.Id).subString(0, 15), pageRef.getURL(), 'Page reference mis-match');
        
        // verify TSM vehicle and planned ship date
        tsmObj = [Select Status__c, Planned_Ship_Transfer_Date__c, Vehicle__c From Shipping_Manifest__c Where Id =: tsmObj.Id AND RecordTypeId =: ShippinManifestSupport.getTSMRecordTypeId()];
        System.assertEquals(newVehicleObj.Id, tsmObj.Vehicle__c, 'Vehicle mis-match');
        System.assertEquals(System.Today() + 13, tsmObj.Planned_Ship_Transfer_Date__c, 'Planned ship date mis-match');
        System.assertEquals(RSMSupport.STATUS_SHIPMENT_COMPLETE, tsmObj.Status__c, 'TSM Status mis-match');
        
        Test.stopTest();
    }
    
    @TestSetUp
    static void testDataSetUp(){
        TestUtilData.createTestData();
    }
    
    // Retrieve data created from data setup
    public static void retrieveData(){
        salesOrderObj = new Sales_Order__c();
        salesOrderObj = [Select Site__c,
                                Brand_Quote__c,
                                Distributor_Contact__c,
                                Distributor_License__c,
                                Distributor_Name__c,
                                Opportunity_Name__c,
                                Payment_Terms__c,
                                Planned_Ship_Date__c,
                                Receiver_Contact__c,
                                Receiver_License__c,
                                Receiver_Name__c,
                                Sample_Order__c,
                                Shipping_Method__c,
                                Shipping_Terms__c,
                                Supplier_Contact__c,
                                Supplier_License__c,
                                Supplier_Name__c
                                from Sales_Order__c];
        
        products = new List<Product2>();
        products = [Select Id from Product2];
    }
    
    // Update necessary data for Assign Vehicle logic
    public static void updateAndCreateData(){
        // Create Vehicle
        vehicleObj = TestUtilData.createVehicle(true);
        
        tsmObj = TestUtilData.createTSM(salesOrderObj, false);
        tsmObj.Vehicle__c = vehicleObj.Id;
        insert tsmObj;
        
        Shipping_Manifest_Line__c tsmLineObj = TestUtilData.createTSMLine(products[0], tsmObj.Id, true);
    }
}