force-app/main/default/objects/Brand_Quote__c/Brand_Quote__c.object-meta.xml
<CustomObject>
    <description>Buy Quote to Purchase from Brands. Sell Quotes to Sell to Dispensaries</description>
    <label>Brand Quote</label>
    <nameField>
        <displayFormat>BQ-{0000000000}</displayFormat>
        <label>Brand Quote</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Brand Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Brand_Quote__c/fields/BQ_Status__c.field-meta.xml
<CustomField>
    <fullName>BQ_Status__c</fullName>
    <inlineHelpText>Status will auto-updated based on workflow defined.</inlineHelpText>
    <label>BQ Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Shipped</fullName>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Brand_Quote__c/fields/Customer_PO_or_Quote__c.field-meta.xml
<CustomField>
    <fullName>Customer_PO_or_Quote__c</fullName>
    <inlineHelpText>For Sell Quote, input Leaflink Order ID, or Retail Delivery Ticket. For Buy Quote, input Sell Quote or TSM</inlineHelpText>
    <label>Order or Service #</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Brand_Quote__c/fields/Distributor_License__c.field-meta.xml
<CustomField>
    <fullName>Distributor_License__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Distributor License</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>State_Licenses__c.License_Name__c</field>
            <operation>equals</operation>
            <valueField>$Source.Distributor_Name__c</valueField>
        </filterItems>
        <filterItems>
            <field>State_Licenses__c.State_License_Holder__c</field>
            <operation>equals</operation>
            <valueField>$Source.Distributor_Name__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>State_Licenses__c</referenceTo>
    <relationshipLabel>Brand Quotes (Distributor License)</relationshipLabel>
    <relationshipName>Brand_Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Brand_Quote__c/fields/Distributor_Name__c.field-meta.xml
<CustomField>
    <fullName>Distributor_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Distributor Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Brand Quotes as Distributor</relationshipLabel>
    <relationshipName>Brand_Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Brand_Quote__c/fields/KP_Ready_for_Delivery__c.field-meta.xml
<CustomField>
    <fullName>KP_Ready_for_Delivery__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Ready for Delivery from Kushy punch API.</description>
    <inlineHelpText>Related to Kushy Punch API data sync.</inlineHelpText>
    <label>KP Ready for Delivery</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Brand_Quote__c/fields/Kushy_Punch_Order_Number__c.field-meta.xml
<CustomField>
    <fullName>Kushy_Punch_Order_Number__c</fullName>
    <externalId>true</externalId>
    <label>Kushy Punch Order Number</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Brand_Quote__c/fields/Opportunity_Name__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Name</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Brand_Quote__c/fields/Ownership__c.field-meta.xml
<CustomField>
    <fullName>Ownership__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ownership</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Brand Quotes as Ownership</relationshipLabel>
    <relationshipName>Brand_Quotes3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Brand_Quote__c/fields/Receiver_Contact__c.field-meta.xml
<CustomField>
    <fullName>Receiver_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Receiver Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Receiver_Name__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Brand Quotes (Receiver Contact)</relationshipLabel>
    <relationshipName>Brand_Quotes1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Brand_Quote__c/fields/Receiver_License__c.field-meta.xml
<CustomField>
    <fullName>Receiver_License__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Receiver License</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>State_Licenses__c.License_Name__c</field>
            <operation>equals</operation>
            <valueField>$Source.Receiver_Name__c</valueField>
        </filterItems>
        <filterItems>
            <field>State_Licenses__c.State_License_Holder__c</field>
            <operation>equals</operation>
            <valueField>$Source.Receiver_Name__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>State_Licenses__c</referenceTo>
    <relationshipLabel>Brand Sell Quotes</relationshipLabel>
    <relationshipName>Brand_Quotes1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Brand_Quote__c/fields/Receiver_Name__c.field-meta.xml
<CustomField>
    <fullName>Receiver_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Receiver Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Brand Quotes as Receiver</relationshipLabel>
    <relationshipName>Brand_Quotes2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Brand_Quote__c/fields/Sales_Origin__c.field-meta.xml
<CustomField>
    <fullName>Sales_Origin__c</fullName>
    <label>Sales Origin</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sales_Origin</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Brand_Quote__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site</label>
    <referenceTo>Site__c</referenceTo>
    <relationshipLabel>Brand Quotes</relationshipLabel>
    <relationshipName>Brand_Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Brand_Quote__c/fields/Supplier_Contact__c.field-meta.xml
<CustomField>
    <fullName>Supplier_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Supplier Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Brand Quotes</relationshipLabel>
    <relationshipName>Brand_Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Brand_Quote__c/fields/Supplier_License__c.field-meta.xml
<CustomField>
    <fullName>Supplier_License__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Supplier License</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>State_Licenses__c.License_Name__c</field>
            <operation>equals</operation>
            <valueField>$Source.Supplier_Name__c</valueField>
        </filterItems>
        <filterItems>
            <field>State_Licenses__c.State_License_Holder__c</field>
            <operation>equals</operation>
            <valueField>$Source.Supplier_Name__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>State_Licenses__c</referenceTo>
    <relationshipLabel>Brand Quotes</relationshipLabel>
    <relationshipName>Brand_Quotes2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Brand_Quote__c/fields/Supplier_Name__c.field-meta.xml
<CustomField>
    <fullName>Supplier_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Supplier Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Brand Quotes as Supplier</relationshipLabel>
    <relationshipName>Brand_Quotes1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Company_Custom_Settings__c/Company_Custom_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Company Custom Settings</label>
</CustomObject>

force-app/main/default/objects/Company_Custom_Settings__c/fields/Default_Contact__c.field-meta.xml
<CustomField>
    <fullName>Default_Contact__c</fullName>
    <description>Default distributor contact ID used in BQ</description>
    <inlineHelpText>Default distributor contact ID used in BQ</inlineHelpText>
    <label>Default Contact</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Company_Custom_Settings__c/fields/Default_Distributor__c.field-meta.xml
<CustomField>
    <fullName>Default_Distributor__c</fullName>
    <description>Default distributor ID used in BQ</description>
    <inlineHelpText>Default distributor ID used in BQ</inlineHelpText>
    <label>Default Distributor</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Company_Custom_Settings__c/fields/Default_KP_Contact__c.field-meta.xml
<CustomField>
    <fullName>Default_KP_Contact__c</fullName>
    <description>Default Filigreen contact on all KP orders from Quick base API</description>
    <inlineHelpText>Default Filigreen contact on all KP orders from Quick base API</inlineHelpText>
    <label>Default KP Contact</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Company_Custom_Settings__c/fields/Default_License__c.field-meta.xml
<CustomField>
    <fullName>Default_License__c</fullName>
    <description>Default state license ID used in BQ</description>
    <inlineHelpText>Default state license ID used in BQ</inlineHelpText>
    <label>Default License</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site__c/Site__c.object-meta.xml
<CustomObject>
    <description>All objects must have a Site Name and License Class or A or M. For separate sales and inventory record.</description>
    <label>Site</label>
    <nameField>
        <label>Site</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Site__c/fields/License_Class__c.field-meta.xml
<CustomField>
    <fullName>License_Class__c</fullName>
    <formula>TEXT(License_ID__r.License_Class__c)</formula>
    <label>License Class</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site__c/fields/License_Name__c.field-meta.xml
<CustomField>
    <fullName>License_Name__c</fullName>
    <formula>License_ID__r.License_Name__r.Name</formula>
    <label>License Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site__c/fields/License_Number__c.field-meta.xml
<CustomField>
    <fullName>License_Number__c</fullName>
    <formula>License_ID__r.License_Number__c</formula>
    <label>License Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/State_Licenses__c/State_Licenses__c.object-meta.xml
<CustomObject>
    <description>Object within the Account to track number of license and address as part of ship to.</description>
    <label>State License</label>
    <nameField>
        <displayFormat>SLID-{YYYY}-{MM}-{0000000000}</displayFormat>
        <label>License</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>State Licenses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/State_Licenses__c/fields/Default_Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Default_Warehouse__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Default Warehouse</label>
    <referenceTo>Site__c</referenceTo>
    <relationshipLabel>State Licenses</relationshipLabel>
    <relationshipName>State_Licenses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/State_Licenses__c/fields/License_Class__c.field-meta.xml
<CustomField>
    <fullName>License_Class__c</fullName>
    <inlineHelpText>License Classification:
Adult Use = A-License
Medicinal Use = M-License</inlineHelpText>
    <label>License Class</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A-License</fullName>
            </value>
            <value>
                <fullName>M-License</fullName>
            </value>
            <value>
                <fullName>AM-License</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/State_Licenses__c/fields/License_Name__c.field-meta.xml
<CustomField>
    <fullName>License_Name__c</fullName>
    <label>License Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>State Licenses</relationshipLabel>
    <relationshipName>State_Licenses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/State_Licenses__c/fields/License_Number__c.field-meta.xml
<CustomField>
    <fullName>License_Number__c</fullName>
    <inlineHelpText>State License Number</inlineHelpText>
    <label>License Number</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/QuickBaseWebhook.cls
@RestResource(urlMapping='/createOrder/*')
global without sharing class QuickBaseWebhook {
    
    @HttpGet
    global static String getData() {
        return 'ReturnDatafromSalesforce';
    }
    
    @HttpPost
    global static Map<String, String> createOrder() {
        Brand_Quote__c newQuote = new Brand_Quote__c(BQ_Status__c = 'Draft');
        Map<String, String> r = new Map<String, String>();
        RestRequest request = RestContext.request;
        System.debug('Actual Request: ' + request);
		System.debug('Order request: ' + request.requestBody.toString());
		Order order = (Order)JSON.deserialize(request.requestBody.toString(), Order.Class);
        if(order.ReadyforDelivery == 'yes'){
            Brand_Quote__c[] bq = [SELECT Id, KP_Ready_for_Delivery__c FROM Brand_Quote__c WHERE Kushy_Punch_Order_Number__c = :order.OrderNumber];
            if(bq.size() > 0 && bq[0].KP_Ready_for_Delivery__c == true){
                return r;
            }
        }
        Site__c[] companySites = [SELECT Id FROM Site__c WHERE Name= : Label.Company_Site_Id];
        Account collective;
        //if(String.isNotBlank(order.AccountName)){
		if(String.isNotBlank(order.StateLicense)){
			State_Licenses__c[] sls = [SELECT Id,License_Name__c FROM State_Licenses__c  WHERE License_Number__c =: order.StateLicense];

	        Account[] collectives = [SELECT Id FROM Account WHERE Id =: sls[0].License_Name__c];//dBA__c =: order.AccountName];
            Account[] kushyPunchs = [SELECT Id ,(SELECT Id FROM State_Licenses__r WHERE License_Class__c ='AM-License') FROM Account WHERE dBA__c = 'Kushy Punch'];
            
            if(!collectives.isEmpty()){
                collective = collectives[0];
                newQuote.Receiver_Name__c = collective.Id;
                Id oppRecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Buy Sell Opportunity').getRecordTypeId();
                Opportunity opp;
                for(Opportunity op: [SELECT Id FROM Opportunity WHERE Name = :order.OrderNumber]){
                    opp = op;
                }
                if(opp == null){
                    opp  = new Opportunity(RecordTypeId = oppRecordTypeId,Name = order.OrderNumber,AccountId = collective.Id,Sales_Origin__c = 'Disty',Site_Name__c = (companySites.isEmpty()?null:companySites[0].Id),StageName = 'Proposal/Price Quote',Type = 'Existing Business');
                    if(!kushyPunchs.isEmpty()){
                        opp.Ownership__c = kushyPunchs[0].Id;
                    }
                    if(String.isNotBlank(order.OrderDate)){
                        String[] orderDateStr = order.OrderDate.split('-');
                        String str = orderDateStr[2]+'-'+orderDateStr[0]+'-'+orderDateStr[1];
                        opp.CloseDate = Date.valueOf(str);
                    }else{
                        opp.CloseDate = System.today();
                    }
                    insert opp;
                }
                newQuote.Opportunity_Name__c = opp.Id;
                System.debug('##opp::'+opp);
            }
            
            if(!kushyPunchs.isEmpty()){
                newQuote.Supplier_Name__c = kushyPunchs[0].Id;
                if(kushyPunchs[0].State_Licenses__r.size() > 0){
                    newQuote.Supplier_License__c = kushyPunchs[0].State_Licenses__r[0].Id;
                }
                newQuote.Ownership__c = kushyPunchs[0].Id;
            }
        }
        if(String.isNotBlank(order.ContactName)){
            Contact receiverContact;
            //String[] names = order.SalesRep.split(', ');
            //String cName = names[1]+' '+names[0]; 
            //for(Contact con: [SELECT Id, Name FROM Contact WHERE Name =: cName and account.dba__c = 'Kushy Punch']){
			for(Contact con: [SELECT Id, Name FROM Contact WHERE Name =: order.ContactName]){
                receiverContact = con;
                break;
            }
            if(receiverContact != null){
                newQuote.Receiver_Contact__c = receiverContact.Id;
            }
        }
		if(String.isNotBlank(order.SalesRep)){
            Contact supplierContact;
            String[] names = order.SalesRep.split(', ');
            String sName = names[1]+' '+names[0]; 
            for(Contact con: [SELECT Id, Name FROM Contact WHERE Name =: sName and account.dba__c = 'Kushy Punch']){
			//for(Contact con: [SELECT Id, Name FROM Contact WHERE Name =: order.ContactName]){
                supplierContact = con;
                break;
            }
            if(supplierContact != null){
                newQuote.Supplier_Contact__c = supplierContact.Id;
            }
        }
        if(String.isNotBlank(order.StateLicense)){
            State_Licenses__c[] sls = [SELECT Id FROM State_Licenses__c  WHERE License_Number__c =: order.StateLicense];
            if(!sls.isEmpty()){
                newQuote.Receiver_License__c = sls[0].Id;
            }
            
        }
        newQuote.Customer_PO_or_Quote__c = order.OrderNumber;
        Id oppRecordTypeId = Schema.SObjectType.Brand_Quote__c.getRecordTypeInfosByName().get('Sell Quote').getRecordTypeId();
        List<Company_Custom_Settings__c> defaultIDs = [select Default_Distributor__c,Default_License__c,Default_Contact__c,Default_KP_Contact__c from Company_Custom_Settings__c];
        if(defaultIDs.size() >0){
            if(defaultIDs[0].Default_Distributor__c != null)
                newQuote.Distributor_Name__c = defaultIDs[0].Default_Distributor__c;
            if(defaultIDs[0].Default_License__c != null)
                newQuote.Distributor_License__c = defaultIDs[0].Default_License__c;
            if(defaultIDs[0].Default_Contact__c != null)
                newQuote.Distributor_Contact__c = defaultIDs[0].Default_Contact__c;
			if(defaultIDs[0].Default_KP_Contact__c != null)
			{
				List<Contact> distyCOntact = [Select id from contact where name =: defaultIDs[0].Default_KP_Contact__c and AccountId =: defaultIDs[0].Default_Distributor__c];
                if(distyCOntact.size() >0)
					newQuote.Distributor_Contact__c = distyCOntact[0].Id;
			}
        }
        newQuote.Payment_Terms__c = 'COD';
        newQuote.Site__c = (companySites.isEmpty()?null:companySites[0].Id);
        newQuote.Sales_Origin__c  = 'Disty';
        newQuote.RecordTypeId = oppRecordTypeId;
        newQuote.Kushy_Punch_Order_Number__c = order.OrderNumber;
        if(order.ReadyforDelivery == 'yes'){
            newQuote.KP_Ready_for_Delivery__c = true;
        }
        if(String.isNotBlank(order.OrderDate)){
            String[] orderDateStr = order.OrderDate.split('-');
            String str = orderDateStr[2]+'-'+orderDateStr[0]+'-'+orderDateStr[1];
            newQuote.Supplier_Acceptance_Date__c = Date.valueOf(str);
        }
		if(String.isNotBlank(order.RequestedShipDate)){
			String[] reqDate = order.RequestedShipDate.split('-');
			String str = reqDate[2]+'-'+reqDate[0]+'-'+reqDate[1];
			newQuote.Requested_Ship_Date__c = Date.valueOf(str);
		}
		if(String.isNotBlank(order.Notes)){
			newQuote.Notes__c	 = order.Notes;
		}
        Database.upsert(newQuote,Brand_Quote__c.Fields.Kushy_Punch_Order_Number__c,false);
        
        System.debug('Order: ' + order);
        r.put('name', order.OrderNumber);
        return r;
    }
    
    public class Order{
        public String OrderNumber					{get;set;}
        public String OrderId 						{get;set;}
        public String OrderDate    					{get;set;}
        public String AccountName    				{get;set;}
        public String ContactName    				{get;set;}
        public String SalesRep       				{get;set;}
        public String OrderStatus        			{get;set;}
        public String TotalComminssion              {get;set;}
        public String TotalDiscountPrice            {get;set;}
        public String Notes                  		{get;set;}
        public String StateLicense                  {get;set;}
        public String ReadyforDelivery              {get;set;}
		public String RequestedShipDate              {get;set;}
        
    }
    
}