force-app/main/default/objects/Brand_Quote__c/Brand_Quote__c.object-meta.xml
<CustomObject>
    <description>Buy Quote to Purchase from Brands. Sell Quotes to Sell to Dispensaries</description>
    <label>Brand Quote</label>
    <nameField>
        <displayFormat>BQ-{0000000000}</displayFormat>
        <label>Brand Quote</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Brand Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Brand_Quote__c/fields/BQ_Status__c.field-meta.xml
<CustomField>
    <fullName>BQ_Status__c</fullName>
    <inlineHelpText>Status will auto-updated based on workflow defined.</inlineHelpText>
    <label>BQ Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Shipped</fullName>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Brand_Quote__c/fields/Collection_Status__c.field-meta.xml
<CustomField>
    <fullName>Collection_Status__c</fullName>
    <inlineHelpText>Invoice Collection Status from PB</inlineHelpText>
    <label>Retailer Collection Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Past Due</fullName>
            </value>
            <value>
                <fullName>Partial Payment</fullName>
            </value>
            <value>
                <fullName>Paid in Full</fullName>
            </value>
            <value>
                <fullName>Not Collectable</fullName>
            </value>
            <value>
                <fullName>Brand Collections</fullName>
            </value>
            <value>
                <fullName>Charge-off</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Brand_Quote__c/fields/Payment_Terms__c.field-meta.xml
<CustomField>
    <fullName>Payment_Terms__c</fullName>
    <defaultValue>(&quot;COD&quot;)</defaultValue>
    <label>Payment Terms</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Payment_Terms</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Brand_Quote__c/fields/Shipping_Terms__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Terms__c</fullName>
    <label>Shipping Terms</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Shipping_Terms</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/Purchase_Order__c.object-meta.xml
<CustomObject>
    <label>Purchase Order</label>
    <nameField>
        <displayFormat>PO-{0000000000}</displayFormat>
        <label>Purchase Order</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Purchase_Order__c/fields/Bill_Created__c.field-meta.xml
<CustomField>
    <fullName>Bill_Created__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bill Created?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/fields/Brand_Quote__c.field-meta.xml
<CustomField>
    <fullName>Brand_Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Quote used to create PO</description>
    <label>Brand Quote</label>
    <referenceTo>Brand_Quote__c</referenceTo>
    <relationshipLabel>Purchase Orders</relationshipLabel>
    <relationshipName>Purchase_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/fields/Payment_Terms__c.field-meta.xml
<CustomField>
    <fullName>Payment_Terms__c</fullName>
    <label>Payment Terms</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Payment_Terms</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/fields/PO_Status__c.field-meta.xml
<CustomField>
    <fullName>PO_Status__c</fullName>
    <label>PO Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Partially Received</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/fields/Retailer_Collection_Status__c.field-meta.xml
<CustomField>
    <fullName>Retailer_Collection_Status__c</fullName>
    <formula>TEXT(Brand_Quote__r.Collection_Status__c )</formula>
    <label>Retailer Collection Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/fields/Shipping_Terms__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Terms__c</fullName>
    <inlineHelpText>Incoterms</inlineHelpText>
    <label>Shipping Terms</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Shipping_Terms</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Supplier_Bill__c/Supplier_Bill__c.object-meta.xml
<CustomObject>
    <label>Supplier Bill</label>
    <nameField>
        <displayFormat>BILL-{YYYY}-{MM}-{000000}</displayFormat>
        <label>Supplier Bill</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Supplier Bills</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Supplier_Bill__c/fields/Brand_Quote__c.field-meta.xml
<CustomField>
    <fullName>Brand_Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Brand Quote</label>
    <referenceTo>Brand_Quote__c</referenceTo>
    <relationshipLabel>Supplier Bills</relationshipLabel>
    <relationshipName>Supplier_Bills</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Supplier_Bill__c/fields/Purchase_Order__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Purchase Order</label>
    <referenceTo>Purchase_Order__c</referenceTo>
    <relationshipLabel>Supplier Bills</relationshipLabel>
    <relationshipName>Supplier_Bills</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Supplier_Bill__c/fields/Shipping_Terms__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Terms__c</fullName>
    <inlineHelpText>INCOTERMS2010</inlineHelpText>
    <label>Shipping Terms</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Shipping_Terms</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/CreateSupplierBillBatchTest.cls
@isTest
public class CreateSupplierBillBatchTest {
    @isTest
    static void testCreateSupplierBillMethods(){
        TestUtilData.createTestData();
        
        Brand_Quote__c brandQuote = [SELECT Id, Collection_Status__c , BQ_Status__c FROM Brand_Quote__c LIMIT 1];
        brandQuote.BQ_Status__c = 'Approved';  
        brandQuote.Collection_Status__c = 'Paid in Full';
        update brandQuote;
        
        List<Purchase_Order__c> purchaseOrders = new List<Purchase_Order__c>();    
        for(Purchase_Order__c purchaseOrderObj : [SELECT Id,Bill_Created__c,Payment_Terms__c,Shipping_Terms__c,PO_Status__c,
                                                  Brand_Quote__c,Retailer_Collection_Status__c 
                                                  FROM Purchase_Order__c]){
                                                      purchaseOrderObj.Brand_Quote__c =  brandQuote.Id;
                                                      purchaseOrderObj.PO_Status__c = 'Approved';                                          
                                                      purchaseOrders.add(purchaseOrderObj);
                                                  }
        
        update purchaseOrders;
        update brandQuote; 
         
        Test.startTest();
        CreateSupplierBillBatchSchedule createSupplierBillBatchSchedule = new CreateSupplierBillBatchSchedule(); 
        String cronExpr = '0 0 2 * * ?'; 
        system.schedule('TestCreateSupplierBillBatch', cronExpr, createSupplierBillBatchSchedule);
        Database.executeBatch(new CreateSupplierBillBatch());
        Test.stopTest();
        List<Supplier_Bill__c> supplierBills = [SELECT Id FROM Supplier_Bill__c];
        System.assertEquals(1, supplierBills.size()); 
        Purchase_Order__c purchaseOrder = [SELECT Id, Bill_Created__c FROM Purchase_Order__c LIMIT 1];
        System.assertEquals(true, purchaseOrder.Bill_Created__c);
    } 
}