force-app/main/default/objects/Brand_Quote__c/Brand_Quote__c.object-meta.xml
<CustomObject>
    <description>Buy Quote to Purchase from Brands. Sell Quotes to Sell to Dispensaries</description>
    <label>Brand Quote</label>
    <nameField>
        <displayFormat>BQ-{0000000000}</displayFormat>
        <label>Brand Quote</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Brand Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Brand_Quote__c/fields/Distributor_Contact__c.field-meta.xml
<CustomField>
    <fullName>Distributor_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Distributor Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Brand Quotes (Distributor Contact)</relationshipLabel>
    <relationshipName>Brand_Quotes2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Brand_Quote_Line__c/Brand_Quote_Line__c.object-meta.xml
<CustomObject>
    <label>Brand Quote Line</label>
    <nameField>
        <displayFormat>BQLI-{0000000000}</displayFormat>
        <label>BQ Line</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Brand Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Brand_Quote_Line__c/fields/Brand_Quote_Number__c.field-meta.xml
<CustomField>
    <fullName>Brand_Quote_Number__c</fullName>
    <label>Brand Quote Number</label>
    <referenceTo>Brand_Quote__c</referenceTo>
    <relationshipLabel>Brand Quote Lines</relationshipLabel>
    <relationshipName>Brand_Quote_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FG_Email_Template__c/FG_Email_Template__c.object-meta.xml
<CustomObject>
    <label>FG Email Template</label>
    <nameField>
        <displayFormat>ETN-{00000}</displayFormat>
        <label>Email Template</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FG Email Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FG_Email_Template__c/fields/Email_Subject__c.field-meta.xml
<CustomField>
    <fullName>Email_Subject__c</fullName>
    <label>Email Subject</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FG_Queries__c/FG_Queries__c.object-meta.xml
<CustomObject>
    <label>FG Queries</label>
    <nameField>
        <displayFormat>FG - {00000}</displayFormat>
        <label>Query Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FG Queries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FG_Queries__c/fields/Query__c.field-meta.xml
<CustomField>
    <fullName>Query__c</fullName>
    <label>Query</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/FG_Template__c/FG_Template__c.object-meta.xml
<CustomObject>
    <label>FG Template</label>
    <nameField>
        <displayFormat>TN-{00000}</displayFormat>
        <label>Template Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FG Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FG_Template__c/fields/Template_Group__c.field-meta.xml
<CustomField>
    <fullName>Template_Group__c</fullName>
    <label>Template Group</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PDFEngine_Config__c/PDFEngine_Config__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>PDFEngine Config</label>
</CustomObject>

force-app/main/default/objects/PDFEngine_Config__c/fields/File_Download_Url__c.field-meta.xml
<CustomField>
    <fullName>File_Download_Url__c</fullName>
    <label>File Download Url</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PDFEngine_Config__c/fields/File_Upload_Url__c.field-meta.xml
<CustomField>
    <fullName>File_Upload_Url__c</fullName>
    <label>File Upload Url</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PDFEngine_Config__c/fields/Google_Api_Token_Url__c.field-meta.xml
<CustomField>
    <fullName>Google_Api_Token_Url__c</fullName>
    <label>Google Api Token Url</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PDFEngine_Config__c/fields/Google_Auth_Drive_Url__c.field-meta.xml
<CustomField>
    <fullName>Google_Auth_Drive_Url__c</fullName>
    <label>Google Auth Drive Url</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PDFEngine_Config__c/fields/Google_Auth_Url__c.field-meta.xml
<CustomField>
    <fullName>Google_Auth_Url__c</fullName>
    <label>Google Auth Url</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PDFEngine_Config__c/fields/Return_Url__c.field-meta.xml
<CustomField>
    <fullName>Return_Url__c</fullName>
    <label>Return Url</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/BrandQuotePDFCtlrTest.cls
@isTest
public class BrandQuotePDFCtlrTest {
	@isTest
    private static void runTest(){
        
        contact con = new contact();
        con.lastname = 'test';
        con.firstname = 'test';
        con.email='test@test.com';
        insert con;
        
        PDFEngine_Config__c pdfConfig = new PDFEngine_Config__c();
        pdfConfig.Google_Api_Token_Url__c = 'https://oauth2.googleapis.com/token';
        pdfConfig.Access_Token__c = 'ya29';
        pdfConfig.Client_Id__c = '523150011284';
        pdfConfig.File_Download_Url__c = 'https://www.googleapis.com/drive/v3/files/';
        pdfConfig.File_Upload_Url__c = 'https://www.googleapis.com/upload/drive/v2/files?uploadType=multipart';
        pdfConfig.Google_Auth_Drive_Url__c = 'https://www.googleapis.com/auth/drive';
        pdfConfig.Google_Auth_Url__c = 'https://accounts.google.com/o/oauth2/';
        pdfConfig.Refresh_Token__c = '0f20obuQ8xNZcCgYIARAAGA8SNwF';
        pdfConfig.Return_Url__c = 'https://filigreen--dev--c.visualforce.com/apex/DocumentGenerator';
        pdfConfig.Secret__c = '77Ft1f3tBeFfRz8e7ckmLFi4';
        insert pdfConfig;
        
        FG_Queries__c fgQuery = new FG_Queries__c();
        fgQuery.Name__c = 'test';
        fgQuery.Active__c = true;
        fgQuery.Query__c = 'SELECT id  FROM Brand_Quote_Line__c WHERE Brand_Quote_Number__c = \'{pv0}\'';
        insert fgQuery;
        
        FG_Email_Template__c fgEmailTem = new FG_Email_Template__c();
        fgEmailTem.Email_Subject__c = 'test subject';
        fgEmailTem.Name__c = 'test';
        fgEmailTem.Active__c = true;
        fgEmailTem.Template_Group__c = 'BrandSellQuote';
        fgEmailTem.Email_Body__c = 'test email body';
        insert fgEmailTem;
        
        FG_Template__c fgTem = new FG_Template__c();
        fgTem.Template_Group__c = 'BrandSellQuote';
        fgTem.Active__c = true;
        fgTem.Name__c = 'test';
        insert fgTem;
        
        ContentVersion cVersion = new ContentVersion();
        cVersion.ContentLocation = 'S';
        cVersion.PathOnClient = 'test.docx';
        cVersion.Origin = 'H';
        cVersion.Title = 'fileName';
        cVersion.VersionData =blob.valueof('test body');
        Insert cVersion;
        
        Id conDocument = [SELECT ContentDocumentId FROM ContentVersion WHERE Id =:cVersion.id].ContentDocumentId;
        ContentDocumentLink cDocLink = new ContentDocumentLink();
        cDocLink.ContentDocumentId = conDocument;
        cDocLink.LinkedEntityId = fgTem.id;
        cDocLink.ShareType = 'I';
        cDocLink.Visibility = 'AllUsers';
        Insert cDocLink;
        
        Brand_Quote__c quote = new Brand_Quote__c();
        insert quote;
        
        string state = 'id='+quote.id+',QueryId='+'[bqline]'+fgQuery.id+'?pv0='+quote.id+',TempateId='+fgTem.id+',templateGroup=BrandSellQuote';
        apexpages.currentpage().getparameters().put('id',quote.id);
        apexpages.currentpage().getparameters().put('templateGroup','BrandSellQuote');
        apexpages.currentpage().getparameters().put('QueryId','[bqline]'+fgQuery.id+'?pv0='+quote.id);
        apexpages.currentpage().getparameters().put('TemplateId',fgTem.id);
        apexpages.currentpage().getparameters().put('EmailTemplateId',fgEmailTem.id);
        apexpages.currentpage().getparameters().put('code','test');
        apexpages.currentpage().getparameters().put('state',state);
        BrandQuotePDFCtlr brandQuote = new BrandQuotePDFCtlr();
        brandQuote.redirectToSendEmail();
        //brandQuote.loadTemplate();
        brandQuote.fileData = 'test';
        brandQuote.createFile();
        //brandQuote.changeEmailBody();
        brandQuote.goBackToEmail();
        brandQuote.AccessToken();
        brandQuote.AccessTokenFromRefreshToken();
        BrandQuotePDFCtlr.updateRefreshToken(pdfConfig.id,'','');
        brandQuote.UploadFile();
        brandQuote.fromDownload = true;
        brandQuote.details.isSaveAsAttachment = true;
        brandQuote.downloadFile('');
        BrandQuotePDFCtlr.deleteFile('','');
        BrandQuotePDFCtlr.FileDetails fileDetial = new BrandQuotePDFCtlr.FileDetails();
        fileDetial.filename = 'test.pdf';
        fileDetial.filetype = 'application/pdf';
        fileDetial.file = 'testing body';
        List<BrandQuotePDFCtlr.FileDetails>fileDetailList = new List<BrandQuotePDFCtlr.FileDetails>();
        fileDetailList.add(fileDetial);
        brandQuote.additionalFiles = JSON.serialize(fileDetailList);        
        brandQuote.additionalAdd = 'test@test.com';
        //brandQuote.invoice.Distributor_Contact__c = con.id;
        brandQuote.ccAdd = 'test@test.com';
        brandQuote.bccAdd = 'test@test.com';
        brandQuote.bodyStr = 'test';
        brandQuote.defaultAttRemoved = false;
        brandQuote.sendEmail();
        brandQuote.searchText = 'test@test.com';
        brandQuote.loadEmail();
        brandQuote.loadInitailSetup();
        brandQuote.goBack();
        brandQuote.redirectBack();
        brandQuote.loadTemplate();
        BrandQuotePDFCtlr.EmailWrapperClass eml = new BrandQuotePDFCtlr.EmailWrapperClass(con.id,con.lastname,'contact',con.email,null);
        
        string status;
        status = BrandQuotePDFCtlr.BRANDQUOTE_FILENAME_BUYQUOTE;
        status = BrandQuotePDFCtlr.BRANDQUOTE_FILENAME_SELLQUOTE;
        
    }
}