force-app/main/default/objects/Brand_Quote__c/Brand_Quote__c.object-meta.xml
<CustomObject>
    <description>Buy Quote to Purchase from Brands. Sell Quotes to Sell to Dispensaries</description>
    <label>Brand Quote</label>
    <nameField>
        <displayFormat>BQ-{0000000000}</displayFormat>
        <label>Brand Quote</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Brand Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Brand_Quote__c/fields/Opportunity_Name__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Name</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Brand_Quote__c/fields/Ownership__c.field-meta.xml
<CustomField>
    <fullName>Ownership__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ownership</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Brand Quotes as Ownership</relationshipLabel>
    <relationshipName>Brand_Quotes3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Brand_Quote__c/fields/Planned_Ship_Date__c.field-meta.xml
<CustomField>
    <fullName>Planned_Ship_Date__c</fullName>
    <inlineHelpText>Planned Ship Date is based on Receiver Acceptance Date. Sell Quote approved before 10:00AM PST will ship next day. Sell Quotes approved after 10:00AM will ship next 48 hours.</inlineHelpText>
    <label>Planned Ship Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Brand_Quote__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site</label>
    <referenceTo>Site__c</referenceTo>
    <relationshipLabel>Brand Quotes</relationshipLabel>
    <relationshipName>Brand_Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Drivers__c/Drivers__c.object-meta.xml
<CustomObject>
    <label>Driver</label>
    <nameField>
        <label>Driver Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Drivers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Drivers__c/fields/Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiration_Date__c</fullName>
    <label>Expiration Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Picklist__c/Picklist__c.object-meta.xml
<CustomObject>
    <description>Picklist is used for Warehouse Picking from inventory Positions</description>
    <label>Picklist</label>
    <nameField>
        <displayFormat>PL-{0000000000}</displayFormat>
        <label>Picklist</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Picklists</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Picklist__c/fields/Brand_Quote__c.field-meta.xml
<CustomField>
    <fullName>Brand_Quote__c</fullName>
    <formula>(Sales_Order__r.Brand_Quote__r.Name)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Brand Quote</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Picklist__c/fields/Driver__c.field-meta.xml
<CustomField>
    <fullName>Driver__c</fullName>
    <formula>Sales_Order__r.Driver__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Driver</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Picklist__c/fields/Ownership__c.field-meta.xml
<CustomField>
    <fullName>Ownership__c</fullName>
    <formula>Sales_Order__r.Ownership__r.Name</formula>
    <label>Ownership</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Picklist__c/fields/Planned_Ship_Date__c.field-meta.xml
<CustomField>
    <fullName>Planned_Ship_Date__c</fullName>
    <formula>Sales_Order__r.Planned_Ship_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Planned Ship Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Picklist__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <label>Sales Order</label>
    <referenceTo>Sales_Order__c</referenceTo>
    <relationshipLabel>Picklists</relationshipLabel>
    <relationshipName>Picklists</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Picklist__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site</label>
    <referenceTo>Site__c</referenceTo>
    <relationshipLabel>Picklists</relationshipLabel>
    <relationshipName>Picklists</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/Purchase_Order__c.object-meta.xml
<CustomObject>
    <label>Purchase Order</label>
    <nameField>
        <displayFormat>PO-{0000000000}</displayFormat>
        <label>Purchase Order</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Purchase_Order__c/fields/Brand_Quote__c.field-meta.xml
<CustomField>
    <fullName>Brand_Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Quote used to create PO</description>
    <label>Brand Quote</label>
    <referenceTo>Brand_Quote__c</referenceTo>
    <relationshipLabel>Purchase Orders</relationshipLabel>
    <relationshipName>Purchase_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/fields/Driver__c.field-meta.xml
<CustomField>
    <fullName>Driver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Driver</label>
    <referenceTo>Drivers__c</referenceTo>
    <relationshipLabel>Purchase Orders</relationshipLabel>
    <relationshipName>Purchase_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/fields/Opportunity_Name__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Name</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Purchase Orders</relationshipLabel>
    <relationshipName>Purchase_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/fields/Planned_Ship_Transfer_Date__c.field-meta.xml
<CustomField>
    <fullName>Planned_Ship_Transfer_Date__c</fullName>
    <label>Planned Ship/Transfer Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site</label>
    <referenceTo>Site__c</referenceTo>
    <relationshipLabel>Purchase Orders</relationshipLabel>
    <relationshipName>Purchase_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Order__c/Sales_Order__c.object-meta.xml
<CustomObject>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>SO-{0000000000}</displayFormat>
        <label>Sales Order</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Order__c/fields/Brand_Quote__c.field-meta.xml
<CustomField>
    <fullName>Brand_Quote__c</fullName>
    <label>Brand Quote</label>
    <referenceTo>Brand_Quote__c</referenceTo>
    <relationshipLabel>Sales Orders</relationshipLabel>
    <relationshipName>Sales_Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Sales_Order__c/fields/Driver__c.field-meta.xml
<CustomField>
    <fullName>Driver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Driver</label>
    <referenceTo>Drivers__c</referenceTo>
    <relationshipLabel>Sales Orders</relationshipLabel>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Order__c/fields/Opportunity_Name__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Name</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Sales Orders</relationshipLabel>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Order__c/fields/Planned_Ship_Date__c.field-meta.xml
<CustomField>
    <fullName>Planned_Ship_Date__c</fullName>
    <inlineHelpText>Date in which the products are to be delivered</inlineHelpText>
    <label>Planned Ship Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Sales_Order__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site</label>
    <referenceTo>Site__c</referenceTo>
    <relationshipLabel>Sales Orders</relationshipLabel>
    <relationshipName>Sales_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipping_Manifest__c/Shipping_Manifest__c.object-meta.xml
<CustomObject>
    <description>Used in the generation of compliance document to enable retail delivery.</description>
    <label>Shipping Manifest</label>
    <nameField>
        <displayFormat>SM-{YYYY}-{MM}-{0000000000}</displayFormat>
        <label>Shipping Manifest</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipping Manifests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Shipping_Manifest__c/fields/Brand_Quote__c.field-meta.xml
<CustomField>
    <fullName>Brand_Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Brand Quote</label>
    <referenceTo>Brand_Quote__c</referenceTo>
    <relationshipLabel>Shipping Manifests</relationshipLabel>
    <relationshipName>Shipping_Manifests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipping_Manifest__c/fields/Driver__c.field-meta.xml
<CustomField>
    <fullName>Driver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Driver</label>
    <referenceTo>Drivers__c</referenceTo>
    <relationshipLabel>Shipping Manifests</relationshipLabel>
    <relationshipName>Shipping_Manifests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipping_Manifest__c/fields/drivers__c.field-meta.xml
<CustomField>
    <fullName>drivers__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>driver</label>
    <referenceTo>Driver__c</referenceTo>
    <relationshipLabel>Shipping Manifests</relationshipLabel>
    <relationshipName>Shipping_Manifests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipping_Manifest__c/fields/Opportunity_Name__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Name</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Shipping Manifests</relationshipLabel>
    <relationshipName>Shipping_Manifests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipping_Manifest__c/fields/Picklist__c.field-meta.xml
<CustomField>
    <fullName>Picklist__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Picklist</label>
    <referenceTo>Picklist__c</referenceTo>
    <relationshipLabel>Shipping Manifests</relationshipLabel>
    <relationshipName>Shipping_Manifests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipping_Manifest__c/fields/Planned_Ship_Transfer_Date__c.field-meta.xml
<CustomField>
    <fullName>Planned_Ship_Transfer_Date__c</fullName>
    <inlineHelpText>Date in which the products are to be delivered</inlineHelpText>
    <label>Planned Ship/Transfer Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Shipping_Manifest__c/fields/Purchase_Order__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Related to Purchase Order</description>
    <label>Purchase Order</label>
    <referenceTo>Purchase_Order__c</referenceTo>
    <relationshipLabel>Shipping Manifests</relationshipLabel>
    <relationshipName>Shipping_Manifests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipping_Manifest__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Order</label>
    <referenceTo>Sales_Order__c</referenceTo>
    <relationshipLabel>Shipping Manifests</relationshipLabel>
    <relationshipName>Shipping_Manifests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipping_Manifest__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site</label>
    <referenceTo>Site__c</referenceTo>
    <relationshipLabel>Shipping Manifests</relationshipLabel>
    <relationshipName>Shipping_Manifests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/RSMTSMDriverDetailsControllerTest.cls
/**
 * Copyright (c) 2018 Filigreen Distro
 * All rights reserved.
 * RSMTSMDriverDetailsControllerTest
 */

@isTest(OnInstall=false SeeAllData=false)
public class RSMTSMDriverDetailsControllerTest {
    
     
   static List<Shipping_Manifest__c> lstrsm;
   static List<Shipping_Manifest__c > lsttsm;
    
   static testMethod void testDriverNotFound(){
          
      RSMTSMDriverDetailsController controllerObj = new RSMTSMDriverDetailsController();
      
       
   }
   
    static testMethod void testretreiveTSMRSMMnullDate(){
        
        Drivers__c objDrive=[select id, Name, Expiration_Date__c from Drivers__c limit 1];
        objDrive.Name =  UserInfo.getName();
        update objDrive;
        
        RSMTSMDriverDetailsController controllerObj = new RSMTSMDriverDetailsController();
        controllerObj.dat = null;
        controllerObj.retreiveTSMRSM();
   } 
    
    
    static testMethod void testUpdateRSMTSM(){
        
        Drivers__c objDrive=[select id, Name, Expiration_Date__c from Drivers__c limit 1];
        objDrive.Name =  UserInfo.getName();
        update objDrive;
        
        RSMTSMDriverDetailsController controllerObj = new RSMTSMDriverDetailsController();
        controllerObj.pageSizeTSM = '2';
        controllerObj.pageSizeRSM = '2';
    
        controllerObj.getPageSizeOptionsTSM();
        controllerObj.getPageSizeOptionsRSM(); 
        
        controllerObj.retreiveTSMRSM();
        
        controllerObj.updateRSMTSM();
        
        controllerObj.setTSM[0].isSelectedTSM = true;
        controllerObj.setRSM[0].isSelectedRSM = true;
        
        controllerObj.updateRSMTSM();
        
        // next action of pagination
        controllerObj.nextTSM();
       
       // previous action of pagination
        controllerObj.previousTSM();
       
        // last action of pagination
        controllerObj.lastTSM();
       
        // first action of pagination
        controllerObj.firstTSM();
       
         // reset page size
        controllerObj.pageSizeTSM = '2';
        controllerObj.doResetTSMPageSize();
       
       
        // next action of pagination
        controllerObj.nextRSM();
       
       
       // previous action of pagination
        controllerObj.previousRSM();
       
       
         // last action of pagination
        controllerObj.lastRSM();
       
       
        // first action of pagination
        controllerObj.firstRSM();
       
        PageReference pageRef = controllerObj.doResetRSMPageSize();
       
       
       
       
       // reset page size
        controllerObj.pageSizeRSM = '10';
        controllerObj.doResetTSMPageSize();
   }
    
    static testMethod void testDriverLicenseExpiredErrorMsg(){
        
        Drivers__c objDrive=[select id, Name, Expiration_Date__c from Drivers__c limit 1];
        objDrive.Name =  UserInfo.getName();
        objDrive.Expiration_Date__c = objDrive.Expiration_Date__c.addDays(-365);
        update objDrive;
        
        RSMTSMDriverDetailsController controllerObj = new RSMTSMDriverDetailsController();
  
       
   }
    
     @TestSetUp
    static void testDataSetUp(){
        TestUtilData.createTestData();
        
        Sales_Order__c objSO =[select id,Site__c, Planned_Ship_Date__c from Sales_Order__c limit 1];
        system.debug('objSO.Planned_Ship_Date__c1'+objSO.Planned_Ship_Date__c);
        objSO.Planned_Ship_Date__c = date.today();
        
        update objSO;
        
        Drivers__c objDriver =TestUtilData.createDriver(true);
        
        system.debug('objSO.Planned_Ship_Date__c2'+objSO.Planned_Ship_Date__c);
        
        
        Picklist__c objPicklist= TestUtilData.createPicklist(objSO, 'Open', true);
        
        list<Shipping_Manifest__c> lstRSM = new list<Shipping_Manifest__c>();
        
        Shipping_Manifest__c objRSM1 = TestUtilData.createRSM(objPicklist, false);
        objRSM1.Planned_Ship_Transfer_Date__c = objSO.Planned_Ship_Date__c;
        objRSM1.Driver__c = objDriver.id;
        objRSM1.RecordTypeId = ShippinManifestSupport.getRSMRecordTypeId();
        lstRSM.add(objRSM1);
        
        Shipping_Manifest__c objRSM2 = TestUtilData.createRSM(objPicklist, false);
        objRSM2.Planned_Ship_Transfer_Date__c = objSO.Planned_Ship_Date__c;
        objRSM2.Driver__c = objDriver.id;
        objRSM2.RecordTypeId = ShippinManifestSupport.getRSMRecordTypeId();
        lstRSM.add(objRSM2);
        
        Shipping_Manifest__c objRSM3 = TestUtilData.createRSM(objPicklist, false);
        objRSM3.Planned_Ship_Transfer_Date__c = objSO.Planned_Ship_Date__c;
        objRSM3.Driver__c = objDriver.id;
        objRSM3.RecordTypeId = ShippinManifestSupport.getRSMRecordTypeId();
        lstRSM.add(objRSM3);
        
        insert lstRSM;
        
        Purchase_Order__c objPO = [Select id, Brand_Quote__c, Opportunity_Name__c, Site__c, Ownership__c, 
                                   Distributor_Name__c, Distributor_Contact__c, Supplier_Name__c, Supplier_Contact__c,
                                   Receiver_Name__c, Receiver_Contact__c from Purchase_Order__c limit 1];
       
        Vehicles__c objVehicle=TestUtilData.createVehicle(true);
        
        
        list<Shipping_Manifest__c> lstTSM = new list<Shipping_Manifest__c>();
        
        
        Shipping_Manifest__c objTSM1 = createTSM(objPO, objDriver.id, objVehicle.id);
        objTSM1.RecordTypeId = ShippinManifestSupport.getTSMRecordTypeId();
        lstTSM.add(objTSM1);
        
        Shipping_Manifest__c objTSM2 = createTSM(objPO, objDriver.id, objVehicle.id);
        objTSM2.RecordTypeId = ShippinManifestSupport.getTSMRecordTypeId();
        lstTSM.add(objTSM2);        
        
        Shipping_Manifest__c objTSM3 = createTSM(objPO, objDriver.id, objVehicle.id);
        objTSM3.RecordTypeId = ShippinManifestSupport.getTSMRecordTypeId();
        lstTSM.add(objTSM3);
        
        insert lstTSM;
        
    }
    
    public static Shipping_Manifest__c createTSM(Purchase_Order__c objPO, id driverID, id vehicleId){
        
        
        Shipping_Manifest__c objTSM = new Shipping_Manifest__c();
        objTSM.Purchase_Order__c = objPO.id;
        objTSM.Brand_Quote__c = objPO.Brand_Quote__c;
        objTSM.Opportunity_Name__c = objPO.Opportunity_Name__c;
        objTSM.Site__c = objPO.Site__c;
        objTSM.Ownership__c = objPO.Ownership__c;
        objTSM.Distributor_Name__c = objPO.Distributor_Name__c;
        objTSM.Distributor_Contact__c = objPO.Distributor_Contact__c;
        objTSM.Supplier_Name__c = objPO.Supplier_Name__c;
        objTSM.Supplier_Contact__c = objPO.Supplier_Contact__c;
        objTSM.Receiver_Name__c = objPO.Receiver_Name__c;
        objTSM.Receiver_Contact__c = objPO.Receiver_Contact__c;
        objTSM.Planned_Ship_Transfer_Date__c = date.today();
        objTSM.Shipping_Method__c = 'Distributor Pick-up';
        objTSM.Shipping_Terms__c ='CIP';
        objTSM.Payment_Terms__c ='COD';
        objTSM.Driver__c = driverID;
        objTSM.Vehicle__c = vehicleId;
 
        return objTSM;
        
    }
        
     
}