force-app/main/default/objects/Brand_Quote__c/Brand_Quote__c.object-meta.xml
<CustomObject>
    <description>Buy Quote to Purchase from Brands. Sell Quotes to Sell to Dispensaries</description>
    <label>Brand Quote</label>
    <nameField>
        <displayFormat>BQ-{0000000000}</displayFormat>
        <label>Brand Quote</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Brand Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Brand_Quote__c/fields/Apply_Excise_Tax__c.field-meta.xml
<CustomField>
    <fullName>Apply_Excise_Tax__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Include Excise tax calculation</description>
    <label>Apply Excise Tax ?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Brand_Quote__c/fields/Distributor_License__c.field-meta.xml
<CustomField>
    <fullName>Distributor_License__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Distributor License</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>State_Licenses__c.License_Name__c</field>
            <operation>equals</operation>
            <valueField>$Source.Distributor_Name__c</valueField>
        </filterItems>
        <filterItems>
            <field>State_Licenses__c.State_License_Holder__c</field>
            <operation>equals</operation>
            <valueField>$Source.Distributor_Name__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>State_Licenses__c</referenceTo>
    <relationshipLabel>Brand Quotes (Distributor License)</relationshipLabel>
    <relationshipName>Brand_Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Brand_Quote__c/fields/Distributor_Name__c.field-meta.xml
<CustomField>
    <fullName>Distributor_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Distributor Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Brand Quotes as Distributor</relationshipLabel>
    <relationshipName>Brand_Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Brand_Quote__c/fields/Opportunity_Name__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Name</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Brand_Quote__c/fields/Ownership__c.field-meta.xml
<CustomField>
    <fullName>Ownership__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ownership</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Brand Quotes as Ownership</relationshipLabel>
    <relationshipName>Brand_Quotes3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Brand_Quote__c/fields/Payment_Terms__c.field-meta.xml
<CustomField>
    <fullName>Payment_Terms__c</fullName>
    <defaultValue>(&quot;COD&quot;)</defaultValue>
    <label>Payment Terms</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Payment_Terms</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Brand_Quote__c/fields/Receiver_License__c.field-meta.xml
<CustomField>
    <fullName>Receiver_License__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Receiver License</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>State_Licenses__c.License_Name__c</field>
            <operation>equals</operation>
            <valueField>$Source.Receiver_Name__c</valueField>
        </filterItems>
        <filterItems>
            <field>State_Licenses__c.State_License_Holder__c</field>
            <operation>equals</operation>
            <valueField>$Source.Receiver_Name__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>State_Licenses__c</referenceTo>
    <relationshipLabel>Brand Sell Quotes</relationshipLabel>
    <relationshipName>Brand_Quotes1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Brand_Quote__c/fields/Receiver_Name__c.field-meta.xml
<CustomField>
    <fullName>Receiver_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Receiver Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Brand Quotes as Receiver</relationshipLabel>
    <relationshipName>Brand_Quotes2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Brand_Quote__c/fields/Sales_Origin__c.field-meta.xml
<CustomField>
    <fullName>Sales_Origin__c</fullName>
    <label>Sales Origin</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sales_Origin</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Brand_Quote__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site</label>
    <referenceTo>Site__c</referenceTo>
    <relationshipLabel>Brand Quotes</relationshipLabel>
    <relationshipName>Brand_Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Brand_Quote__c/fields/Supplier_Name__c.field-meta.xml
<CustomField>
    <fullName>Supplier_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Supplier Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Brand Quotes as Supplier</relationshipLabel>
    <relationshipName>Brand_Quotes1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Brand_Quote__c/recordTypes/Sell_Quote.recordType-meta.xml
<RecordType>
    <fullName>Sell_Quote</fullName>
    <active>true</active>
    <description>Used for selling to Receiver, Invoice and Purchase Order will be issued to Brand or Lab</description>
    <label>Sell Quote</label>
</RecordType>

force-app/main/default/objects/Brand_Quote_Line__c/Brand_Quote_Line__c.object-meta.xml
<CustomObject>
    <label>Brand Quote Line</label>
    <nameField>
        <displayFormat>BQLI-{0000000000}</displayFormat>
        <label>BQ Line</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Brand Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Brand_Quote_Line__c/fields/Apply_Excise_Tax__c.field-meta.xml
<CustomField>
    <fullName>Apply_Excise_Tax__c</fullName>
    <description>IF(TExt(Product_Name__r.Apply_Excise_Tax__c) = &apos;Yes&apos;  &amp;&amp;  Brand_Quote_Number__r.Apply_Excise_Tax__c  = true, 
TEXT(Product_Name__r.Apply_Excise_Tax__c), &apos;No&apos;)</description>
    <formula>IF(TExt(Product_Name__r.Apply_Excise_Tax__c) = &apos;Yes&apos;  &amp;&amp;  Brand_Quote_Number__r.Apply_Excise_Tax__c  = true, 
&apos;Yes&apos;, &apos;No&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Apply Excise Tax?</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Brand_Quote_Line__c/fields/Opportunity_Name__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Name__c</fullName>
    <formula>Brand_Quote_Number__r.Opportunity_Name__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Opportunity Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Brand_Quote_Line__c/fields/Producer_Name__c.field-meta.xml
<CustomField>
    <fullName>Producer_Name__c</fullName>
    <formula>Product_Name__r.Producer_Name__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Producer Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Brand_Quote_Line__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <formula>Brand_Quote_Number__r.Site__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Site</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Inventory_Location__c/Inventory_Location__c.object-meta.xml
<CustomObject>
    <label>Inventory Location</label>
    <nameField>
        <label>Inventory Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inventory Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Inventory_Location__c/fields/Default_for_Site__c.field-meta.xml
<CustomField>
    <fullName>Default_for_Site__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Default for Site</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Inventory_Location__c/fields/Site_Name__c.field-meta.xml
<CustomField>
    <fullName>Site_Name__c</fullName>
    <label>Site Name</label>
    <referenceTo>Site__c</referenceTo>
    <relationshipLabel>Inventory Locations</relationshipLabel>
    <relationshipName>Inventory_Locations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Site__c/Site__c.object-meta.xml
<CustomObject>
    <description>All objects must have a Site Name and License Class or A or M. For separate sales and inventory record.</description>
    <label>Site</label>
    <nameField>
        <label>Site</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sites</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Site__c/fields/License_Class__c.field-meta.xml
<CustomField>
    <fullName>License_Class__c</fullName>
    <formula>TEXT(License_ID__r.License_Class__c)</formula>
    <label>License Class</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site__c/fields/License_ID__c.field-meta.xml
<CustomField>
    <fullName>License_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>License ID</label>
    <referenceTo>State_Licenses__c</referenceTo>
    <relationshipLabel>Sites</relationshipLabel>
    <relationshipName>Sites</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Site__c/fields/License_Name__c.field-meta.xml
<CustomField>
    <fullName>License_Name__c</fullName>
    <formula>License_ID__r.License_Name__r.Name</formula>
    <label>License Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site__c/fields/License_Number__c.field-meta.xml
<CustomField>
    <fullName>License_Number__c</fullName>
    <formula>License_ID__r.License_Number__c</formula>
    <label>License Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/State_Licenses__c/State_Licenses__c.object-meta.xml
<CustomObject>
    <description>Object within the Account to track number of license and address as part of ship to.</description>
    <label>State License</label>
    <nameField>
        <displayFormat>SLID-{YYYY}-{MM}-{0000000000}</displayFormat>
        <label>License</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>State Licenses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/State_Licenses__c/fields/License_Class__c.field-meta.xml
<CustomField>
    <fullName>License_Class__c</fullName>
    <inlineHelpText>License Classification:
Adult Use = A-License
Medicinal Use = M-License</inlineHelpText>
    <label>License Class</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A-License</fullName>
            </value>
            <value>
                <fullName>M-License</fullName>
            </value>
            <value>
                <fullName>AM-License</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/State_Licenses__c/fields/License_Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>License_Expiration_Date__c</fullName>
    <inlineHelpText>License Expiration Date</inlineHelpText>
    <label>License Expiration Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/State_Licenses__c/fields/License_Name__c.field-meta.xml
<CustomField>
    <fullName>License_Name__c</fullName>
    <label>License Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>State Licenses</relationshipLabel>
    <relationshipName>State_Licenses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/State_Licenses__c/fields/License_Number__c.field-meta.xml
<CustomField>
    <fullName>License_Number__c</fullName>
    <inlineHelpText>State License Number</inlineHelpText>
    <label>License Number</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/State_Licenses__c/fields/License_Status__c.field-meta.xml
<CustomField>
    <fullName>License_Status__c</fullName>
    <inlineHelpText>License Status from State</inlineHelpText>
    <label>License Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
            <value>
                <fullName>Revoked</fullName>
            </value>
            <value>
                <fullName>Terminated</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/State_Licenses__c/fields/License_Type__c.field-meta.xml
<CustomField>
    <fullName>License_Type__c</fullName>
    <label>License Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>License_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/BQCloneControllerTest.cls
@isTest(SeeAllData=false)
public class BQCloneControllerTest {
    static List<Brand_Quote_Line__c> bqLines;
    static final String BQ_STATUS_DRAFT = 'Draft';
    
       
    static testmethod void runBQClone(){
        Test.setMock(HttpCalloutMock.class, new StateLicense_MockResponseTest()); 
        Account objAccount = new Account();
        objAccount.Name = 'Test Account1';
        objAccount.Payment_Terms__c = 'COD';
        insert objAccount;
        //distributor Account
        Account objAccount2 = new Account();
        objAccount2.Name = 'Test Account2';
        objAccount2.Payment_Terms__c = 'COD';
        insert objAccount2;
        //receiver Account
        Account objAccount3 = new Account();
        objAccount3.Name = 'Test Account3';
        objAccount3.Payment_Terms__c = 'COD';
        insert objAccount3;

        //Create State License

        //Supplier License
        State_Licenses__c objStateLicenses = new State_Licenses__c();
        objStateLicenses.License_Name__c = objAccount.id;
        objStateLicenses.License_Number__c = 'AbcTest12345';
        objStateLicenses.License_Status__c = 'Active';
        objStateLicenses.License_Type__c = 'Type 1';
        objStateLicenses.License_Class__c = 'A-License';
        objStateLicenses.License_Expiration_Date__c = date.valueof(system.now());
        insert objStateLicenses;
        //distributor License
        State_Licenses__c objStateLicenses2 = new State_Licenses__c();
        objStateLicenses2.License_Name__c = objAccount2.id;
        objStateLicenses2.License_Number__c = 'AbcTest45678';
        objStateLicenses2.License_Status__c = 'Active';
        objStateLicenses2.License_Type__c = 'Type 1';
        objStateLicenses2.License_Class__c = 'A-License';
        objStateLicenses2.License_Expiration_Date__c = date.valueof(system.now());
        insert objStateLicenses2;
        //receiver License
        State_Licenses__c objStateLicenses3 = new State_Licenses__c();
        objStateLicenses3.License_Name__c = objAccount3.id;
        objStateLicenses3.License_Number__c = 'AbcTest54321';
        objStateLicenses3.License_Status__c = 'Active';
        objStateLicenses3.License_Type__c = 'Type 1';
        objStateLicenses3.License_Class__c = 'A-License';
        objStateLicenses3.License_Expiration_Date__c = date.valueof(system.now());

        insert objStateLicenses3;

        
        Google_Distance_Matrix_API__c ct =  new Google_Distance_Matrix_API__c();
        ct.Name = 'GMaps_Endpoint';
        ct.Value__c = 'value';
        insert ct;
        Google_Distance_Matrix_API__c ct1 =  new Google_Distance_Matrix_API__c();
        ct1.Name = 'Gmaps_APIKey';
        ct1.Value__c = 'value';
        insert ct1;
        
        //Create Site.
        Site__c objSite = new Site__c();
        objSite.Name = 'Test Site';
        //objSite.License_ID__c= objStateLicenses.id;
        insert objSite;



        Inventory_Location__c newInventoryLocation = new Inventory_Location__c();
        newInventoryLocation.Name = 'Test InventoryLocation';
        newInventoryLocation.Site_Name__c = objSite.id;
        newInventoryLocation.Default_for_Site__c = true;

        insert newInventoryLocation;

        RecordType bqType = [select id, name, developername from recordtype where developername = 'Buy_Sell_Opportunity' limit 1];
        Opportunity opp = new Opportunity();
        opp.AccountId = objAccount.Id;
        opp.Name = 'Test Opp';
        opp.Sales_Origin__c = 'Brand';
        opp.Type = 'New Business';
        opp.CloseDate = Date.today().addDays(5);
        opp.StageName = 'Qualification';
        opp.RecordTypeId = bqType.Id;
        opp.Site_Name__c = objSite.Id;
        opp.Ownership__c = objAccount.id;
        opp.Payment_Terms__c='COD';

        insert opp;

        System.debug('opp.id' + opp.id);

        //Create Product

        //Create Product1
        /*
        Product2 objProduct1 = new Product2();
        objProduct1.Name = 'product 1';
        objProduct1.Family = 'Edibles';
        objProduct1.Description = 'test product 1';
        objProduct1.Producer_Name__c = objAccount.id;
        objProduct1.Apply_Cultivation_Tax__c = 'Yes';
        objProduct1.Apply_Excise_Tax__c = 'Yes';
        objProduct1.IsActive = true;
        insert objProduct1; */
        
        Product2  objProduct1 = new Product2 ();
        objProduct1.Name = 'product KD 1';
        objProduct1.Quantity_Type__c = 'Quantity';
        objProduct1.Family = 'Accessories';
        objProduct1.Description = 'test product 1';
        objProduct1.Producer_Name__c = objAccount2.id;
        objProduct1.Apply_Cultivation_Tax__c='Yes';
        objProduct1.Apply_Excise_Tax__c='Yes';
        objProduct1.IsActive = true;
        objProduct1.Unit_Height__c  = 10.0;
        objProduct1.Unit_Length__c = 10.0;
        objProduct1.Unit_Width__c = 5.0;
        objProduct1.Apply_Excise_Tax__c = 'Yes';
        objProduct1.Track_Trace_Category__c='Capsule';
        objProduct1.Net_Weight_UOM__c='EA';
        objProduct1.Unit_Of_Measure__c='Grams';
        insert objProduct1;
        
        //Create Product2
        /*
        Product2 objProduct2 = new Product2();
        objProduct2.Name = 'product 2';
        objProduct2.Family = 'Edibles';
        objProduct2.Description = 'test product 2';
        objProduct2.Producer_Name__c = objAccount.id;
        objProduct2.Apply_Cultivation_Tax__c = 'Yes';
        objProduct2.Apply_Excise_Tax__c = 'Yes';
        objProduct2.IsActive = true;
        insert objProduct2; */
        
        Product2  objProduct2 = new Product2 ();
        objProduct2.Name = 'product KD 2';
        objProduct2.Quantity_Type__c = 'Quantity';
        objProduct2.Family = 'Accessories';
        objProduct2.Description = 'test product 2';
        objProduct2.Producer_Name__c = objAccount3.id;
        objProduct1.Apply_Cultivation_Tax__c='Yes';
        objProduct2.Apply_Excise_Tax__c='Yes';
        objProduct2.IsActive = true;
        objProduct1.Unit_Height__c  = 10.0;
        objProduct2.Unit_Length__c = 10.0;
        objProduct2.Unit_Width__c = 5.0;
        objProduct2.Apply_Excise_Tax__c = 'Yes';
        objProduct2.Track_Trace_Category__c='Capsule';
        objProduct2.Net_Weight_UOM__c='EA';
        objProduct2.Unit_Of_Measure__c='Grams';
        insert objProduct2;
        
        
        Id pricebookId = Test.getStandardPricebookId();
		PricebookEntry pbe = new PricebookEntry(
          Pricebook2Id = pricebookId, Product2Id = objProduct1.Id,
          UnitPrice = 10000, IsActive = true);
        PricebookEntry pbe2 = new PricebookEntry(
          Pricebook2Id = pricebookId, Product2Id = objProduct2.Id,
          UnitPrice = 10000, IsActive = true);
        insert new List<PricebookEntry>{pbe,pbe2};
        //PricebookEntry pbe = [SELECT Id FROM PricebookEntry where isActive = true LIMIT 1];

        //Create New Opportunity
        OpportunityLineItem opLineItem = new OpportunityLineItem();
        opLineItem.Quantity = 1;
        opLineItem.OpportunityId = opp.id;
        opLineItem.TotalPrice = 100;
        opLineItem.PricebookEntryId = pbe.Id;
        insert opLineItem;

        

        RecordType bqTypeID = [select id, name, developername from recordtype where developername = 'Sell_Quote' limit 1];
        Brand_Quote__c bq = new Brand_Quote__c();
        bq.Opportunity_Name__c = opp.id;
        bq.Distributor_Name__c = objAccount2.id;
        bq.Distributor_License__c = objStateLicenses2.id;
        bq.Receiver_Name__c = opp.AccountId;
        bq.Receiver_License__c = objStateLicenses.id;
        bq.Supplier_Name__c = opp.Ownership__c;
        bq.Supplier_License__c = objStateLicenses.id;
        bq.BQ_Status__c = 'Draft';
        bq.Shipping_Method__c = 'Distributor Pick-up';
        bq.Sales_Origin__c = 'Brand';
        bq.Shipping_Terms__c = 'CFR';
        bq.Payment_Terms__c = 'COD';
        bq.Site__c = objSite.id;
        bq.RecordTypeId = bqTypeID.Id;
        bq.Ownership__c = opp.Ownership__c;
        insert bq;
        
        RecordType bqTypeID2 = [select id, name, developername from recordtype where developername = 'Sell_Quote' limit 1];
        Brand_Quote__c bq2 = bq.clone();
        bq2.Opportunity_Name__c = opp.id;
        bq2.Distributor_Name__c = objAccount2.id;
        bq2.Distributor_License__c = objStateLicenses2.id;
        bq2.Receiver_Name__c = opp.AccountId;
        bq2.Receiver_License__c = objStateLicenses.id;
        bq2.Supplier_Name__c = opp.Ownership__c;
        bq2.Supplier_License__c = objStateLicenses.id;
        bq2.BQ_Status__c = BQ_STATUS_DRAFT;
        bq2.Shipping_Method__c = 'Distributor Pick-up';
        bq2.Sales_Origin__c = 'Brand';
        bq2.Shipping_Terms__c = 'CFR';
        bq2.Payment_Terms__c = 'COD';
        bq2.Site__c = objSite.id;
        bq2.RecordTypeId = bqTypeID2.Id;
        bq2.Ownership__c = opp.Ownership__c;
        bq2.KP_Ready_for_Delivery__c = false;
        bq2.Kushy_Punch_Order_Number__c = null;
        bq2.Receiver_Acceptance_Date__c = null;
        bq2.Planned_Ship_Date__c = null;
        bq2.Collection_Status__c = null;
        bq2.Last_Payment_Date__c = null;
        
        insert bq2;
        

        Brand_Quote_Line__c objbqline1 = new Brand_Quote_Line__c();
        objbqline1.Brand_Quote_Number__c = bq.id;
        objbqline1.Product_Name__c = objProduct1.id;
        objbqline1.MOQ__c = 10;
        objbqline1.Quantity_Cases__c = 200;

        Brand_Quote_Line__c objbqline2 = new Brand_Quote_Line__c();
        objbqline2.Brand_Quote_Number__c = bq.id;
        objbqline2.Product_Name__c = objProduct2.id;
        objbqline2.MOQ__c = 20;
        objbqline2.Quantity_Cases__c = 50;

        Brand_Quote_Line__c objbqline3 = new Brand_Quote_Line__c();
        objbqline3.Brand_Quote_Number__c = bq.id;
        objbqline3.Product_Name__c = objProduct1.id;
        objbqline3.MOQ__c = 8;
        objbqline3.Quantity_Cases__c = 100;

        list<Brand_Quote_Line__c> lstBrandQuoteLine = new list<Brand_Quote_Line__c> ();
        lstBrandQuoteLine.add(objbqline1);
        lstBrandQuoteLine.add(objbqline2);
        lstBrandQuoteLine.add(objbqline3);

        insert lstBrandQuoteLine;
        ApexPages.StandardController sc = new ApexPages.StandardController(bq);
        BQCloneController bqc = new BQCloneController(sc);
        
        bqc.cloneBrandQuote();
        
        AuraResponse r = new AuraResponse('BQCloneController.cloneBQ()');    
        BQCloneController assign = new BQCloneController();
        
        BQCloneController.cloneBQ(bq.Id);
        BQCloneController.getBQ(bq.Id);
        BQCloneController.getBQLines(bq.Id);
        
        List<BQCloneController.BrandQuoteLineWrapper> bqliWrapprList = new List<BQCloneController.BrandQuoteLineWrapper>();    
       
        BQCloneController.BrandQuoteLineWrapper bqliWrappr1  = new  BQCloneController.BrandQuoteLineWrapper();
        BQCloneController.BrandQuoteLineWrapper bqliWrappr2  = new  BQCloneController.BrandQuoteLineWrapper();
        BQCloneController.BrandQuoteLineWrapper bqliWrappr3  = new  BQCloneController.BrandQuoteLineWrapper();

        bqliWrappr1.isSelected = true;
        bqliWrappr1.brandQuoteLineBQ = objbqline1;
        bqliWrapprList.add(bqliWrappr1);
        
        bqliWrappr2.isSelected = true;
        bqliWrappr2.brandQuoteLineBQ = objbqline2;
        bqliWrapprList.add(bqliWrappr2);
        
        bqliWrappr3.isSelected = true;
        bqliWrappr3.brandQuoteLineBQ = objbqline3;
        bqliWrapprList.add(bqliWrappr3);
        
        BQCloneController.cloneBrandQuoteLight(bq, bqliWrapprList);
        

        
        //AuraResponse ar = BQCloneController.cloneBrandQuoteLight(bq, bqliWrapprList); 

        
    }
    static testmethod void runBQClone1(){
         Test.setMock(HttpCalloutMock.class, new StateLicense_MockResponseTest()); 
        Account objAccount = new Account();
        objAccount.Name = 'Test Account1';
        objAccount.Payment_Terms__c = 'COD';
        insert objAccount;
        //distributor Account
        Account objAccount2 = new Account();
        objAccount2.Name = 'Test Account2';
        objAccount2.Payment_Terms__c = 'COD';
        insert objAccount2;
        //receiver Account
        Account objAccount3 = new Account();
        objAccount3.Name = 'Test Account3';
        objAccount3.Payment_Terms__c = 'COD';
        insert objAccount3;

        //Create State License

        //Supplier License
        State_Licenses__c objStateLicenses = new State_Licenses__c();
        objStateLicenses.License_Name__c = objAccount.id;
        objStateLicenses.License_Number__c = 'AbcTest12345';
        objStateLicenses.License_Status__c = 'Active';
        objStateLicenses.License_Type__c = 'Type 1';
        objStateLicenses.License_Class__c = 'A-License';
        objStateLicenses.License_Expiration_Date__c = date.valueof(system.now());
        insert objStateLicenses;
        //distributor License
        State_Licenses__c objStateLicenses2 = new State_Licenses__c();
        objStateLicenses2.License_Name__c = objAccount2.id;
        objStateLicenses2.License_Number__c = 'AbcTest45678';
        objStateLicenses2.License_Status__c = 'Expired';
        objStateLicenses2.License_Type__c = 'Type 1';
        objStateLicenses2.License_Class__c = 'A-License';
        objStateLicenses2.License_Expiration_Date__c = date.valueof(system.now().addDays(-10));
        insert objStateLicenses2;
        Google_Distance_Matrix_API__c ct =  new Google_Distance_Matrix_API__c();
        ct.Name = 'GMaps_Endpoint';
        ct.Value__c = 'value';
        insert ct;
        Google_Distance_Matrix_API__c ct1 =  new Google_Distance_Matrix_API__c();
        ct1.Name = 'Gmaps_APIKey';
        ct1.Value__c = 'value';
        insert ct1;
        
        //receiver License
        State_Licenses__c objStateLicenses3 = new State_Licenses__c();
        objStateLicenses3.License_Name__c = objAccount3.id;
        objStateLicenses3.License_Number__c = 'AbcTest54321';
        objStateLicenses3.License_Status__c = 'Active';
        objStateLicenses3.License_Type__c = 'Type 1';
        objStateLicenses3.License_Class__c = 'A-License';
        objStateLicenses3.License_Expiration_Date__c = date.valueof(system.now());

        insert objStateLicenses3;

        //Create Site.
        Site__c objSite = new Site__c();
        objSite.Name = 'Test Site';
        //objSite.License_ID__c= objStateLicenses.id;
        insert objSite;



        Inventory_Location__c newInventoryLocation = new Inventory_Location__c();
        newInventoryLocation.Name = 'Test InventoryLocation';
        newInventoryLocation.Site_Name__c = objSite.id;
        newInventoryLocation.Default_for_Site__c = true;

        insert newInventoryLocation;

        RecordType bqType = [select id, name, developername from recordtype where developername = 'Buy_Sell_Opportunity' limit 1];
        Opportunity opp = new Opportunity();
        opp.AccountId = objAccount.Id;
        opp.Name = 'Test Opp';
        opp.Sales_Origin__c = 'Brand';
        opp.Type = 'New Business';
        opp.CloseDate = Date.today().addDays(5);
        opp.StageName = 'Qualification';
        opp.RecordTypeId = bqType.Id;
        opp.Site_Name__c = objSite.Id;
        opp.Ownership__c = objAccount.id;
        opp.Payment_Terms__c='COD';

        insert opp;

        System.debug('opp.id' + opp.id);

        //Create Product

        //Create Product1
        /*
        Product2 objProduct1 = new Product2();
        objProduct1.Name = 'product 1';
        objProduct1.Family = 'Edibles';
        objProduct1.Description = 'test product 1';
        objProduct1.Producer_Name__c = objAccount.id;
        objProduct1.Apply_Cultivation_Tax__c = 'Yes';
        objProduct1.Apply_Excise_Tax__c = 'Yes';
        objProduct1.IsActive = true;
        insert objProduct1; */
        
         Product2  objProduct1 = new Product2 ();
        objProduct1.Name = 'product KD 1';
        objProduct1.Quantity_Type__c = 'Quantity';
        objProduct1.Family = 'Accessories';
        objProduct1.Description = 'test product 1';
        objProduct1.Producer_Name__c = objAccount.id;
        objProduct1.Apply_Cultivation_Tax__c='Yes';
        objProduct1.Apply_Excise_Tax__c='Yes';
        objProduct1.IsActive = true;
        objProduct1.Unit_Height__c  = 10.0;
        objProduct1.Unit_Length__c = 10.0;
        objProduct1.Unit_Width__c = 5.0;
        objProduct1.Apply_Excise_Tax__c = 'Yes';
        objProduct1.Track_Trace_Category__c='Capsule';
        objProduct1.Net_Weight_UOM__c='EA';
        objProduct1.Unit_Of_Measure__c='Grams';
        insert objProduct1;
        
        //Create Product2
        /*
        Product2 objProduct2 = new Product2();
        objProduct2.Name = 'product 2';
        objProduct2.Family = 'Edibles';
        objProduct2.Description = 'test product 2';
        objProduct2.Producer_Name__c = objAccount.id;
        objProduct2.Apply_Cultivation_Tax__c = 'Yes';
        objProduct2.Apply_Excise_Tax__c = 'Yes';
        objProduct2.IsActive = true;
        insert objProduct2; */
        
        Product2  objProduct2 = new Product2 ();
        objProduct2.Name = 'product KD 2';
        objProduct2.Quantity_Type__c = 'Quantity';
        objProduct2.Family = 'Accessories';
        objProduct2.Description = 'test product 2';
        objProduct2.Producer_Name__c = objAccount.id;
        objProduct2.Apply_Cultivation_Tax__c='Yes';
        objProduct2.Apply_Excise_Tax__c='Yes';
        objProduct2.IsActive = true;
        objProduct2.Unit_Height__c  = 10.0;
        objProduct2.Unit_Length__c = 10.0;
        objProduct2.Unit_Width__c = 5.0;
        objProduct2.Apply_Excise_Tax__c = 'Yes';
        objProduct2.Track_Trace_Category__c='Capsule';
        objProduct2.Net_Weight_UOM__c='EA';
        objProduct2.Unit_Of_Measure__c='Grams';
        insert objProduct2;
        
        Id pricebookId = Test.getStandardPricebookId();
		PricebookEntry pbe = new PricebookEntry(
          Pricebook2Id = pricebookId, Product2Id = objProduct1.Id,
          UnitPrice = 10000, IsActive = true);
        PricebookEntry pbe2 = new PricebookEntry(
          Pricebook2Id = pricebookId, Product2Id = objProduct2.Id,
          UnitPrice = 10000, IsActive = true);
        insert new List<PricebookEntry>{pbe,pbe2};
        //PricebookEntry pbe = [SELECT Id FROM PricebookEntry where isActive = true LIMIT 1];

        //Create New Opportunity
        OpportunityLineItem opLineItem = new OpportunityLineItem();
        opLineItem.Quantity = 1;
        opLineItem.OpportunityId = opp.id;
        opLineItem.TotalPrice = 100;
        opLineItem.PricebookEntryId = pbe.Id;
        insert opLineItem;

        RecordType bqTypeID = [select id, name, developername from recordtype where developername = 'Sell_Quote' limit 1];
        Brand_Quote__c bq = new Brand_Quote__c();
        bq.Opportunity_Name__c = opp.id;
        bq.Distributor_Name__c = objAccount2.id;
        bq.Distributor_License__c = objStateLicenses2.id;
        bq.Receiver_Name__c = opp.AccountId;
        bq.Receiver_License__c = objStateLicenses.id;
        bq.Supplier_Name__c = opp.Ownership__c;
        bq.Supplier_License__c = objStateLicenses.id;
        //bq.Supplier_License__r.License_Status__c = 'Active';
        bq.BQ_Status__c = 'Draft';
        bq.Shipping_Method__c = 'Distributor Pick-up';
        bq.Sales_Origin__c = 'Brand';
        bq.Shipping_Terms__c = 'CFR';
        bq.Payment_Terms__c = 'COD';
        bq.Site__c = objSite.id;
        bq.RecordTypeId = bqTypeID.Id;
        bq.Ownership__c = opp.Ownership__c;
        insert bq;

         List<Brand_Quote__c> b = [SELECT Id FROM Brand_Quote__c WHERE Id =:bq.Id];
 		System.debug('Price after trigger fired: ' + b.size());
 
 // Test that the trigger correctly updated the price
         System.assertEquals(1,b.size());
        
        RecordType bqTypeID2 = [select id, name, developername from recordtype where developername = 'Sell_Quote' limit 1];
        Brand_Quote__c bq2 = new Brand_Quote__c();
        bq2.Opportunity_Name__c = opp.id;
        bq2.Distributor_Name__c = objAccount2.id;
        bq2.Distributor_License__c = objStateLicenses2.id;
        bq2.Receiver_Name__c = opp.AccountId;
        bq2.Receiver_License__c = objStateLicenses.id;
        bq2.Supplier_Name__c = opp.Ownership__c;
        bq2.Supplier_License__c = objStateLicenses.id;
        //bq2.Supplier_License__r.License_Status__c = 'Draft';
        bq2.BQ_Status__c = BQ_STATUS_DRAFT;
        bq2.Shipping_Method__c = 'Distributor Pick-up';
        bq2.Sales_Origin__c = 'Brand';
        bq2.Shipping_Terms__c = 'CFR';
        bq2.Payment_Terms__c = 'COD';
        bq2.Site__c = objSite.id;
        bq2.RecordTypeId = bqTypeID2.Id;
        bq2.Ownership__c = opp.Ownership__c;
        bq2.KP_Ready_for_Delivery__c = false;
        bq2.Kushy_Punch_Order_Number__c = null;
        bq2.Receiver_Acceptance_Date__c = null;
        bq2.Planned_Ship_Date__c = null;
        bq2.Collection_Status__c = null;
        bq2.Last_Payment_Date__c = null;
        
        insert bq2;


        Brand_Quote_Line__c objbqline1 = new Brand_Quote_Line__c();
        objbqline1.Brand_Quote_Number__c = bq.id;
        objbqline1.Product_Name__c = objProduct1.id;
        objbqline1.MOQ__c = 10;
        objbqline1.Quantity_Cases__c = 200;

        Brand_Quote_Line__c objbqline2 = new Brand_Quote_Line__c();
        objbqline2.Brand_Quote_Number__c = bq.id;
        objbqline2.Product_Name__c = objProduct2.id;
        objbqline2.MOQ__c = 20;
        objbqline2.Quantity_Cases__c = 50;

        Brand_Quote_Line__c objbqline3 = new Brand_Quote_Line__c();
        objbqline3.Brand_Quote_Number__c = bq.id;
        objbqline3.Product_Name__c = objProduct1.id;
        objbqline3.MOQ__c = 8;
        objbqline3.Quantity_Cases__c = 100;

        list<Brand_Quote_Line__c> lstBrandQuoteLine = new list<Brand_Quote_Line__c> ();
        lstBrandQuoteLine.add(objbqline1);
        lstBrandQuoteLine.add(objbqline2);
        lstBrandQuoteLine.add(objbqline3);

        insert lstBrandQuoteLine;
        ApexPages.StandardController sc = new ApexPages.StandardController(bq);
        BQCloneController bqc = new BQCloneController(sc);
        
        bqc.cloneBrandQuote();   
        
         AuraResponse r = new AuraResponse('BQCloneController.cloneBQ()');    
        BQCloneController assign = new BQCloneController();
        
        BQCloneController.cloneBQ(bq.Id);
        
        BQCloneController.getBQ(bq.Id);
        BQCloneController.getBQLines(bq.Id);
        
        List<BQCloneController.BrandQuoteLineWrapper> bqliWrapprList = new List<BQCloneController.BrandQuoteLineWrapper>();    
       
        BQCloneController.BrandQuoteLineWrapper bqliWrappr1  = new  BQCloneController.BrandQuoteLineWrapper();
        BQCloneController.BrandQuoteLineWrapper bqliWrappr2  = new  BQCloneController.BrandQuoteLineWrapper();
        BQCloneController.BrandQuoteLineWrapper bqliWrappr3  = new  BQCloneController.BrandQuoteLineWrapper();

        bqliWrappr1.isSelected = true;
        bqliWrappr1.brandQuoteLineBQ = objbqline1;
        bqliWrapprList.add(bqliWrappr1);
        
        bqliWrappr2.isSelected = true;
        bqliWrappr2.brandQuoteLineBQ = objbqline2;
        bqliWrapprList.add(bqliWrappr2);
        
        bqliWrappr3.isSelected = true;
        bqliWrappr3.brandQuoteLineBQ = objbqline3;
        bqliWrapprList.add(bqliWrappr3);
        System.debug('bq.Distributor_License__r.License_Status__c...'+bq.Distributor_License__r.License_Status__c);
        AuraResponse ar = BQCloneController.cloneBrandQuoteLight(bq, bqliWrapprList); 
        //AuraResponse ar1 = BQCloneController.cloneBrandQuoteLight(bq2, bqliWrapprList); 
    }
 

}