force-app/main/default/objects/Brand_Quote__c/Brand_Quote__c.object-meta.xml
<CustomObject>
    <description>Buy Quote to Purchase from Brands. Sell Quotes to Sell to Dispensaries</description>
    <label>Brand Quote</label>
    <nameField>
        <displayFormat>BQ-{0000000000}</displayFormat>
        <label>Brand Quote</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Brand Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Brand_Quote__c/fields/BQ_Status__c.field-meta.xml
<CustomField>
    <fullName>BQ_Status__c</fullName>
    <inlineHelpText>Status will auto-updated based on workflow defined.</inlineHelpText>
    <label>BQ Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Shipped</fullName>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Brand_Quote__c/fields/Kushy_Punch_Order_Number__c.field-meta.xml
<CustomField>
    <fullName>Kushy_Punch_Order_Number__c</fullName>
    <externalId>true</externalId>
    <label>Kushy Punch Order Number</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Brand_Quote__c/fields/Opportunity_Name__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Name</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Brand_Quote_Line__c/Brand_Quote_Line__c.object-meta.xml
<CustomObject>
    <label>Brand Quote Line</label>
    <nameField>
        <displayFormat>BQLI-{0000000000}</displayFormat>
        <label>BQ Line</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Brand Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Brand_Quote_Line__c/fields/Brand_Quote_Number__c.field-meta.xml
<CustomField>
    <fullName>Brand_Quote_Number__c</fullName>
    <label>Brand Quote Number</label>
    <referenceTo>Brand_Quote__c</referenceTo>
    <relationshipLabel>Brand Quote Lines</relationshipLabel>
    <relationshipName>Brand_Quote_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Brand_Quote_Line__c/fields/Disty_Discount_Per_Unit__c.field-meta.xml
<CustomField>
    <fullName>Disty_Discount_Per_Unit__c</fullName>
    <label>Disty Discount Per Unit</label>
    <precision>16</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Brand_Quote_Line__c/fields/Disty_Margin__c.field-meta.xml
<CustomField>
    <fullName>Disty_Margin__c</fullName>
    <label>Disty Margin</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Brand_Quote_Line__c/fields/Kushy_Punch_Order_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Kushy_Punch_Order_Line_Item__c</fullName>
    <externalId>true</externalId>
    <label>Kushy Punch Order Line Item</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Brand_Quote_Line__c/fields/MOQ__c.field-meta.xml
<CustomField>
    <fullName>MOQ__c</fullName>
    <description>MOQ - Minimum Order Quantity</description>
    <inlineHelpText>Minimum Order Quantity</inlineHelpText>
    <label>Qty per Case (MOQ)</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Brand_Quote_Line__c/fields/Opportunity_Name__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Name__c</fullName>
    <formula>Brand_Quote_Number__r.Opportunity_Name__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Opportunity Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Brand_Quote_Line__c/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Price Book</label>
    <referenceTo>Pricebook2</referenceTo>
    <relationshipLabel>Brand Quote Lines</relationshipLabel>
    <relationshipName>Brand_Quote_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Brand_Quote_Line__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Name</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Product2.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Brand Quote Lines</relationshipLabel>
    <relationshipName>Brand_Quote_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Brand_Quote_Line__c/fields/Retail_Wholesale_Price__c.field-meta.xml
<CustomField>
    <fullName>Retail_Wholesale_Price__c</fullName>
    <label>Retail Wholesale Price</label>
    <precision>16</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/KPWebhookLineItem.cls
@RestResource(urlMapping='/createOrderLine/*')
global without sharing class KPWebhookLineItem {
    
    @HttpGet
    global static String getData() {
        return 'ReturnKPOrderLineDatafromSalesforce';
    }
    
    @HttpPost
    global static Map<String, String> createOrderLineItem() {
        Brand_Quote__c newQuote = new Brand_Quote__c(BQ_Status__c = 'Draft');
        Map<String, String> r = new Map<String, String>();
        try{
        RestRequest request = RestContext.request;
        System.debug('Actual Order Line Request: ' + request);
		System.debug('Order Line ITem request: ' + request.requestBody.toString());
		Order order = (Order)JSON.deserialize(request.requestBody.toString(), Order.Class);
        Id BQLRecordTypeId = Schema.SObjectType.Brand_Quote_Line__c.getRecordTypeInfosByName().get('Sell Quote Line').getRecordTypeId();
        Brand_Quote_Line__c bql = new Brand_Quote_Line__c(RecordTypeId=BQLRecordTypeId,Kushy_Punch_Order_Line_Item__c = order.LineItemNumber,Product_Title__c ='Distributor',MOQ__c =1,Quantity_Cases__c=order.Quantity,Retail_Wholesale_Price__c=(String.isNotBlank(order.price)?Decimal.valueOf(order.price.replace('$','')):0));
        Brand_Quote__c bq = new Brand_Quote__c(Kushy_Punch_Order_Number__c = order.OrderNumber);
 
		System.debug('bq List='+bq);		
		Brand_Quote__c oppID = [select id,Opportunity_Name__c from Brand_Quote__c where Kushy_Punch_Order_Number__c =: order.OrderNumber];
		System.debug('oppID List='+oppID);
		 
		bql.Brand_Quote_Number__r = bq;
        bql.Retail_Wholesale_Price__c = Decimal.valueOf(order.SalePrice.remove('$'));
		List<OpportunityLineItem> oliList = new List<OpportunityLineItem>();
		if(String.isNotBlank(order.Product)){
            OpportunityLineItem[] existingOLIs = [SELECT Id, PricebookEntry.DistyMargin__c,Disty_Discount_Per_Unit__c FROM  OpportunityLineItem WHERE Kushy_Punch_Order_Line_Item__c = :order.LineItemNumber LIMIT 1];
            for(Product2 prd:[SELECT Id, Name FROM Product2 WHERE StockKeepingUnit = :order.Product]){
                bql.Product_Name__c = prd.Id;
                break;
            }
            if(bql.Product_Name__c != null){
                for(PriceBookEntry pbe: [SELECT Id, PriceBook2Id FROM PriceBookEntry WHERE Product2Id = :bql.Product_Name__c AND PriceBook2.IsStandard = true]){
                    bql.Price_Book__c = pbe.PriceBook2Id;
                    OpportunityLineItem oli;
                    if(existingOLIs.isEmpty()){
                        oli = new OpportunityLineItem(OpportunityId=oppID.Opportunity_Name__c, PricebookEntryId=pbe.Id, Quantity = order.Quantity, UnitPrice = Decimal.valueOf(order.SalePrice.remove('$')), Product_Title__c = 'Distributor',Kushy_Punch_Order_Line_Item__c = order.LineItemNumber);
                    }else{
                        oli = new OpportunityLineItem(OpportunityId=oppID.Opportunity_Name__c, Quantity = order.Quantity, UnitPrice = Decimal.valueOf(order.SalePrice.remove('$')), Product_Title__c = 'Distributor',Kushy_Punch_Order_Line_Item__c = order.LineItemNumber);
                    }

					oliList.add(oli);
					System.debug('OLI List='+oli);
                    break;
                }
            }
        }
		Database.UpsertResult[] res = Database.upsert(oliList,OpportunityLineItem.fields.Kushy_Punch_Order_Line_Item__c,false);
            System.debug('##Database.UpsertResult[]::'+res);
        for(OpportunityLineItem oli: [SELECT Id, PricebookEntry.DistyMargin__c,Disty_Discount_Per_Unit__c FROM  OpportunityLineItem WHERE Id IN :oliList]){
            bql.Disty_Margin__c = oli.PricebookEntry.DistyMargin__c;
            bql.Disty_Discount_Per_Unit__c = oli.Disty_Discount_Per_Unit__c;
        }
		System.debug('OPPLI List='+oliList);
		Database.upsert(bql,Brand_Quote_Line__c.Fields.Kushy_Punch_Order_Line_Item__c,false);
		
		System.debug('BQL: ' + bql);
        r.put('name', order.OrderNumber);
        }catch(Exception e){
            System.debug('###Exception:'+e.getMessage());
        }
        return r;
    }
    public class Order{
        public String OrderNumber			{get;set;}
        public String LineItemNumber 		{get;set;}
        public String Product  				{get;set;}
        public Integer Quantity     		{get;set;}
        public String Price      			{get;set;}
        public String SalePrice       		{get;set;}
    }
    
}